### ISSUE TITLE
Disable SourceMaps in production

### ISSUE THREAD

**Issue by Ronny25** [jaredpalmer/razzle#1000]
Is there any way to disable generating of SourceMaps for production build?

CRA has .env variable called - GENERATE_SOURCEMAP.

I cannot see anything in docs. So, I suppose, the only possible way is to extend webpack config inside razzle.config.js?

**Comment by krazyjakee** [comment]
>  extend webpack config inside razzle.config.js

This is the solution. An example razzle.config.js.

```js
module.exports = {
  modify: (config, { target, dev }) => {
    config.devtool = dev ? 'source-map' : false;
    return config;
  },
};
```

**Comment by Ronny25** [comment]
@krazyjakee yes that what I was talking about and I have the same in my code right now.
But this is a bit overcomplicated as for me to achieve such a goal. Not too accurate, to be honest.
Prefer the CRA way to do it.
However, if it is the only possible way then ok.

**Comment by krazyjakee** [comment]
@Ronny25 If you really want to use environment variables you could do something like:

```js
module.exports = {
  modify: config => {
    config.devtool = process.env.GENERATE_SOURCEMAP ? 'source-map' : false;
    return config;
  },
};
```

Then you get the same accuracy as CRA.

**Comment by Ronny25** [comment]
@krazyjakee that's not completely true 😄 
Firstly, you need to create a config file with some logic inside then an env variable, sounds strange 😉 
But I can live with is 😁

**Comment by SamirJouni** [comment]
@krazyjakee 
This only seems to disable source maps for .js files. 
.css files still get source map files generated.

**Comment by andersnylund** [comment]
In Razzle 4.0 the following 

```javascript
module.exports = {
  // ...
  modifyWebpackConfig({ env: { dev }, webpackConfig }) {
    if (!dev) {
      webpackConfig.devtool = undefined
    }
    return webpackConfig
  }
  // ...
}
```

will disable sourcemaps in production

https://razzlejs.org/docs/customization
