### ISSUE TITLE
No repository link on npm

### ISSUE THREAD

**Issue by dandv** [jaredpalmer/razzle#1007]
https://www.npmjs.com/package/razzle doesn't show a link to the repo.

**Comment by dandv** [comment]
@nimaa77: Hi, just got notified that this issue was closed. What is the resolution?

**Comment by nimaa77** [comment]
oh, my bad :)

**Comment by nimaa77** [comment]
so, I didn't get what you were pointing to first time I read the issue...

we have some kind of repo URL here in package.json:
https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/package.json#L5

but maybe it's wrong or something that npm can't find it

**Comment by nimaa77** [comment]
@dandv should be fixed now, but we can see this on npm only when we release a new version
