### ISSUE TITLE
razzle in dev mode does not print error log

### ISSUE THREAD

**Issue by redlapin** [jaredpalmer/razzle#1009]
when I start razzle with "razzle start" in dev mode, I found the webpack-dev-server is configured by "clientLogLevel: 'none'" and "quiet: true" by default. That leads to nothing printed when error occurs.

I'd like to know your design purpose and if possible to log something for errors and warnings.

**Comment by aga5tya** [comment]
I'm using https://www.npmjs.com/package/friendly-errors-webpack-plugin and adding them to plugins in razzle config. Solves the problem for now.

**Comment by redlapin** [comment]
> I'm using https://www.npmjs.com/package/friendly-errors-webpack-plugin and adding them to plugins in razzle config. Solves the problem for now.

Thank you for your suggestion. Finally I modify the webpack server configuration in my own razzle.config.js and that works.

What confuses me is just why the writer of razzle designs like this

**Comment by fivethreeo** [comment]
Fixed in dev , add —verbose
