### ISSUE TITLE
razzle test: --watch is not supported without git/hg

### ISSUE THREAD

**Issue by prichmp** [jaredpalmer/razzle#1016]
**Current behavior:** 
When using razzle in a project without a git or hg repository (we are using svn), Jest watch fails with the error code message: 
```
> razzle test --env=jsdom
Determining test suites to run...
--watch is not supported without git/hg, please use --watchAll
```

**Suggested solution:**
I tracked the issue to line 33 of /scripts/test,js. 

```
if (!process.env.CI && argv.indexOf('--coverage') < 0) {
  argv.push('--watch');
}
```

Instead of trying to determine if the files should be watch, we might think about giving that control back to the user by changing the npm script to `"test": "razzle test --env=jsdom --watch"`

**Comment by nimaa77** [comment]
fixed in #1080
