### ISSUE TITLE
Build breaks due to webpack error when updating from 3.0.0-alpha.2 to 3.0.0

### ISSUE THREAD

**Issue by wingertge** [jaredpalmer/razzle#1017]
### Expected Behaviour
Build works the same going from razzle and razzle-plugin-typescript 3.0.0-alpha.2 to 3.0.0

### Actual Behaviour
On razzle start and razzle build, webpack throws the following configuration error:

```
{ ValidationError: webpack Dev Server Invalid Options

options.clientLogLevel should be {String} and equal to one of the allowed values

 [ 'info', 'warn', 'error', 'debug', 'trace', 'silent' ]
```

### Versions
| React | v16.8.6 |
| Razzle | v3.0.0-alpha.2 |
| Razzle-Plugin-Typescript | v3.0.0-alpha.2 |
| Webpack | v4.31.0 |
| Typescript | v3.4.5 |

**Comment by jaredpalmer** [comment]
Can you submit a PR?

**Comment by wingertge** [comment]
I really don't understand Webpack configs (which is why I use a framework that does the configuration for me in the first place), so I'd appreciate if someone with a bit more experience could handle that instead.

**Comment by tatchi** [comment]
@wingertge from what I see from the [webpack-dev-server repo](https://github.com/webpack/webpack-dev-server/releases) they've removed the `none` option from `clientLogLevel` possible values in the `3.40` release (released 2 days ago).

But then they added back this option in the 3.4.1 release. It's now deprecated but will only be removed in a major release (I assume to avoid breaking changes).

I tested with both versions and while I got the same error as you with the `3.4.0`, everything went well with the `3.4.1`.

So normally if you update it to the new version it should be fine.

**Comment by wingertge** [comment]
@tatchi Thanks a lot, I thought the build broke due to upgrading the cached version, but I guess it wasn't on razzle after all. I've manually added 3.4.1 now and it works perfectly fine. That's a pretty big mistake by webpack-dev-server though.
