### ISSUE TITLE
Missing chunks when using react-loadable

### ISSUE THREAD

**Issue by ericlifs** [jaredpalmer/razzle#1026]
Hello folks.

I'm trying to setup my existing razzle project with react-loadable and I'm having an issue.

The main idea is first to split the codebase by pages. I'm following the with-react-loadable example and I arrived to a point where I do not understand what it's trying to do: 

![image](https://user-images.githubusercontent.com/7376892/58841734-9dcd8980-8641-11e9-8046-bd0319a268bd.png)

As we can see in the [server.js](https://github.com/jaredpalmer/razzle/blob/master/examples/with-react-loadable/src/server.js) file, it's including the assets.js file (which is not splitted) and each chunk js file, so it's having the chunks code duplicated (because they are included in the bundle.js file).

![image](https://user-images.githubusercontent.com/7376892/58841955-9ce92780-8642-11e9-9d78-bed4b48240cb.png)

If I remove the line which includes the bundle.js file, which in my opinion it's how it should work (since I'm including the chunks files), I just get the 0.chunk.js file requested and my app js do not work anymore:

![image](https://user-images.githubusercontent.com/7376892/58842049-d3bf3d80-8642-11e9-8597-4101f3498158.png)

I hope someone could explain me what it's happening or if I am misunderstanding how code-splitting should work.

Thanks!

**Comment by fivethreeo** [comment]
React loadable is not the reccomended way to do code splitting. Use lazy or use @loadable/component.

**Comment by fivethreeo** [comment]
See: https://github.com/fivethreeo/razzle/tree/loadable-component/examples/with-loadable-component

**Comment by wagnerjsilva** [comment]
Hi @fivethreeo, 

I've tried your example and it's not starting unfortunately: 

See error below: 

`> 949 | throw new Error("Module parse failed: Unexpected token (6:9)\nFile was processed with these loaders:\n * ./node_modules/babel-loader/lib/index.js\nYou may need an additional loader to handle the result of these loaders.\n| import loadable from 'loadable-components';\n| var Header = loadable(function () {\n>   return import(\n|   /* webpackChunkName: \"header\" */\n|   './Header');");
`

**Comment by fivethreeo** [comment]
Use @loadable/component not loadable-components :)
