### ISSUE TITLE
Serve static files from same port in dev example

### ISSUE THREAD

**Issue by stevenroussey-privicy** [jaredpalmer/razzle#1029]
`.env` file can have `CLIENT_PUBLIC_PATH=http://localhost:3000/`

and in the `server.js` after the static file serving:

```
  .get('(/static/*)|(/*.hot-update.(js|json))', function(req, res) {  
    var url = "http://localhost:3001/" + req.url;
    req.pipe(request(url)).pipe(res);
  })
```

**Comment by nimaa77** [comment]
hello @stevenroussey-privicy can you explain more about this?
I can't understand what you are trying to fix here

**Comment by fivethreeo** [comment]
He wants to run everything off one port. Could be done as a example.

**Comment by fivethreeo** [comment]
But could cause HMR errors.

**Comment by nimaa77** [comment]
this is good for `codesandbox` support

**Comment by fivethreeo** [comment]
But other way around would be better. Serve the server behind the devServer. Because the server reloads first. If it is not fully up when HMR for the client tries to get the hot update, client possibly won’t find the update. But I may be wrong 😀

**Comment by fivethreeo** [comment]
We could modify config.devServer.before and add 

https://github.com/villadora/express-http-proxy/blob/master/README.md#skiptonexthandlerfiltersupports-promise-form, so if the server gives a 404 we get static instead. So everything is reachable at 3001.

Or reverse the use pattern to negate static and hmr updates and sockjs and include favicon.

**Comment by fivethreeo** [comment]
Added example on how to do this

https://github.com/jaredpalmer/razzle/tree/next/examples/with-single-exposed-port

**Comment by fivethreeo** [comment]
Added example on how to best accomplish this. Closing
