### ISSUE TITLE
Raw and base64 loaders does not work

### ISSUE THREAD

**Issue by MaxSvargal** [jaredpalmer/razzle#1030]
I'm trying to load a woff font inline and every time I get an asset url. No matter that I use: on use `raw-loader` or `url-loader` or `base64-inline-loader` i got the same result: path string.

```
module.exports = {
  modify(defaultConfig, { target, dev }, webpack) {
    const config = defaultConfig

    config.module.rules = [
      ...config.module.rules,
      {
        test: /\.(woff2)?$/,
        loader: 'raw-loader'
      },
    ]
}
```
And also using code on typescript

`import * as DidotBoldFont from 'raw-loader!./AvenirLTStd-Book.woff2'`

I got `Object [Module] {
  default:
   'module.exports = __webpack_public_path__ + "static/media/AvenirLTStd-Book.6651ba62.woff2";' }`

When I use `base64-inline-loader` I got
`data:font/woff2;charset=utf-8;base64,bW9kdWxlLmV4cG9ydHMgPSBfX3dlYnBhY2tfcHVibGljX3BhdGhfXyArICJzdGF0aWMvbWVkaWEvQXZlbmlyTFRTdGQtQm9vay42ZjlkMjIxNC53b2ZmMiI7`

After decoding it's the same `module.exports = __webpack_public_path__ + "static/media/AvenirLTStd-Book.6f9d2214.woff2";`

When I use `url-loader` I got the same
`data:font/woff2;base64,bW9kdWxlLmV4cG9ydHMgPSBfX3dlYnBhY2tfcHVibGljX3BhdGhfXyArICJzdGF0aWMvbWVkaWEvQXZlbmlyTFRTdGQtQm9vay5kMTQ2NGMzMi53b2ZmMiI7`

I used `razzle-dev-utils/makeLoaderFinder` and no way.
```
    const urlLoaderFinder = makeLoaderFinder('url-loader');
    const urlRule = config.module.rules.find(urlLoaderFinder);
    urlRule.test = [/\.bmp$/, /\.gif$/, /\.jpe?g$/, /\.png$/, /\.woff2$/]
    urlRule.options.limit = 0
```

How to do this simple thing? >_<

**Comment by MaxSvargal** [comment]
Decision:

```
    const urlLoaderFinder = makeLoaderFinder('url-loader');
    const urlRule = config.module.rules.find(urlLoaderFinder);
    urlRule.test = [/\.bmp$/, /\.gif$/, /\.jpe?g$/, /\.png$/, /\.woff2$/]
    urlRule.options.limit = 100000

    const fileLoaderFinder = makeLoaderFinder('file-loader');
    const fileRule = config.module.rules.find(fileLoaderFinder);
    fileRule.exclude = [
      /\.html$/,
      /\.(js|jsx|mjs)$/,
      /\.(ts|tsx)$/,
      /\.(vue)$/,
      /\.(less)$/,
      /\.(re)$/,
      /\.(s?css|sass)$/,
      /\.json$/,
      /\.bmp$/,
      /\.gif$/,
      /\.jpe?g$/,
      /\.png$/,
      /\.woff2$/,
    ]
```

**Comment by alveshelio** [comment]
Hi @MaxSvargal,

I'm having the same issue to load woff2 fonts. Where did you placed your code above, does it needs to go in razzle.config.js?
Where does makeLoaderFinder comes from? I'm using TypeScript and it always complains about stuff that's not typed :)

**Comment by fivethreeo** [comment]
Use !!raw-loader to ignore rules.

```js
import txt from '!!raw-loader!./file.txt';
```
