### ISSUE TITLE
--inspect not working

### ISSUE THREAD

**Issue by jmfsilva** [jaredpalmer/razzle#1031]
Hello,
I followed the Quick Start guide:
npx create-razzle-app my-app
cd my-app

and then i did yarn start --inspect

And there was no Remote Target on chrome://inspect

i'v the following dedicated DevTools for node configured.
![Screenshot from 2019-06-11 16-11-26](https://user-images.githubusercontent.com/4760349/59284100-97ec2f80-8c63-11e9-9766-d242cf6dc015.png)

Any one with the same issue with inspect?

Razzle versions:
 - 2.4.1
 - 3.0.0

**Comment by mschipperheyn** [comment]
Maybe try to specify the port `razzle start --inspect --inspect-port 9230`? I have no problems running inspect on VSCode.

**Comment by jmfsilva** [comment]
Ye sure, but i'm talking about inspect without port.
Either it should work or documentation should not say that you can use it.
Probably the default port on --inspect that is on documentation is not correct?

**Comment by fivethreeo** [comment]
There is a pull to fix this. This i on my radar. Closing issue
