### ISSUE TITLE
macros config not loaded in production environement

### ISSUE THREAD

**Issue by micabe** [jaredpalmer/razzle#1032]
see here usage of babel macros
https://github.com/kentcdodds/babel-plugin-macros/blob/HEAD/other/docs/user.md

it load the file `babel-plugin-macros.config.js` in dev mode but not in prod mode

**Comment by micabe** [comment]
my babel.rc file
```
{
  "presets": ["razzle/babel"],
  "plugins": ["macros"]
}

```

**Comment by micabe** [comment]
my babel-plugin-macro.config.js file
```
module.exports = {
  tailwind: {
    config: './src/theme/styles/tailwind.js',
    format: 'auto',
  },
};
```

**Comment by chrisdostert** [comment]
@micabe did you figure this out? I'm hitting the same issue
