### ISSUE TITLE
yarn/npm start no longer prints listen port

### ISSUE THREAD

**Issue by fredvd** [jaredpalmer/razzle#1036]
I noticed that when I start a new razzle project in development mode it now only outputs:
```
✅  Server-side HMR Enabled!
🚀 started
```

Where the screenshot in the main README shows a message of 'started on port 3000'? Especially for newbies starting the server for the first time (or when you configure an alternative port in a project) it is very useful to output the port on development startup.

**Comment by MetaMemoryT** [comment]
Getting this issue also, also nothing runs on port 3000 when this message is sent.

**Comment by monowai** [comment]
I'm no expert, but I might have inadvertently resolved this when looking and Typescript linting problems. 
In `index` I moved the error callback to `.on` instead of passing it as a function into the `listen` method, so `express` now looks like:
```
export default express()
  .use((req, res) => app.handle(req, res))
  .listen(port, () => {
    console.log(`> Started on port ${port}`);
  })
  .on("error", e => {
    console.error(e.message);
    throw e;
  });
```

Now the port is displayed.  HTH
