### ISSUE TITLE
Build: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by StevenLangbroek** [jaredpalmer/razzle#1042]
Hey all! As soon as I run `yarn build`, it stops with this message:

```bash
Failed to compile.

ENOENT: no such file or directory, stat '/Users/stevenlangbroek/Code/my-project/public'
```

What's interesting is that if I create this empty directory, it works, but this dir is never even really used (builds end up in `./build` instead of `./public`...

Any idea what's going on here?

**Comment by sergiopellegrini** [comment]
By default razzle creates a default public directory. This directory has the robots.txt file as well as the favicon.ico. 

You can use it also for other static assets on your express server. See public folder static express middleware below from the server file.

`
server.use(express.static(process.env.RAZZLE_PUBLIC_DIR))
`

**Comment by StevenLangbroek** [comment]
Ahhhhhh of course. Cool. Thanks!
