### ISSUE TITLE
Issue with server HMR

### ISSUE THREAD

**Issue by txs** [jaredpalmer/razzle#1044]
The HMR does refresh. But each time the code refreshes, the server code was the same as the initial build instead of new one. I have to go to the command and type 'rs' so that it manually reload the code.

Is there a way to auto reload the server code?

**Comment by nimaa77** [comment]
this is a bug we have to really fix this :)

Check #1069 they have the same problem, for now, we move this conversation on that issue so we have everything in one place.

thanks for your bug report
