### ISSUE TITLE
with-react-loadable example no longer working 

### ISSUE THREAD

**Issue by wagnerjsilva** [jaredpalmer/razzle#1048]
I've downloaded and started a fresh copy of the example:

https://github.com/jaredpalmer/razzle/tree/master/examples/with-react-loadable

Unfortunately the example is no longer working, breaking with the following error message: 

`> 1113 | throw new Error("Module parse failed: Unexpected token (12:11)\nFile was processed with these loaders:\n * ./node_modules/babel-loader/lib/index.js\nYou may need an additional loader to handle the result of these loaders.\n| var Intro = Loadable({\n|   loader: function loader() {\n>     return import('./Intro');\n|   },\n|   modules: ['./Intro'],");
`

**Comment by wagnerjsilva** [comment]
I was able to replicate the same issue using the example: 

https://github.com/jaredpalmer/razzle/tree/master/examples/with-loadable-components

**Comment by kyle-johnson** [comment]
Looks like loadable has their own, more recent example: https://github.com/smooth-code/loadable-components/tree/master/examples/razzle

**Comment by kyle-johnson** [comment]
See #985

**Comment by wagnerjsilva** [comment]
Thanks Kyle,

I'll try with the new example, hope it works as my applications is getting big now.
