### ISSUE TITLE
Is dev-dependency 'husky' used in this project?

### ISSUE THREAD

**Issue by kkalavantavanich** [jaredpalmer/razzle#1056]
I can see that `"husky": "^0.14.3"` is specified in `package.json`. However, the package is not being used anywhere in the project. Unless I am missing something, I think that `husky` should be remove from `package.json` if it is not used or planned to be used.

**Comment by hennessyevan** [comment]
husky is used to run the precommit git hook here https://github.com/jaredpalmer/razzle/blob/master/package.json#L22

see: https://github.com/typicode/husky

**Comment by kkalavantavanich** [comment]
Oh, thanks! Should I update it to a newer version (not forgeting to update the precommit hook in `package.json`), for the sake of keeping things up-to-date?

**Comment by hennessyevan** [comment]
You could, I use newer versions of husky in my projects however you'll need to move that precommit hook since after husky v0.14 there is a new way to specify hooks. see: https://github.com/typicode/husky#upgrading-from-014

**Comment by kkalavantavanich** [comment]
Done #1059
