### ISSUE TITLE
Wait for deleting build folder until new build is created

### ISSUE THREAD

**Issue by Rehan712** [jaredpalmer/razzle#1060]
I have a scenario when i create build on ubuntu server build folder deleted untill new build compiled which causes my site down. Is there any config that previous build not deleted until new bulild created.

**Comment by nimaa77** [comment]
no, currently there is no option for that. technically what you are doing is wrong.

read about blue-green deployment [here](https://martinfowler.com/bliki/BlueGreenDeployment.html)
