### ISSUE TITLE
Jest Config

### ISSUE THREAD

**Issue by PatrickQuintal** [jaredpalmer/razzle#1065]
Hey,

I'm wondering what the reason for not using jest.config.js was?

Razzle reads jest config from the package.json why? It could of been read from jest.config.js?

Razzle also strips out jest config, I can't tell for what reason. Its not like it /won't/ work since the generated config is just passed directly into Jest. This causes problems since now I can't customize jest how I want.

My suggestion is to also load the jest config if my package.json "jest" object is not defined.

doing something like:

`let config = {...defaultRazzleConfig, ...jest.config.js, {setupTestFrameworkScriptFile: setupTestsFile}}`

Overriding the 'setupTestFrameworkScriptFile' property (and other properties) as required.

**Comment by nimaa77** [comment]
nice idea. I will get back to this issue soon.

**Comment by fivethreeo** [comment]
What about a modifyJestConfig in razzle.config.js and in plugins?

**Comment by fivethreeo** [comment]
There is support for modifyJestConfig in dev, will be in the next release.
