### ISSUE TITLE
Css loader doesn't load css code as in example

### ISSUE THREAD

**Issue by bryaan** [jaredpalmer/razzle#1071]
From the css-loader docs this should be possible:

./App.js
```
const css = require('./App.css').toString()
console.dir(css)
```

But instead it returns an empty object.

**Comment by fivethreeo** [comment]
Works in the server in razzle canary, so probably MiniCssExtractPlugin or OptimizeCSSAssetsPlugin causes this.

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/issues/1591#issuecomment-813474885

**Comment by fivethreeo** [comment]
https://razzlejs.org/docs/customization#css-modules

Use import and not require
