### ISSUE TITLE
Remote debugging cannot load from http://localhost

### ISSUE THREAD

**Issue by bryaan** [jaredpalmer/razzle#1076]
How can I allow for both local dev at http://localhost:3000 as well as remote debugging a mobile device on the local network at the host machine's IP http://10.0.1.10:3000.  Accessing the website works however the js bundle never gets loaded.  The console log shows the mobile device trying to hit http://localhost:3001/static/js/bundle.js fails because the 'localhost' should really be the IP address. (Server is running on another local network machine)

**Comment by nimaa77** [comment]
hello @bryaan,
we are going to add this feature for the next release.

for now, what you can do is to simply specify an env variable called `HOST` with the value of IP of the machine you are running razzle on it.


```
// .env.development (in root of project next to the package.json)
HOST=192.168.1.100
```

and then run `razzle start`

GG

**Comment by komali2** [comment]
This is the first result on google for "Razzle allow remote debugging," if possible, could you link to where in the documentation this presumably now-added feature can be found? I've yet to find it.
