### ISSUE TITLE
.env.development PORT seems to not be respected

### ISSUE THREAD

**Issue by ThisIsMissEm** [jaredpalmer/razzle#1079]
I've just added a `.env.development` file to my project setup with Razzle, and it seems Razzle doesn't load that file until after checking if it can listen on whatever PORT is.

It seems setPorts is called here: https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/scripts/start.js#L101

However, at that point in time, `let serverConfig = createConfig('node', 'dev', razzle, webpack);` hasn't yet been run, meaning that `process.env.PORT` isn't set from the `.env.development` file, as `createConfig` is what reads those `.env` files

This seems like potentially unintended functioning; I'd expect the dotenv files to be loaded up before `setPort` is called, allowing me to use those files to specify the PORT

**Comment by ThisIsMissEm** [comment]
Further, running as `PORT=4000 yarn start` also doesn't work as expected. Seems to always wish to run on port 3001, which is the default in setPorts (I think) — https://github.com/jaredpalmer/razzle/blob/master/packages/razzle-dev-utils/setPorts.js

**Comment by ThisIsMissEm** [comment]
Actually, seems I needed to set both `PORT` and `PORT_DEV`, which was unexpected and undocumented.

**Comment by fivethreeo** [comment]
Should be fixed in dev version :)
