### ISSUE TITLE
Outdated jest leads to vague errors instead of diff

### ISSUE THREAD

**Issue by mschipperheyn** [jaredpalmer/razzle#1084]
I ran into the issue `TypeError: Cannot read property 'prototype' of undefined instead of diff` described here: https://github.com/facebook/jest/issues/8822

It manifests by showing this error when you have a key on your `resolves.toMatchObject` that is not in the returned object. The reason is an outdated jest dependency in a mono repo with razzle.

The workaround is to add  "jest-config": "^24.8.0" to the "resolutions" key in your root packages.json.

**Comment by nimaa77** [comment]
this is fixed now, I'm going to close it.
