### ISSUE TITLE
Is it possible to make custom environment variables required?

### ISSUE THREAD

**Issue by ThisIsMissEm** [jaredpalmer/razzle#1085]
Currently, on `process.env` all variables are typed as `string | undefined` which means that functions that require a `string` will give a typescript warning unless you do `process.env.RAZZLE_FOO as string`

In other applications, I've taken the approach of using [envalid](https://npm.im/envalid), which automatically generates types for environment variables given a spec of what environment variables should exist.

I'm mostly looking to not need to do `process.env.RAZZLE_FOO as string`

**Comment by jimmyhedstr0m** [comment]
```process.env.RAZZLE_FOO!``` does also work to stop TypeScript from complaining.
