### ISSUE TITLE
Read environment variables at runtime and serve settings

### ISSUE THREAD

**Issue by iberodev** [jaredpalmer/razzle#1086]
I've been reading a few issues related, but either they're closed or they are not exactly clear.
There is also an example of env variables here: https://github.com/jaredpalmer/razzle/tree/master/examples/with-custom-environment-variables but it's only for build time.

Is there any approach for the react app SSR with razzle that can read environment variables at runtime and replace them accordingly for the first load?

The motivation is the following: if we containerize the app, we don't want to apply settings per environment at build time because it's not ideal to create different docker images per environment. Ideally we should only build one docker image for the app, totally environment-agnostic and inject the environment variables at runtime when doing `docker run -e ...`

That way some process could apply the proper settings values and serve the app for first time with them.

I apologize if this is supported or there's an existing approach. Does it? I believe nextJs does something similar but not sure either.

**Comment by fivethreeo** [comment]
https://github.com/fivethreeo/react-ssr-django-jwt-docker/tree/master/src/config

Is how I do runtime settings.

**Comment by nimaa77** [comment]
it's documented here
https://github.com/jaredpalmer/razzle#runtime-variables
