### ISSUE TITLE
How do I add after.js

### ISSUE THREAD

**Issue by nesbtesh** [jaredpalmer/razzle#1087]
I recently created a razzle project but I cannot find a way to do server rendering request, I havent been able to install after js

**Comment by nimaa77** [comment]
just clone the "with-afterjs" example!

**Comment by nimaa77** [comment]
I'm currently working on after.js and there are some examples in [after.js repo ](https://github.com/jaredpalmer/after.js) that can help you with that.

so I'm going to close this issue.
