### ISSUE TITLE
Customize webpack config not implemented when running test script

### ISSUE THREAD

**Issue by fakhrishahab** [jaredpalmer/razzle#1091]
I'm adding some webpack config on `razzle.config.js` such as webpack `DefinePlugin`. But it won't work when I running the test.
How can I customize the `test` runtime script ?

**Comment by fivethreeo** [comment]
I think this is intentional because you might want to modify the config per test. But the basic example could do with a integrationtest to show how to do this.

**Comment by fivethreeo** [comment]
If you specifically want defines I have a possible workaround. 

In package.json add 
```json
{"jest": { "globalSetup": "<rootDir>/test/globalSetup.js" } }
```

Then in test/globalSetup.js

```js
const env = require('razzle/config/env');
module.exports = async () => {
  global.globals = env.getClientEnvironment('web');
}
```

I have not tried this, but should be possible if jest docs are correct.

**Comment by fivethreeo** [comment]
Will look into adding jest configuration to razzle.config.js

**Comment by fivethreeo** [comment]
Added modifyJestConfig in razzle.config.js to canary. Webpack config only affects built code so you would need to test the built code or modify the jest configuration accordingly.
