### ISSUE TITLE
CSS not loaded after heroku deployment

### ISSUE THREAD

**Issue by GabrielDeM** [jaredpalmer/razzle#1094]
Hi guys, css is not loaded when deploying into heroku.

Here are the steps : 

1. npx create-razzle-app app-name
2. cd app-nave
3. yarn install
4. git init
5. git add .
6. git commit -m "First commit"
7. heroku create
8. git push heroku master
9. heroku open

Just html is loaded.

Thanks for the help :)

**Comment by nesbtesh** [comment]
Same issue, but I am also getting an error with the deployment to heroku

 Module not found: Can't resolve './Home.css' in '/tmp/build_3f54fa3da25d4702aa68e590a21a3ae2/src/js/home'

**Comment by rvanlaarhoven** [comment]
You'll probably have to set the `RAZZLE_PUBLIC_DIR` environment variable to the path where the assets are stored on the dyno (e.g. `/app/build/public` if you're using the default nodejs buildpack)
