### ISSUE TITLE
Update fork-ts-checker-webpack-plugin to 1.5.0

### ISSUE THREAD

**Issue by PabloDiablo** [jaredpalmer/razzle#1095]
The current version of razzle-plugin-typescript is using fork-ts-checker-webpack-plugin version ^0.4.1. The latest version of fork-ts-checker-webpack-plugin (1.5.0) has functionality to allow it to discover tslint.json configuration using the same methodology as the tslint CLI. The version used by razzle-plugin-typescript will only use the root level tslint.json config.

**Comment by nimaa77** [comment]
hello @PabloDiablo we will update this very soon :)
but it's going to be a breaking change.
