### ISSUE TITLE
Unable to run project on multiple devices in development mode

### ISSUE THREAD

**Issue by ZhouHansen** [jaredpalmer/razzle#1096]
I have two laptops. I run `npm start` on one of them, my local network address is `192.168.52.26`, so I visited `http://192.168.52.26:3000` on the browser, it worked fine.

But when I visited `http://192.168.52.26:3000` on the other laptop under the same network, the app won't run. 

I checked the dev tool, and found the problem, `http://localhost:3001/static/js/bundle.js` can't not be loaded.

![WechatIMG90](https://user-images.githubusercontent.com/8222181/64498157-d1294f80-d2e5-11e9-93d0-60bd86976fbf.jpeg)

<img width="512" alt="WechatIMG91" src="https://user-images.githubusercontent.com/8222181/64498163-e0100200-d2e5-11e9-95c2-d717c366388e.png">

I think Razzle should support its dev server to be hosted at the local network address like other front-end frameworks doing. Because some apps require test on multiple devices.

<img width="403" alt="WechatIMG92" src="https://user-images.githubusercontent.com/8222181/64498167-e1d9c580-d2e5-11e9-8fc5-7fd2a887fc15.png">

**Comment by ZhouHansen** [comment]
Create a `.env` file can solve it:
```
HOST="192.168.52.26"
```

But it's better to host local network address automatically.

**Comment by fivethreeo** [comment]
Just set CLIENT_PUBLIC_PATH or HOST this is documented and works. Closing
