### ISSUE TITLE
Material UI example's production build not loading styles properly

### ISSUE THREAD

**Issue by OscarCR88** [jaredpalmer/razzle#1100]
Hi

Just cd to examples/with-material-ui, did `yarn build` and `yarn start:prod` and styles are not being properly loaded in the prod build.
For example, the styles being injected are in this form:

```
jss1{
...
}
```
however, the html is expecting the style's classname as `makeStyle-1`.

Steps to reproduce: 
- clone the repo
- cd to examples/with-material-ui
- run `yarn build, yarn start:prod`
- you'll see example's style crashing

According to this: https://material-ui.com/getting-started/faq/#why-aren-39-t-my-components-rendering-correctly-in-production-builds
Looks like might be a webpack issue? 

Any help would be greatly appreciated

**Comment by OscarCR88** [comment]
Ok, so, the problem is that the styles being rendered by the client won't match the styles being sent by the server. Like, the server is sending classes like:

```
jss1{...}
jss2{...}
jssn{...}
```
whereas the classes being rendered by the client are like this:

```
makeStyles-1{...}
makeStyles-2{...}
makeStyles-n{...}
```
thus, first render's style is f**cked up.

What I did to solve the problem is to wrap my App component with a StyleProvider and generate prd classnames with the jss prefix (to match what's being sent by  the server):

```
import { createGenerateClassName, StylesProvider } from "@material-ui/styles"
/*import other stuff*/

//build new classnames prefix, using jss
const generateClassName = createGenerateClassName({
  productionPrefix: "jss"
})

const App = () => {
  return (
    {/*Wrap the app component with styles provider using declared classnames prefix*/}
    <StylesProvider generateClassName={generateClassName}>
      <Switch>
        <Route exact path="/" component={Home} />
        <Route exact path="/signin" component={SignIn} />
        <Route exact path="/signup" component={Signup} />
        <Route component={NotFound} />
      </Switch>
    </StylesProvider>
  )
}

export default App
```
Et voila.

P.S: Yes it may look like a hack ): ... but I couldn't found any other solution

**Comment by idonov** [comment]
The above is not working for me. I added Mui v5 to the razzle-typescript template and tried the fix with the generateClassName and it didnt work.
What fixed it is implement Mui SSR as suggested in the Mui examples:
https://github.com/mui-org/material-ui/tree/next/examples/ssr
