### ISSUE TITLE
Cant get the static file using with-router-3

### ISSUE THREAD

**Issue by subhendukundu** [jaredpalmer/razzle#1103]
So I am trying to see my javascript file as I am getting an error of `Uncaught SyntaxError: Unexpected token <` in my `bundle.18e42c63.js:1` file but when I am trying to open the js file it shows only my html code. Local works great, SyntaxError is happening only in prod.
How do I fix the behaviour?
Would love to know your thoughts.

**Comment by fhayes301** [comment]
@subhendukundu did you ever find a solution to this? I'm running into the same error.

**Comment by nimaa77** [comment]
if you want to create isomorphic apps with react-router just use After.js (trust me on this)
