### ISSUE TITLE
Production Build - keep build folder git config

### ISSUE THREAD

**Issue by simon-pelletier** [jaredpalmer/razzle#1110]
When we build in production the script build.js is running and do :
`fs.emptyDirSync(paths.appBuild);`

I want to create a git subModule in build folder.
Is there a way to avoid this function to keep the git config in the build folder ?

Btw : When I build the client compilation create a public folder with static folder, this is ok, but while the server compilation there is a new static folder in build root with duplicate assets. Do you know why ?

**Comment by nimaa77** [comment]
hello, I don't know why you want to do this, but it's not a good idea.

about the static folder, it's just static files that needed for `server.js` file, I think we can't put png files inside server.js ...
