### ISSUE TITLE
error starting razzle project - cannot find module '/build/assets.json'

### ISSUE THREAD

**Issue by mwarger** [jaredpalmer/razzle#1117]
I'm getting an issue when attempting to start a fresh project that's using TypeScript.  Repro here: https://github.com/mwarger/razzle-assets-repro

Cannot find module '..../razzle-assets-repro/build/assets.json'

Hopefully, I didn't goof something up on my end... Thanks for any advice.

**Comment by nimaa77** [comment]
I think this issue is fixed in the latest version of razzle so I'm going to close this for now.
If you think it's a mistake just reopen it.
