### ISSUE TITLE
Turn off server side hot reloading

### ISSUE THREAD

**Issue by aoshi321** [jaredpalmer/razzle#1119]
Hi

Is there a way to turn off server side hot reloading

thanks

aoshi

**Comment by meff34** [comment]
Hello!

You can just delete all the code after line 
```
console.log('✅  Server-side HMR Enabled!');
```
in file `src/index.js`

This is what is hot reloading on server side

**Comment by fivethreeo** [comment]
Meff34 sort of, but not really :)

https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/config/createConfig.js#L339

Needs a signal: false here, so no.
