### ISSUE TITLE
Example code for react app

### ISSUE THREAD

**Issue by IvayloAtanasov** [jaredpalmer/razzle#1120]
I think there's a missing call to `Loadable.preloadAll()` in the [with-react-loadable](https://github.com/jaredpalmer/razzle/blob/master/examples/with-react-loadable/src/server.js#L19) example.

I imagine something like this:

```
server
  .disable('x-powered-by')
  .use(cookieParser())
  .use(compression())
  .use(express.static(process.env.RAZZLE_PUBLIC_DIR))
  .get('/*', (req, res) => {
    Loadable.preloadAll().then(() => {
      const context = {};
      const modules = [];
      const markup = renderToString(
        <Capture report={(moduleName) => modules.push(moduleName)}>
          <StaticRouter context={context} location={req.url}>
            <App />
          </StaticRouter>
        </Capture>
      );

    ...
```

[This step](https://github.com/jamiebuilds/react-loadable#preloading-all-your-loadable-components-on-the-server) is important and I was not able to SSR the bundles without it. The bundle loading is asynchronous, therefore they need to be present before being synchronously rendered with `renderToString`.

I was not able to load them outside the api route. As far as I see razzle's webpack dev server does not give me a chance to attach custom middleware (app.use) on initialization. So I've placed the preloading in the route itself.

This may seem like a heavy task to be executed in the api route. However, it seems like calling preloadAll on every single request should not impact performance. As you can see [here](https://github.com/jamiebuilds/react-loadable/blob/master/src/index.js#L307), loadable initializers (ALL_INITIALIZERS) should be empty on every subsequent request.

**Comment by finmavis** [comment]
You mean [Preload in here](https://github.com/jaredpalmer/razzle/blob/master/examples/with-react-loadable/src/index.js) ?
