### ISSUE TITLE
Production build doesen't optimize?

### ISSUE THREAD

**Issue by Borming** [jaredpalmer/razzle#1121]
I see in my production build that i still have console.log, code comments etc. Is there a way to tell Razzle to do production build like it should?

**Comment by PabloValor** [comment]
I guess razzle in prod mode won't remove the console.log statements.

**Comment by nimaa77** [comment]
@Borming hello, I think you are loading .map files and you just checking files inside browser...
and razzle won't remove `console.log` statements by default, but you can tweak it a little to handle this ...
