### ISSUE TITLE
hot reload error: sockjs.js: line 1606 GET CLIENT_PUBLIC_PATH/sockjs-node/info?t=... net::ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by laurencefass** [jaredpalmer/razzle#1124]
type: bug report.
browsers: chrome and firefox latest
port: default port 3000
report: Hot module reload says its working to be working but i have to hit page refresh to see the update. Please note the site is running behind a nginx proxy but this hasnt affected other react and next apps running ok on different ports.

here is the server log on saving a change to a file.... looks like its working.

1|razzle  | ℹ Compiling Client
1|razzle  | ℹ Compiling Server
1|razzle  | ✔ Server: Compiled successfully in 389.42ms
1|razzle  | ✔ Client: Compiled successfully in 413.53ms
1|razzle  | ℹ Compiling Client
1|razzle  | 🔁  HMR Reloading `./server`...
1|razzle  | [HMR] Updated modules:
1|razzle  | [HMR]  - ./src/Home.js
1|razzle  | [HMR]  - ./src/App.js
1|razzle  | [HMR]  - ./src/server.js
1|razzle  | [HMR] Update applied.
1|razzle  | ✔ Client: Compiled successfully in 526.55ms

thanks

**Comment by laurencefass** [comment]
here is the log when i start the app. certainly looks like the HMR is working.

```
0|razzle   | ℹ Compiling Client
0|razzle   | ℹ ｢wds｣: Project is running at http://apps.syntapse.co.uk:3001/
0|razzle   | ℹ ｢wds｣: webpack output is served from undefined
0|razzle   | ℹ ｢wds｣: Content not from webpack is served from /app/razzle/razzle
0|razzle   | ℹ ｢wds｣: 404s will fallback to /index.html

0|razzle  | ✔ Client: Compiled successfully in 7.12s
0|razzle  | ℹ Compiling Server
0|razzle  | ✔ Server: Compiled successfully in 540.83ms
0|razzle  | Warning: Please use `require("react-router-dom").Route` instead of `require("react-router-dom/Route")`. Support for the latter will be removed in the next major release.
0|razzle  | Warning: Please use `require("react-router-dom").Switch` instead of `require("react-router-dom/Switch")`. Support for the latter will be removed in the next major release.
0|razzle  | * TRACE: js = https://apps.syntapse.co.uk/razzle/static/js/bundle.js
0|razzle  | * TRACE: css=undefined
0|razzle  | * TRACE: RAZZLE_PUBLIC_DIR=/app/razzle/razzle/public
0|razzle  | * TRACE: CLIENT_PUBLIC_PATH=https://apps.syntapse.co.uk/razzle/
0|razzle  | * TRACE: PUBLIC_PATH=https://razzle.syntapse.co.uk/
0|razzle  | * TRACE: REACT_BUNDLE_PATH=undefined
0|razzle  | ✅  Server-side HMR Enabled!
0|razzle  | 🚀 started
```

**Comment by laurencefass** [comment]
the page is making repeated failed calls to socket url. looks like the page is polling for changes?

console.log error:

```
"sockjs.js:1606 GET https://apps.syntapse.co.uk:3001/sockjs-node/info?t=1572018247174 net::ERR_SSL_PROTOCOL_ERROR"

and

The development server has disconnected. Refresh the page if necessary.
(from webpackHotDevClient.js:76)
```

network info:

url=https://apps.syntapse.co.uk:3001/sockjs-node/info?t=1571847228425
status=failed
type=xhr
initiator=sockjs.js:1606

header info:

```
General:
Request URL: https://apps.syntapse.co.uk:3001/sockjs-node/info?t=1571847232592
Referrer Policy: no-referrer-when-downgrade
```
and
```
Request headers:
Provisional headers are shown
DNT: 1
Origin: https://razzle.syntapse.co.uk
Referer: https://razzle.syntapse.co.uk/?fbclid=IwAR2sdhz9TCnS_Eevqxb-gKx2y5PALzK3balX-lYtwmM21CAad6G77GneJzQ
Sec-Fetch-Mode: cors
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
```
and

```
Query String Parameters
t: 1571847232592
```

**Comment by laurencefass** [comment]
Also....

Where would i see socket error failures on the server if there are any? Are they included in the tests?
Is the browser polling the server for for changes?

**Comment by fivethreeo** [comment]
I have the same issue. Do you use any code splitting?

**Comment by laurencefass** [comment]
Nothing outside the most basic create-razzle-app code and config.

**Comment by fivethreeo** [comment]
I made it work now. Do you have a repo I could look at?

**Comment by laurencefass** [comment]
No repo to show but this is the basic create-razzle-app so i havent added anything. The problem must be configuration.  

To confirm: have you made hot reload work? If so may I ask what changes you have made. My docker-compose config very similar to yours and using the same env vars so shouldnt be wildly different.

thanks

**Comment by laurencefass** [comment]
The only changes I have made from the default app is addition of .env file. 

.env file looks like this:
```
HOST='apps.syntapse.co.uk'
PORT=3000
VERBOSE='true'
NODE_ENV='production'
BUILD_TARGET='server'
PUBLIC_PATH='https://after.syntapse.co.uk/'
CLIENT_PUBLIC_PATH='https://apps.syntapse.co.uk/'
NODE_ENV='development'
```

the app is behind nginx reverse proxy:

```
server {
     listen 80;
     server_name apps.syntapse.co.uk;
      location / {
         proxy_pass http://0.0.0.0:3001;
         proxy_http_version 1.1;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection 'upgrade';
         proxy_set_header Host $host;
         proxy_cache_bypass $http_upgrade;
      }    	
 }

#razzle.js
server {
    listen 80;
    server_name razzle.syntapse.co.uk;
    location / {
        proxy_pass http://0.0.0.0:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
     }    	
}

```
i can only guess (hope) there is another env var needed to get sockets working as https://apps.syntapse.co.uk:3001/sockjs-node/info?t=1571847232592 fails.

**Comment by fivethreeo** [comment]
I disabled code splitting in dev and fixed the træfik routing.

PathPrefixStrip here https://github.com/fivethreeo/react-ssr-django-jwt-docker/blob/master/docker-compose.dev.yml#L82

Custom env vars here
https://github.com/fivethreeo/react-ssr-django-jwt-docker/blob/master/docker-compose.dev.yml#L91

Client here
https://github.com/fivethreeo/react-ssr-django-jwt-docker/blob/master/src/client.js#L70

Patching here to get rid of the 3001
https://github.com/fivethreeo/react-ssr-django-jwt-docker/blob/master/razzle.config.js#L47

**Comment by laurencefass** [comment]
# Env vars required for hot reloading
      RAZZLE_HOTCLIENT_NOPORT: "true"
      RAZZLE_DISABLE_CODESPLIT: "true"

Are these already defined in the default create-razzle-app or have you defined them for your own patch?

**Comment by fivethreeo** [comment]
Well, how did you mount your code in docker? Your client should be ok already. If you forward 3001 patch and prefixstrip are not needed. RAZZLE_HOTCLIENT_NOPORT in the patch. RAZZLE_DISABLE_CODESPLIT i use in razzle-config.js and client since i use code splitting. So your code should work already. Can you post your client.

**Comment by laurencefass** [comment]
thanks by client do you mean client.js file?

everything is default apart from .env file.

```
import React from 'react';
import { hydrate } from 'react-dom';
import { BrowserRouter } from 'react-router-dom';
import { ensureReady, After } from '@jaredpalmer/after';
import './client.css';
import routes from './routes';

ensureReady(routes).then(data =>
  hydrate(
    <BrowserRouter>
      <After data={data} routes={routes} />
    </BrowserRouter>,
    document.getElementById('root')
  )
);

if (module.hot) {
  module.hot.accept();
}

```

**Comment by fivethreeo** [comment]
Yes

**Comment by fivethreeo** [comment]
Ah, ensureready breaks it

**Comment by laurencefass** [comment]
? does that mean the default create-razzle-app is broken?

**Comment by fivethreeo** [comment]
It means the after example is broken.

**Comment by laurencefass** [comment]
apologies here is the default create-razzle-app client.js used in the original post.

```
import App from './App';
import BrowserRouter from 'react-router-dom/BrowserRouter';
import React from 'react';
import { hydrate } from 'react-dom';

hydrate(
  <BrowserRouter>
    <App />
  </BrowserRouter>,
  document.getElementById('root')
);

if (module.hot) {
  module.hot.accept();
}

```

**Comment by fivethreeo** [comment]
That should work

**Comment by laurencefass** [comment]
i don't want to get off-topic but are you able to explain why the after.js example is broken, and do you think its worth raising separate issue?

**Comment by fivethreeo** [comment]
I think jared himself is dropping after.js as it is now. React core will add better serverside code splitting and suspense for data fetching soon so not much use for after.js. So there fix would be remove the example.

**Comment by fivethreeo** [comment]
Broken hot module reloading that is. The rest works.

**Comment by fivethreeo** [comment]
Bu if you limit to one chunk in dev and just hydrate without the ensureReady it will work for dev and code split and use ensureReady in production.

**Comment by laurencefass** [comment]
this is a complete record of the errors generated on the browser. there are some hard-coded references to http:// in here most likely cause of errors.

```

abstract-xhr.js:132 GET https://razzle.syntapse.co.uk:3001/sockjs-node/info?t=1572283653134 net::ERR_SSL_PROTOCOL_ERROR
./node_modules/sockjs-client/lib/transport/browser/abstract-xhr.js.AbstractXHRObject._start @ abstract-xhr.js:132
(anonymous) @ abstract-xhr.js:21
setTimeout (async)
AbstractXHRObject @ abstract-xhr.js:20
XHRCorsObject @ xhr-cors.js:8
InfoAjax @ info-ajax.js:19
./node_modules/sockjs-client/lib/info-receiver.js.InfoReceiver._getReceiver @ info-receiver.js:39
./node_modules/sockjs-client/lib/info-receiver.js.InfoReceiver.doXhr @ info-receiver.js:56
(anonymous) @ info-receiver.js:25
setTimeout (async)
InfoReceiver @ info-receiver.js:24
SockJS @ main.js:121
(anonymous) @ webpackHotDevClient.js:61
./node_modules/razzle-dev-utils/webpackHotDevClient.js @ webpackHotDevClient.js:274
__webpack_require__ @ bootstrap:726
fn @ bootstrap:100
1 @ react.svg:1
__webpack_require__ @ bootstrap:726
(anonymous) @ bootstrap:793
(anonymous) @ bootstrap:793
webpackHotDevClient.js:76 The development server has disconnected.
Refresh the page if necessary.

and

The development server has disconnected. Refresh the page if necessary.
(from webpackHotDevClient.js:76)
```

**Comment by fivethreeo** [comment]
Post your razzle-config.js too

**Comment by laurencefass** [comment]
i havent defined any razzle-config.js at all. Im trying to make it work with simplest possible configuration. Is there any basic config required for docker but not documented?

only change i have made to create-razzle-app is the .ext file. trying to start as simple as possible.

ps: big thanks for your help on this. documentation is sparse and I am by no means an expert in webpack... i hope this trail helps others getting started...

**Comment by fivethreeo** [comment]
How does port 3001 reach docker?

**Comment by laurencefass** [comment]
I've published a range of ports starting 3000 in my docker-compose file. 3001 is def exposed to the world because the client is using it to get the bundle.js file.

```
services:
  apps:
    container_name: apps
    hostname: apps.syntapse.co.uk
    ports:
    - "3000-3010:3000-3010"
    expose:
    - "80"
```
ive set up DNS to route apps.syntapse.co.uk requests through to this container and nginx takes care of the redirects.

**Comment by fivethreeo** [comment]
Then you need to use http not https if this is your actual setup.

**Comment by laurencefass** [comment]
The nginx reverse-proxy for the razzle app is sitting behind a higher level reverse proxy that provides https to a range of containers. To the outside world they are all https though they are all configured locally as http. The top level reverse proxy does the SLL conversion. 

However I fix it I need the razzle docker container to remain https:// to the outside world.

**Comment by fivethreeo** [comment]
Ah then you need a razzle.config.js.

```js

'use strict';

module.exports = {
  modify: (defaultConfig, { target, dev }, webpack) => {
    const config = defaultConfig;

    if (target === 'web' && dev) {
      config.devServer.public = 'localhost:443';
    }
    return config;
};
```

**Comment by fivethreeo** [comment]
Try this one :)

https://github.com/fivethreeo/razzle-with-docker-nginx

**Comment by laurencefass** [comment]
most likely cause of issues:

initsocket in socketjs is calling http:// address this is destined to fail as the site is only accessible via browser as http.

is there some socket specific config that is not been documented in Razzle config?

```
initSocket | @ | socket.js:20
-- | -- | --
  | (anonymous) | @ | client:176
  | ./node_modules/webpack-dev-server/client/index.js?http://apps.syntapse.co.uk:3001 | @ | client:176
```

**Comment by laurencefass** [comment]
solved in https://github.com/jaredpalmer/razzle/issues/1144
