### ISSUE TITLE
What is the correct way to prefetch data on the server before component SSR?

### ISSUE THREAD

**Issue by laurencefass** [jaredpalmer/razzle#1129]
Im evaluating razzle after using next.js which employs Component.getInitialProps() to prefetch data on the server prior to SSR.

Whats the correct way to do server side fetch and ssr components with Razzle?

thanks

**Comment by adambisek** [comment]
I am using it with Apollo.

https://www.apollographql.com/docs/react/performance/server-side-rendering/

**Comment by laurencefass** [comment]
Thanks Adam is there a recommended place/hook to do the fetch on the server before component is rendered similar to next.getInitialProps? 
thanks.

**Comment by laurencefass** [comment]
After.js looks very promising.

**Comment by amstel5212** [comment]
> Thanks Adam is there a recommended place/hook to do the fetch on the server before component is rendered similar to next.getInitialProps?
> thanks.

@laurencefass Could you please give me link to your example?
