### ISSUE TITLE
support for running in docker container and access through SSL (https://)

### ISSUE THREAD

**Issue by laurencefass** [jaredpalmer/razzle#1132]
The simple instructions to install and run razzle are specific to running AND browsing the app on localmachine:3000. i am evaulating this for the first time for three days with no progress and no notable error logs, though everything that can fail has failed (hot module reload not working, errors adding new npm packages, and bundle.js mixed-content errors failing to load styling as I am running https). There are no useful error logs to suggest anything is misconfigured and it was broken on installation (into a docker container behind an nginx proxy). Has anyone had any success running from a docker container and accessing the site through a remote browser that does not have direct access to localhost on the razzle server?

thanks

**Comment by fivethreeo** [comment]
Check out: https://github.com/fivethreeo/react-ssr-django-jwt-docker, only hmr on client not working, yet hopefully.

**Comment by laurencefass** [comment]
Thanks I would like to try to start with the most basic installation alongside a set of working Next and CRA live reload apps but cant seem to get started and no obvious online support channel. Is there some docker config missing from the documentation?  It doesnt appear to "just work" as other libraries have. I can't see any notes on docker support or for installation prerequisites . I cant find any notes for using on non-localhost and a bit puzzled by why the home page is trying to pull svg files and bundle.js files from an http address? 

My setup: I am using nginx to redirect Razzle, CRA and Next domain requests to respective ports and this automatically takes care of 3000 redirect. To enable 3001 access I have had to (i) publish 3001 port in docker-compose (ii) add Razzle's container hostname as a DNS record, and (iii) add the hostname to the .env file containing Razzles env vars.

I am glad of your assistance, thank you for your patience.

**Comment by fivethreeo** [comment]
For the address it is trying to pull the svg from. Look here https://github.com/fivethreeo/react-ssr-django-jwt-docker/blob/master/docker-compose.staging.yml#L51, theese are env vars that need to be set at build time. For 3001 port it is a bit more cumbersome since it is always process.env.PORT at build time + 1 or current port in browser + 1. You could put 3001 at another path and use sub filter to replace the port in the code https://github.com/jaredpalmer/razzle/blob/master/packages/razzle-dev-utils/webpackHotDevClient.js#L62 or fork razzle. I wish there was a better way. ;)

**Comment by laurencefass** [comment]
thanks based on your info i have set up an .env file in the project root directory (same level as package.json)

```
HOST='apps.syntapse.co.uk'
PORT=3000
VERBOSE='true'
NODE_ENV='production'
BUILD_TARGET='server'
PUBLIC_PATH: 'https://razzle.syntapse.co.uk'
CLIENT_PUBLIC_PATH: 'https://apps.syntapse.co.uk'
```

the log is still pointing to http address.

```
0|razzle   | ℹ ｢wds｣: webpack output is served from undefined
0|razzle   | ℹ ｢wds｣: Content not from webpack is served from /app/razzle/razzle
0|razzle   | ℹ ｢wds｣: 404s will fallback to /index.html
0|razzle   | ✔ Client: Compiled successfully in 6.79s
0|razzle   | ℹ Compiling Server
0|razzle   | ✔ Server: Compiled successfully in 375.09ms
0|razzle   | * TRACE: js = http://apps.syntapse.co.uk:3001/static/js/bundle.js
0|razzle   | * TRACE: css=undefined
0|razzle   | * TRACE: public dir=/app/razzle/razzle/public
0|razzle   | ✅  Server-side HMR Enabled!
0|razzle   | 🚀 started
0|razzle   |
0|razzle   | > my-razzle-app@0.1.0 start /app/razzle/razzle
0|razzle   | > razzle start
0|razzle   |

0|razzle  |  WAIT  Compiling...
0|razzle  | ℹ Compiling Client
0|razzle  | ℹ ｢wds｣: Project is running at http://apps.syntapse.co.uk:3001/
0|razzle  | ℹ ｢wds｣: webpack output is served from undefined
0|razzle  | ℹ ｢wds｣: Content not from webpack is served from /app/razzle/razzle
0|razzle  | ℹ ｢wds｣: 404s will fallback to /index.html
0|razzle  | ✔ Client: Compiled successfully in 4.43s
0|razzle  | ℹ Compiling Server
0|razzle  | ✔ Server: Compiled successfully in 375.51ms
0|razzle  | Warning: Please use `require("react-router-dom").Route` instead of `require("react-router-dom/Rout0|razzle  | Warning: Please use `require("react-router-dom").Switch` instead of `require("react-router-dom/Swi0|razzle  | * TRACE: js = http://apps.syntapse.co.uk:3001/static/js/bundle.js
0|razzle  | * TRACE: css=undefined
0|razzle  | * TRACE: public dir=/app/razzle/razzle/public
0|razzle  | ✅  Server-side HMR Enabled!
0|razzle  | 🚀 started
```

and bundle.js remains blocked on the SSL page.

Request URL: **http://apps.syntapse.co.uk:3001/static/js/bundle.js**
Referrer Policy: no-referrer-when-downgrade

Razzle is not respecting the client path.

**Comment by laurencefass** [comment]
working! @fivethreeo sincere and massive thanks for you advice.

```
HOST='apps.syntapse.co.uk'
PORT=3000
VERBOSE='true'
NODE_ENV='production'
BUILD_TARGET='server'
PUBLIC_PATH='https://razzle.syntapse.co.uk'
CLIENT_PUBLIC_PATH='https://apps.syntapse.co.uk'
```

still doesn't resolve the extra (3001) port requirement but i've got enough to continue with evaluation for now.

**Comment by fivethreeo** [comment]
Got a fix for you here :)

https://gist.github.com/fivethreeo/48558e2bf0ec228af4b4763d4199df0c
