### ISSUE TITLE
Badges not loading.

### ISSUE THREAD

**Issue by danialmalik** [jaredpalmer/razzle#1137]
Badges on README are not being loaded correctly. Please look into that.

![image](https://user-images.githubusercontent.com/42166091/67465488-b6752500-f65e-11e9-8c25-cfa0f61f8adf.png)

**Comment by nimaa77** [comment]
sure, I will go for fixing this later tonight

**Comment by fivethreeo** [comment]
Updated badges. Seems to load fine now.
