### ISSUE TITLE
Unable to include /location after CLIENT_PUBLIC_PATH to enable nginx proxy redirects using location block.

### ISSUE THREAD

**Issue by laurencefass** [jaredpalmer/razzle#1139]
I want to use nginx to proxy multiple (N) Razzle dev apps and their dev client ports.

Problem summary:  I want to use a nginx server block with mutliple locations to redirect /location requests based on the CLIENT_PUBLIC_PATH definitions of my apps to active ports but I am  limited to domain only definitions of CLIENT_PUBLIC_PATH. e.g. http:/myapp.com/ delivers the correct bundle.js file but http:/razzle.dom/myapp/ results in a 404 with correct nginx routing. I quite sure nginx is doing the correct routing but the static output isnt available.

Here is my .env config for the first project. Ports increment in 2's for new apps.

```
PORT=3000
PUBLIC_PATH='https://razzle1.syntapse.co.uk/'
CLIENT_PUBLIC_PATH='https://apps.syntapse.co.uk/razzle1/'
```

second app...

```
PORT=3002
PUBLIC_PATH='https://razzle1.syntapse.co.uk/'
CLIENT_PUBLIC_PATH='https://apps.syntapse.co.uk/razzle2/'
```

etc.

The apps.syntapse.co.uk URL is common to all razzle dev apps to redirect requests to the correct +1 port and routing is defined in nginx.  Here is a two razzle app configuration:

```
/ * redirects for client +1 port */
server {
     listen 80;
     server_name apps.syntapse.co.uk;
     location /razzle2 {
         proxy_pass http://0.0.0.0:3003;
         proxy_http_version 1.1;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection 'upgrade';
         proxy_set_header Host $host;
         proxy_cache_bypass $http_upgrade;
      }    	
    ...
     location /razzle1 {
         proxy_pass http://0.0.0.0:3001;
         proxy_http_version 1.1;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection 'upgrade';
         proxy_set_header Host $host;
         proxy_cache_bypass $http_upgrade;
      }    	
 }

#after.js
server {
    listen 80;
    server_name razzle2.syntapse.co.uk;
    location / {
        proxy_pass http://0.0.0.0:3002;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
     }    	
}

#razzle.js
server {
    listen 80;
    server_name razzle1.syntapse.co.uk;
    location / {
        proxy_pass http://0.0.0.0:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
     }    	
}
```
However this doesnt work because though the client points to the correct address the result is a 404. It appears that webpack is not respecting the CLIENT_PUBLIC_PATH?

browser request:

```
General
Request URL: https://apps.syntapse.co.uk/razzle/static/js/bundle.js
Request Method: GET
Status Code: 404 
Remote Address: 51.38.71.147:443
Referrer Policy: no-referrer-when-downgrade
```

Expected result:
I expected Razzle to generate static data at the CLIENT_PUBLIC_PATH/static/bundle.js if the nginx server_name/location block matches the CLIENT_PUBLIC_PATH in the env file. This doesnt work.

Actual result:
Razzle client is trying to pull a bundle from the CLIENT_PUBLIC_PATH/static/ location resulting in a 404.

If I change the CLIENT_PUBLIC_PATH to work with nginx locations how can i also change Razzle's configuration to output to CLIENT_PUBLIC_PATH/static/bundle.js so that the server can respond with the correct file?

thanks

**Comment by laurencefass** [comment]
I have tried setting REACT_BUNDLE__PATH and HOST to;

HOST='apps.syntapse.co.uk'
REACT_BUNDLE_PATH="/razzle/static/js/bundle.js"

in the hope to eliminate the 404 and have the bundle output to CLIENT_PUBLIC_PATH/REACT_BUNDLE_PATH but this doesnt work

**Comment by fivethreeo** [comment]
Try changing

```nginx
     location /razzle1 {
         proxy_pass http://0.0.0.0:3001;
         proxy_http_version 1.1;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection 'upgrade';
         proxy_set_header Host $host;
         proxy_cache_bypass $http_upgrade;
      }    	

```

to

```nginx
     location /razzle1 {
         proxy_pass http://0.0.0.0:3001/;
         proxy_http_version 1.1;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection 'upgrade';
         proxy_set_header Host $host;
         proxy_cache_bypass $http_upgrade;
      }    	

```

Note the /, then the devserver thinks it is at / and not /razzle1

**Comment by laurencefass** [comment]
worked! 
closing as this was nginx support query.
sincere thanks @fivethreeo

**Comment by fivethreeo** [comment]
Glad I could help :)
