### ISSUE TITLE
Razzle momentarily rendering the page before styling is applied

### ISSUE THREAD

**Issue by laurencefass** [jaredpalmer/razzle#1140]
I'm using default create-razzle-app using the default components and css. The page content is being loaded and displayed before styling is rendered. 

This is not a good UX experience. Would it make more sense to load the bundle so all styling is available before rendering an unstyled page?

thanks

**Comment by fivethreeo** [comment]
This is only in dev since everything is loaded via js.

**Comment by laurencefass** [comment]
thanks.
