### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by laurencefass** [jaredpalmer/razzle#1147]
environment: dev with HMR enabled and working

`[HMR] Waiting for update signal from WDS.`

followed by 

`Uncaught SyntaxError: Unexpected token '<'`

![image](https://user-images.githubusercontent.com/3512857/67935961-ce9af600-fbc2-11e9-942c-70941de4f7a2.png)

**Comment by feruzm** [comment]
What was the cause?
