### ISSUE TITLE
Razzle + razzle typescript plugin + babel typescript plugin - how to combine?

### ISSUE THREAD

**Issue by mz8i** [jaredpalmer/razzle#1149]
I am using razzle with TypeScript. I wanted to use https://github.com/milesj/babel-plugin-typescript-to-proptypes to generate React propTypes based on TS types, but I cannot seem to get the combination of all the elements to work. What am I missing? Is this related to razzle or not?

My `razzle.config.js`:
```
module.exports = {
    plugins: [
        {
            name: 'typescript',
            options: {
                useBabel: true
            }
        }
    ],
    modify: (config, { target, dev }, webpack) => {
        // load webfonts
        rules = config.module.rules || [];
        rules.push({
            test: /\.(eot|svg|ttf|woff|woff2)$/,
            loader: 'file-loader?name=public/fonts/[name].[ext]'
        })
        config.module.rules = rules;

        return config;
    },
};
```

My `.babelrc`:
```
{
    "presets": ["razzle"],
    "plugins": ["babel-plugin-typescript-to-proptypes"]
}
```

TS is transpiled correctly, but generated `propTypes` for components are missing.

**Comment by mz8i** [comment]
I figured out what the problem was: `babel-plugin-typescript-to-proptypes` needs Babel to transform TS files into TS. Meanwhile, the `razzle-typescript` plugin with `useBabel: true` sets up `babel-loader` to run after `ts-loader` for `.ts(x)` files.

The solution for me was to modify the webpack config generated by the Razzle typescript plugin so that `babel-loader` actually runs before `ts-loader`, not after. I guess the takeaway is that using the loaders in such an order is a valid (albeit probably niche) use-case - perhaps the order of loaders could be configured through a plugin option? I believe there are other Babel plugins that transform TS to TS, and so would need to be used before `ts-loader`

**Comment by nimaa77** [comment]
take look at my plugin: [razzle-plugin-babel-ts](https://www.npmjs.com/package/razzle-plugin-babel-ts)
