### ISSUE TITLE
Basic react router 5 example with default create-razzle-app

### ISSUE THREAD

**Issue by laurencefass** [jaredpalmer/razzle#1153]
I'm still learning how Razzle works. I am seeking a default create-razzle-app with react router 4 example. The default create-razzle-app doesnt have any routes configured.

I've been testing with after.js example as an "out-the-box" routing solution but i need to retro-fit a router into basic create-razzle-app example and other examples that do not use after.js routing.

Live example: https://razzle.syntapse.co.uk/router-dev/

The Routes object in the router-3 example is basic and has no history and no base path. I'm using a domain/path to access the router-3 app so it wasn't working by default.

as a first step i've modified routes.js to include a history item with a base name. this gives me basic traversal with <Link>s.

routes.js

```
import { createMemoryHistory } from 'history';
const customHistory = createMemoryHistory({ basename: '/router-dev' });;

const Routes = props => {
  return (
    <Router history={customHistory} {...props}  >
      <Route path="/" component={Home} />
      <Route path="home" component={Home} />
      <Route path="about" component={About} />
      <Route path="demo" component={Demo} />
    </Router>
  );
}; 
```

and Im navigating elsewhere with <Link> e.g.

```
          <div>
            <Link to="/">Home</Link>
            <Link to="about">About</Link>
            <Link to="demo">Demo</Link>
          </div>
```

This works for <Link> traversal but the browser navigation is broken. Also the page refresh on navigation is very choppy and untidy and does not create a good UX. Compare to after.js example:

Live example of after.js example (smooth rendering with working browser navigation): 

https://razzle.syntapse.co.uk/after-dev/

Compared to router3 example (choppy rendering with broken browser navigation):  

https://razzle.syntapse.co.uk/router-dev/

Any help or advice will be greatly appreciated.

Thanks

**Comment by fivethreeo** [comment]
Show how you render in client.js

**Comment by laurencefass** [comment]
im closing this issue and going to concentrate on getting <Link>s working default create-razzle-app. i notice it doesnt have history (something i tried to add) before i discovered a "working" router example. I think the default create-razzle-app should work with routes but the router example offers a different solution...

default razzle:

```
import App from './App';
import BrowserRouter from 'react-router-dom/BrowserRouter';
import React from 'react';
import { hydrate } from 'react-dom';

hydrate(
  <BrowserRouter>
    <App />
  </BrowserRouter>,
  document.getElementById('root')
);

if (module.hot) {
  module.hot.accept();
}

```

router 3 example (from here: https://github.com/jaredpalmer/razzle/blob/master/examples/with-react-router-3/src/client.js)

```
import React from 'react';
import Routes from './routes';
import { hydrate } from 'react-dom';

hydrate(<Routes />, document.getElementById('root'));

if (module.hot) {
  module.hot.accept();
}
```

and routes.js is 

```
import React from 'react';
import { Router, Route, browserHistory } from 'react-router';

import Home from './Home';
import About from './About';

const Routes = props => {
  return (
    <Router history={browserHistory} {...props}>
      <Route path="/" component={Home} />
      <Route path="home" component={Home} />
      <Route path="about" component={About} />
    </Router>
  );
};

export default Routes;
```

no browser router....?
