### ISSUE TITLE
jest __tests__ folder being picked up for webpack build

### ISSUE THREAD

**Issue by elliottjro** [jaredpalmer/razzle#1160]
Given folder structure:
```
src
|-- config
|-- |-- __tests__
|-- |-- |-- config.test.js
|-- |--  staging.js
|-- |--  production.js
```

when you run `razzle start` it should not include `config.test.js` in the final build but it does.

Tried to add something like this to `razzle.config.js` but no dice:
```js
modify: (config, ...) => {
  config.modules.rules.push({
    test: /test\.js$/,
    exclude: 'src/config/__tests__/config.test.js'
  })
  return config
}
```

**Comment by fivethreeo** [comment]
What about?

```js
modify: (config, ...) => {
  config.modules.rules.unshift({
    test: /test\.js$/,
    exclude: 'src/config/__tests__/config.test.js'
  })
  return config
}
```

**Comment by nimaa77** [comment]
@elliottjro @fivethreeo any updated on this?

**Comment by fivethreeo** [comment]
My answer might be wrong, maybe needs to change the babel-loader rule. Have not had this issue myself.

**Comment by fivethreeo** [comment]
Is this still a issue, closing for now reopen if it is.
