### ISSUE TITLE
Autoprefixer removing certain prefixes.

### ISSUE THREAD

**Issue by VikalpP** [jaredpalmer/razzle#1161]
**Type**: bug

### Description 
While using `-webkit-box-orient` css property in scss it's being removed by autoprefixer.
For more context, check out an issue related this on lib/ autoprefixer — https://github.com/postcss/autoprefixer/issues/1220

### Possible Solution
Update `autoprefixer` package dependency as that issue has been fixed in `autoprefixer v9.6.1`. Currently being used older version `8.6.2`.

**Comment by fivethreeo** [comment]
Fixed in dev
