### ISSUE TITLE
css bundle hash is always the same

### ISSUE THREAD

**Issue by anz000** [jaredpalmer/razzle#1164]
Whenever I build the css bundle, the calculated hash is always the same even if I change the content. I'm using the default razzle setup. [ Note : the js bundle hash gets updated even with no changes ]

I'm currently attempting to override the functionality to see if anything changes.
I can't seem to make this work `value instanceof MiniCssExtractPlugin` . 
```

'use strict';
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = {
    modify(config, { target, dev }, webpack) {
        const appConfig = config; // stay immutable here

        const updatedCssPlugin = new MiniCssExtractPlugin({
            filename: 'static/css/[name].[contenthash:2].css',
            allChunks: true,
            chunkFilename: 'static/css/[id].[contenthash:8].css',
            sourceMap: false
        });

        const plugins = [];

        appConfig.plugins.forEach( value => {
            console.log(value instanceof MiniCssExtractPlugin);
            if(value instanceof MiniCssExtractPlugin){
                plugins.push(updatedCssPlugin);
            } else {
                plugins.push(value);
            }
        });
        appConfig.plugins = plugins;

        return appConfig;
    },
};
```

Any other way to override or what could have gone wrong on this whole css hash generation?

**Comment by fivethreeo** [comment]
Does:

typeof value === 'function' &&  value.constructor.name === 'MiniCssExtractPlugin'

Work?

**Comment by fivethreeo** [comment]
```javascript

'use strict';

module.exports = {
  modify(config, { target, dev }, webpack) {
    const appConfig = config; // stay immutable here
    appConfig.plugins.map( value => {
        console.log(target)
        console.log(typeof value)
        console.log(value.constructor.name)
        console.log(value)
        
    });
    return appConfig;
  }
};

```
So:

```javascript
typeof value === 'object' && value.constructor.name === 'MiniCssExtractPlugin'
```

But about the contenthash not changing, I have no ideas yet.

**Comment by anz000** [comment]
Yeah, that fulfills the condition. Thanks.

The bundle hash is working in the default razzle app. To add more details, my css files are all inline in the js files except `App.css` and `index.css`. I changed the contents of these files, and I see a different hash generated.

So, my assumption now is that my inline css contents are not in the css bundle, but in js bundle.

My styles are mostly like this inside the js files:
```
const Label = styled(`div`)`
  ${sv.label};
  color: ${sv.colors.grey};
  margin: 8px 0;
  text-transform: none;
`;
```

**Comment by nimaa77** [comment]
I think this issue is resolved and I'm going to close it.
if you think it's a mistake just reopen it
