### ISSUE TITLE
Add a default service-worker

### ISSUE THREAD

**Issue by anz000** [jaredpalmer/razzle#1165]
Any updates on [ Implement Service Worker caching ] - https://github.com/jaredpalmer/razzle/issues/276  ? 

Or, I'd love to hear about any workarounds people have figured out. Thanks.

**Comment by fivethreeo** [comment]
I could try doing a razzle plugin if someone tells/shows me a example of how it should work.

**Comment by anz000** [comment]
Some one has a plugin related to this @ https://www.npmjs.com/package/razzle-plugin-serviceworker . I couldn’t get it to work. I ran into some issues with the library it was running under the hood.

I ran through jared’s commit @ https://github.com/jaredpalmer/razzle/commit/e5a024831c29fc7ff7d0698de398845c3743cd8d . I could get the file service-worker.js to load in the browser, however I couldn't get it to work as expected. The commit is pretty self - explanatory of what he wanted to do.

**Comment by fivethreeo** [comment]
Did you try razzle-plugin-serviceworker with yarn start or yarn start:prod?

**Comment by fivethreeo** [comment]
https://github.com/NekR/offline-plugin/blob/master/docs/troubleshooting.md#offline-plugin-isnt-working-in-dev-mode

**Comment by anz000** [comment]
Nope. I had tested it on the build version. I even deployed it to my test server to test it.

**Comment by fivethreeo** [comment]
Using any other plugins or code splitting?

**Comment by anz000** [comment]
As it turns out, it was my mistake. I had put the `razzle.config.js` file inside the `src` directory but it was supposed to go in the `root` directory. 

I deployed and it's working. My only concern is previously it had `service-worker.js` file registered for the domain. The plugin creates `sw.js` by default. I hope that the updated service worker overwrites the old one on clients that had the old service-worker with a different name. I might as well override the name so that it is more clearer to people who might work on the project. Thanks.

**Comment by anz000** [comment]
Further update based on the behavior I saw:
[`service-worker.js` : old] & [`sw.js` : new]

After name change: 
On load, the `sw.js` doesn't gets installed, when `forceRefreshed` it gets installed but waits to be activated. The `service-worker.js` is still functioning. I load the application in a different tab, I see the same old content with `service-worker.js` still active. Hard Refresh didn't help too.

Closed all tabs that had the application running, and then hit the application. The `sw.js` is now active with the new contents.

The `sw.js` could have been activated forcefully (programmatically as well as through console). The `service-worker.js` was active because there were clients using it. If `sw.js` were allowed to be active rightaway then there would be two different version of the application in different tabs. Once `service-worker.js` is not serving any clients, then `sw.js` kicks in and becomes active.

I tried changing the `name` of the service-worker in `razzle.config.js` file, but couldn't get it working. I'm hoping that the service-worker will eventually expire on end-users browsers (looks like 1 day), and new one kick in.

**Comment by nimaa77** [comment]
consider using `workbox` package :)
it's easy and awesome

and I think you should move this issue to [razzle-plugin-serviceworker](https://github.com/gnarr/razzle-plugin-serviceworker#readme)

**Comment by NickCis** [comment]
On most projects that I've built with razzle, I end up copying create react app's workbox configuration and sw registration. 

I've written a razzle plugin that does just that: [`razzle-plugin-workbox`](https://github.com/NickCis/razzle-plugin-workbox) feel free to use it if you find it useful :)

**Comment by behnam-maqsudi** [comment]
@NickCis how can i use injectManifest in razzle-plugin-workbox?

**Comment by NickCis** [comment]
@benamm you can't. The plugin is just a wrapper for `WorkboxWebpackPlugin.GenerateSW`, you can check the source code [here](https://github.com/NickCis/razzle-plugin-workbox/blob/master/index.js). If you want to add the `injectManifest` feature, you can send the PR.
