### ISSUE TITLE
First E

### ISSUE THREAD

**Issue by nesbtesh** [jaredpalmer/razzle#1166]
The CSS never loads on first render of the page for new users

![Screen Shot 2019-11-21 at 12 41 07 PM](https://user-images.githubusercontent.com/3814044/69362309-4a391180-0c5c-11ea-9f12-100b02e8abd4.png)

**Comment by fivethreeo** [comment]
too little info, which example is this based on?

**Comment by nesbtesh** [comment]
We are having a consistent issue with Razzle, whenever the page loads for the first time in any device, it loads withouth the CSS and an issue with Javascirpt as you can see in the image above. You can try it at www.noritex.com

**Comment by fivethreeo** [comment]
In dev or production? Using any plugins? Using codesplitting? How is the client rendering? How is the bundle served?

**Comment by nesbtesh** [comment]
In Production, the only plugin we are using is the Heroku Plungin, and yes we are code splitting. The issue always happened even before we had code splitting

**Comment by fivethreeo** [comment]
I see a service worker on that page... This is probably not a issue with razzle but with the setup somehow. But without more details, the specific config used it is hard to say.

**Comment by nesbtesh** [comment]
This is my razzle.config

`'use strict';
// module.exports = {
//   modify: require("razzle-heroku"),
// }



const razzleHeroku = require('razzle-heroku');

module.exports = {
  modify(config, { target, dev }, webpack) {
    config = razzleHeroku(config, {target, dev}, webpack);
    return config;
  },
 
};`

and my server code, I am checking to see if there is a cached version, if there is I returned the cached path. If not I render as string and return the HTML content

`

endDate = new Date();
            seconds = (endDate.getTime() - startDate.getTime());
            console.log("time from start to all promises", seconds)
            const context = {};
            // Pass our routes and data array to our App component
            const markup = renderToString(
              <StaticRouter context={context} location={req.url}>
                <App routes={routes} initialData={data} initialToken={token} />
              </StaticRouter>
            );

            endDate = new Date();
            seconds = (endDate.getTime() - startDate.getTime());
            console.log("time from start to after react markup ready", seconds)
            
            const helmet = Helmet.renderStatic();
            var cache = [];
            let html = ""
            if (context.url) {
              res.redirect(context.url);
            } else {
              endDate = new Date();
              seconds = (endDate.getTime() - startDate.getTime());
              console.log("time from start to send response", seconds)
             
              html =  `<!doctype html>
              <html ${helmet.htmlAttributes.toString()}>
              <head>
                  <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
                  <meta charSet='utf-8' />
                  ${helmet.title.toString()}
                  ${helmet.meta.toString()}
                  ${helmet.link.toString()}
                  <meta name="viewport" content="width=device-width, initial-scale=1">
                  
                  <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
                  <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
                  <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
                  <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
                  <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
                  <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
                  <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
                  <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
                  <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
                  <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
                  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
                  <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
                  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
                  <link rel="manifest" href="/manifest.json">
                  <meta name="msapplication-TileColor" content="#ffffff">
                  <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
                  <meta name="theme-color" content="#ffffff">


                  ${assets.client.css
                    ? `<link rel="stylesheet" href="${assets.client.css}">`
                    : ''}
                    <script defer>
                      !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t,e){var n=document.createElement("script");n.type="text/javascript";n.async=!0;n.src="https://www.noritex.com/analytics.js/v1/"+t+"/analytics.min.js";var a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(n,a);analytics._loadOptions=e};analytics.SNIPPET_VERSION="4.1.0";
                      analytics.load("SOME TOKEN");
                      analytics.page();
                      }}();
                    </script>
                    <script>
                        if('serviceWorker' in navigator) {
                          navigator.serviceWorker
                                   .register('/sw.js')
                                   .then(function() { console.log("Service Worker Registered"); });
                        }
                    </script>
                  </head>
                  <body id="main-body"  ${helmet.bodyAttributes.toString()}> 
                      <div id="root">${markup}</div>
                      <script>window._INITIAL_DATA_ = ${JSON.stringify(data, function(key, value) {
                        if (typeof value === 'object' && value !== null) {
                            if (cache.indexOf(value) !== -1) {
                                // Duplicate reference found, discard key
                                return;
                            }
                            // Store value in our collection
                            cache.push(value);
                          } 
                          return value;
                        })};
                      </script>
                      <script src="${assets.client.js}" defer></script>
                  </body>

                  
                    <script defer type='text/javascript'>
                    (function(){ function trigger() { var widget_id = 'SOME TOKEN';
                        var s = document.createElement('script'); s.defer = true; s.type = 'text/javascript'; s.async = true; s.src = '//code.jivosite.com/script/widget/'+widget_id; var ss = document.getElementsByTagName('script')[0]; ss.parentNode.insertBefore(s, ss);
                      }
                      setTimeout(trigger, 5000);
                    })();
                    </script>
                    
              </html>`
              
            }
            if (res.statusCode !== 200) {
                res.send(html);
                return
            }
            if (token === "" || token == null) ssrCache.set(key, html);
            res.setHeader('x-cache', 'MISS');
            res.status(200).end(html, () => {
                endDate = new Date();
                seconds = (endDate.getTime() - startDate.getTime());
                console.log("time from start to end", seconds)
            });
          })
`

**Comment by fivethreeo** [comment]
I visited the page and it loaded well the first time. Could it be that the service worker is not up to date in your browser? Just grasping here 😀

**Comment by nimaa77** [comment]
I got the same results here and css loaded at the first time
