### ISSUE TITLE
undefined error message while create-razzle-app

### ISSUE THREAD

**Issue by sujishpradeep** [jaredpalmer/razzle#1169]
I have installed Razzle(v3.0.0). create-react-app is errors out while installing, with an undefined message.

Node version: v10.16.0

Creating my-razzle-app...

> Success! Created files for "my-razzle-app" razzle app

  Installing npm modules:
    react
    react-dom
    react-router-dom
    razzle
    express

**> Error! Failed to install react, react-dom, react-router-dom, razzle, express, try again.
undefined**

**Comment by AjayPoshak** [comment]
In my case, I'm getting this log
```
yarn run v1.19.1
$ razzle start
 WAIT  Compiling...


✔ Client
  Compiled successfully in 3.37s

✔ Server
  Compiled successfully in 341.05ms

ℹ ｢wds｣: Project is running at http://localhost:3001/
ℹ ｢wds｣: webpack output is served from undefined
ℹ ｢wds｣: Content not from webpack is served from /Users/ajayposhak/Projects/my-app
ℹ ｢wds｣: 404s will fallback to /index.html
Warning: Please use `require("react-router-dom").Route` instead of `require("react-router-dom/Route")`. Support for the latter will be removed in the next major release.
Warning: Please use `require("react-router-dom").Switch` instead of `require("react-router-dom/Switch")`. Support for the latter will be removed in the next major release.
✅  Server-side HMR Enabled!
🚀 started

```
But when I navigate to `http://localhost:3001/`, its showing a blank page, with `Error` as document title.

**Comment by jaredpalmer** [comment]
Do you have something running on port 3000?

**Comment by AjayPoshak** [comment]
Its showing the correct page, when I open `http://localhost:3000/`. But on terminal output, it asks to open `http://localhost:3001/` which has this error `Cannot GET /`.

**Comment by jeco123** [comment]
I got the same message :-)

**Comment by Nilomiranda** [comment]
I've got the same thing. Any update about this?

**Comment by vferdiansyah** [comment]
@AjayPoshak see https://github.com/jaredpalmer/razzle/issues/1182#issuecomment-576262469

**Comment by fivethreeo** [comment]
Should make it more clear in the console output. Just dig into razzle/scripts/start.js, but the title of this issue is unrelated.

**Comment by fivethreeo** [comment]
I have been looking into create-razzle-app and have not encountered this (undefined) error when running create-razzle-app. But it could happen with bad connectivity and timeouts? Which example is this with, if any. Which os? Using yarn or npm?

**Comment by fivethreeo** [comment]
Needs more info, reopen if you have some :)

**Comment by jeco123** [comment]
Hi, 
I retry today and i do not have the pb anymore.
Thanks.
Jérôme 

    Le samedi 9 mai 2020 à 16:35:41 UTC+2, Øyvind Saltvik <notifications@github.com> a écrit :  
 
 


Needs more info, reopen if you have some :)
