### ISSUE TITLE
Setting config.plugins crashes Razzle

### ISSUE THREAD

**Issue by lesmo** [jaredpalmer/razzle#1173]
When attempting to configure [WebPack's ProvidePlugin](https://webpack.js.org/plugins/provide-plugin/) in ```razzle.config.js```, it never gets past the compiling stage:

![Screen Shot 2019-12-17 at 5 49 04 AM](https://user-images.githubusercontent.com/2228196/70993199-1a313280-2091-11ea-8577-e9c2de6904b8.png)

Using ```razzle 3.0```, I'm trying to mock ```window``` object for some modules that were not thought for SSR [with this package](https://github.com/lukechilds/window):
```js
config.plugins = [
  new webpack.ProvidePlugin({
    window: 'window',
    document: ['window', 'document']
  })
];
```

This should be reproducible in the [with-react-native-web](https://github.com/jaredpalmer/razzle/tree/master/examples/with-react-native-web) example (with [this fix](https://github.com/jaredpalmer/razzle/issues/842#issuecomment-475722036) to get it to work). This issue appears to occur with whatever module specified in the plugin, not just with the ```window``` package:
```js
config.plugins = [
  new webpack.ProvidePlugin({
    nope: 'express' // even if not used, it halts compilation
  })
];
```

I've tried using the ```webpack``` argument of the ```modify``` callback in ```razzle.config.js``` and requiring it directly, but it ends in the same result:
```js
const otherWebpack = require('webpack');

module.exports = {
  modify(config, { target, dev }, webpack) {
    config.plugins = [
      // Same result using webpack
      new otherWebpack.ProvidePlugin({
        window: 'window',
        document: ['window', 'document']
      })
    ];
  }
};
```

**Comment by klarstrup** [comment]
It's because you're overriding some webpack plugins that razzle needs. Rather do `config.plugins.push(new YourPlugin())` or `config.plugins =[...config.plugins, new YourPlugin()]`

**Comment by lesmo** [comment]
> It's because you're overriding some webpack plugins that razzle needs. Rather do `config.plugins.push(new YourPlugin())` or `config.plugins =[...config.plugins, new YourPlugin()]`

I could've sworn that was my first attempt at this. Just tried again and it's building.
