### ISSUE TITLE
Type checking errors after installing @types/styled-components

### ISSUE THREAD

**Issue by alveshelio** [jaredpalmer/razzle#1176]
I'm having these weird errors after I install @types/styled-components

![image](https://user-images.githubusercontent.com/8176422/71326112-36373880-24c4-11ea-85eb-7964ad7e68cc.png)

I have pushed the code to this branch: https://github.com/alveshelio/razzle-typescript-redux-styled-components-starter-kit/tree/styled-components

I don't understand why @types/styled-components is throwing these errors at all.

**Comment by alveshelio** [comment]
According with the error messages, the types seem to be conflicting with typescript types, I don't know if styled types are wrong or what but if I edit file globals.d.ts and correct the types I get no more errors.

**Comment by bartels** [comment]
This is likely the issue with @types/styled-components:  
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33015

It's a conflict between @types/node and @types/react-native (which is installed by @types/styled-components). Unfortunately, the only fix that works for me is adding `"skipLibCheck": true` in tsconfig.json
