### ISSUE TITLE
set PORT=xxxx not working

### ISSUE THREAD

**Issue by majidsajadi** [jaredpalmer/razzle#1177]
Created a Razzle app and run the app. App runs on port 3000 by default. 
I`m using windows and set the port in Powershell by this command.

    `"start:prod": "set PORT=5000&&set NODE_ENV=production&&node build/server.js"`

But app still running on port 3000. and assets are running on port 3001.
Am i doing anything wrong?

**Comment by TJ-Palmer** [comment]
"start:prod" runs the production build which set's the port when you run the build script command. So set the port in the build script. If there is another way let me know but this works for me. (Tested on Ubuntu 18.04 LTS)

`"build": "PORT=5000 razzle build"`

**Comment by majidsajadi** [comment]
Is there any reason that port sets in build script?
In my case i need to serve the app on several servers and i want copy the built application and run it on different ports.

One more thing, can i send a pull request and add `cross-env` module for easier development in windows ?

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/blob/master/examples/basic/src/index.js#L17

Change

```js
const port = process.env.PORT || 3000;
```
to

```js
const port = process.env['PORT'] || 3000;
```

For setting port at runtime

**Comment by majidsajadi** [comment]
Changed

```javascript
server.listen(process.env.PORT || 3000)
```

to

```javascript
server.listen(process.env['PORT'] || 3000)
```

Built the app. then ran the command

`set PORT=4000&&node server.js`

But the app is still running on port 3000.

**Comment by fivethreeo** [comment]
Is this on windows? it should just be 

```bash
PORT=4000 NODE_ENV=production node server.js
```

**Comment by majidsajadi** [comment]
Actually changing

`const port = process.en.PORT || 3000;`

to

` const port = process.en.port || 3000;`

solves the problem. But i think there should be a better way.

**Comment by fivethreeo** [comment]
razzle uses webpack.DefinePlugin

If this needs to be changed this line must be changed in razzle core:

https://github.com/jaredpalmer/razzle/blob/bffe14f8caf29efe1fd9d6222c65ae660c3372e9/packages/razzle/config/env.js#L88

**Comment by fivethreeo** [comment]
https://gist.github.com/mattlubner/4a3eff31455180e8dac8ad8cf1b17ed1
