### ISSUE TITLE
Data from API not showing when i View Page Source

### ISSUE THREAD

**Issue by orizzz** [jaredpalmer/razzle#1179]
i Have simple API from MySql to get list of data it's work just fine when i run the web

but when i check the view page source data that i got from API is not there, only the hardcode that show in view page sourcet

this is my code

>
         </div>
            {this.renderList(this.state.rekomendasi)}
          <div className="d-flex pt-5 pb-3">
            <div className="h3 font-weight-bold mx-auto my-auto">Kost Pilihan kami</div>
          </div>
            {this.renderList(this.state.terbaru)}
          </div>
>

the fuction this.renderList() not showing at view page source but other

this the fuction
>
 renderList(item){
    let units = item;
    let listRekomendasi = units.map(unit => 
        <div className="col-lg-4 col-6 my-2">
        <Link  to={{
          pathname:  '/Detail/' + unit.id_kost + '/' + unit.nama_kost,
          state: {items_id: unit.id_kost} ,
        }}>
            <Card className="border-0 shadow-sm h-100" key={unit.index}>
              <Card.Img variant="top" src={banner_1} alt="{unit.nama_kost}" /> 
              <Card.Body className="text-dark">
                  <div className="h6">{unit.nama_kost}</div>
                  <div className="h6  font-weight-light">{unit.lokasi}</div>
              </Card.Body>
              <Card.Footer>
                  <div className="h6">
                    <div>Rp.  
                      <CurrencyFormat value={unit.harga} displayType={'text'} thousandSeparator={true} />
                      /Bulan</div>
                  </div>
              </Card.Footer>
            </Card>
          </Link >
        </div>
        );
    return (
        <Row>
            {listRekomendasi}
        </Row>
    );
 }
>

this is one of my fetching code

>
   fetch(API_URL, {
            method: 'POST',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                req:"recommended",
                limit: 6
            })
    }).then(response => response.json())
    .then(responseJson => {
        if(responseJson.status){
            this.setState({rekomendasi: responseJson.data});
        }else{
            alert(responseJson.message);
        }
        console.log(this.state.rekomendasi);
        }).catch((error) => {
        console.log(error)
    });
>

**Comment by oyo-ravi-yadav** [comment]
can you share where you call this fetch?
If it's in the DidMount lifecycle it would not be called during SSR

**Comment by orizzz** [comment]
yes i put it in Didmount, so where should i put it to be called during SSR

should i put it on constructor or Willmount ?

**Comment by hadeeb** [comment]
If you are trying to fetch data during SSR, check out [after.js](https://github.com/jaredpalmer/after.js#razzle-quickstart).

[razzle with after.js](https://github.com/jaredpalmer/razzle/tree/master/examples/with-afterjs)

**Comment by oyo-ravi-yadav** [comment]
@orizzz have a look at this server file 
https://github.com/ilkeraltin/react-ssr-news/blob/master/src/index.js
This is the gist of most of how SSR works with react and redux
Basically you attach a prop on your Route component which can be referenced in the server after route matches and then returns a promise.
Inside the promise you call you APIs update the redux store and after all promises are resolved yourrender your react app on server with the updated store. and send the created store on client in html

If u want you can use the same logic in client to handle route changes or else add same logic in DidMount or useEffect for react hooks

**Comment by orizzz** [comment]
> If you are trying to fetch data during SSR, check out [after.js](https://github.com/jaredpalmer/after.js#razzle-quickstart).
> 
> [razzle with after.js](https://github.com/jaredpalmer/razzle/tree/master/examples/with-afterjs)

is there any example ? 
with real fetching data example

**Comment by orizzz** [comment]
> @orizzz have a look at this server file
> https://github.com/ilkeraltin/react-ssr-news/blob/master/src/index.js
> This is the gist of most of how SSR works with react and redux
> Basically you attach a prop on your Route component which can be referenced in the server after route matches and then returns a promise.
> Inside the promise you call you APIs update the redux store and after all promises are resolved yourrender your react app on server with the updated store. and send the created store on client in html
> 
> If u want you can use the same logic in client to handle route changes or else add same logic in DidMount or useEffect for react hooks

thanks i will try it

**Comment by nimaa77** [comment]
@orizzz use after.js and you will be fine
there are some good examples to start
