### ISSUE TITLE
HTML Script Google Maps window

### ISSUE THREAD

**Issue by NickCarducci** [jaredpalmer/razzle#1181]
Sorry I cannot find an answer
<img width="389" alt="Screen Shot 2020-01-15 at 1 02 25 PM" src="https://user-images.githubusercontent.com/12148373/72458817-555d7900-3797-11ea-8f5b-d91e329bc747.png">
"google is not defined"
<img width="520" alt="Screen Shot 2020-01-15 at 12 56 50 PM" src="https://user-images.githubusercontent.com/12148373/72458502-b5075480-3796-11ea-9075-2a0fb3698743.png">

started with https://github.com/jaredpalmer/razzle/tree/master/examples/with-now-v2
and added some router strategy from your create razzle-app

my attempt at identifying the problem:
How do we implement html with hydration?
I'm guessing "google is not defined" because the client doesn't have access to that html... or something else.  is there a quick fix or an area I should research?
Thanks!

**Comment by hadeeb** [comment]
It looks like `google` is injected to window by some script tag. If that is the case, `google` will be `undefined` during SSR.

Try moving all the code that depends on DOM/window objects to post render lifecycles(`componentDidMount`/`useEffect`).

**Comment by NickCarducci** [comment]
Great idea thanks that should work hold on... 
<img width="350" alt="Screen Shot 2020-01-21 at 2 55 14 PM" src="https://user-images.githubusercontent.com/12148373/72838404-3743bd00-3c5e-11ea-83c0-271d1254c59a.png">
<img width="383" alt="Screen Shot 2020-01-21 at 2 55 47 PM" src="https://user-images.githubusercontent.com/12148373/72838418-3ca10780-3c5e-11ea-8867-2c4fdca90088.png">
It worked all that depended on `window` like `window.location.pathname` & `window.google` on first render I made into `this.setState({pathname:window.location.pathname})` & `const google; this.service = new google.maps.places.AutocompleteService` inside `componentDidMount`/`UseEffect` after mounting
