### ISSUE TITLE
Razzle gtm replication issue

### ISSUE THREAD

**Issue by siasjustin** [jaredpalmer/razzle#1184]
Hi, so for this site we built with Razzle, https://www.fairplaystrategies.org/ we just added this https://www.npmjs.com/package/react-gtm-module to sync it up with google tag manager. But as we navigate through the site, it re-initializes gtm and we see multiple tag managers logging data to google. We are no sure if it is a server side rendering thing, a razzle thing, a gtm thing or a react-gtm-module meets razzle thing, or a react-gtm-module meets server side rendering thing. 

This is the code we put in the app.js file. We initialized it with useEffect to stop the code from initializing multiple instances bu that did not stop it. 
```
const App = (props) => {
  const [initialized, initialize] = useState(false)

  useEffect(() =>  {
    if(!initialized) {
      const tagManagerArgs = {
        gtmId: 'GTM-WVBNT63'
      }
      console.log("tracking")
      TagManager.initialize(tagManagerArgs)
    }
    initialize(true)
    
  })
```

**Comment by fivethreeo** [comment]
This is not a razzle issue:

```js
const App = (props) => {
    useEffect(() =>  {
      const tagManagerArgs = {
        gtmId: 'GTM-WVBNT63'
      console.log("tracking")
      TagManager.initialize(tagManagerArgs)
    } 
  }, [])
})
```

or

```js
const App = (props) => {
    useEffect(() =>  {
      const tagManagerArgs = {
        gtmId: 'GTM-WVBNT63'
      console.log("tracking")
      TagManager.initialize(tagManagerArgs)
      return () => {
       TagManager.uninitialize(tagManagerArgs)
      }
    } 
  }, [])
})
```
