### ISSUE TITLE
Change CSS output location

### ISSUE THREAD

**Issue by saintberry** [jaredpalmer/razzle#1189]
How can I change the output location of the compiled CSS? 

I want put all my of my static assets inside a folder based on the short git commit hash so I can create immutable deployment bundles for hosting on s3.

All rendered CSS should be located in `static/${shorthash}/css/bundle.css`

This is super easy for images and js however I can't seem to get it working for css. 

It seems like the MiniCssExtractPlugin defines the output location for css in Razzle webpack config.

When I remove this plugin from config.plugins and re-add it via 

```
new MiniCssExtractPlugin({
  filename: `${outputPath}/css/bundle.css`,
  chunkFilename: `${outputPath}/css/[name].chunk.css`,
  allChunks: true,
}
```

Webpack throws errors on build.

Thanks!

**Comment by fivethreeo** [comment]
Post your razzle.config.js to show how you try to do this. 😀

**Comment by saintberry** [comment]
I worked it out. For others benefit I did the following:

```      for (let i = 0; i < config.plugins.length; i += 1) {
        if (config.plugins[i].constructor.name === 'MiniCssExtractPlugin') {
          config.plugins[i].options.filename = `${outputPath}/css/bundle.css`;
          config.plugins[i].options.chunkFilename = `${outputPath}/css/[name].chunk.css`;
        }
      }```

When it wasn't working I had tried removing the old instance of MiniCssExtractPlugin and replaced it with a new one. For whatever reason that was causing issues with inline CSS.
