### ISSUE TITLE
Package size seems unreasonably big

### ISSUE THREAD

**Issue by Siilwyn** [jaredpalmer/razzle#1191]
The package install size of Razzle weighs 178MB:
https://packagephobia.now.sh/result?p=razzle

Seems mainly because of 20+ postcss related dependencies all around 1-2MB individually and `rxjs` adding 17MB.

Might be some opportunities to decrease this size.

**Comment by nimaa77** [comment]
@Siilwyn hello, maybe adding `"sideEffects": false` to package.json help you. this will help tree-shaking do its job better.

if you are using CSS or SASS in your project just specify them in sideEffects

```js
"sideEffects": ["*.css"]
```

**Comment by Siilwyn** [comment]
Hi @nimaa77 unfortunately that won't help since this is about the package *install size*. I've looked a bit more into this issue and looks like this size is caused by including dependencies for all plugins even when none are used!

**Comment by nimaa77** [comment]
that's not that much big 

if you fetch those packages once, they are going to be stored inside the yarn/npm cache storage on your local machine, if you are using CI/CD you have to enable cache between pipelines and in this way node_modules will be available between each step of CI/CD setup

sorry for my bad English :)

**Comment by Siilwyn** [comment]
It's still a waste of space, installation time and 50+ MB packages really are uncommon: definitely a bad practice I think.

Besides using Razzle in the context of serverless functions becomes harder since most cloud providers limit the size, e.g. AWS Lambdas can only be 50MB.

**Comment by nimaa77** [comment]
do you have any ideas about how we can fix this?

**Comment by Siilwyn** [comment]
@nimaa77 I think somewhere a dependency of `packages/razzle` is requiring some example or maybe a devDependency down the line that in turn requires other dependencies?

Tried to look into it but got stuck since I can't seem to find out how the packages are published to replicate locally at least. Do you know more about this perhaps?

**Comment by nimaa77** [comment]
I don't know about the dependencies, but I think you can skip downloading dev dependencies with adding --production to install command:
```bash
npm install --production
```

one other thing that could be useful is that you can fork razzle and remove things you don't want and just deploy in inside [Github Package Registry](https://github.com/features/packages) or just put the Github repo link into package.json 

and then install razzle from there

**Comment by nimaa77** [comment]
you can also watch for releases and get notified when a new version gets released so you don't miss anything
![image](https://user-images.githubusercontent.com/25016067/77589978-52ef6c00-6f0a-11ea-8784-da67bbd56866.png)

**Comment by mikestopcontinues** [comment]
Does the size shrink if you bundle an app that uses razzle? I find this concerning, as I would like to push razzle into a lambda func for ssr.

**Comment by ricardobeat** [comment]
As razzle has no runtime, you only need it in `devDependencies`, so it adds almost nothing to a production build.

I installed in a clean project here and got 139MB, majority from rxjs / jsdom / webpack:

```
 flightstats ✭ yarn why rxjs
yarn why v1.22.4
warning package.json: No license field
[1/4] 🤔  Why do we have the module "rxjs"...?
[2/4] 🚚  Initialising dependency graph...
warning No license field
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "rxjs@6.6.0"
info Reasons this module exists
   - "razzle#react-dev-utils#inquirer" depends on it
   - Hoisted from "razzle#react-dev-utils#inquirer#rxjs"
info Disk size without dependencies: "16.93MB"
info Disk size with unique dependencies: "16.98MB"
info Disk size with transitive dependencies: "16.98MB"
info Number of shared dependencies: 1
✨  Done in 0.71s.
 flightstats ✭ yarn why webpack
yarn why v1.22.4
warning package.json: No license field
[1/4] 🤔  Why do we have the module "webpack"...?
[2/4] 🚚  Initialising dependency graph...
warning No license field
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "webpack@4.43.0"
info Reasons this module exists
   - "razzle" depends on it
   - Hoisted from "razzle#webpack"
info Disk size without dependencies: "2.82MB"
info Disk size with unique dependencies: "8.82MB"
info Disk size with transitive dependencies: "24.78MB"
info Number of shared dependencies: 98
✨  Done in 0.72s.
 flightstats ✭ yarn why jsdom
yarn why v1.22.4
warning package.json: No license field
[1/4] 🤔  Why do we have the module "jsdom"...?
[2/4] 🚚  Initialising dependency graph...
warning No license field
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "jsdom@11.12.0"
info Reasons this module exists
   - "razzle#jest#jest-cli#jest-config#jest-environment-jsdom" depends on it
   - Hoisted from "razzle#jest#jest-cli#jest-config#jest-environment-jsdom#jsdom"
info Disk size without dependencies: "5.18MB"
info Disk size with unique dependencies: "9.28MB"
info Disk size with transitive dependencies: "21.28MB"
info Number of shared dependencies: 43
✨  Done in 0.69s.
```

**Comment by fivethreeo** [comment]
This size is only in dev, if you use razzle in a lambda you are adding the dependencies in the wrong way. The way we could get the size down is to make css support be a plugin. But I think a CRA alternative like razzle should do css by default. If the output bundle is big. That is another case. Closing
