### ISSUE TITLE
Ability to create razzle app with example from npm

### ISSUE THREAD

**Issue by sergeysova** [jaredpalmer/razzle#1194]
What about to install example from npm? Like CRA https://create-react-app.dev/docs/custom-templates/

For example:

```bash
npx create-razzle-app --example with-effector my-effector-app
# or
yarn create razzle-app --example with-effector my-effector-app
```
If `with-effector` was not found locally, next search for npm package named `razzle-example-with-effector`.

**Comment by fivethreeo** [comment]
I will take a look at making that work. Maybe make it possible to do npm:package and github:user/repo@branch:folder and a git:url@branch:folder.

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/pull/1283

**Comment by fivethreeo** [comment]
There is a pull request, closing
