### ISSUE TITLE
recommended way to lazy load client rendered components

### ISSUE THREAD

**Issue by laurencefass** [jaredpalmer/razzle#1196]
I want to selectively load components that rely on calls to browser specific DOM resources or need to calculate values on the client. This wont work with SSR.  Is there a recommended way or best practice to selectively lazy load components with razzle? suspense/lazy not currently supported.

thanks

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/issues/1193

**Comment by fivethreeo** [comment]
https://gist.github.com/fivethreeo/8527ff4c7b73913b6d6b55204be60c4b

**Comment by laurencefass** [comment]
thanks fivethreeo but I dont really understand the relevance of either of the links. the use case i wish to satisfy is to load a component on the client from a component rendered by Razzle on the server.  I think the loadableComponents examples may be  the best option as recommended by React Team until suspense/lazy is supported in ReactDOMServer

razzle example here:
https://github.com/jaredpalmer/razzle/tree/master/examples/with-loadable-components

loadablecomponents example here:
https://github.com/gregberge/loadable-components/tree/master/examples/razzle

**Comment by fivethreeo** [comment]
Ah, yes. I use @loadable/component for that. So do the import conditionally in loadable() like in the examples I showed to only load the lazy component client-side.
