### ISSUE TITLE
Is it possible to render UI after all API calls are made?

### ISSUE THREAD

**Issue by stikhomirov** [jaredpalmer/razzle#1203]
Hello everyone, sorry if it's not the right place for questions, but I didn't have a chance to find an answer myself.

I have a simple app that renders some components with the data from REST API. The problem is that when network is pretty slow, user gets HTML generated on server  fast, but than, after js.bundle is loaded, user view is rerendered by react and gets the same as was generated on server only after all API calls succeded. This may take a while, and for this time user loses access to information that was available before js bundle was loaded.

Is there a way to let React  control UI only after all async api calls are made?

**Comment by fivethreeo** [comment]
You have to use something like react-ssr-prepass (until react supports server side suspense) and a server side cache that ouputs the fetched cached data on e.g. window.__SERVER_DATA__ then have some logic that tries to get data from that variable first instead of refetcing in the browser. Really a complex problem, and depends a lot on your specific codebase.

**Comment by fivethreeo** [comment]
Or if you dont want to do any api calls serverside, just use suspense in react.

**Comment by stikhomirov** [comment]
@fivethreeo Thank you very much for your answer. Occaisionally I seem to have found the way to do what I want and it is amazing After.js. I fetch the data on server and pass it to the page through ctx object. As an extra bonus I have speed gain as my pages are lazy-loaded now, for free.
@jaredpalmer As data fetching is very common usecase in almost all projects, I would suggest puting a link to After.js on feature section of Razzle readme. It may save some time for newbies like me looking for the perfect stack for their first SPA.

**Comment by fivethreeo** [comment]
After.js is a possibility, but it requires different code server-side, if you use graphql check out urql with ssrexchange.
