### ISSUE TITLE
How to deploy to Azure

### ISSUE THREAD

**Issue by Julien-Sytadelle** [jaredpalmer/razzle#1204]
Hi,

After a long struggle to make our razzle app work on azure windows instance, I thought I write quickly here how I made it work. It may not be perfect but at least it display our site.

1/ Ensure the node version you use is supported (you can check in avanced tools in portal)
I used 10.15.2

**2/ razzle.config.js:**
You must prevent inlining of env variables like PORT (else you will have an errror about address 3000 being alerady in use, and empty the externals list else it will tell that it cannot find react package.

module.exports = {
    modify: (config, { target, dev }, webpack) => {

    const appConfig = Object.assign({}, config);

    //@BUG: Do not inline certain env vars; https://github.com/jaredpalmer/razzle/issues/356
    if (target === 'node') {
        const idx = appConfig.plugins.findIndex(plugin => plugin.constructor.name === 'DefinePlugin');
        const { definitions } = appConfig.plugins[idx];
        const newDefs = Object.assign({}, definitions);
        
        delete newDefs['process.env.PORT'];
        delete newDefs['process.env.HOST'];
        delete newDefs['process.env.PUBLIC_PATH'];

        appConfig.plugins = [].concat(appConfig.plugins);
        appConfig.plugins[idx] = new webpack.DefinePlugin(newDefs)
    }

    // Clear externals list else it cannot find some packages
    if (target === "node" && !dev) {
      appConfig.externals = []    
    }

  return appConfig;
  },
};

**3/ provide a web.config file for iis**
 
<?xml version="1.0" encoding="utf-8"?>

<configuration>
  <system.webServer>
    
    <webSocket enabled="false" />
    <handlers>
      
      <add name="iisnode" path="server.js" verb="*" modules="iisnode"/>
    </handlers>
    <rewrite>
      <rules>
        
        <rule name="NodeInspector" patternSyntax="ECMAScript" stopProcessing="true">
          <match url="^server.js\/debug[\/]?" />
        </rule>

        
        <rule name="StaticContent">
          <action type="Rewrite" url="public{REQUEST_URI}"/>
        </rule>

        
        <rule name="DynamicContent">
          <conditions>
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="True"/>
          </conditions>
          <action type="Rewrite" url="server.js"/>
        </rule>
      </rules>
    </rewrite>
    
    
    <security>
      <requestFiltering>
        <hiddenSegments>
          <remove segment="bin"/>
        </hiddenSegments>
      </requestFiltering>
    </security>

    
    <httpErrors existingResponse="PassThrough" />

    
    
    
  </system.webServer>
</configuration>

**4/ Pipeline**
Start with a task to setup the right node version
npm run install
npm run-script build
Copy build directory to artifact
Copy web.config to artifact
Publish

The release is a standard azure web deploy.

I hope it helps someone.
Thanks a lot to other issuers I could get all hints from.

**Comment by Riteshsulakhe1** [comment]
How you solved the issue ? I m having the same issue
