### ISSUE TITLE
Allow adding node arguments for StartServerPlugin as part of the razzle start command

### ISSUE THREAD

**Issue by zahidma91** [jaredpalmer/razzle#1205]
### Issue
The default max header size for node http requests is 8KB. However, my site's domain has an unusually large number of cookies, that causes the header size for the request to exceed that limit. This results in every request returning a `HTTP 431 Request Header Fields Too Large` status code. The fix for this (apart from actually reducing cookies, which unfortunately is not an option as it's an existing domain), is to use the `-max-http-header-size` CLI option with node. However, there doesn't seem to be a way to pass in extra arguments to the StartServerPlugin without actually overriding the whole thing.

### Feature request
Add support to pass node arguments for the StartServerPlugin when starting the dev server. It could just involve passing through all arguments(or maybe a whitelisted set of arguments) to the plugin. Currently, only --inspect and --inspect-break are supported.

For eg:
```
razzle start --max-http-header-size=16384
```

**Comment by fivethreeo** [comment]
Just modify the config like so:

```js
'use strict';

module.exports = {
  modify(config, { target, dev }, webpack) {
    const appConfig = config;

    appConfig.plugins = appConfig.plugins.reduce((plugins, plugin) => {
        if (plugin.constructor.name === 'StartServerPlugin') {
          plugin.options.nodeArgs.push('--max-http-header-size=16384');
          plugins.push(plugin);
        }
        else {
           plugins.push(plugin);
        }
        return plugins;
    }, []);
    return appConfig;
  }
};
```

**Comment by nimaa77** [comment]
i'm going to close this issue, if you think it's a mistake just reopen it
