### ISSUE TITLE
Absolute Imports

### ISSUE THREAD

**Issue by itsemirhanengin** [jaredpalmer/razzle#1206]
Hello,

I need absolute imports. I don't want to use "../../../../components/Button" every single time. I want to use like "~/components/Button". Is it possible? I found an thing for this but it works like "components/Button" i want to add prefix.

Best,

**Comment by nimaa77** [comment]
@itsemirhanengin hello, check #1112 

we are going to have a new version of razzle in this or next week

**Comment by nimaa77** [comment]
oh sorry didn't want to close this :)

**Comment by itsemirhanengin** [comment]
I'm still using like that but sometimes eslint can't handle that because it seems like a package. That's why i want to make prefixes actually. I'm excited about new version :)

**Comment by nathanburgess** [comment]
Just started working with Razzle today and #1112 doesn't seem to work for me.

**Comment by itsemirhanengin** [comment]
It should've work. Could you send me your config codes that you wrote to razzle.config.js?

**Comment by nimaa77** [comment]
Hello
I merged branch next to develop

and this is what happened :)
CI/CD pipeline failed

so new version didn't deploy on npm

this is why you can't use this

**Comment by nimaa77** [comment]
you can use this feature in razzle 3.1

**Comment by ost12666** [comment]
I just used it, its great! The only problem is that this and other 3.1 features are not updated in the project readme...

**Comment by nimaa77** [comment]
this issue fixed, closing now

(@ost12666 I will add docs for absolute imports)
