### ISSUE TITLE
Consider replacing Babel with SWC

### ISSUE THREAD

**Issue by krazyjakee** [jaredpalmer/razzle#1208]
Transpilation feels like the number one bottleneck for my productivity in large Razzle projects. In some projects, I have to wait for half a minute to see the code changes in my browser. Luckily, some clever developers are working on [SWC](https://swc-project.github.io/), the "Speedy Web Compiler". It basically replaces Babel, and it's crazy fast: [16 to 40 times faster](https://github.com/swc-project/swc#performance), according to their own benchmarks.

SWC can be [used with webpack](https://swc-project.github.io/docs/usage-swc-loader) and it supports pretty much all of the most important features (JSX, Typescript, source maps, legacy ES).

Maybe the project is not mature enough to fully replace Babel, but I think it makes sense to put it on the radar.

**Comment by fivethreeo** [comment]
This could be done as a plugin.

**Comment by fivethreeo** [comment]
```js
'use strict';


function modify(defaultConfig, { target, dev }, webpack) {
  const config = defaultConfig;

  config.module.rules = config.module.rules.reduce((rules, rule) => {

      if (rule.test &&
        rule.test.toString()===/\.(js|jsx|mjs)$/.toString() &&
        !rule.enforce) { // !rule.enforce to not conflict with eslint plugin

        const { use, ...rest } = rule;

        rules.push({ ...rest, ...{
          use: [{
              loader: require.resolve('swc-loader'),
              options: {
                // swc options
              }
            }
          ]
        }});
      }
      else {
        rules.push(rule);
      }
      return rules;
    }, []);
  
  return config;
}

module.exports = modify;
```

**Comment by fivethreeo** [comment]
Made the plugin, here: https://github.com/fivethreeo/razzle-plugin-swc
