### ISSUE TITLE
Expose resolveApp for plugins

### ISSUE THREAD

**Issue by fivethreeo** [jaredpalmer/razzle#1209]
https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/config/paths.js#L10

**Comment by nimaa77** [comment]
we have to create 2 APIs so with that
1) users easily change the paths 
2) they access paths inside razzle.config.js and other razzle plugins

**Comment by fivethreeo** [comment]
Don't quite get what you mean. I just meant export resolveApp. But what is your idea? 😀

**Comment by nimaa77** [comment]
I saw in multiple issues people want to access some paths in `razzle.config.js`, there is a pull request for it too

so I'm thinking about a way to give users all the path variables are available in paths.js file

**Comment by fivethreeo** [comment]
So like a paths argument in a plugin or razzle.config.js? Pull #?

**Comment by fivethreeo** [comment]
Do you mean #457?

**Comment by nimaa77** [comment]
#940 714

**Comment by nimaa77** [comment]
no, not that one/
look at this #714

**Comment by nimaa77** [comment]
@fivethreeo hey, I want to ask @jaredpalmer to tag a new minor relase for Razzle.
I saw you had some cool open pull requests, merge those to `next` branch and then ping me.

thanks

**Comment by fivethreeo** [comment]
Jared tried something like #714 in #457 and there one pr open in #940. I agree on giving access to paths in the plugins/modify but changing them might be a bit easy to cause conflicts if done in plugins and add extra complexity even if just added to razzle.config.js. If you need custom paths derive them from resolveApp.  If builtin options except in start or build scripts needs overriding just replace loaders/plugins with the new options since it is more specific and you know what they will affect. If anything we could add some kind of context where modify/plugins can share options if need be.

**Comment by nimaa77** [comment]
umm

**Comment by nimaa77** [comment]
but it's cool to have it

**Comment by fivethreeo** [comment]
But can be a bit confusing if multiple plugins change paths. So maybe just in razzle.config.js? I see multiple modules importing './paths' so we need to pass those around somehow leading to making some parts calls/callbacks instead of imports.

**Comment by nimaa77** [comment]
Another question
do we need to add `sideEffects: false` to `babel-loader` in webpack loaders config or it's unnecessary

**Comment by fivethreeo** [comment]
I think terser takes care of that. But not quite sure.

**Comment by fivethreeo** [comment]
Been thinking some more about this, there are many options except just regular paths people want to change. What if we change createConfig to first make the options to the various parts of the webpack configuration. Then pass that to modifyOptions in plugins and razzle.config.js to be modified before creating the webpack config. But I also see a need for modifyPaths (even in plugins) aswell. Should it be a way to set where razzle should look for razzle.config.js in monorepos, e.g. a env var?
