### ISSUE TITLE
Unable to deploy on ec2.

### ISSUE THREAD

**Issue by akif-ih** [jaredpalmer/razzle#1213]
When i tried to deploy my app on ec2 ubuntu VM, i changed my host to public ip of vm but i will through the below error. @jaredpalmer  Please help i am stuck in this issue.

Error: Could not find an open port at 34.207.75.195.
Network error message: listen EADDRNOTAVAIL: address not available 34.207.75.195

    at /root/ssr/test-razzle/node_modules/react-dev-utils/WebpackDevServerUtils.js:387:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async module.exports (/root/ssr/test-razzle/node_modules/razzle-dev-utils/setPorts.js:9:22)

**Comment by akif-ih** [comment]
@jaredpalmer @jamalc

**Comment by carsonaaberle** [comment]
Same issue here, did you figure this out? 

EDIT:
I was able to get this at least running on my machine after I commented out the HOST and PORT variables from my .env file

Versions:
Node 12.18.0
Razzle 3.1.3
razzle-plugin-runtimeenv 1.0.1

**Comment by fivethreeo** [comment]
You are running the wrong thing. Don’t run the devServer on ec2. Use yarn start:prod. But if you used that and want to set PORT and HOST from the env you need to modify DefinePlugin options. This will be easier to do in razzle 4+.

**Comment by felipegouveiae** [comment]
I have faced that issue running docker containers on AWS and I fixed that setting PORT and HOSTNAME env variables.
