### ISSUE TITLE
Why not update npm package version?

### ISSUE THREAD

**Issue by yaoweiprc** [jaredpalmer/razzle#1224]
It's been one year from last npm version 3.0.0 update, when will the next version release?

**Comment by nimaa77** [comment]
hello, we are working on it, next version will come out in the next few weeks

**Comment by J-env** [comment]
@nimaa77 
Looking forward to the release of the new version.
Recently I prepared to use "razzle" to develop the project.

**Comment by nimaa77** [comment]
@J-env yeap I will send an email to @jaredpalmer to tag a new minor release later today

**Comment by storesbuzz** [comment]
Witing for npm update for razzle, I am using Razzle + After Js + Redux but Getting too many (50+) warnings when building, from razzle

example - 
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/razzle/node_modules/fsevents/node_modules/set-blocking' -> '/usr/local/lib/node_modules/razzle/node_modules/fsevents/node_modules/.set-blocking.DELETE'

**Comment by nimaa77** [comment]
@storesbuzz that npm warnings are not important that much
actually fsevents is only for macOS, so it's ok to get some warnings if you don't have a device with macOS

https://www.npmjs.com/package/fsevents

and as a personal advice user yarn :)
+
we have After.js 2 that is way faster than V1, but we need a new version of Razzle to make that work

**Comment by rclmenezes** [comment]
Any update on the npm update?

Help us, @nimaa77 , you're our only hope :)

![image](https://user-images.githubusercontent.com/736775/79996383-6993cf00-8486-11ea-8210-ccce1aeffa4f.png)

**Comment by nimaa77** [comment]
we are working on it. I merged branch `next` to `master` in order to tag a new release

there is only one little problem 

https://github.com/jaredpalmer/razzle/runs/609829355?check_suite_focus=true#step:6:311 

I asked Jared to fix the npm_token issue and then we are good to go.

**Comment by nimaa77** [comment]
oh by the way if you run `npm i razzle@3.1.0-canary.8` 
it's going to install lasted version :)

since it's deployed on npm ...

**Comment by fivethreeo** [comment]
New version is out, closing
