### ISSUE TITLE
Can i import a JS file from another folder?

### ISSUE THREAD

**Issue by itsemirhanengin** [jaredpalmer/razzle#1227]
Hello! Can i import js file from another folder? I mean, not in src folder. I want to create folder structure like this:

api/index.js
src/server.js
...

And i want to import api/index.js file from src/server.js file. Is it possible? When i try this, it gives me error: build\server.js:765 throw new Error("Module parse failed: Unexpected token (1:21)\nYou may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n> module.exports = (req: any, res: any): void => {\n| \tres.send('HOLLLAAA');\n| }");

Thank you :)

**Comment by fivethreeo** [comment]
That should work. Need more info.

**Comment by itsemirhanengin** [comment]
But this is not working. I'm getting webpack loader error for some reasons. Because razzle js handles src file, and if i want to access out of src, that gives me error that above on this comments.

**Comment by fivethreeo** [comment]
Sorry, you are right. It only allows src by default.

**Comment by fivethreeo** [comment]
// razzle.config.js

```js
'use strict';

const path = require('path');
const fs = require('fs');
const appDirectory = fs.realpathSync(process.cwd());
const resolveApp = relativePath => path.resolve(appDirectory, relativePath);

module.exports = {
  modify: (defaultConfig, { target, dev }, webpack) => {
    const config = Object.assign({}, defaultConfig);

    config.module.rules = config.module.rules.reduce((rules, rule) => {

      if (rule.test &&
        rule.test.toString()===/\.(js|jsx|mjs)$/.toString() &&
        !rule.enforce) {

        const { include, ...rest } = rule;

        rules.push({ ...rest, ...{
          include: include.concat([resolveApp('api')])
        }});

      }
      else {
        rules.push(rule);
      }
      
    return rules;
    
  }, []);
  
  return config;
  
};
```

**Comment by itsemirhanengin** [comment]
LGTM! Thank you so much :) I wanna ask something, with this modify function, we can change webpack configuration, right?

**Comment by fivethreeo** [comment]
Yes :)

**Comment by itsemirhanengin** [comment]
Thank you so much again :)
