### ISSUE TITLE
Changing 'static/media/' path?

### ISSUE THREAD

**Issue by baj84** [jaredpalmer/razzle#1229]
Hi,

I can't see the build path where media gets stored as a configured anywhere. Is it possible to override this?

Thanks

**Comment by fivethreeo** [comment]
You can modify it by altering the file loader rule in razzle.config.js I can show some code tomorrow.

**Comment by iliyanyotov** [comment]
As per the comment from @fivethreeo, you can adjust the loader configuration (file-loader/url-loader) by defining a `razzle.config.js` file. Not very clean, but it does the job. Just a side note, the static folder will still be inside the main build folder.

```javascript
module.exports = {
  modify: (config) => {
    config.module.rules[2].options.name = "static/[name].[hash:8].[ext]";
    config.module.rules[3].options.name = "static/[name].[hash:8].[ext]";

    return config;
  }
};
```

**Comment by fivethreeo** [comment]
fixed in dev
