### ISSUE TITLE
Problem with ESM module imports

### ISSUE THREAD

**Issue by jutunen** [jaredpalmer/razzle#1241]
I'm trying to include https://github.com/JoshK2/react-spinners-css to my razzle build.
React-spinners-css doesn't use/support commonJS modules at all.

I get following error when I run npm start:

>/node_modules/react-spinners-css/dist/index.js:1
>import Circle from './Circle';
>^^^^^^
>
>SyntaxError: Cannot use import statement outside a module

I tried to use my own .babelrc:

```javascript
{
  "presets": [
    "razzle/babel"
   ],
   "plugins": [
     "@babel/plugin-transform-modules-commonjs"
   ]
}
```
But that didn't help...
Can anyone please advise on how to get those ESM modules imported?

**Comment by JoshK2** [comment]
@jutunen I responded to you in my project repo, otherwise, you can try to install just the component you need using my [bit.dev](https://bit.dev) collection: https://bit.dev/joshk/react-spinners-css
Tell me if it's worked for you.

**Comment by fivethreeo** [comment]
You need to change config.externals to make razzle allow the esm module to be bundled.

**Comment by fivethreeo** [comment]
So, use cjs or modify config.externals. Or write a esm plugin to add modifications automatically for listed packages.

**Comment by JoshK2** [comment]
Hi, I fixed this in the last version.
And also wrote details about it here: https://github.com/JoshK2/react-spinners-css#how-to-use-with-ssr

**Comment by fivethreeo** [comment]
fixed in dev
