### ISSUE TITLE
Updating Plugins, And Removing Typescript plugin!!

### ISSUE THREAD

**Issue by nimaa77** [jaredpalmer/razzle#1242]
I'm going to update these plugins (some of them are not implemented yet and some other very old)
so we are going to have some breaking changes

- razzle-plugin-mdx
- razzle-plugin-preact
- razzle-plugin-scss
- razzle-plugin-typescript (maybe remove this??)
- razzle-plugin-eslint

### What? Why We Remove Typescript Plugin?
We are using `babel` for transpiling our Javascript code right now. recently (about a year ago) babel team and typescript team released a new plugin called [babel-plugin-transform-typescript](https://babeljs.io/docs/en/babel-plugin-transform-typescript) so with this plugin babel can transpile Typescript code to Javascript.

in:
```ts
const x: number = 0;
```

out:
```js
const x = 0;
```

#### What about type checking

just install `tsc` (typescript compiler) and we are good to go:
```
yarn add tsc
yarn tsc
```

#### What about configuration?
create a valid `tsconfig.json` at the root of your project and that's all.

#### What about absolute imports?
WE ALREADY COVERED THAT 😎
https://github.com/jaredpalmer/razzle/pull/1112

so we can add `babel-plugin-transform-typescript` to `babel-preset-razzle` and also update the webpack config to handle ts and tsx files with babel-loader:

```js
{
  test: ts|tsx|js|jsx$,
  loader: babel-loader
}
```

with these changes, adding typescript to razzle is going to be super easy, only in two steps:
1. `yarn add tsc`
2. create `tsconfig.json` at the root of the project

**Comment by fivethreeo** [comment]
Seems good to me, but be sure to fix the typescript example.

**Comment by piecyk** [comment]
Yeah i think it's good idea to drop `razzle-plugin-typescript ` Would create separate issue and address it in separate PR.

**Comment by fivethreeo** [comment]
Merged, closing
