### ISSUE TITLE
Question: How can I see which errors triggered the Server message "Compiled with some errors"?

### ISSUE THREAD

**Issue by hcharley** [jaredpalmer/razzle#1249]
Output seems kind of a mystery to me:

```
./node_modules/.bin/razzle start
 WAIT  Compiling...


✔ Client
  Compiled successfully in 3.72s

✖ Server
  Compiled with some errors in 16.78s

ℹ ｢wds｣: Project is running at http://localhost:3001/
ℹ ｢wds｣: webpack output is served from undefined
ℹ ｢wds｣: Content not from webpack is served from /code/@app/razzle
ℹ ｢wds｣: 404s will fallback to /index.html
✅  Server-side HMR Enabled!
🚀 started
```

**Comment by fivethreeo** [comment]
Yeah, razzle eats the tracebacks.

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/blob/master/packages/razzle-dev-utils/printErrors.js#L15

**Comment by fivethreeo** [comment]
Maybe add a --verbose cli option to razzle somehow

**Comment by hcharley** [comment]
> Maybe add a --verbose cli option to razzle somehow

Great idea.

Thank you for providing a lead to me. This will help me maybe hack a console.log into the source code, perhaps.

**Comment by fivethreeo** [comment]
Found something else aswell:
https://github.com/facebook/create-react-app/blob/master/packages/react-dev-utils/formatWebpackMessages.js#L86

**Comment by R-Bower** [comment]
I've run into the exact same issue.  @charlex have you found a solution?

**Comment by fivethreeo** [comment]
Should be fixed in canary, remember to set verbose
