### ISSUE TITLE
WDS being verbose in `razzle start`

### ISSUE THREAD

**Issue by sneridagh** [jaredpalmer/razzle#1252]
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/486927/80112207-24a09300-8581-11ea-80ac-596586302a44.png">

It happens in the current 3.0.0 and also in the new canary (screenshot).

**Comment by sneridagh** [comment]
Anybody knows why or how to prevent it?

**Comment by nimaa77** [comment]
I can't understand :)
what's the problem?

**Comment by sneridagh** [comment]
[WDS] messages are ugly, and confusing, since there's nothing in 3001 but the hot reload dev server.

**Comment by sneridagh** [comment]
let alone they are pretty useless... earlier versions of Razzle (using earlier versions of webpack-dev-server) didn't have them.

**Comment by nimaa77** [comment]
yeah, actually that message comes from `webpack-dev-server` and they (webpack team) didn't provide any options to disable the message.

@fivethreeo can we eat `webpack-dev-server` logs so users don't see them?

**Comment by fivethreeo** [comment]
I looked into it and it might be possible. https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L759

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/pull/1255

**Comment by fivethreeo** [comment]
But I think we should add a --verbose to razzle start. So we can get tracebacks and wds output if needed.

**Comment by sneridagh** [comment]
:tada: Nice work, thanks @fivethreeo @nimaa77

**Comment by fivethreeo** [comment]
Fixed, closing
