### ISSUE TITLE
css file is not compiling on server side

### ISSUE THREAD

**Issue by jaypandya73** [jaredpalmer/razzle#1256]
In development environment I've installed `razzle-plugin-scss` plugin and when I try to load application css/scss files are not compiling and hence while page is loading it's breaking assets on-page and then when it switches to client-side it loads all assets and when I checked `assets` by doing `console.log(assets)` inside `server.js` I'm not getting `.css` file I'm getting only compiled .js file.

Here is the output of log:
```js
{ client: { js: 'http://localhost:3001/static/js/bundle.js' } }
```
I've tried it with [with-scss](https://github.com/jaredpalmer/razzle/tree/master/examples/with-scss) example and same result.

How can I compile css/scss also on server side `assets` so that it doesn't break page on initial load?

Also I've not set `RAZZLE_ASSETS_MANIFEST` env. variable from where we're fetching assets on server-side
```js
const assets = require(process.env.RAZZLE_ASSETS_MANIFEST)
```
I guess it's default `build` folder inside the project as it has `assets.json` file but compiled css file is missing.

**Comment by nimaa77** [comment]
hello
1) on development mode not even one CSS file is created and they created in run time and injected to the HTML by webpack (this is how webpack works to enable HMR for CSS files)
2) on production build CSS files created and then all of them will go to a file called bundle.css ...

and this is how your html looks like, we will import that css file from `chunks.client.css` to our html:
```html
<!doctype html>
    <html lang="">
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta charSet='utf-8' />
        <title>Welcome to Razzle</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        ${chunks.client.css.map(path => `<link rel="stylesheet" href="${path}">`)}  // 👈 
    </head>
    <body>
        <div id="root">${markup}</div> 
        <script>window.env = ${serialize(runtimeConfig)};</script>
        ${chunks.client.js.map(path => `<script src="${path}" defer crossorigin></script>`)}        
    </body>
</html>
```

**Comment by nimaa77** [comment]
the best place to import CSS files is `App.js` or `clinet.js` file and all of them will be bundled into the `chunks.client.css` ...

BUT if you do code-splitting things will work differently, because when you do code splitting you will create multiple CSS files but in our initial HTML, we only bundle the `chunks.client.css` and then on client-side after js files loaded webpack runtime can load rest of CSS files required for the current request. so libraries like react-loadable and loadable components will handle this for you...

**Comment by nimaa77** [comment]
if you are an advanced user you can use chunks.json to implement that thing yourself without any need to install external libraries, check #1178

**Comment by nimaa77** [comment]
you should not import CSS files into `server.js` or any other module that's going to only used in `server.js`

logically this is wrong ...

**Comment by jaypandya73** [comment]
@nimaa77 - Thanks for clarification I suspected that on server side it's wrong to import any css file but i thought is it only me or am i missing something that in development environment it's not loading assets but it's clear now :smile: 

And I will surely try loading css in chunks.

**Comment by nimaa77** [comment]
can we close this :D ?

**Comment by jaypandya73** [comment]
Yes as it's expected behavior going to close this one. Again thanks @nimaa77 for info
