### ISSUE TITLE
Implementing React Refresh!! 😍

### ISSUE THREAD

**Issue by nimaa77** [jaredpalmer/razzle#1257]
it's very nice to have this in razzle
@fivethreeo what's your idea

guys on the `next.js` team implemented this:
https://twitter.com/timneutkens/status/1251942933953228802?s=20

more info:
https://github.com/facebook/react/issues/16604#issuecomment-528663101

**Comment by fivethreeo** [comment]
Some research:

https://github.com/zeit/next.js/blob/07b24e6fa1d7d825fab0c4cf02ef9d42aae45476/packages/next/build/webpack-config.ts#L768

https://github.com/zeit/next.js/blob/07b24e6fa1d7d825fab0c4cf02ef9d42aae45476/packages/next/build/webpack-config.ts#L782

**Comment by nimaa77** [comment]
![1399-02-05 06 03 08](https://user-images.githubusercontent.com/25016067/80214946-ee324900-8650-11ea-9684-ab68006d75d2.gif)

:D It was easy

**Comment by fivethreeo** [comment]
Ah, nice :)

**Comment by nimaa77** [comment]
I forgot to push the branch :)

I will push it and then we talk about the implementation ...

**Comment by fivethreeo** [comment]
Are you working on this or should I give it a go?

**Comment by nimaa77** [comment]
@fivethreeo I'm not good as you on webpack :)
and also there are some problems with after.js I'm working on those

there is one more thing that Sebastian mentioned about react performance and webpack bundler

https://twitter.com/sebmarkbage/status/1250284377138802689?s=20

**Comment by fivethreeo** [comment]
Can you push your branch to github, I think the @next react-refresh does not support webpack5 either. Then using the way you did it is simpler and adds less crud.

**Comment by nimaa77** [comment]
my implemention dose not wokring with ssr mode, it's only work with spa mode -.-

do we really need to support webpack 5 right now?

**Comment by fivethreeo** [comment]
No problem I’ll fix the ssr stuff. It is experimental so we will skip webpack5 for this.

**Comment by fivethreeo** [comment]
There is a pull request, closing
