### ISSUE TITLE
How can I configure Razzle.js to serve the app assets from several CDNs?

### ISSUE THREAD

**Issue by gazpachu** [jaredpalmer/razzle#1258]
I've asked this question in StackOverflow (to avoid flooding this board), but I don't get any answer. Does anyone know how to do this?

Browsers usually restrict the maximum amount of parallel loads from a given subdomain. Therefore, I want to spread asset loading across 4 CDNs:

https://cdn0.domain.ltd
https://cdn1.domain.ltd
https://cdn2.domain.ltd
https://cdn3.domain.ltd

Using something like this (based on the file name) to determine the cdn number:

```
"/static/media/asset-name.6d24aee6.png".split('').reduce((a, b) => a + b.charCodeAt(0), 0) % 4
```

How can I do this in Razzle?

So far, this is what I have. In `razzle.config.js`:

```
const PUBLIC_PATH = process.env.PUBLIC_PATH || '/';

module.exports = {
  modify: (config, { dev, target }, webpack) => {
    if (!dev) {
      config.devtool = false;

      // Use the CDN in production
      config.output = {
        publicPath: PUBLIC_PATH
      };
    }

    config.plugins.push(
      new webpack.DefinePlugin({
        'process.env.PUBLIC_PATH': JSON.stringify(PUBLIC_PATH)
      }),
    }
 }
```

**Comment by fivethreeo** [comment]
I think you need to look into webpack configuration for public path. Also look at url and file loader options and dynamic webpack_public_path. This should be doable by webpack configuration. Find out how to do it in webpack and razzle can do it, also if you figure out how in webpack I will help with making it work in razzle.

**Comment by fivethreeo** [comment]
https://github.com/agoldis/webpack-require-from
