### ISSUE TITLE
Add support for postcss.config.js 

### ISSUE THREAD

**Issue by piecyk** [jaredpalmer/razzle#1265]
### Current Behavior

Adding custom postcss plugins can be done by extending webpack config, but it's not very convenient. Postcss starts to be first choice for next css rather than popular sass or less, checkout also https://tailwindcss.com/ 

### Desired Behavior

It's should be allowed to use custom config for postcss. Similar as it's done with `.babelrc`

### Suggested Solution

Add support for overriding default postcss config with .postcssrc.js or postcss.config.js 

### Who does this impact? Who is this for?

People who want to use next css future today!

### Describe alternatives you've considered

Extending webpack config.

### Additional context

There was a PR address this issue https://github.com/jaredpalmer/razzle/pull/521 but was closed as stale. Can fork it and push new. I thing we can manage to push it with next release. What do you think @nimaa77 ?

**Comment by nimaa77** [comment]
hello, why not

but should we add it to razzle core or we create a separate plugin for that?

**Comment by piecyk** [comment]
I would say to `razzle core` as we already add there postcss options.

**Comment by nimaa77** [comment]
this is a valid webpack config [postCSS](https://github.com/postcss/postcss-loader)

```js
{
  loader: 'postcss-loader',
  options: {
    config: {
      path: 'path/to/.config/' 
    }
  }
}
```

and this is the configuration for postCSS loader in [razzle](https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/config/createConfig.js#L221)
```js
const postCssOptions = {
  ident: 'postcss', // https://webpack.js.org/guides/migrating/#complex-options
  plugins: () => [
    require('postcss-flexbugs-fixes'),
    require('postcss-preset-env')({
      autoprefixer: {
        flexbox: 'no-2009',
      },
      stage: 3,
    }),
  ],
};
```

if we add that to our path to razzle it should work!!
```js
config: {
    path: 'path/to/.config/' 
}
```

I think there is no need to specify the `path` if we are not changing the config directory
https://github.com/postcss/postcss-loader#config

> You can manually specify the path to search for your config (postcss.config.js) with the config.path option. This is needed if you store your config in a separate e.g ./config || ./.config folder.

let's create a simple project and add a `postcss.config.js` and see how it goes

**Comment by piecyk** [comment]
Don't quite understand this 

> if we add that to our path to razzle it should work!!

When we add `postcss.config.js` to project, `postcss-loader` will not look for it as we pass options. My idea was to re-use what `postcss-loader` does to check if there is config. 

Something like this https://github.com/jaredpalmer/razzle/compare/master...piecyk:feature/postcss-config

**Comment by nimaa77** [comment]
looks good

**Comment by fivethreeo** [comment]
Merged, closing

**Comment by vferdiansyah** [comment]
@fivethreeo @nimaa77 i see this is already merged. any ETA on when this feature gonna be released?

**Comment by fivethreeo** [comment]
Aiming for a canary release tomorrow 😀

**Comment by YuraKolesnikov** [comment]
I still don't get it, what should I do?
This is my razzle.config.js

```
const path = require('path');

module.exports = {
	plugins: [
		{
			name: 'scss',
			options: {
				sass: {
					dev: {
						additionalData: `@import "${path.resolve(__dirname, './src/styles/propertySets.scss').replace(/\\/g, '/')}";`,
					},
					prod: {
						additionalData: `@import "${path.resolve(__dirname, './src/styles/propertySets.scss').replace(/\\/g, '/')}";`,
					},
				},
			},
		},
	],
}
```

**Comment by fivethreeo** [comment]
```js
const path = require('path');

module.exports = {
    plugins: [
        {
            name: 'scss',
            options: {
                sass: {
                    dev: {
                        sassOptions: {
                            additionalData: `@import "${path.resolve(__dirname, './src/styles/propertySets.scss').replace(/\\/g, '/')}";`,
                        }
                    },
                    prod: {
                        sassOptions: {
                            additionalData: `@import "${path.resolve(__dirname, './src/styles/propertySets.scss').replace(/\\/g, '/')}";`,
                        }
                    },
                },
            },
        },
    ],
}
```
