### ISSUE TITLE
Unable to build application because `minimize` option is deprecated

### ISSUE THREAD

**Issue by suciudan** [jaredpalmer/razzle#1269]
### Current Behavior

When running `npm run build` in a project with `razzle-plugin-scss`, the build fails with the following error:

```
./src/App.scss
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'minimize'. These properties are valid:
   object { url?, import?, modules?, sourceMap?, importLoaders?, localsConvention?, onlyLocals?, esModule? }
```

### Expected behavior

App should build without errors.

### Reproducible example

Tested with `examples/with-scss`

### Suggested solution(s)

Removing `minimize: true` from `razzle-plugin-scss/index.js` fixes the error.

**Comment by nimaa77** [comment]
yeap, I will push the fix later tonight

**Comment by fivethreeo** [comment]
Fixed in next branch, new release soon. Closing
