### ISSUE TITLE
React-Router v5 : staticContext is coming as undefined

### ISSUE THREAD

**Issue by techdiary** [jaredpalmer/razzle#1270]
## 🐛 Bug report

Trying to access `staticContext` from `App.js` but comes undefined.

### Current Behavior
Verified it on 3.0.0 & 3.1.0

### Expected behavior
To get passed staticContext object from server into app js.

### Reproducible example
server.js
```const markup = renderToString(
      <StaticRouter context={{x:"y"}} location={req.url}>
        <App />
      </StaticRouter>
    );
```
App.js
```
const App = ({staticContext}) => {
  console.log(staticContext);
}
```

### Additional context
Tried accessing the same variable inside Route rendered components, but same behaviour happened

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 3.1.0/3.0.0
| Node             | 12
| Browser          | All
| npm/Yarn         | npm
| Operating System | mac
| React            | 16.13.1
| React-Router-Dom | 5.1.2|

**Comment by nimaa77** [comment]
hello @techdiary 
you can't use `staticContext` like that, react-router won't work like that.

read more: https://reacttraining.com/react-router/web/example/static-router

**Comment by techdiary** [comment]
Thank you @nimaa77 for quick help
