### ISSUE TITLE
Add new templates to create-razzle-app, typescript, client-only

### ISSUE THREAD

**Issue by piecyk** [jaredpalmer/razzle#1276]
### Current Behavior

When creating new razzle project for example with typescript there is much manual work to be done.

### Desired Behavior

Running `npx create-razzle-app my-app --template typescript` should setup everything. 

### Suggested Solution

Add templates.

### Who does this impact? Who is this for?

All users.

### Describe alternatives you've considered

Copy paste from examples.

### Additional context

None.

**Comment by nimaa77** [comment]
you can use `create-razzle-app` to create a new project from examples folder:

```bash
npx create-razzle-app --example with-typescript my-razzle-typescript-app
```

and also I'm going to update all of the examples `README.md` files to have a line about this ...

**Comment by nimaa77** [comment]
but I think it would be cool to add support for Github repo URLs with CLI tool

something like `create-react-app`

**Comment by piecyk** [comment]
Ooo didn't know about this, cool 👍Thanks!

**Comment by fivethreeo** [comment]
Nima I have a plan to get on adding that. Just working out what to add and how. I would use npm programmatically to get tar.gz archive urls, download them, use zip -stream and tar-stream to unzip to a temporary directory and copy to new dir and run commands. Then for github use the way we use for official examples just both updated to use request, zip-stream and tar-stream. For git urls use a git module to clone to temp dir...

**Comment by fivethreeo** [comment]
There is a pull for loading examples from more sources. Closing this one

**Comment by isc30** [comment]
@piecyk  this resolution isn't properly documented

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/tree/master/packages/create-razzle-app#or-initialize-a-project-from-npmgithubgitfile-examples

**Comment by isc30** [comment]
Hey @fivethreeo I think many people would benefit from having that command as part of https://razzlejs.org/getting-started

```
npx create-razzle-app --example with-typescript my-razzle-typescript-app
```
