### ISSUE TITLE
Move to Client-side Rendering

### ISSUE THREAD

**Issue by mding5692** [jaredpalmer/razzle#1279]
## ❓Question

We started using Razzle early-on for building out a prototype for a company web app and it did really great things. However, we've encountered many difficulties and generally very unfamiliar with deploying SSR and Razzle on AWS and in production. Is there a easy way for us to move from our current Razzle app setup to a Client-Side rendered app with html files that we can just put on s3? Or even simpler, a way to generate a dist or build folder with html files etc that we can easily use like a client-side rendered react app?

**Comment by nimaa77** [comment]
you can use spa mode
https://github.com/jaredpalmer/razzle#build-types

there is an example in the examples directory (it's called `basic-spa`)

**Comment by mding5692** [comment]
Thanks guys! Going to try that now

**Comment by nimaa77** [comment]
so can we close this issue?

**Comment by mding5692** [comment]
Dont think it worked for us. These are the commands in our package.json we tried using, it did not make a public folder or index.html like the basic-spa example:

- "dev": "cross-env NODE_OPTIONS=--max_old_space_size=8192 razzle start --type=spa",
- "build": "yarn && yarn clean-build; NODE_ENV=production cross-env NODE_OPTIONS=--max_old_space_size=8192  razzle build --type=spa"

**Comment by nimaa77** [comment]
you have to create the `index.html` file yourself.

**Comment by mding5692** [comment]
oh ok, so we create a public folder with an index.html? And it populates the index.html when run the command? Apologies just trying to understand whats fastest way right now for our company to implement the change

**Comment by mding5692** [comment]
Ah I get it now, this is pretty much like a normal client-side react app with just App.js and the index.html references that file inside.

**Comment by nimaa77** [comment]
just copy the HTML file from the public folder of basic-spa example

**Comment by nimaa77** [comment]
> Ah I get it now, this is pretty much like a normal client-side react app with just App.js and the index.html references that file inside.

yeap

**Comment by mding5692** [comment]
Thanks, going to try that right now

**Comment by fivethreeo** [comment]
Seems resolved. Closing
