### ISSUE TITLE
How to change terserOptions

### ISSUE THREAD

**Issue by kaeon** [jaredpalmer/razzle#1282]
## ❓Question
Hi, I use razzle with custom webpack config. I managed to change some of the rules but I can't figure out how to change config.optimization.minimizer, specifically the terserOptions in the TerserPlugin. I would like to set the option compress.drop_console to remove the console output. Is there a way to add this option without changing default configuration?

**Comment by fivethreeo** [comment]
Changing plugin options can be troublesome without loosing defaults. Will look into making options overridable.

**Comment by fivethreeo** [comment]
This is now possible in the finch branch. Use the modifyWebpackOptions hook and modify webpackOptions.terserOptions.
