### ISSUE TITLE
using React Context Api in Razzle

### ISSUE THREAD

**Issue by mrzslr** [jaredpalmer/razzle#1288]
## ❓Question
Hi folks, I've a question, I've been using React Context Api in non-ssr project. since I decide to accomplish this project with SSR I faced with some kind of errors while using react context api in project. however, wanna know is there any example about use context api in SSR or even Razzle?

**Comment by fivethreeo** [comment]
Context api works in razzle SSR, but feel free to ask a specific question about your issue 😀closing until more info is provided
