### ISSUE TITLE
Allow for development build

### ISSUE THREAD

**Issue by cereallarceny** [jaredpalmer/razzle#1289]
### Current Behavior

`razzle build` always returns a build with `NODE_ENV` set to `production`

### Desired Behavior

I would like to be able to specify my `NODE_ENV` like such: `NODE_ENV=development razzle build`.

### Suggested Solution

[This line of code forces builds to always default to `production` mode](https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/scripts/build.js#L4). I'd like to make this conditional. Meaning that if you haven't already specified an environment yourself, it should still default to `production` mode.

### Who does this impact? Who is this for?

Nobody - this feature is opt-in. 😄 

### Describe alternatives you've considered

None, I feel this is fairly straight-forward. Although, I tried doing `NODE_ENV=development razzle build` only to find out that it doesn't work. That led me to read the code and it was pretty obvious why what I wanted to do didn't work.

### Additional context

The reason I'd like to do this is because I'm deploying to two different Firebase projects, one that hosts my development database and another that hosts my production database. I'm server-rendering my application as a Firebase function and want to be able to locally test against the two different databases. The Firebase credentials are configured properly as environment variables. I think it's a pretty straight-forward request and shouldn't result in more than a line or two added to the codebase.

**Comment by cereallarceny** [comment]
I've just confirmed by attempting to do this PR myself that adding a conditional does not actually change the contents of the build. Any thoughts on how this could be supported @nimaa77?

**Comment by fivethreeo** [comment]
@cereallarceny what about just adding a RAZZLE_BUILD_TYPE=staging because lots of razzle decides what to build based on NODE_ENV=development

**Comment by cereallarceny** [comment]
@fivethreeo Quite frankly I don't think that does the job. The goal is to separate my environment variables into two different `.env` files. I have `.env.development` for development and `.env.production` for production. That's a fairly standard dotenv setup, but becomes complicated when I want to test a bundled version of my application with my development keys.

If I do what you're saying, I'd need to put ALL of my environment variables for all environments into one big file. Sounds like a pretty easy way to leak my production keys if I'm not extra careful. I'm not trying to do anything beyond standard practice - is there another workaround possible?

**Comment by fivethreeo** [comment]
@cereallarceny: https://github.com/motdotla/dotenv/blob/master/README.md#should-i-have-multiple-env-files

**Comment by cereallarceny** [comment]
That’s great, but why is this so universally supported in virtually all codebases if it’s not recommended by dotenv themselves? Doing environment specific environment files is universal in thousands of major JavaScript projects that all use dotenv: create-react-app, angular-cli, and vue-cli just to name a few. This is a standard practice, even if dotenv doesn’t recommend it.

Likewise, they don’t really offer an actionable alternative. They just say mention they strongly don’t recommend multiple files. **What’s an alternative?**

**Comment by fivethreeo** [comment]
razzle supports env.production.local and env.production make env.production the same as env.development (symlink?) and keep env.production.local in a safe place?

**Comment by fivethreeo** [comment]
I don't see any other way to do this, close?

**Comment by fivethreeo** [comment]
Closing as wontfix, but if you come up with a better solution we would look into it 😀

**Comment by cereallarceny** [comment]
@fivethreeo It seems actually like it is the intended use-case to manage multiple `.env` files in a project: https://github.com/motdotla/dotenv/issues/437. Come on, you really don't think it's reasonable to add support for various environment-specific environment files?

**Comment by fivethreeo** [comment]
I will reopen this. But I have no idea how this should work. A PR would be great :)

**Comment by brightonmike** [comment]
I'd really like this too - I've actually done it (with errors that don't seem to affect anything) by copying the build script into my own scripts folder and adding a `builddev` command to the package.json.

The bit I haven't got working yet is the watch/build.

**Comment by fivethreeo** [comment]
I have a idea for this now, it has been at the back of my mind. I think it should be clear that it is a production build. So make tha razzle code say anything not development is production. Add a cli arg to razzle build --node-env. Also ask to run if it is not exactly "production" unless you pass --noninteractive. Also force env to end with /staging$|production$/.

**Comment by fivethreeo** [comment]
I think I will add this if someone takes care of documenting it once added.

**Comment by fivethreeo** [comment]
I added this to razzle now. But the build gets larger for some reason when not using “production” node env. May be related to babel checking NODE_ENV. But it works...

**Comment by silviubogan** [comment]
@fivethreeo What is the current status on this issue? The following command

```
NODE_ENV=staging tsc -b && NODE_ENV=staging razzle build --noninteractive --node-env staging
```

does a production build according to the very small sizes of the files in the build as shown by the command above.

```
File sizes after gzip:

  670.86 KB  build/public/static/js/client.24d8f906.js
  25.05 KB   build/public/static/js/875.0a0457c2.chunk.js
  14.3 KB    build/public/static/js/786.e5898511.chunk.js
  2.75 KB    build/public/static/css/client.f583c45a.css
  1.83 KB    build/assets.json
  662 B      build/public/static/css/786.f5293233.chunk.css
```

The command shown above prints this, after waiting a little:

```
DefinePlugin
Conflicting values for 'process.env.NODE_ENV'
'"staging"' !== '"production"'
```

What am I misunderstanding?

**Comment by fivethreeo** [comment]
https://stackoverflow.com/questions/66772358/webpack-warning-warning-in-defineplugin-conflicting-values-for-process-env-no

https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/config/env.js#L79

**Comment by fivethreeo** [comment]
Staging should be close to production build.

**Comment by silviubogan** [comment]
@fivethreeo 

> Staging should be close to production build.

I actually want development, not staging but I read the comments above and I thought it works only with staging.

If I run:

```
$ NODE_ENV=development npx tsc -b && NODE_ENV=development razzle build --noninteractive --node-env development
```

I get:

```
Failed to compile.
Cannot find module 'razzle-plugin-scss'
Require stack:
- /home/silviub/.config/yarn/global/node_modules/razzle/config/runPlugin.js
- /home/silviub/.config/yarn/global/node_modules/razzle/config/createConfig.js
- /home/silviub/.config/yarn/global/node_modules/razzle/scripts/build.js
```

If I run the following, I get:

```
$ npm ls razzle-plugin-scss
my-project@0.1.0 /some/path/to/my/project
└── razzle-plugin-scss@4.0.6
```

[This](https://gist.github.com/silviubogan/68b8b6c0c652930234c5daa208b3332b) is the razzle.config.js.

Please let me know if I should open a new discussion for this issue.

Thanks.

**Comment by fivethreeo** [comment]
You have razzle installed globally and the plugin locally. Require probably can't find it.

**Comment by silviubogan** [comment]
@fivethreeo 

> You have razzle installed globally and the plugin locally. Require probably can't find it.

This seems to work well but generates the production bundle:

```
$ NODE_ENV=development npx tsc -b && NODE_ENV=development npx razzle build --noninteractive --node-env development
```

Why does this not produce a development bundle? Please see the razzle.config.js link in the previous message. Thanks.

**Comment by fivethreeo** [comment]
Build only builds production and staging for now

https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/scripts/build.js#L13

Open to changing this

**Comment by silviubogan** [comment]
@fivethreeo 

> Build only builds production and staging for now
> 
> https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/scripts/build.js#L13
> 
> Open to changing this

Please let me know if I can help with something. Thanks.

**Comment by fivethreeo** [comment]
Just do a pull request with proposed changes :) If it is not backwards incompatibe I will pull it.

**Comment by silviubogan** [comment]
@fivethreeo 

> Just do a pull request with proposed changes :) If it is not backwards incompatibe I will pull it.

Thank you. I think I've done the main changes locally, without the docs for them. I am currently getting around CONTRIBUTING.md. I think I have to run the tests with them. If I need help I will post here. I am wondering how can I test a local version of Razzle in my existing application?

**Comment by fivethreeo** [comment]
you can use yarn link or npm link

**Comment by silviubogan** [comment]
@fivethreeo Please see: https://github.com/jaredpalmer/razzle/pull/1691

**Comment by fivethreeo** [comment]
Added development build
