### ISSUE TITLE
Upgrade 3.0.0 to 3.1.1 prettyNodeErrors import problem

### ISSUE THREAD

**Issue by mschipperheyn** [jaredpalmer/razzle#1295]
## 🐛 Bug report
I have a multi package project of which the server is one package. I have a heavily customized razzle.config.js.

Getting this error after upgrading
```
/Users/me/project/packages/server/build/webpack:/webpack/bootstrap:754
 		modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
^
TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (/Users/me/project/packages/server/build/webpack:/webpack/bootstrap:754:1)
    at fn (/Users/me/project/packages/server/build/webpack:/webpack/bootstrap:59:1)
    at Object.0 (/Users/me/project/packages/server/build/server.js:105157:1)
    at __webpack_require__ (/Users/me/project/packages/server/build/webpack:/webpack/bootstrap:754:1)
    at /Users/me/project/packages/server/build/webpack:/webpack/bootstrap:848:1
    at Object.<anonymous> (/Users/me/project/packages/server/build/server.js:853:10)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)

```
The actual import that is going wrong is this one. It tries to retrieve razzle-dev-tools from the package node_modules when the file is actually in the root node_modules.
```
__webpack_require__(/*! razzle-dev-utils/prettyNodeErrors */"../../node_modules/razzle-dev-utils/prettyNodeErrors.js");
```
My server package jsconfig.json looks like this. I had to change `baseUrl: '.'` to `baseUrl: 'src'` to get razzle to start at all.
```
{
	"compilerOptions": {
		"target": "es2017",
		"allowSyntheticDefaultImports": false,
		"moduleResolution": "node",
		"baseUrl": "src",
		"paths": {
			"common-lib/*": [
				"../common-lib/*"
			],
			"social/*": [
				"../social/*"
			],
			"UI/*": [
				"../common-lib/src/components/UI/*"
			],
			"locale/*": [
				"./src/shared/locale/*"
			],
			"router/*": [
				"../common-lib/src/router/*"
			],
			"store/*": [
				"./src/shared/store/*"
			],
			"styles/*": [
				"../common-lib/src/style/*"
			],
			"server/*": [
				"./src/server/*"
			]
		}
	},
	"exclude": [
		"node_modules",
		"../../node_modules",
		"build"
	]
}
```

babel.config.js is in the project root
```
const path = require('path');

const moduleResolver = require('babel-plugin-module-resolver');

module.exports = api => {
	api.cache(true);
	console.log('babel root config loading');
	return {
		sourceType: 'unambiguous',
		presets: [
			'babel-preset-expo',
			'@lingui/babel-preset-react',
		],
		plugins: [
			'@babel/plugin-transform-flow-strip-types',
			'macros',
			[
				'module-resolver',
				{
					extensions: [
						'.web.js',
						'.native.js',
						'.ios.js',
						'.android.js',
						'.js',
						'.json',
					],
					alias: {
						root: path.resolve(__dirname, ''),
						assets: path.resolve(__dirname, 'assets'),
						web: path.resolve(__dirname, 'packages/web'),
						social: path.resolve(__dirname, 'packages/social'),
						server: path.resolve(__dirname, 'packages/server/src/server'),
						shared: path.resolve(__dirname, 'packages/server/src/shared'),
						'common-lib': path.resolve(__dirname, 'packages/common-lib'),
						styles: path.resolve(__dirname, 'packages/common-lib/src/style'),
						UI: path.resolve(
							__dirname,
							'packages/common-lib/src/components/UI',
						),
						helpers: path.resolve(__dirname, 'packages/common-lib/src/helpers'),
						router: path.resolve(__dirname, 'packages/common-lib/src/router'),
					},
				},
			],
			'@loadable/babel-plugin',
		],
		env: {
			development: {
				compact: false,
			},
			test: {
				compact: false,
			},
		},
	};
};

```
### Current Behavior

startup failure

### Expected behavior

Obviously razzle 3.1.1 is less forgiving of my current config. My money is on the package structure.

### Suggested solution(s)

I'm not really sure if this report is very actionable. Perhaps it will trigger a "did you look at that". 

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 3.1.1
| Razzle Plugins   | 
| Node             | 12.16.x
| Browser          | Chrome
| npm/Yarn         | yarn
| Operating System | MAc os
| TypeScript       |
| React            | 16.9.0

**Comment by fivethreeo** [comment]
This is where this is added https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/config/createConfig.js#L283, not sure why this happens but the error might not be from this module but gets printed by it. Or we need to resolve it differently somehow. Paths and exclude in jsconfig has no effect on razzle as far as I know.

**Comment by fivethreeo** [comment]
Or your babel resolve plugin is resolving wrong somehow. Hard to tell in I complex setup with babel plugins.🙁but we will see if anyone else encounters it with a less complex setup. Do tell us if you figure it out 😀

**Comment by mschipperheyn** [comment]
> This is where this is added https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/config/createConfig.js#L283, not sure why this happens but the error might not be from this module but gets printed by it. Or we need to resolve it differently somehow. Paths and exclude in jsconfig has no effect on razzle as far as I know.

Hmm, yes, that code 
```
config.entry.unshift('webpack/hot/poll?300');
config.entry.unshift('razzle-dev-utils/prettyNodeErrors');
```
looks a bit iffy to me.

This is how it was imported before
```
alias: {
        // This is required so symlinks work during development.
        'webpack/hot/poll': require.resolve('webpack/hot/poll'),
      },
```

I recommend changing that to use actual require statements.

**Comment by fivethreeo** [comment]
Not quite sure, maybe it should be the other way around. Resolve the other one too. But your resolve babel plugin may be the issue. None of those lines changed from, 3.0.0 to 3.1.1, I need to investigate this. But could you make a simple example that has the same problem? Else we would have to wait for someone else to encounter this in a more basic setup.

**Comment by mschipperheyn** [comment]
@fivethreeeo in fact they did AFAIK. I looked at the 3.0.0 code and it used require statements.

**Comment by nimaa77** [comment]
@mschipperheyn hello
I think I know what's the problem with this 

it's related to this PR https://github.com/jaredpalmer/razzle/pull/1112

I'm going to add an option to support `compilerOptions.paths`.

and when we add that option there is no need to config `babel-plugin-module-resolver`, razzle will handle that for us

**Comment by fivethreeo** [comment]
Fixed in canary release
