### ISSUE TITLE
version 3.1.3 - Http-proxy dependency is high risk

### ISSUE THREAD

**Issue by matt-catellier** [jaredpalmer/razzle#1300]
### Current Behavior

When I run npm audit --audit-level=moderate, the audit fails dues to http-proxy package.

![image](https://user-images.githubusercontent.com/16104817/82077386-2c40ec80-9694-11ea-966a-cd2e10fed76e.png)

### Expected behavior

I can run audit with level moderate and pass in my CI pipeline

### Reproducible example

Use version 3.1.3 of razzle, run npm audit --audit-level=moderate

### Suggested solution(s)

https://www.npmjs.com/advisories/1486

It seems to be coming version of webpack-dev server? Maybe you can update that package and it has fix? If not may need to use different package as http-proxy is the issue and it does not seem to be maintained anymore

### Additional context

In the meantime I have increased the audit level, so our CI pipeline is not rejecting code, and team continue dev efforts

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 3.1.3
| Node             | v12.13.0
| npm/Yarn         | 6.12.0
| Operating System | Mac OS Version 10.15.4

**Comment by fivethreeo** [comment]
I see this is a issue with all versions of a webpack dev server dependency which is a pretty important part of razzle and only used in development. So it should be reported to webpack dev server so they could fix it. Not much can be done with it on our end unfortunately.

**Comment by matt-catellier** [comment]
Thanks for your response. Will follow up with them and close this issue when it has been resolved.

**Comment by fivethreeo** [comment]
Fixed
