### ISSUE TITLE
3.1.3 doesn't work with CSS modules variables

### ISSUE THREAD

**Issue by SuperIRis** [jaredpalmer/razzle#1302]
### Current Behavior

After updating to 3.1.3, CSS modules is not recognizing the [variables](https://github.com/css-modules/css-modules/blob/master/docs/values-variables.md) anymore. I am using razzle-plugin-postcss.
Server shows error:
`You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.`
And client shows that it cannot read the variables with errors like
`TypeError: Cannot read property 'main-bg' of undefined`

### Expected behavior

CSS modules variables work properly, and can be used within different files. This worked in Razzle <3.1.3. It can be tested by changing the version in the example, the errors are gone and the app works properly.

### Reproducible example

https://github.com/SuperIRis/test-razzle

### Suggested solution(s)

Not completely sure why this is happening or how to fix it.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 3.1.3
| Razzle Plugins   | razzle-plugin-postcss
| Node             | v12.16.1
| Browser          | Chrome 81.0.4044.138
| npm/Yarn         | 6.13.4
| Operating System | MacOS 10.14.6
| React            | 16.13.1

**Comment by fivethreeo** [comment]
razzle-plugin-postcss is not ours, please report in their repository :)

**Comment by fivethreeo** [comment]
Use razzle-plugin-scss also supports postcss.
