### ISSUE TITLE
How to add a webpack module to razzle.config.js file?

### ISSUE THREAD

**Issue by Arshazar** [jaredpalmer/razzle#1303]
## ❓Question
I wanted to add the below webpack config to razzle.config.js and integrate it:
```
### {
  test: /\.svg$/,
  use: [
    {
      loader: "babel-loader"
    },
    {
      loader: "react-svg-loader",
      options: {
        jsx: true // true outputs JSX tags
      }
    }
  ]
}
```

In spite of the written " modify(baseConfig, {target, dev}, webpack) { ..." which had been mentioned before, I wonder how to implement it since its syntax differs... 
Please notice me if you can give a hand...

**Comment by fivethreeo** [comment]
Like so :)

```js
'use strict';

module.exports = {
  modify: (defaultConfig, { target, dev }, webpack) => {
    const config = Object.assign({}, defaultConfig);
    
    config.module.rules = config.module.rules.reduce((rules, rule) => {

        if (rule.exclude &&
          rule.loader.indexOf('file-loader') !== -1) {

          const { exclude, ...rest } = rule;

          rules.push({ ...rest, ...{
            exclude: exclude.concat([/\.svg$/])
          }});

        }
        else {
          rules.push(rule);
        }
        
      return rules;
      
    }, []);
    
    config.module.rules = config.module.rules.push({
      test: /\.svg$/,
      use: [
        {
          loader: require.resolve('babel-loader'),
        },
        {
          loader: require.resolve('react-svg-loader'),
          options: {
            jsx: true // true outputs JSX tags
          }
        }
      ]
    });
    
    return config;
    }
  };
```

**Comment by Arshazar** [comment]
**Thanks...** :))))

**Comment by Arshazar** [comment]
> Like so :)
> 
> ```js
> 'use strict';
> 
> module.exports = {
>   modify: (defaultConfig, { target, dev }, webpack) => {
>     const config = Object.assign({}, defaultConfig);
>     
>     config.module.rules = config.module.rules.reduce((rules, rule) => {
> 
>         if (rule.exclude &&
>           rule.loader.indexOf('file-loader') !== -1) {
> 
>           const { exclude, ...rest } = rule;
> 
>           rules.push({ ...rest, ...{
>             exclude: exclude.concat([/\.svg$/])
>           }});
> 
>         }
>         else {
>           rules.push(rule);
>         }
>         
>       return rules;
>       
>     }, []);
>     
>     config.module.rules = config.module.rules.push({
>       test: /\.svg$/,
>       use: [
>         {
>           loader: require.resolve('babel-loader'),
>         },
>         {
>           loader: require.resolve('react-svg-loader'),
>           options: {
>             jsx: true // true outputs JSX tags
>           }
>         }
>       ]
>     });
>     
>     return config;
>     }
>   };
> ```

> Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
>  - configuration.module.rules should be an array:
>    [object { compiler?, enforce?, exclude?, include?, issuer?, loader?, loaders?, oneOf?, options?, parser?, query?, realResource?, resolve?, resource?, resourceQuery?, rules?, sideEffects?, test?, type?, use? }]
>    -> An array of rules applied for modules.

**Comment by fivethreeo** [comment]
Try

```js
'use strict';

module.exports = {
  modify: (defaultConfig, { target, dev }, webpack) => {
    const config = Object.assign({}, defaultConfig);
    
    config.module.rules = config.module.rules.reduce((rules, rule) => {

        if (rule.exclude &&
          rule.loader.indexOf('file-loader') !== -1) {

          const { exclude, ...rest } = rule;

          rules.push({ ...rest, ...{
            exclude: exclude.concat([/\.svg$/])
          }});

        }
        else {
          rules.push(rule);
        }
        
      return rules;
      
    }, []);
    
    config.module.rules.push({
      test: /\.svg$/,
      use: [
        {
          loader: require.resolve('babel-loader'),
        },
        {
          loader: require.resolve('react-svg-loader'),
          options: {
            jsx: true // true outputs JSX tags
          }
        }
      ]
    });
    
    return config;
    }
  };
```

**Comment by fivethreeo** [comment]
I did not test this but it should give you a general idea. Add some console logs in there to see what is actually going on. It is just a regular webpack config so modify accordingly 😀

**Comment by alexanderankin** [comment]
@fivethreeo this modify function never runs

**Comment by fivethreeo** [comment]
In finch branch modify changed to modifyWebpackConfig.

**Comment by fivethreeo** [comment]
Also, this can be done better now. I will post a new way later.

**Comment by fivethreeo** [comment]
In the **finch** release you can do:

```js
'use strict';

module.exports = {
  modifyWebpackOptions(opts) {
    const options = Object.assign({}, opts.options.webpackOptions);    // Add .svg to exlude
    options.fileLoaderExlude = [/\.svg$/, ...options.fileLoaderExlude];
    return options;
  },
  modifyWebpackConfig(opts) {
    const config = Object.assign({}, opts.webpackConfig);
    const options = Object.assign({}, opts.options.webpackOptions);
    
   config.module.rules.push({
      test: /\.svg$/,
      use: [
        options.babelRule.use[0],
        {
          loader: require.resolve('react-svg-loader'),
          options: {
            jsx: true // true outputs JSX tags
          }
        }
      ]
    });
    return config;
  },
};
```

**Comment by alexanderankin** [comment]
@fivethreeo excellent thanks and thanks for sticking around to maintain the project
