### ISSUE TITLE
.babelrc not being used in application upgraded from v2 to v3

### ISSUE THREAD

**Issue by erdengel-noah** [jaredpalmer/razzle#1318]
Hallo.

I am trying to use a .babelrc File in an Application that was created with Version 2 of razzle and later upgraded to version 3. With both Versions 3.1.3 and 3.0.0 i get the message "Using .babelrc defined in your app root", however that file is not used. I can write something completely invalid or leave it without the required preset and the application builds anyways and works correct. Same when configured correctly with a additional plugin that we require now. The Plugin is not being loaded.

Any help in tracking down the issue that prevents razzle from working correctly would be appreciated as i suspect its something internal in the packe. When i create a completly new application, it works as expected.
Are there maybe some Dependencys that need manual update ?

**Comment by fivethreeo** [comment]
Where is your .babelrc located in the project?

**Comment by erdengel-noah** [comment]
In the root folder, at same level as package.json and razzle.config

(Thanks for reaching out)

**Comment by fivethreeo** [comment]
Did you update all razzle-* packages?

**Comment by erdengel-noah** [comment]
Yes. As i thought it might be a Bug in Version 3.0, i upgraded everything to 3.1.3 and tested there. Although we could not keep that Version as it broke some things in our release pipeline that we will have to fix first.

Everything is in our case is razzle, razzle-plugin-typescript, razzle-plugin-scss.

**Comment by erdengel-noah** [comment]
It seems to be related to the plugin razzle-plugin-typescript, after adding it to a newly scaffolded solution with create-razzle-app and adding the razzle-plugin-typescript, a custom .babelrc is being ignored.

**Comment by fivethreeo** [comment]
Did you add useBabel: true option to the typescript plugin?

**Comment by erdengel-noah** [comment]
No. 
That's exactly what was missing. Thanks for the assistance 😅.
