### ISSUE TITLE
PORT_DEV

### ISSUE THREAD

**Issue by pseudo-su** [jaredpalmer/razzle#1320]
## ~📖 Documentation~ Feature request

I have a monorepo and I'm setting it up with multiple packages that each use razzle. I was confused as to why I couldn't get them all to run in dev mode at the same time (each package is using a different sequential `PORT` value).

After a bit of digging I realised that [the secret sauce](https://github.com/jaredpalmer/razzle/tree/7087508ab625ea498b0a3420e0fa9bedf78a5222#how-razzle-works-the-secret-sauce) was the cause of my issues 😄 (implicitly choosing the next sequential port as the dev port).

After a little more digging I've found `PORT_DEV` in the code [here](https://github.com/jaredpalmer/razzle/blob/8a356247ab866bc6ecdfcbb508ec1f4592fe52c1/packages/razzle-dev-utils/setPorts.js) but it's not documented.

EDIT: turns out although although the reference to PORT_DEV exists in the code it doesn't seem to be used anymore? I'd like to suggest making it work **and** adding it to the docs

**Comment by fivethreeo** [comment]
Fixed

**Comment by pseudo-su** [comment]
@fivethreeo any idea when this might be released? would be nice to get rid of my workaround

**Comment by fivethreeo** [comment]
Will see what I can do about that 😀
