### ISSUE TITLE
Transpiling node_modules like CRA

### ISSUE THREAD

**Issue by hennessyevan** [jaredpalmer/razzle#1327]
Create React App supports transpiling es6 node_modules since v2. Is that something being considered in razzle? I've been trying to wrestle with razzle and getting es6 modules through `babel-loader`. As more libraries ship with es6 only syntax, it's important to not exclude all node_modules as razzle does by default.

**Comment by fivethreeo** [comment]
In the dev version this can be done by adding a jsconfig with compilerOptions.paths set to { “somemodule/\*”: “somemodule/\*” } , may consider adding include and exclude support to razzle if this does not work.

**Comment by hennessyevan** [comment]
This didn't work unfortunately after trying it all sorts of different ways. There is a pesky `map-obj` sub-dependency that doesn't include an es5 bundle but uses object spread syntax and so breaks browsers like MS Legacy Edge. I have a repro here https://github.com/hennessyevan/razzle-transpile-repro.

The bundle includes `map-obj` and the spread syntax un-transpiled. Packages like `lodash-es` work fine as long as I whitelist them from `nodeExternals` because I'm importing them directly in my project. 

In the meantime I pinned `map-obj` to a previous version that was written in es5 to get around this.

**Comment by fivethreeo** [comment]
Hi, the jsconfig solution is not in the release version yet. I can try adding this as a example there :)

**Comment by fivethreeo** [comment]
I made a new ticket to fix this. But not quite sure how to do this the right way. Bit i’ll try 😀
