### ISSUE TITLE
Env variables. showing in bundle js on production mode

### ISSUE THREAD

**Issue by folababa100** [jaredpalmer/razzle#1329]
## ❓Question

I ran yarn build to deploy my app on production and decided to search my files to see it my env were showing in the build folder bundle.js. Is there a way to prevent this.
Thanks for your feedback.

**Comment by fivethreeo** [comment]
Some env vars are in the code. But only those added that are defined in DefinePlugin. See build env vars in the docs. If you see anything not defined there or not prefixed by RAZZLE it is a bug.

**Comment by fivethreeo** [comment]
Can you try out the new canary release?

**Comment by fivethreeo** [comment]
Assuming this is fixed, reopen if that is not the case.
