### ISSUE TITLE
Question around performance on build times.

### ISSUE THREAD

**Issue by jcblw** [jaredpalmer/razzle#1332]
## ❓Question

Hey there,

My team has been using Razzle for the past couple of months. We recently have been running into some major pains with build times sometimes taking up to 20 seconds to be able to debug the new code that we have pushed. A couple of unique things about our application.

* Its Typescript
* Its a monorepo ( yarn workspaces & Lerna )
* We use barrel files
* We currently only have one additional Webpack plugin `circular-dependency-plugin`
* Its a large codebase

**Versions**

* Razzle 3.1.0
* Node 10.15
* Typescript 3.7.4

Wondering if anyone has some experience with getting build times down in Razzle? The teams are functioning right now, but its starting to become an issue and we would love to hear from the Razzle community if there is something that we can do to help reduce our build times.

Any feedback welcomed.

**Comment by fivethreeo** [comment]
Razzle 3.2 will have builtin typescript support. 

You could look into using thread-loader in babel to compile in paralell.

**Comment by fivethreeo** [comment]
Next.js does this with thread-loader and cache-loader. We should have this in razzle too.

**Comment by jcblw** [comment]
@fivethreeo thanks for your recommendations, those are some great recommendation. I think we will look into the thread loader that looks promising. I did not know that existed. 

We were able to get some gains from removing the circular dependency plugin on development. I think the team is happy with the change and love the recs. Closing this ticket.

**Comment by fivethreeo** [comment]
Great! If you find a good solution to this please update us :)
