### ISSUE TITLE
Android Browser Only Error: Uncaught SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by nesbtesh** [jaredpalmer/razzle#1340]
## 🐛 Bug report

Uncaught SyntaxError: Use of const in strict mode.

### Current Behavior

<img width="1194" alt="Screen Shot 2020-07-02 at 9 27 59 AM" src="https://user-images.githubusercontent.com/3814044/86371295-5485aa00-bc46-11ea-801a-b51a46b2492b.png">

I am trying to pinpoint the error but I cant seem to find the error. I keep getting "Use of const in strict mode". whenever I try running my site on Android Browser

**Comment by fivethreeo** [comment]
Need more info 😀

**Comment by fivethreeo** [comment]
This is probably a dependency that is not valid es5. Closing.

**Comment by yjwSurCode** [comment]
解决了吗
