### ISSUE TITLE
can't use process.env.FOO (from .env) in server.js

### ISSUE THREAD

**Issue by aforty** [jaredpalmer/razzle#1353]
### Current Behavior

If I try to access `process.env.FOO` (where `FOO="foo bar"` in my .env) and insert it into the HTML it comes up as undefined.

### Expected behavior

The documentation makes it seem as though I should be able to access any variables defined in dotenv files via `process.env`.

### Reproducible example

```
npx create-razzle-app test-razzle-dotenv
cd test-razzle-dotenv
echo "FOO=\"foo bar\"" > .env
```

On line 44 of `src/server.js` (inside the body tag) add: `<p>${process.env.FOO}</p>`

``` 
npm run build
npm run start:prod
open http://localhost:3000
```

### Suggested solution(s)

I wish I had any...

### Additional context

n/a

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | v3.1.5
| Razzle Plugins   | n/a
| Node             | v14.3.0
| Browser          | n/a
| npm/Yarn         | npm @ v6.14.5
| Operating System | macos
| TypeScript       | n/a
| React            | n/a

**Comment by fivethreeo** [comment]
In html or in js?

**Comment by cseas** [comment]
Did you try prefixing your variable name with `RAZZLE_`?
The [documentation](https://razzlejs.org/docs/environment-variables) states that custom environment variable names must start with `RAZZLE_`.

In your example, that would be
```sh
echo "RAZZLE_FOO=\"foo bar\"" > .env
```

**Comment by fivethreeo** [comment]
Fixed
