### ISSUE TITLE
Razzle/Vercel(aka zeit) deployement

### ISSUE THREAD

**Issue by momosetti** [jaredpalmer/razzle#1355]
## ❓Question
Any deployment  guide for deploy razzle app on vercel? thanks!

**Comment by whjvenyl** [comment]
Create this vercel.json in the root directory of your project:
`{
    "name": "after-js",
    "version": 2,
    "builds": [
        {
            "src": "build/public/**",
            "use": "@now/static"
        },
        {
            "src": "build/server.js",
            "use": "@now/node-server"
        }
    ],
    "routes": [
        { "src": "/assets.json", "dest": "build/assets.json" },
        { "src": "/chunks.json", "dest": "build/chunks.json" },
        { "src": "/favicon.ico", "dest": "build/public/favicon.ico" },
        { "src": "/robots.txt", "dest": "build/public/robots.txt" },
        { "src": "/static/(.*)", "dest": "build/public/static/$1" },
        { "src": "/(.*)", "dest": "build/server.js" }
        
    ]
}`

Then do a local build with 'npm run build'. 
Afterwards deploy from a local terminal with 'vercel'
