### ISSUE TITLE
The options of babel plugin @babel/plugin-proposal-object-rest-spread is unavailable

### ISSUE THREAD

**Issue by 617976080** [jaredpalmer/razzle#1364]
### Current Behavior

the babel convert origin code with babel's helper instead of Object.assign:
```javascript
var mapStateToProps = function mapStateToProps(store) {
  return _babel_runtime_helpers_objectSpread__WEBPACK_IMPORTED_MODULE_0___default()({}, store.app);
};
```

### Desired Behavior

```javascript
var mapStateToProps = function mapStateToProps(store) {
  return Object.assign({}, store.app);
};
```

### Suggested Solution
modify the babel-preset-razzle to this:
```javascript
// ...
module.exports = {
  // ...
  plugins: [
    [
      "@babel/plugin-proposal-object-rest-spread",
      { loose: true, useBuiltIns: true },
    ],
    // ...
  ],
};
```
see more  [@babel/babel-plugin-proposal-object-rest-spread](https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread)
```

**Comment by fivethreeo** [comment]
Won't that be a issue on older browsers? We could maybe differentiate between node and web builds?

**Comment by 617976080** [comment]
> Won't that be a issue on older browsers? We could maybe differentiate between node and web builds?

Ok. Thanks.
