### ISSUE TITLE
multiple entry points

### ISSUE THREAD

**Issue by mark-steven-au** [jaredpalmer/razzle#1365]
## ❓Question
I have not used Razzle but it looks extremely promising
I am wondering if it is possible to build a Razzle App with multiple entry points.
Eg one App with
index.html, admin.html, about.html
So a user can explicitly go direct to admin.html and enter App without going though the prerequisite
index.html
I have looked things like rewire but they break it in order to obtain this option so hoping Razzle can do this without breaking React.
thanks for any feedback

**Comment by fivethreeo** [comment]
With server side rendering it works like that by default. But not with html files, just paths. We will soon have static export as well that prerenders specified paths to a directory tree with index.html in each dir.

**Comment by npearson72** [comment]
Multiple entry points are must if you plan to build browser extensions. It's also necessary to disable filename hashing.

Any chance Razzle offers enough hooks into webpack to allow modifying the entry points?
