### ISSUE TITLE
Multiple html files with same js  possible with Razzle?

### ISSUE THREAD

**Issue by mark-steven-au** [jaredpalmer/razzle#1366]
## ❓Question
I am interested to know if it is possible to have multiple entry points on a Razzle App without exiting?
Looking at building single App that has more than the standard index.html entry point.
Eg example.com with index.html, 
admin.example.com with admin.html,
and about.example.com with about.html
Ability to enter app through admin directly without going through index?
Any examples out there.
Thanks in advance.

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/tree/master/examples/with-react-router

**Comment by 617976080** [comment]
You can use the modify function to change the webpack config:
1. change the entry to an object. Its key is entry name, its value is entry javascript file path.
2. change the output to like: "[name].js" to ensure generate multiply bundle.
3. change the plugins, push back serveral HTMLWebpackPlugin.

**Comment by mark-steven-au** [comment]
Thanks very much!
i'll give it a go.

**Comment by mark-steven-au** [comment]
OK feeling pretty stupid on this hoping you can help.
If I use your recommended setup eg
npx create-razzle-app test-app it works fine and installs a working small razzle App very quickly but without your examples.

 I wanted to try your full example app 
https://github.com/jaredpalmer/razzle

I download this Master directly from GitHub then using terminal 
installed 
updates and many other attempts using both npm npx and yarn and could not get it to work.
Any chance you can give me the steps needed to get this example to fire up?
I am sure it simple but just cannot get it to work my end

**Comment by fivethreeo** [comment]
Hi, cloning razzle is not necessary to use the examples.

Try
`npx create-razzle-app test-app —example with-react-router`

**Comment by mark-steven-au** [comment]
Hi again,
Sorry no further along so I must be missing something fundamental in what I am thinking how Razzle works.
Standard React project you always enter React through index.html/index.js
Then it is possible with React router to have other virtual pages eg
example.com/page1 example.com/page2 which are in fact 
example.com/page1.js, example.com/page2.js etc
however if you go as a direct URL to example.com/page2.html you do not get to enter the React App.
So is it possible to enter Razzle on a direct URL to exaple.com/page2.html?
I am trying to have the main App on example.com
then another 
admin.example.com
and 
about.example.com

I  did as you directed 
npx create-razzle-app test-app —example with-react-router
and it built the App easily so thank you for that section
I then ran
npm run build to see what it produced which was a bundle of js  in the build folder but no html page?

So is there a explanation page somewhere of how to set it up to produce an index page plus page1.html and page2.html in the build?

Appreciate any direction here as I am lost as to what is going on.
Sorry to trouble you on this.
Regards
mark

**Comment by fivethreeo** [comment]
I think you are a bit too focused on the html files part. 😀

If you run npm run start or yarn start you get a development server running,

If you run npm run build or yarn build and then run npm run start:prod or yarn start:prod you get a production server running.

The pages are rendered server side so there is no html files. Just rendered html returned to your browser. If you want just a static site (no server side rendering) you can go with a single page application build. But then you have to do a lot of custom configuration of razzle. If you look at razzles source code. (createConfig.js) you see html webpack plugin configuration at the bottom. So basically add more html webpack plugin instances there by using razzle.config.js

We are working on a razzle export that exports a static version of the server rendered app that would fit your use-case but that won’t be out in a while.

Hope this clarifies things 😀

**Comment by mark-steven-au** [comment]
HI And thanks very much for the clarification!
This lack of HTMl defiantly confused as I was used to a single html in standard React.
I am looking at a site that will be both dynamic and static with emphasis on dynamic.
It does sound like what you are working on might be what I am trying to achieve so look forward to what you guys do there.

With DNS usually wanting an html page to "look" at, are there any tricks to getting DNS providers a correct way to trying to get the CNAME to look at individual js file? DNS providers had no idea of how this could be achieved hence the question.
They kept referring back to site needing an html page.
If I could be of any help int eh development either via help of financially supporting it get back to me.
Cheers
Mark

**Comment by fivethreeo** [comment]
I got a idea for you 😀

If the server is httpd only, this won’t work with nginx 

In the served directory add a .htaccess containing this:

```apacheconf
RewriteEngine On
SetEnvIf Host "^(.*?)\..*" DOMAIN_PREFIX=$1
RewriteRule "^/$" "/%{DOMAIN_PREFIX}.html" [L]
```

Not sure if this will work, but you could give it a try 😀

When I get closer to static export working I’ll give you a heads up 😀

**Comment by mark-steven-au** [comment]
Awesome thanks very much.
It is AWS S3 bucket so http via cloudfront to https.
Ill give your suggestion a go and
Look forward to your new project
