### ISSUE TITLE
Latest version of Razzle inserting a /:PORT/ segment into the URL breaking HMR on reverse proxied app.

### ISSUE THREAD

**Issue by laurencefass** [jaredpalmer/razzle#1372]
### Current Behavior

I am trying to run razzle app behind an nginx reverse proxy. Razzle is inserting a /:PORT/ section inthe URL breaking HMR. The following settings worked without additional plugins in an earlier version of Razzle ("razzle": "^3.0.0") but the exact same config is now inserting a /:PORT/ in the URL address.

e.g. 

`https://razzle.syntapse.co.uk/myapp/webpack/:3001/sockjs-node/info?t=1596182701927`

settings: 

.env

```
PUBLIC_PATH='https://razzle.syntapse.co.uk/myapp/'
CLIENT_PUBLIC_PATH='https://razzle.syntapse.co.uk/myapp/webpack/'
PORT=3000
```

razzle.config.js (working as expected in earlier Razzle version)

```
module.exports = {
  modify(config, { target, dev }, webpack) {
    console.log(config);
    const appConfig = config;
    if ( target==='web' && dev ) {
      appConfig.devServer.sockHost = "razzle.syntapse.co.uk/myapp/webpack/";
      appConfig.devServer.sockPath = "/sockjs-node/";
    }
    return appConfig;
  },
};

```

The nginx configuration is consistent between the older working version and the latest version:

```
    location ^~ /myapp/webpack/ {
        proxy_pass http://0.0.0.0:3001/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
    location ^~ /myapp/ {
        proxy_pass http://0.0.0.0:3000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
```
### Expected behavior

The socket query should not explicitly contain the PORT reference. The Correct URL returning meaningful data is:

https://razzle.syntapse.co.uk/latest-dev/webpack/sockjs-node/info?t=1596182701927

Note exclusion of the port

### Reproducible example

work in progress.

### Suggested solution(s)

remove the extra /:PORT/ segment of the URL.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           |     "razzle": "^3.1.6",
| Razzle Plugins   | none
| Node             | 12.13.1
| Browser          | chrome latest
| npm/Yarn         | 1.21.1
| Operating System | linux debian
| TypeScript       | n/a
| React            |     "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-router-dom": "^5.2.0"

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/tree/canary/examples/with-single-exposed-port

**Comment by laurencefass** [comment]
thanks i dont understand how i can use this information to remove the /:PORT/ from the URL. Its presence looks like an error as i haven't specified that i want it anywhere (and it doesnt apppear in earlier build of Razzle).

The URL is correct without the /:PORT/ section. Do I use devServer.proxy to remove it?

**Comment by fivethreeo** [comment]
I think so. :)

**Comment by laurencefass** [comment]
Still looks like a bug. It doesnt look like it should be there as the URL doesnt make sense with it in. The PORT is the correct one, just not in the URL.

**Comment by fivethreeo** [comment]
https://webpack.js.org/configuration/dev-server/#devserverpublic

**Comment by fivethreeo** [comment]
https://gist.github.com/fivethreeo/947607499127199a91f4b3f695dca27d

**Comment by fivethreeo** [comment]
Did this solve it? 😃

**Comment by laurencefass** [comment]
not yet will try again next week. thanks.

**Comment by schuylr** [comment]
I don't think you have a bug since you're including a path inside of the `sockHost`, so Webpack will try to interpolate the port to the end of it. Try making a separate `location` block in the Nginx config in addition to your current ones:

```
    # Note it's ~ ^ instead of ^~ so the path is included to the proxy
    location ~ ^/myapp/sockjs-node {
        proxy_pass http://0.0.0.0:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
```

And use this Razzle config instead:

```
module.exports = {
  modify(config, { target, dev }, webpack) {
    console.log(config);
    const appConfig = config;
    if ( target==='web' && dev ) {
      appConfig.devServer.sockHost = "razzle.syntapse.co.uk";
      appConfig.devServer.sockPath = "/myapp/sockjs-node/";
      appConfig.devServer.sockPort = "443";
    }
    return appConfig;
  },
};
```

Then `devServer` will listen under `/myapp/sockjs-node/` and Nginx will include that path to the proxy i.e. `http://0.0.0.0:3001/myapp/sockjs-node/`

I had a similar problem setting up HMR to work through Nginx reverse proxies, and this is what worked for me.

**Comment by fivethreeo** [comment]
Oh, did not see ~ ^ instead of ^~

But you don't have to set sockPort/Host/Path config.

```js
appConfig.devServer.public = "razzle.syntapse.co.uk:80"; // fixes the port
```

```nginxconf
 location ~ ^/myapp {
  proxy_pass http://0.0.0.0:3001/; #  note the / will strip off myapp/   
}
```

**Comment by laurencefass** [comment]
none of suggestions above working. any variation of 

**location ~ ^/myapp** results in error and fail to compile nginx conf:

`nginx: [emerg] "proxy_pass" cannot have URI part in location given by regular expression, or inside named location, or inside "if" statement, or inside "limit_except" block in /etc/nginx/conf.d/default.conf:422`

ive edited the sockHost and sockPath config paths which gives the correct REQ URL but still fails with a 404

```
module.exports = {
  modify(config, { target, dev }, webpack) {
    const appConfig = config;
    console.log(config);
    if ( target==='web' && dev ) {
      appConfig.devServer.sockHost = "razzle.syntapse.co.uk";
      appConfig.devServer.sockPath = "/razzle-dev/webpack/sockjs-node";
    }
    return appConfig;
  },
};

```

results in:

```
Request URL: https://razzle.syntapse.co.uk/razzle-dev/webpack/sockjs-node/info?t=1596727304839
Request Method: GET
Status Code: 404 
Remote Address: 51.38.64.221:443
Referrer Policy: no-referrer-when-downgrade

```

which looks correct and what i would expect...

nginx conf remains the same:

```
    location ^~ /razzle-dev/webpack/ {
        proxy_pass http://0.0.0.0:3001/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
    location ^~ /razzle-dev/ {
        proxy_pass http://0.0.0.0:3000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
```

i've spent hours configuring this and previous versions would be great if razzle shipped with some default configuration examples for quick start and new developers.

**Comment by laurencefass** [comment]
> Oh, did not see ~ ^ instead of ^~
> 
> But you don't have to set sockPort/Host/Path config.
> 
> ```js
> appConfig.devServer.public = "razzle.syntapse.co.uk:80"; // fixes the port
> ```
> 
> ```nginx
>  location ~ ^/myapp {
>   proxy_pass http://0.0.0.0:3001/; #  note the / will strip off myapp/   
> }
> ```

I dont think that devserver.public is consistent with the .env entry 

`CLIENT_PUBLIC_PATH='https://razzle.syntapse.co.uk/razzle-dev/webpack/'`

on which i'm basing all other paths. a working example with nginx.conf, .env and razzle.config.js would be very useful.

**Comment by fivethreeo** [comment]
https would be :443

**Comment by laurencefass** [comment]
Thanks. Making individual edits to separate lines/files may not be the best approach to get this working. Possibly a consistent presentation for configuration for .env, nginx.conf and razzle.config.js may be more useful not only for myself but for other devs if an example was included in the docs.

**Comment by laurencefass** [comment]
With the latest changes above the socket URL looks correct but still failing with 404.

**Comment by laurencefass** [comment]
OK so ive resolved the port in the REQ URL issue by including in razzle.config.js

`appConfig.devServer.public = "razzle.syntapse.co.uk"
`

this removes the unwanted port section but the URL still fails with a 404 even though the URL looks correct. 

```
Request URL: https://razzle.syntapse.co.uk/latest-dev/webpack/sockjs-node/info?t=1596731822400
Request Method: GET
Status Code: 404 
Remote Address: 51.38.64.221:443
Referrer Policy: no-referrer-when-downgrade
```

this matches the .env and nginx.conf specs so i cant see whats wrong here.

**Comment by laurencefass** [comment]
Is there a testable and reproducible set of config files to conclusively prove this isnt a bug with the latest version of razzle?

**Comment by fivethreeo** [comment]
Then it  is just a nginx issue i think

 first check localhost:3000/ then localhost:3001/ then localhost:3001/sockjs-node/info?t=1596731822400

**Comment by fivethreeo** [comment]
To see what is going on

```nginxconf
log_format upstream_logging '[$time_local] $remote_addr - $remote_user - $server_name to: $upstream_addr: $request upstream_response_time $upstream_response_time msec $msec request_time $request_time';
access_log /var/log/nginx/upstream_logging.log upstream_logging;
```

**Comment by laurencefass** [comment]
Here's my tested reproducible configuration working through an SSL termination proxy and upstream nginx app reverse proxy.  the only difference between this and original post is inclusion of **appConfig.devServer.public config in razzle.config.js** otherwise the configuration is identical. It may not be the best solution but it works. Note the nginx config doesnt require additional /sockjs-node location to resolve.

**razzle.config.js**


```
module.exports = {
  modify(config, { target, dev }, webpack) {
    console.log(config);
    const appConfig = config;
    if ( target==='web' && dev ) {
      appConfig.devServer.public = "razzle.syntapse.co.uk";
      appConfig.devServer.sockHost = "razzle.syntapse.co.uk/latest-dev/webpack";
      appConfig.devServer.sockPath = "/sockjs-node";
    }
    return appConfig;
  },
};
```

**nginx.conf** 

```
    location ^~ /latest-dev/webpack/ {
        proxy_pass http://0.0.0.0:3006/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
    location ^~ /latest-dev/ {
        proxy_pass http://0.0.0.0:3005/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
```

thank you for assisting me your input is very much appreciated.

**Comment by fivethreeo** [comment]
Minimum tested config :)

```bash
CLIENT_PUBLIC_PATH=http://localhost:8080/razzle-dev/ yarn start
```

```nginxconf
http {

    server {
        listen       8080; # or 80 or 443
        server_name  _;
        location /razzle-dev { # no /, no regex
            return 302 /razzle-dev/; # a /
        }
        location /razzle-dev/ { # no regex
            proxy_pass   http://127.0.0.1:3001/; # a /
            proxy_http_version 1.1;
            proxy_set_header Upgrade \$http_upgrade;
            proxy_set_header Connection "upgrade";
        }
        location /razzle-dev/sockjs-node/ { # no regex
            proxy_pass   http://127.0.0.1:3001; # no /
            proxy_http_version 1.1;
            proxy_set_header Upgrade \$http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
```

```js
'use strict';

module.exports = {
  modify(config, { target, dev }, webpack) {
    const appConfig = config; // stay immutable here

    if (target === 'web' && dev) {
      appConfig.devServer.public = 'localhost:8080' // or 80 or 443
      appConfig.devServer.proxy = {
        context: () => true,
        target: 'http://localhost:3000'
      };
      appConfig.devServer.sockPath = '/razzle-dev/sockjs-node';
    }

    return appConfig;
  },
};

```
