### ISSUE TITLE
Hot reloading not working on Vue examples 

### ISSUE THREAD

**Issue by timbaas** [jaredpalmer/razzle#1380]
## ❓Question

Hi there, 

Just asking this here first, because I can't imagine this being a bug. 
For both the Vue and Vue Router examples Hot reloading isn't working.

My environment: 
- Windows 10 (insider preview)
- WSL 2
- Node 14.5.0
- Yarn 1.22.4
- Webpack 4.43.0

Steps to reproduce:
- Clone the repo (main branch)
- cd into `razzle/examples/with-vue` (or `with-vue-router`)
- run `yarn install && yarn start`
- Open `localhost:3000` in Edge
- Change `App.vue`

Expectation:
- Client recompiles
- Change is pushed to browser

What actually happens:
- No (visible) recompile
- Changed not pushed to browser

Am I missing a step here?

**Comment by fivethreeo** [comment]
Dont use WSL with razzle just use normally in windows.

**Comment by fivethreeo** [comment]
I will test this in linux soon, to be sure it is not a razzle bug.

**Comment by fivethreeo** [comment]
Tested in windows 10 without WSL, working fine.

**Comment by jemeric** [comment]
It seems like this is a more general problem with HMR in WSL2. It won't work if the files are in a mounted drive (e.g. mnt/c/.../projects/app), but if you use the virtual Linux file system (e.g. ~/projects/app) it works fine (it's also way faster).
