### ISSUE TITLE
onTouchStart is not working on mobile view 

### ISSUE THREAD

**Issue by thongtran715** [jaredpalmer/razzle#1382]
### Current Behavior
The button is able to be functional with onClick and onTouchStart on the normal web view and mobile simulator on Chrome. However, when I tried on my phone, the button is not functional. It means it is not triggering any event from onTouchStart even though it works on the phone simulator on Chrome. 

Please see the code below 

`  
<button
          onTouchStart={() => alert("ds")}
          style={{ cursor: "pointer" }}
          onClick={() => alert("Good day")}
        >
          Click me
 </button>
`

### Expected behavior

onTouchStart needs to be triggered on the mobile view. 

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           |  3.16
| Razzle Plugins   | 
| Node             | 12.14.0
| Browser          |
| npm/Yarn         | 6.14.5
| Operating System | Mac OS
| TypeScript       | 3.9.3
| React            | 16.13.1

**Comment by fivethreeo** [comment]
Is this part of a example supplied with razzle. If not this is not a razzle issue. It might be you need to add some polyfills.

**Comment by fivethreeo** [comment]
Closing as it needs more info. Reopen if you provide a minimal example.

**Comment by Diwas15** [comment]
the same issue
