### ISSUE TITLE
flash of unstyled content (FOUC) issue in quick-start example app

### ISSUE THREAD

**Issue by vincentchauhk01** [jaredpalmer/razzle#1385]
### Current Behavior

flash of unstyled content (FOUC) issue when SSR even from the quick-start example app

### Expected behavior

no FOUC

### Reproducible example

quick-start example in readme

**Comment by fivethreeo** [comment]
This is with razzle start or in production?

**Comment by hornta** [comment]
~~I'm not experiencing FOUC in production.~~
Nevermind. I see you talking about the development environment. The production environment does not suffer from FOUC but development does.

**Comment by fivethreeo** [comment]
It is expected since the css is loaded in javascript in dev.

**Comment by mghazanfar** [comment]
I face this in prod as well. How can I get rid of it?

**Comment by fivethreeo** [comment]
https://stackoverflow.com/questions/3221561/eliminate-flash-of-unstyled-content/43823506

**Comment by fivethreeo** [comment]
This happens many a times if we have the link tag of style sheets referred at the bottom of the web page

**Comment by mghazanfar** [comment]
@fivethreeo my razzle is latest. Using buildType: "iso", having FOUC. I have no place to add this JS statement.
