### ISSUE TITLE
Point of embedding some of the environment variables?

### ISSUE THREAD

**Issue by ludvigalden** [jaredpalmer/razzle#1390]
## ❓Question

What is the point of embedding some of the environment variables? For instance, running a production server with a specified `PORT`, like `PORT=8080 node build/server.js`, does not work if the port was not defined as such when compiling. This makes things more difficult than necessary to work with, for instance in cases where you want to be able to build a container image for future use with varying ports. Same thing with `PUBLIC_PATH`, one would have to re-build the whole thing.

If the problem is not clear, `console.log(process.env.PORT)` prints `3000`, while `console.log(process.env)` prints `{ PORT: "8080" }`, which is what I refer to by "embedding the environment variables".

So, if your answer is that these environment variables are intended to be usable on both the server and client, I think that's the wrong approach. Sure, you could run into problems, but I'm also running into problems, and I'm having a much harder getting around these problems than just requiring dynamic environment variables to be passed from server to client through JSON.

Alternatively, you could make it possible to stop embedding some of the environment variables. I suppose that would be easiest.

**Comment by fivethreeo** [comment]
It will be easier to disable specific variables in the next version of razzle. I think it is this way since this is based on create-react-app where everything is client side only.

**Comment by thomasjm** [comment]
This is still a problem, maybe this issue could be reopened?

I worked around it like this:

```javascript
const getPort = (env) => env["PORT"];
const rawPort = getPort(process.env);
const port = rawPort ? parseInt(rawPort, 10) : 3000;
```

**Comment by fivethreeo** [comment]
Look up forceRuntimeEnvVars razzle option in the docs.
