### ISSUE TITLE
Is there a way to enable CORS on the development server? 

### ISSUE THREAD

**Issue by Steveeeie** [jaredpalmer/razzle#1391]
## ❓Question

Is there a way to enable CORS on the development server?

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/blob/master/examples/with-custom-devserver-options/razzle.config.js
https://webpack.js.org/configuration/dev-server/#devserverbefore
https://expressjs.com/en/resources/middleware/cors.html

**Comment by Steveeeie** [comment]
Excellent thanks
