### ISSUE TITLE
razzle-dev-utils is missing dependency on webpack-dev-server

### ISSUE THREAD

**Issue by cletter7** [jaredpalmer/razzle#1394]
### Current Behavior

Got this error during build time:
```
<REPO_PATH>/node_modules/razzle-dev-utils/webpackHotDevClient.js
Module not found: Can't resolve 'webpack-dev-server/client/utils/createSocketUrl' in '<REPO_PATH>/node_modules/razzle-dev-utils'
```

### Expected behavior

No errors.

### Suggested solution(s)

Add `webpack-dev-server` as a dependency of `razzle-dev-utils`.

### Additional context

https://github.com/jaredpalmer/razzle/blob/333f9a8d5d9559a2fedbd305dc9db6e9aad3c6a4/packages/razzle-dev-utils/webpackHotDevClient.js#L15

Currently `razzle-dev-utils` requires `webpack-dev-server` in the code, though it doesn't have it in dependencies. When I add `webpack-dev-server` to my project's dependencies, it solves the issue.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 3.1.2
| Node             | 12.18.1
| Yarn         | 1.22.4
| Operating System | MacOS

**Comment by fivethreeo** [comment]
fixed in 3.1.7
