### ISSUE TITLE
React Router v4

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/razzle#140]
I am going to be working on this later today

**Comment by adamjv90** [comment]
Is there anything I could do to help integrate React Router v4?

**Comment by jaredpalmer** [comment]
My team is using v3 until the ecosystem moves to v4.  At the moment, there is limited upside to v4 with SSR and data fetching since you need to double render or use an addon to allow static route declarations. The former is meh for performance and the latter adds extra boilerplate to do the exact same thing that v3 does. My plan is to wait for v4 to get out of beta and re-assess the best path forward in order to limit churn. If we @palmerhq move to v4, then we'll upgrade.

**Comment by williamoliveira** [comment]
Could you briefly explain why the double render would happen?

**Comment by jaredpalmer** [comment]
See #212
