### ISSUE TITLE
Eliminate unreachable code server/client-side

### ISSUE THREAD

**Issue by hornta** [jaredpalmer/razzle#1401]
I wish that code that is only meant to be executed on the server will not be shipped out to the client and vice versa. I have this function that will be executed both on the server and client and I need to check if it's executed on the client because of preloaded redux state.

```js
function makeStore() {
	const storeOptions = { reducer: rootReducer };

	if (typeof window !== "undefined") {
		const preloadedState = window.__PRELOADED_STATE__;
		delete window.__PRELOADED_STATE__;
		storeOptions.preloadedState = preloadedState;
	}

	const store = configureStore(storeOptions);
	return store;
}
```

As of Razzle 3.1.6 the if statement block is bundled in the server bundle despite it won't be executed. The same goes for when the condition looks like this: `typeof window !== "undefined"` - it's bundled in the client as well.

This is can be achieved with https://www.npmjs.com/package/babel-plugin-transform-define
Next.js implemented it like this: https://github.com/vercel/next.js/pull/8355 and tests: https://github.com/vercel/next.js/pull/8361
It can be put in the docs for explanation.

**Comment by fivethreeo** [comment]
This will be fixed with the new babel configuration in razzle 4.0

**Comment by fivethreeo** [comment]
fixed in dev

**Comment by hornta** [comment]
That's awesome. Hoping to see it in the documentation. 
I checked the https://github.com/jaredpalmer/razzle/blob/next/packages/babel-preset-razzle/razzle-four-preset.js but I couldn't find anything about the subject. Am I looking in the wrong place?

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/blob/next/packages/razzle/config/babel/razzle-babel-loader.js#L194
