### ISSUE TITLE
HTML response along with eventhandlers in server side 

### ISSUE THREAD

**Issue by Keerthanashri** [jaredpalmer/razzle#1403]
## How should I get the html response in server side along with it's event handlers that is onclick and onchange etc..,??

I have created a application in razzle which contains interactive components like Accordion, Tab, Flip cards etc..,

In this I have got the exact output in the client side and in server side got the Html response of those components. But when I am trying to save the response in a **.html file** and open that file in the browser it shows the interactives but the only thing is the event handlers are not working since the html response doesn't contains eventhandlers on the respective html tags. For example It shows the Flipcard but it can't be turned over back since the function is in onclick

Here is the sample html response for the flipcard component
![Screenshot from 2020-09-08 18-46-02](https://user-images.githubusercontent.com/70942813/92481210-a37e2b80-f203-11ea-8f97-3b6bdd1cb4be.png)

Now my question is, Is there any possible way to get the html response along with the event handlers (onclick,onchange etc...,) in the respective html tags?

**Comment by fivethreeo** [comment]
Mixing react with regular jquery/bootstrap will cause issues. Try reactstrap. You could do a custom babel plugin to pass thru handlers but that is a complex way to do it wrong ;)
