### ISSUE TITLE
AWS Deployment

### ISSUE THREAD

**Issue by mding5692** [jaredpalmer/razzle#1406]
## ❓Question
Anybody who has deployed a razzle.js project on AWS that can provide any guidance? I've tried with AWS EC2s as a test but its very rough so hoping could get a discussion going for people who have experience with this or tried deploying it on AWS.

Also any tips for using Razzle in production would be good too! Much thanks!

**Comment by fivethreeo** [comment]
You could try

https://docs.docker.com/engine/context/ecs-integration/#run-compose-applications

With something like

https://github.com/fivethreeo/razzle-with-docker-nginx/

Caution: Never tried it myself

**Comment by fivethreeo** [comment]
https://medium.com/faun/deploy-of-a-docker-compose-application-in-an-aws-environment-using-ecs-cli-a4441ed3d445

**Comment by mding5692** [comment]
Thanks @fivethreeo will try this out to see

**Comment by momosetti** [comment]
Hey @mding5692, try to check #629, it can be helpfull.

**Comment by mding5692** [comment]
> Hey @mding5692, try to check #629, it can be helpfull.

Saw this example in there: https://gist.github.com/jgcmarins/f4ebf0bae9d1408a87836b36b976a0ef

Definitely useful reference
