### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by fivethreeo** [jaredpalmer/razzle#1410]
With regards to documentation.

Specifically on the canary branch, what do you think is missing or needs more elaboration?

Any pointers or pull requests greatly apprechiated :)

**Comment by alexanderankin** [comment]
does modify still work? docs should reflect that

**Comment by fivethreeo** [comment]
documented the change now

https://razzle-git-canary.jared.vercel.app/docs/customization#extending-webpack

**Comment by alexanderankin** [comment]
@fivethreeo can you tell where and what changes? As far as i can tell [this should still work](https://razzle-docs.vercel.app/docs/customization#extending-webpack) but it didnt for me.

**Comment by fivethreeo** [comment]
do you use the finch/canary or stable release. Do a `yarn why razzle`.

**Comment by alexanderankin** [comment]
@fivethreeo here's the output, i just used the yarn create functionality:

```
yarn why v1.22.5
[1/4] Why do we have the module "razzle"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "razzle@4.0.0-finch.8"
info Has been hoisted to "razzle"
info This module exists because it's specified in "devDependencies".
info Disk size without dependencies: "1.9MB"
info Disk size with unique dependencies: "1.9MB"
info Disk size with transitive dependencies: "1.9MB"
info Number of shared dependencies: 272
Done in 1.17s.
```

**Comment by fivethreeo** [comment]
https://razzle-git-finch.jared.vercel.app/docs/customization#extending-webpack

**Comment by smcyr** [comment]
There seems to be missing options for static export in the canary documentation:
https://razzle-git-canary.jared.vercel.app/docs/customization#to-enable-static-export
I can see here that there is the `paralell` options:
https://github.com/jaredpalmer/razzle/blob/canary/packages/razzle/scripts/export.js#L155
(It also has a typo, it should be `parallel` and not `paralell`.

**Comment by nimaa77** [comment]
ok, I'm going to add some future todos here

- [x] add docs for razzle static
- [x] add docs Absolute Imports (#1206)
- [x] move plugins docs to docs website
- [x] add docs for deploying razzle apps on azure, amazon, and others ...

**Comment by parkerault** [comment]
@nimaa77 I created a PR for the non-relative imports documentation here: #1468. Let me know if it meets your expectations.

**Comment by andyzeli** [comment]
deploying Razzle to ElasticBeanstalk is a very simple 5 minute task. worth adding the steps? thanks for the great project

**Comment by fivethreeo** [comment]
Yeah, adding the steps for that would be great.

**Comment by andyzeli** [comment]
**Elastic Beanstalk Steps**


**Pre**
- this assumes some familiarity with creating AWS account, basic workings,  having for example your keys in the ~/.aws folder for mac. will add steps later if needed
- install awsebcli. for mac can just use brew install awsebcli

**Razzle**
1. `npx create-razzle-app myapp`
2. `cd myapp`, make some changes (if working with other aws services, aws-sdk a good thing to npm install for project), make your app. npm start to verify razzle working
3. `git init` and  commit (make a remote origin too if needed but eb doesnt care about this)
4. !! change razzle from dev dependency to regular/prod dependency in `package.json`
5. still in myapp folder in terminal, `eb init` which will take you through some questions:
    - follow the instructions to set up your folder to interact with eb. 
    - usually don't need to SSH into instance, so no
    - Node 12 on Linux 2 (latest everything) has made config a bit easier, and different. can add steps to previous versions too - the short of it is a single Procfile replaces some envar config files
6. go to your AWS eb console (make sure you choose the right location from dropdown or it wont show). The new application scaffolding which you named in `eb init` will show up
7. click on that application name. then click "Create New Environment" to actually create the environment. could do this from EB Cli too but its just as easy to click on the AWS console. 
  --choices:  Web Server. Managed. Node 12 on Linux 2. 
    -- **Choose "Sample Application"** instead of upload. we will blow away anyway. 
9. Once environment creation complete, click on url shown in console to verify AWS's sample application worked. 
10. Take note of Environment name. back in local terminal, do `eb use <name of environement>`
11. at root of folder, `touch Procfile` (make a Procfile. no file type)
      -- procfile need only contain one line instructing eb what to do to start everything. just type `npm run myscript`
12. now make myscript. go to `package.json` and combine 2 of razzles scripts by adding `"myscript": "razzle build -s && node build/server.js"` underneath the start:prod script
13. I have found that eb is most reliable with some configs by doing them on the console. go to eb console, click on **Environment--> Configuration--> Software--> Environment Properties** and add some key value pairs. this is also where you put RDS key pairs if you want to add database, so below is example of using an external-to-eb Datastore, which i think is actually easier than "adding datastore to eb" instructions you find in eb docs. the only annoying part is setting up security groups but aws docs aren't too bad here
     - NODE_ENV = production
     - PORT = 8081
     - RDS_HOSTNAME =  foo appus-west-1.rds.amazonaws.com
    -  RDS_PORT: 5432
    -  RDS_DB_NAME: ebdb
     - RDS_USERNAME: postgres
      - RDS_PASSWORD: foofoofoo
     - AWS_ACCESS_KEY_ID: AGDFTGHKKJGHKYUJHG
     - AWS_SECRET_ACCESS_KEY: skflsadkjhfalskdjhflkjsdhflkas
 
--Sort of annoying, making changes here automatically kicks off a re deploy of app. 

14. from root of project in terminal, `eb deploy` should now work. 
15. make changes, git commit them, eb deploy, repeat

**Comment by fivethreeo** [comment]
We probably could use the cdk ts to automate this. But may be better to explain it like this to make it easier to newcomers. But I think newcomers should be encouraged to build locally and deploy. Unless they do some CI release or CodePipeline. Rather tell them stuff , so they get how it works. Can you make this a pull to the docs? I can add the files and doc links if you write the actual docs.

**Comment by fivethreeo** [comment]
Razzle 4.0.1 is released. File doc issues as separate issues or do a pull request :)
