### ISSUE TITLE
Typescript support for static_export.js on 3.3.0-canary.5

### ISSUE THREAD

**Issue by smcyr** [jaredpalmer/razzle#1412]
### Current Behavior

When you write a `src/static_export.ts` for 3.3.0-canary.5, `yarn build` doesn't compile it to `build/static_export.js`.

### Desired Behavior

It should compile it to `build/static_export.js`.

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/releases/tag/v3.3.0-canary.6

**Comment by smcyr** [comment]
It works, thank you!
