### ISSUE TITLE
Error in modifyJestConfig

### ISSUE THREAD

**Issue by pontussalenbo** [jaredpalmer/razzle#1413]
### Current Behavior

$ razzle test
C:\Users\Pontu\Desktop\code\TypeScript\razzle-canary\node_modules\razzle\scripts\test.js:22
  throw err;
  ^

TypeError: Assignment to constant variable.
    at C:\Users\Pontu\Desktop\code\TypeScript\razzle-canary\node_modules\razzle\config\createJestConfig.js:120:14

### Expected behavior

Allow overriding of JestConfig as stated in the docs.

### Reproducible example

Just use the modifyJestConfig from the canary docs and modify anything, e.g: 
 jestConfig.testEnvironment = 'node';
 jestConfig.testMatch = ['<rootDir>/test/api/*.test.(ts|js)'];

### Your environment

| Software          | Version(s) |
| ---------------- | ---------- |
| Razzle              | 4.0.0-finch.8
| Razzle Plugins |  none
| Node              | 12.18.4
| Browser          | Chrome
| npm/Yarn        | 1.12.4
| Operating System | Win 10 
| TypeScript       | 4.0.2
| React            | 16.13.1

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/releases/tag/v3.3.0-canary.7

**Comment by fivethreeo** [comment]
fixed
