### ISSUE TITLE
Static export all routes in parallel

### ISSUE THREAD

**Issue by smcyr** [jaredpalmer/razzle#1414]
### Current Behavior

When I do `yarn export`, my hundred of urls are rendered at the same time so my server (which serves the GraphQL data) timeouts even if I have the option `paralell` to 1. I added a console.log in the method `render_static_export` of `razzle/scripts/export.js` and the console.logs output all at the same time.

### Expected behavior

If I a set the option `paralell` to 1, the export should execute the render one after the other.

### Suggested solution(s)

If I replace the asyncPool in `razzle/scripts/export.js` with:
```javascript
const rendersInfo = [];

for (const route of routes) {
    rendersInfo.push(await render_static_export(route));
}
```
It works as expected. So the logic for asyncPool should be updated.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 3.3.0-canary.5
| Node             | v12.18.1
| npm/Yarn         | Yarn 1.22.4
| Operating System | Windows 10

**Comment by fivethreeo** [comment]
Hm, not sure how to fix this correctly yet.

**Comment by smcyr** [comment]
I found the problem:
https://github.com/jaredpalmer/razzle/pull/1415/files

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/releases/tag/v3.3.0-canary.8

Thanks
