### ISSUE TITLE
Lots of deprecated packages in razzle-plugin-typescript

### ISSUE THREAD

**Issue by parkerault** [jaredpalmer/razzle#1417]
## ❓Question
Should I be using the master release for `razzle-plugin-typescrip`? There are several scary warnings about breaking changes in future node versions.

**Comment by fivethreeo** [comment]
Razzle will support typescript natively in razzle 4+. The plugin may be updated if needed.

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/pull/1408

**Comment by fivethreeo** [comment]
There is a pull request to fix this, closing this issue in favor of the pull request.
