### ISSUE TITLE
Support TypeScript's path mapping out of box

### ISSUE THREAD

**Issue by dodas** [jaredpalmer/razzle#1425]
### Current Behavior
Currently if I define path aliases in tsconfig's `paths`, module resolution does not respect these aliases.
To make it work, I currently have `tsconfig-paths-webpack-plugin` set up in `razzle.config.js`.

### Suggested Solution
Since 4.0 will suport TS out of box, it would be nice to have its path aliases work out of box too.

------
Thanks!

**Comment by fivethreeo** [comment]
That should work already in 3.3

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/config/modules.js#L53

**Comment by dodas** [comment]
Oops, I overlooked that.
Can confirm, it works in 3.3!

Great work, these rarely work out of box in other solutions ☺️

**Comment by fivethreeo** [comment]
If this does not work it is a bug. It will not work with the typescript plugin i think, only with the builtin ts support.
