### ISSUE TITLE
Serialize Javascript Issue

### ISSUE THREAD

**Issue by matt-catellier** [jaredpalmer/razzle#1426]
### Current Behavior

Razzle dependancy 'serialize-javascript' has high risk vulnerability

![image](https://user-images.githubusercontent.com/16104817/94724423-21b78480-030f-11eb-93d8-0be563d87577.png)

### Expected behavior

Razzle should not have  'serialize-javascript'  high risk vulnerability

### Reproducible example

npm audit

### Solution

Known issue with copy-webpack-plugin. https://github.com/vuejs/vue-cli/issues/5782 

Suggest updating from copy-webpack-plugin 5.1.1 to 5.1.2

**Comment by fivethreeo** [comment]
fixed in dev
