### ISSUE TITLE
Environment variable PORT is getting overridden

### ISSUE THREAD

**Issue by nicklasmoeller** [jaredpalmer/razzle#1428]
### Current Behavior

`process.env.PORT` gets set to `3000`

### Expected behavior

That it actually uses the port defined in your environment variables.

### Reproducible example

You can just run the `with-custom-environment-variables` example on master. That's what I did, to confirm that it's not working as intended.

### Additional context

<img width="919" alt="Screenshot 2020-10-02 at 18 25 04" src="https://user-images.githubusercontent.com/3519728/94946846-013d2500-04dd-11eb-8ab7-1c7e4e1623ae.png">

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           |  master
| Razzle Plugins   |
| Node             |
| Browser          |
| npm/Yarn         |
| Operating System |
| TypeScript       |
| React            |

**Comment by fivethreeo** [comment]
fixed in master dev, will release 3.3.3 soon

**Comment by nicklasmoeller** [comment]
Confirmed to work on the example :)
