### ISSUE TITLE
Breaking change from 3.1.x to 3.3.x

### ISSUE THREAD

**Issue by Munter** [jaredpalmer/razzle#1430]
The 3.3.x minor release line includes breaking changes when updating from the 3.1.x minor release line.

There are no notes on breaking API changes in the 3.3.0 release notes.

Could you add a warning in the 3.3.0 release notes that the API of the `razzle.config.js` `modify`-call has changed? Or, if this breaking change was a mistake, backport the 3.1.x API to the 3.3.x release line?

**Comment by fivethreeo** [comment]
Modify should still work in 3.3.3, but should give a warning.

**Comment by fivethreeo** [comment]
But if it does not work it is a bug.

**Comment by fivethreeo** [comment]
Note that warnings breaks the build if env.CI is set to true.

**Comment by fivethreeo** [comment]
Can you confirm this is a error or just a warning?

**Comment by Munter** [comment]
I can't recreate the problem with the latest release
