### ISSUE TITLE
Error building with experimental new babel loader

### ISSUE THREAD

**Issue by ceopaludetto** [jaredpalmer/razzle#1433]
### Current Behavior

When trying to build with new babel experimental loader, the error below are thrown:

<details>
  <summary>Stack</summary>
  <pre>Error: Cannot find module 'babel-preset-razzle/razzle-four-preset'
Require stack:
- /home/carlos/Documents/Projetos/Javascript/nest-new-graphql/node_modules/razzle/config/babel-loader/razzle-babel-loader.js
- /home/carlos/Documents/Projetos/Javascript/nest-new-graphql/node_modules/loader-runner/lib/loadLoader.js
- /home/carlos/Documents/Projetos/Javascript/nest-new-graphql/node_modules/loader-runner/lib/LoaderRunner.js
- /home/carlos/Documents/Projetos/Javascript/nest-new-graphql/node_modules/webpack/lib/NormalModule.js
- /home/carlos/Documents/Projetos/Javascript/nest-new-graphql/node_modules/webpack/lib/NormalModuleFactory.js
- /home/carlos/Documents/Projetos/Javascript/nest-new-graphql/node_modules/webpack/lib/Compiler.js
- /home/carlos/Documents/Projetos/Javascript/nest-new-graphql/node_modules/webpack/lib/webpack.js
- /home/carlos/Documents/Projetos/Javascript/nest-new-graphql/node_modules/razzle/scripts/build.js</pre>
</details>

### Expected behavior

Application builds correctly

### Reproducible example

Create a fresh project in version 3.3.3

### Suggested solution(s)

I think the problem is related to razzle trying to install canary version of babel-preset-razzle which not exports razzle-four-preset.js file

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           |  3.3.3
| Node             | 12.16.2
| Browser          | Chrome 85
| Yarn         |  1.22.5
| Operating System | Arch Linux 5.8.13
| TypeScript       |  4.0.3
| React            |  16.13.1

**Comment by fivethreeo** [comment]
Stop finding bugs 😂😋

Great work trying out the new release. Will look into it tomorrow 😀

**Comment by fivethreeo** [comment]
Fixed, released v3.3.4

**Comment by ceopaludetto** [comment]
Sorry for finding bugs 😂😂😂😂, thx for the great job.
