### ISSUE TITLE
@babel/plugin-syntax-bigint and @babel/plugin-proposal-numeric-separator are not listed in babel-preset-razzle package.json

### ISSUE THREAD

**Issue by ceopaludetto** [jaredpalmer/razzle#1434]
### Current Behavior

When try build with new razzle preset, the error below are thrown:

<details>
  <summary>Stack</summary>
  <pre>Error: [BABEL] /home/carlos/Documents/Projetos/Javascript/nest-new-graphql/src/client/index.tsx: Cannot find module '@babel/plugin-proposal-numeric-separator'
Require stack:
- /home/carlos/Documents/Projetos/Javascript/nest-new-graphql/node_modules/babel-preset-razzle/index.js
- /home/carlos/Documents/Projetos/Javascript/nest-new-graphql/node_modules/razzle/babel.js
- /home/carlos/Documents/Projetos/Javascript/nest-new-graphql/node_modules/@babel/core/lib/config/files/plugins.js
- /home/carlos/Documents/Projetos/Javascript/nest-new-graphql/node_modules/@babel/core/lib/config/files/index.js
- /home/carlos/Documents/Projetos/Javascript/nest-new-graphql/node_modules/@babel/core/lib/index.js
- /home/carlos/Documents/Projetos/Javascript/nest-new-graphql/node_modules/babel-loader/lib/index.js
- /home/carlos/Documents/Projetos/Javascript/nest-new-graphql/node_modules/loader-runner/lib/loadLoader.js
- /home/carlos/Documents/Projetos/Javascript/nest-new-graphql/node_modules/loader-runner/lib/LoaderRunner.js
- /home/carlos/Documents/Projetos/Javascript/nest-new-graphql/node_modules/webpack/lib/NormalModule.js
- /home/carlos/Documents/Projetos/Javascript/nest-new-graphql/node_modules/webpack/lib/NormalModuleFactory.js
- /home/carlos/Documents/Projetos/Javascript/nest-new-graphql/node_modules/webpack/lib/Compiler.js
- /home/carlos/Documents/Projetos/Javascript/nest-new-graphql/node_modules/webpack/lib/webpack.js
- /home/carlos/Documents/Projetos/Javascript/nest-new-graphql/node_modules/razzle/scripts/build.js (While processing: "/home/carlos/Documents/Projetos/Javascript/nest-new-graphql/node_modules/razzle/babel.js")
    at Generator.next (<anonymous>)
    at Generator.next (<anonymous>)
    at Generator.next (<anonymous>)</pre>
</details>

### Expected behavior

Application builds correctly

### Reproducible example

Just create a new sample project with razzle/babel in presets

### Suggested solution(s)

Add both plugins to package.json

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 3.3.3
| Node             | 12.16.2
| Browser          | Chrome 85
| Yarn         | 1.22.5
| Operating System | Arch Linux 5.8.13
| TypeScript       |  4.0.3
| React            | 16.13.1

**Comment by fivethreeo** [comment]
Fixed, released v3.3.4
