### ISSUE TITLE
Regression: no tests found after upgrading to 3.3.0

### ISSUE THREAD

**Issue by Caerbannog** [jaredpalmer/razzle#1443]
### Current Behavior

Running `npm test` in `razzle/examples/basic/` fails with `No tests found, exiting with code 0`.

### Expected behavior

The `src/App.test.js` test should be run by Jest.

### Reproducible example

To trigger the problem, just run `npm test` in `razzle/examples/basic/`
To fix the problem, run `npm install razzle@3.1.8` before `npm test`.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 3.3.0
| Node             | v14.9.0
| npm/Yarn         | npm 6.14.8

**Comment by fivethreeo** [comment]
Fixed in v3.3.6
