### ISSUE TITLE
Setting browerslist in package.json results in Autoprefixer warning

### ISSUE THREAD

**Issue by jasnross** [jaredpalmer/razzle#1446]
### Current Behavior

When a browserslist entry is present in package.json, the following warning is displayed when running `razzle build` or `razzle start`:

```
$ yarn build
yarn run v1.22.10
$ razzle build
Creating an optimized production build...
Compiling client...

  Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option can cause errors. Browserslist config
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist



  Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option can cause errors. Browserslist config
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist


Compiled client successfully.
Compiling server...
Compiled server successfully.
Compiled successfully.

File sizes after gzip:

  47.7 KB  build/public/static/js/bundle.3fb41b92.js
  323 B    build/public/static/css/bundle.3fb41b92.css
  114 B    build/chunks.json

✨  Done in 5.25s.
```

### Expected behavior

No warnings should be displayed if build is successful.

### Reproducible example

This repository is the result of a fresh `npx create-razzle-app razzle-autoprefixer-warnings`. The only change was adding a browserslist entry to package.json:

https://github.com/jasnross/razzle-autoprefixer-warnings

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 3.3.6
| Razzle Plugins   | -
| Node             | 12.18.4
| Browser          | N/A
| npm/Yarn         | yarn 1.22.10
| Operating System | macOS 10.14.6
| TypeScript       | N/A
| React            | 16.14.0

**Comment by fivethreeo** [comment]
Fixed in v3.3.7
