### ISSUE TITLE
Less loader options dont work (javascript)

### ISSUE THREAD

**Issue by OmarEMC** [jaredpalmer/razzle#1452]
### Current Behavior

When i use the `less` plugin, i can't enable Inline JavaScript option of less.

### Expected behavior

Less working without problems.

### Reproducible example

1. `npm i razzle-plugin-less -D`
2. add: 
```js
plugins: [
    {
      name: 'less',
      options: {
        less: {
          ...lessOptions,
          dev: {
            lessOptions: {...lessOptions}
          },
          prod: {
            lessOptions: {...lessOptions}
          }
        }
      }
    }
  ]
```
to razzle.config.js with lessOptions object being:
```js
const lessOptions = {
  modifyVars: {
    "@base-color": "#30b874",
    "@ns": "da-"
  },
  javascriptEnabled: true
}
```
3. run `npm start` and it give me this error:
```
// It's hack way to make this function will be compiled preferentially by less
.tinyColorMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
      in /workspace/website/r/node_modules/rsuite/lib/styles/mixins/tiny-color.less (line 1183, column 0)
```

I'm using rsuite (https://rsuitejs.com/)
### Suggested solution(s)

idk :c

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 3.3.7
| Razzle Plugins   | less: 3.3.7
| Node             | 12.18.3
| Browser          | x
| npm/Yarn         | 6.14.7
| TypeScript       | x
| React            | 16.14.0

**Comment by fivethreeo** [comment]
```js
plugins: [
    {
      name: 'less',
      options: {
        less: {
          dev: {
            lessOptions: lessOptions
          },
          prod: {
            lessOptions: lessOptions
          }
        }
      }
    }
  ]
```

**Comment by OmarEMC** [comment]
```js
plugins: [
    {
      name: 'less',
      options: {
        less: {
          dev: lessOptions,
          prod: lessOptions
       }
      }
    }
  ]
```
https://www.npmjs.com/package/less-loader/v/5.0.0

**Comment by fivethreeo** [comment]
```js
plugins: [
    {
      name: 'less',
      options: {
        less: {
          dev: lessOptions,
          prod: lessOptions
       }
      }
    }
  ]
```


https://www.npmjs.com/package/less-loader/v/5.0.0

**Comment by OmarEMC** [comment]
> ```js
> plugins: [
>     {
>       name: 'less',
>       options: {
>         less: {
>           dev: lessOptions,
>           prod: lessOptions
>        }
>       }
>     }
>   ]
> ```
> 
> https://www.npmjs.com/package/less-loader/v/5.0.0

@fivethreeo now, the client is `Compiled with some errors in 1.35m` and the server say:
```
Module parse failed: Unexpected token (23:23)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders
```
but it is for optional chaining:
```
|   React.useEffect(() => {
>     if (props.location?.match?.params.id && user.id === props.location?.match?.params.id) props.history.push("/perfil/");
```

**Comment by fivethreeo** [comment]
You could try:

https://razzlejs.org/docs/experimental-features#enable-the-new-babel-loader

**Comment by fivethreeo** [comment]
I will look at upgrading the loader in the canary branch. Chaining should work with new babel loader.

**Comment by dmitryshelomanov** [comment]
@fivethreeo how to fix less ?

**Comment by dmitryshelomanov** [comment]
```js
function modifyLess(webpackConfig) {
  const less = webpackConfig.module.rules[webpackConfig.module.rules.length - 1];

  if (!less.test.test('.less')) {
    throw new Error('[modifyLess]: less not founded');
  }

  const lessLoader = less.use[less.use.length - 1];

  lessLoader.options.lessOptions = {
    ...lessLoader.options.lessOptions,
    ...lessOptions,
  };
}
```

👌
