### ISSUE TITLE
Razzle 4 canary document peerdeps

### ISSUE THREAD

**Issue by ceopaludetto** [jaredpalmer/razzle#1455]
### Current Behavior

When I install new razzle canary 2 version, some deps are missing such as `razzle-dev-utils` and `mini-css-extract-plugin`

### Expected behavior

Razzle 4 should build correctly

### Reproducible example

My project previously used razzle 3, now I'm just set the new razzle 4 in package.json then after install with yarn, when I run `razzle build` the missing dependencies error are thrown.

### Suggested solution(s)

Just add these packages, `mini-css-extract-plugin` and `razzle-dev-utils` in package.json of `razzle` package

### Aditional Context

`razzle-dev-utils` should have canary version in package.json

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 4.0.0-canary.2
| Razzle Plugin Typescript   | 4.0.0-canary.2
| Node             | 12.16.2
| Browser          | Chrome 86
| Yarn         | 1.22.10
| Operating System | Arch Linux 5.9.1
| TypeScript       | 4.0.3
| React            | 16.14.0

**Comment by fivethreeo** [comment]
This should be a docs fix. Those deps are now peerdeps.

**Comment by ceopaludetto** [comment]
Oh sorry, i didn't know.

In my project I don't use css, just jss with material ui, how can i disable this feature to avoid requiring this package?

**Comment by fivethreeo** [comment]
Css is builtin so you can't at this moment. :(

**Comment by fivethreeo** [comment]
fixed
