### ISSUE TITLE
Unable to debug using inspect and vscode

### ISSUE THREAD

**Issue by saunlani** [jaredpalmer/razzle#1456]
Could someone please advise on the correct configuration to debug with vscode/breakpoints with razzle react/nodejs?
I'm attempting to debug with the below configuration, but my breakpoints are grey.

**launch.json**
{
    "version": "0.2.0",
    
    "configurations": [
        {
            "name": "Attach to dev server",
            "type": "node",
            "request": "attach",
            "protocol": "inspector",
            "address": "localhost",
            "port": 9230
        }
    ]
}

**package.json**

{
  "name": "my-razzle-app",
  "version": "0.1.0",
  "license": "MIT",
  "scripts": {
    "start": "set PORT=8181 && razzle start --inspect --verbose",
    "build": "razzle build",
    "test": "razzle test --env=jsdom",
    "start:prod": "NODE_ENV=production node build/server.js"
  },
  "dependencies": {
    "@date-io/date-fns": "^1.3.13",
    "@material-ui/core": "^4.11.0",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/lab": "^4.0.0-alpha.56",
    "@material-ui/pickers": "^3.2.10",
    "activedirectory": "^0.7.2",
    "antd": "^4.7.0",
    "connect-mssql": "^1.5.0",
    "cross-fetch": "^3.0.6",
    "date-fns": "^2.16.1",
    "express": "4.17.1",
    "express-session": "^1.17.1",
    "fs-extra": "^9.0.1",
    "hashmap": "^2.4.0",
    "http": "0.0.1-security",
    "ini": "^1.3.5",
    "isomorphic-fetch": "^3.0.0",
    "ldapjs-client": "^0.1.1",
    "material-table": "^1.57.2",
    "mssql": "^6.2.3",
    "node-datetime": "^2.1.2",
    "node-fetch": "^2.6.1",
    "os": "^0.1.1",
    "razzle": "3.1.8",
    "razzle-plugin-scss": "^3.1.8",
    "react": "^16.13.1",
    "react-bar-loader": "^1.0.0",
    "react-dom": "^16.13.1",
    "react-hook-form": "^6.8.4",
    "react-idle-timer": "^4.3.7",
    "react-inlinesvg": "^2.1.0",
    "react-loader-spinner": "^3.1.14",
    "react-promise-tracker": "^2.1.0",
    "react-router-dom": "5.2.0",
    "react-scripts": "^3.4.3",
    "react-spinners": "^0.9.0",
    "styled-components": "^5.2.0",
    "websocket": "^1.0.32"
  },
  "devDependencies": {
    "eslint": "^7.10.0"
  }
}

**razzle.config.js**

module.exports = { modify(config, { target, dev }, webpack) {
  config.devtool = dev ? 'eval-source-map' : 'none';
  return config;
},
    plugins: ["scss"]
  };

thank you!

**Comment by nimaa77** [comment]
hey @saunlani 

update your start script and add `--inspect=9230` (`--inspect=[port]` or `--inspect=[host:port]`) to it: 

```
"start": "razzle start --inspect=9230 --verbose",
```

read more: https://razzlejs.org/getting-started#debugging-with-inspector

and then it should work without any problems, let me know how it goes

**Comment by nimaa77** [comment]
@fivethreeo `--inspect` without any port and host is not working there might be a problem with the default values (it should default to `127.0.0.1:9229` but right now its default is something else)

**Comment by fivethreeo** [comment]
This works correctly in canary. Not sure why not in master.

**Comment by fivethreeo** [comment]
npm needs -- --inspect, with yarn, yarn --inspect
