### ISSUE TITLE
Razzle-plugin-scss issue in the newest version

### ISSUE THREAD

**Issue by SamKhachatryan** [jaredpalmer/razzle#1465]
When you install the latest version of razzle-plugin-scss, it says that needs **'css-loader'** package.

So after instalation of the latest version of **css-loader** it gives and error that can't find the module called '**css-loader/locals'** and use **onlyLocals** option instead, new versions of this package doesn't include the **onlyLocals** option... and after changing it gives an error that **onlyLocals** is not a valid option...

So I find a version with watching the source code of the **css-loader** that includes the **onlyLocals** options and doesn't include the locals module,
It is the version tagged **3.6.0**,
And its started to work.

Please add this version to your module or review the codes, cause its very hard to find this version :))

**Comment by fivethreeo** [comment]
Fixed in master, will release in next patch release
