### ISSUE TITLE
Not able to serve brotli compressed files

### ISSUE THREAD

**Issue by ATakaSKY** [jaredpalmer/razzle#1474]
## ❓Question

I am trying to send compressed files in brotli format for browsers which support it. I have also managed to generate assets in the build folder. However the app isn't responsing with brotli format files, it always responds with gzip(tested this with chrome and safari). Here's the code:

```
import App from "./App";
import React from "react";
import { StaticRouter } from "react-router-dom";
import express from "express";
import { renderToString } from "react-dom/server";
import expressStaticGzip from "express-static-gzip";

const assets = require(process.env.RAZZLE_ASSETS_MANIFEST);

const server = express();
server
  .disable("x-powered-by")
  .use(
    expressStaticGzip(process.env.RAZZLE_PUBLIC_DIR, {
      enableBrotli: true,
      orderPreference: ["br", "gz"],
      index: false,
    })
  )
  .get("/*", (req, res) => {
    const context = {};
    const markup = renderToString(
      <StaticRouter context={context} location={req.url}>
        <App />
      </StaticRouter>
    );

    if (context.url) {
      res.redirect(context.url);
    } else {
      res.status(200).send(
        `<!doctype html>
    <html lang="">
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta charset="utf-8" />
        <title>Welcome to Razzle</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        ${
          assets.client.css
            ? `<link rel="stylesheet" href="${assets.client.css}">`
            : ""
        }
        ${
          process.env.NODE_ENV === "production"
            ? `<script src="${assets.client.js}" defer></script>`
            : `<script src="${assets.client.js}" defer crossorigin></script>`
        }
    </head>
    <body>
        <div id="root">${markup}</div>
    </body>
</html>`
      );
    }
  });

export default server;
```

Only dependency I have added here is "express-static-gzip". 
Below is how the asset's look compressed in build folder:

<img width="497" alt="Screenshot 2020-11-17 at 10 23 15 PM" src="https://user-images.githubusercontent.com/17201629/99420901-ca538f00-2923-11eb-9a92-96cd5dc75f57.png">

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | ^3.1.6
| Node             | 14.15.0
| Browser          | chrome
| npm/Yarn         | 6.14.8
| Operating System | mac os
| React            | ^16.13.1
| express-static-gzip | ^2.1.0

**Comment by aakashmeesho** [comment]
seems this doesn't work well on local. Was able to see the brotli compressed files sent once deployed to production.

You guys can close this one.
