### ISSUE TITLE
Why doesn't this overrides the other webpack configs like webpackObject, path etc. ?

### ISSUE THREAD

**Issue by bhavin-a** [jaredpalmer/razzle#1482]
https://github.com/jaredpalmer/razzle/blob/799dc46fcecdf854d035e3c3e1e19f4308ccff68/examples/with-loadable-components/razzle.config.js#L23

Was following the above code. Just had a doubt that why doesn't the above return overrides the other config options. Shouldn't it remove the options like webpackObject, path, etc. from the returned configs? The code is running fine though in my system. Just a bit curious. Thanks!

**Comment by fivethreeo** [comment]
It does remove it :)

https://github.com/jaredpalmer/razzle/blob/799dc46fcecdf854d035e3c3e1e19f4308ccff68/examples/with-loadable-components/razzle.config.js#L6

Does not override the rest since it can depend on previous plugins or hooks.

**Comment by bhavin-a** [comment]
> It does remove it :)
> 
> https://github.com/jaredpalmer/razzle/blob/799dc46fcecdf854d035e3c3e1e19f4308ccff68/examples/with-loadable-components/razzle.config.js#L6
> 
> Does not override the rest since it can depend on previous plugins or hooks.

Sure @fivethreeo . Thanks for the clarification :smile:
