### ISSUE TITLE
Misspelling option in modifyWebpackOptions hook

### ISSUE THREAD

**Issue by ceopaludetto** [jaredpalmer/razzle#1485]
### Current Behavior

Sorry about this issue  😂 😂 😂

The key fileLoaderExclude option has spelt as fileLoaderExlude.

### Expected behavior

Fix the misspelling error 

### Reproducible example

Add new custom razzle.config.js file, try to console.log webpackOptions

```js
module.exports = {
  modifyWebpackOptions({ options: { webpackOptions } }) {
    console.log(webpackOptions);

    return webpackOptions;
  },
}
```
<details>
  <summary>Output</summary>
  <pre>
{
  fileLoaderExlude: [ // <-- here
    /\.html$/,
    /\.(js|jsx|mjs)$/,
    /\.(ts|tsx)$/,
    /\.(vue)$/,
    /\.(less)$/,
    /\.(re)$/,
    /\.(s?css|sass)$/,
    /\.json$/,
    /\.bmp$/,
    /\.gif$/,
    /\.jpe?g$/,
    /\.png$/
  ],
  urlLoaderTest: [ /\.bmp$/, /\.gif$/, /\.jpe?g$/, /\.png$/ ],
  definePluginOptions: {
    'process.env.NODE_ENV': '"production"',
    'process.env.PORT': '3000',
    'process.env.VERBOSE': 'false',
    'process.env.HOST': '"localhost"',
    'process.env.RAZZLE_ASSETS_MANIFEST': '"/home/carlos/Documents/Projetos/Javascript/nest-new-graphql/build/assets.json"',
    'process.env.RAZZLE_CHUNKS_MANIFEST': '"/home/carlos/Documents/Projetos/Javascript/nest-new-graphql/build/chunks.json"',
    'process.env.BUILD_TARGET': '"client"',
    'process.env.PUBLIC_PATH': '"/"',
    'process.env.CLIENT_PUBLIC_PATH': undefined,
    'process.env.RAZZLE_PUBLIC_DIR': '"/home/carlos/Documents/Projetos/Javascript/nest-new-graphql/build/public"',
    'process.env.FAST_REFRESH': 'false',
    'process.env.RAZZLE_LOADABLE_MANIFEST': '"/home/carlos/Documents/Projetos/Javascript/nest-new-graphql/build/loadable-stats.json"'
  },
  splitChunksConfig: {
    chunks: 'all',
    cacheGroups: {
      default: false,
      vendors: false,
      defaultVendors: false,
      framework: [Object],
      lib: [Object],
      shared: [Object]
    },
    maxInitialRequests: 25,
    minSize: 20000
  },
  terserPluginOptions: {
    terserOptions: {
      parse: [Object],
      compress: [Object],
      mangle: [Object],
      output: [Object]
    },
    sourceMap: true
  }
}
</pre>
</details> 

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 3.3.7
| Node             | 12.16.2
| Browser          | Firefox 83.0
| Yarn         | 1.22.10
| Operating System | Arch Linux 5.9.11-arch2-1
| TypeScript       | 4.1.2
| React            | 17.0.1

**Comment by fivethreeo** [comment]
Fixed :)
