### ISSUE TITLE
Add ability to disable terser mangle in server

### ISSUE THREAD

**Issue by ceopaludetto** [jaredpalmer/razzle#1486]
### Current Behavior

I have a application which uses typescript decorators in server side, such as ORM, the class names should not change in this case because the ORM uses to sync table name in db.

### Desired Behavior

Classes and functions names keep their names of source code.

### Suggested Solution

Some option to razzle.config.js can be added to keep in sync with `mangle: false` in terserOptions, thus this will avoid mangling in class names or functions, another option is change `keep_fnames` and `keep_classnames` keys to false.

This modification should only affect server side.

### Who does this impact? Who is this for?

Typescript/Advanced users.

### Describe alternatives you've considered

Add a overwrite terser plugin in my own configuration

**Comment by fivethreeo** [comment]
There is no terser being used server-side

**Comment by ceopaludetto** [comment]
Not directly, but webpack uses terser as default minifier when mode is production even when target is node

**Comment by fivethreeo** [comment]
Need to look at that after 4.0 is out

**Comment by fivethreeo** [comment]
Actually, can add this in 4.0 if you add a pull request with the suggested changes. 😀

**Comment by ceopaludetto** [comment]
> Actually, can add this in 4.0 if you add a pull request with the suggested changes. grinning

Ok, i'll try to implement this today or tomorrow.

Do you think it is better to provide an option to disable mangle or a way to pass all options to the terser plugin? The option should affect only the server? @fivethreeo

**Comment by fivethreeo** [comment]
Follow 

https://github.com/jaredpalmer/razzle/blob/canary/packages/razzle/config/createConfigAsync.js#L192

Somehow :)

**Comment by fivethreeo** [comment]
If you want to try hacking on this, I have a workflow:

```bash
npm install -g yalc
git clone https://github.com/jaredpalmer/razzle.git
cd razzle
git checkout -B canary
NODE_ENV=development yarn install ---ignore-engines
yarn try-example basic
# or any example in the examples dir
# or just add your own in the examples dir
cd example
yarn start
yarn build
```

Make changes to razzle and run:

```bash
yarn updateyalc
yarn build
yarn start
```

In the example dir to use your modified razzle

You can even add dependencies in the example dir with yarn

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/commit/df4b895ffd29934417f3570b5dd730d55a6b5e23

added in v4.0.0-canary.19
