### ISSUE TITLE
React 17 Support and Upgrade Guide/Example

### ISSUE THREAD

**Issue by dvdprrsh** [jaredpalmer/razzle#1487]
## ❓Question
Hey, Razzle is awesome and makes my life a lot easier, I was just wondering if there are any plans on providing an upgrade guide for React 17 and/or an example? :)

**Comment by nimaa77** [comment]
just run `yarn add react react-dom` or `npm install --save react react-dom` and you are good to goo :D

**Comment by dvdprrsh** [comment]
> just run `yarn add react react-dom` or `npm install --save react react-dom` and you are good to goo :D

Thanks man!
