### ISSUE TITLE
Jest issue: --watch is not supported without git/hg, please use --watchAll

### ISSUE THREAD

**Issue by silviubogan** [jaredpalmer/razzle#1497]
### Current Behavior

I get this output when running `razzle test` without `--watchAll` (`$ razzle test`):

```
Determining test suites to run...
--watch is not supported without git/hg, please use --watchAll 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

IMHO the following line does something wrong since I get the message above when running `$ razzle test`:

https://github.com/jaredpalmer/razzle/blob/9871b0100432f13089264bf0a1c213463a24e1d1/packages/razzle/scripts/test.js#L37

### Expected behavior

No diverging output, simply run the tests with Jest.

### Reproducible example

Steps 1-4 from [this DEVELOP.md](https://github.com/eea/volto-slate/blob/7e46949a4dadc1bae61ed5ea7ef2f35782e884a9/DEVELOP.md), then attempt to run `$ yarn test` (equivalent of `$ razzle test --env=jsdom --passWithNoTests`) or simply `$ razzle test`.

### Suggested solution(s)

I do not know why `--watch` is used in the code snippet at the beginning of this issue, but I think that maybe an update can be done.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 3.1.5 |
| Razzle Plugins   | "razzle-plugin-bundle-analyzer": "1.2.0" |
| Node             | 12.18.2 |
| Browser        | N/A |
| npm/Yarn         | Yarn 1.22.5 |
| Operating System | Manjaro Linux |
| TypeScript       | N/A |
| React            | 16.13.1 |

**Comment by fivethreeo** [comment]
Maybe test for .git or .hg before adding —watch.

**Comment by fivethreeo** [comment]
Added --no-watch in canary now, will release soon

**Comment by stuartrapop** [comment]
I still get this same issue 

`--watch is not supported without git/hg, please use --watchAll`

```
{
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "test": "jest --watch",
    "test:ci": "jest --ci"
  },
  "dependencies": {
    "next": "latest",
    "react": "^18.1.0",
    "react-dom": "^18.1.0"
  },
  "devDependencies": {
    "@testing-library/jest-dom": "5.16.4",
    "@testing-library/react": "13.2.0",
    "@testing-library/user-event": "14.2.0",
    "@types/react": "18.0.9",
    "jest": "28.1.0",
    "jest-environment-jsdom": "28.1.0",
    "typescript": "4.6.4"
  }
}
```
