### ISSUE TITLE
Issues with canary version of babel-preset-razzle

### ISSUE THREAD

**Issue by SimeonC** [jaredpalmer/razzle#1504]
Related code;
https://github.com/jaredpalmer/razzle/blob/5a5b6c5fa74b0014bc2f86535fcd5295bb4531d2/packages/babel-preset-razzle/index.js#L69-L80
https://github.com/jaredpalmer/razzle/blob/5a5b6c5fa74b0014bc2f86535fcd5295bb4531d2/packages/babel-preset-razzle/index.js#L90-L101

In our projects we use [emotion](https://emotion.sh) and their babel plugin which works with the 'automatic' setting in https://babeljs.io/docs/en/babel-plugin-transform-react-jsx#react-automatic-runtime to support the new JSX runtimes https://emotion.sh/docs/css-prop#babel-preset

I don't know if this is relevant for anyone not using emotion, but I think this also prevents opting in to the new JSX runtimes with in theory are better? In the meantime I used this "hack" to support automatic mode via a custom babel-preset.

```js
const babelRazzle = require('babel-preset-razzle');

module.exports = function tcReactSystemBabelPreset(api, options) {
  const razzleConfig = babelRazzle(api, {
    ...options,
    'preset-react': {
      runtime: 'automatic',
      importSource: '@emotion/react',
      pragma: undefined
    }
  });

  // apparently plugins isn't a "real" array so we cant .filter or .reduce it
  const filteredPlugins = [];
  for (let i = 0; i < razzleConfig.plugins; i += 1) {
    const [, pluginOptions] = razzleConfig.plugins[i];
    // detect razzle's special import for react plugin as we use emotions
    if (
      !pluginOptions ||
      !pluginOptions.module ||
      pluginOptions.module !== 'react'
    ) {
      filteredPlugins.push(razzleConfig.plugins[i]);
    }
  }
  razzleConfig.plugins = filteredPlugins;
  razzleConfig.plugins.push('@emotion/babel-plugin');
  razzleConfig.plugins.push('@babel/plugin-transform-react-constant-elements');
  return razzleConfig;
};
```

**Comment by fivethreeo** [comment]
Canary has a modifyBabelPreset now, would that work?

**Comment by fivethreeo** [comment]
Any suggestions on how to improve this would be great 😀

**Comment by fivethreeo** [comment]
I will add a option for this tomorrow.

**Comment by SimeonC** [comment]
Cool, thanks. I was a bit late answering, from my point of view I think the easiest option is that if `runtime: 'automatic'` is set, just skip `./babel-plugins/jsx-pragma` and don't set `pragma: '__jsx'` (you can't set `pragma` or `pragmaFrag` with automatic runtime).

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/commit/5bc4c50d0fc6204a7a7f8ba1ab84683884ac48f3

**Comment by fivethreeo** [comment]
Fixed in canary 13
