### ISSUE TITLE
PostCSS 8

### ISSUE THREAD

**Issue by rolandleth** [jaredpalmer/razzle#1505]
Not convinced whether this should be under Feature Request or Bug Report, I feel it's a bit of both 🙈

I don't have a lot of experience with web tooling, so if there's any other solution for this, I haven't managed to find it.

### Current Behavior
Using a PostCSS plugin/tool that relies on PostCSS 8+ doesn't work, I get this error back: `PostCSS plugin <tailwindcss|postcss-import|postcss-flexbugs-fixes|anything-else> requires PostCSS 8`

### Desired Behavior
To be able to use latest/official versions of said tools.

### Suggested Solution
Update the PostCSS dependency to 8.

### Who does this impact? Who is this for?
People using PostCSS plugins that rely on version 8 of PostCSS, like `postcss-import` or `tailwindcss`.

### Describe alternatives you've considered
For my particular use case, I switched to using TailwindCSS' [compatibility build](https://tailwindcss.com/docs/installation#post-css-7-compatibility-build) and I'm in no real need of `postcss-import` (and if I were, I suppose I could use an older version), but it would be nice to be able to use main/latest builds.

Thank you!

**Comment by fivethreeo** [comment]
fixed in canary, note postcss needs to be in your package.json, that bit me
