### ISSUE TITLE
 Add with-react-server-components example 

### ISSUE THREAD

**Issue by laurencefass** [jaredpalmer/razzle#1507]
### Current Behavior
Razzle offers client and server side rendering. React team is working on new experimental features for Server side components offering a new way of pre-rendering React components on the server with next level granularity for (i) managing data on the server through React components and (ii) controlling what is rendered on server and client. 

See Dan Abramov intro here:
https://reactjs.org/blog/2020/12/21/data-fetching-with-react-server-components.html

### Desired Behavior
Razzle is my first choice for SSR it would be great to see 1st class support for server components out of the box.

### Suggested Solution
React team suggests that the initial releases will be delivered as webpack and next.js plugins. It would be great to have a Razzle plugin to support Server Components.

### Who does this impact? Who is this for?
Impacts: Server and client (full-stack) development

Target audience: intermediate, advanced React developers

### Describe alternatives you've considered
SSR, CSR, Next.js, Webpack

**Comment by sibelius** [comment]
I hope this helps https://github.com/sibelius/react-server-components-playground

**Comment by fivethreeo** [comment]
Working on this.

https://github.com/jaredpalmer/razzle/tree/canary/examples/with-flight

But could use some help.

**Comment by fivethreeo** [comment]
If you need to change anything in razzle to make this work, I have a workflow:

```bash
npm install -g yalc
git clone https://github.com/jaredpalmer/razzle.git
cd razzle
git checkout -B canary
NODE_ENV=development yarn install ---ignore-engines
yarn try-example with-flight
cd example
yarn start
yarn build
```

Make changes to razzle and run:

```bash
yarn updateyalc
yarn build
yarn start
```

In the example dir to use your modified razzle

You can add dependencies in the example dir with yarn

**Comment by fivethreeo** [comment]
If you want to try hacking on this, I have a workflow:

```bash
sudo npm install add-dependencies -g

git clone https://github.com/jaredpalmer/razzle.git
cd razzle
git checkout canary
NODE_ENV=development yarn install ---ignore-engines

cd examples/with-react-server-components
example="$(basename $PWD)"
pushd ../..

# if it is a example with webpack5 you need to do
yarn add -W webpack@5.16.0

# switch back to webpack4 later to work with webpack4
yarn add -W webpack@4.46.0

# then
yarn bootstrap-examples $example
popd
yarn build

# if you want to add dependencies to the example
add-dependencies somedependency
yarn restrap
# razzle packages are symlinked so any changes to razzle can be tested right away 
# if you add any dependencies to razzle packages make sure you run restrap aswell

# to make sure tests pass
yarn test --runInBand

# to add a new example
yarn new-example existingexample with-somefeature
```

**Comment by fivethreeo** [comment]
I am stuck now

```bash
npx create-razzle-app@canary --example with-react-server-components with-react-server-components

cd with-react-server-components
yarn start
```

Any ideas?

**Comment by laurencefass** [comment]
I can't see this in the examples repo. Is the w-r-s-c example located elsewhere?

Also how are you stuck whats the outcome of running those commands?

**Comment by fivethreeo** [comment]
I think I forgot the loader. https://github.com/jaredpalmer/razzle/tree/canary/examples/with-react-server-components

**Comment by fivethreeo** [comment]
And I need to take out the webpack register since we use the loader instead.

**Comment by laurencefass** [comment]
I didn't understand context for last two comments but as soon as that is installing correctly I will also install and test. Waiting for a green light.

**Comment by fivethreeo** [comment]
It builds, but server does not run. Don't know why

**Comment by fivethreeo** [comment]
It works, just needs polishing

```bash
npx create-razzle-app@canary --example with-react-server-components with-react-server-components

cd with-react-server-components
yarn start
```

**Comment by fivethreeo** [comment]
Fixed, working now :)
