### ISSUE TITLE
How to get css assets in the server rendered html

### ISSUE THREAD

**Issue by therealgilles** [jaredpalmer/razzle#1509]
## ❓Question

I've looked at a few examples (like --with-single-exposed-port) and the App.css is not been added to the server rendered html. It's only added once the client.js file is interpreted by the browser. There should be a way to have css added as link resources in the header (I see the code is there for that).

If someone could clarify how that's supposed to work, I would be grateful.

**Comment by fivethreeo** [comment]
Look at the basic example and copy that. If you can fix the example can you do a pull request?

**Comment by therealgilles** [comment]
There seems to be a couple solutions here:

1) Use the isomorphic-style-loader plugin as described [here](https://medium.com/@danielnmai/load-css-in-react-server-side-rendering-with-isomorphic-style-loader-848c8140a096). This requires using the plugin in the App code.

2) Use the file-loader plugin for css/sass/scss files. This requires using `import styles from './App.css'` instead of `import './App.css'`. See [here](https://dev.to/achhapolia10/adding-style-to-server-side-rendering-and-automating-the-build-process-59l).

Still researching... will try to put a separate example together.

**Comment by fivethreeo** [comment]
Basic example is working, no loaders are needed :)

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/blob/canary/examples/basic/src/server.js#L8

**Comment by therealgilles** [comment]
I'm looking at the basic example and I don't see any link tag stylesheet added to the generated html. My understanding is the styles are added when the client.js script is loaded.

PS: I am looking at the non-canary version right now.

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/blob/master/examples/basic/src/server.js#L21

**Comment by therealgilles** [comment]
I see this code but assets.client.css is empty, so nothing is getting added.

**Comment by fivethreeo** [comment]
In development css is loaded in js.

**Comment by therealgilles** [comment]
Oh I see. May I ask why?

**Comment by fivethreeo** [comment]
If you run the build version it is added

**Comment by fivethreeo** [comment]
So hot reloading works in dev

**Comment by therealgilles** [comment]
Is there a way to test it's working in development mode?

**Comment by fivethreeo** [comment]
I have had some issues with that aswell, don't know really :|

**Comment by therealgilles** [comment]
I think I got it working by hacking createConfigAsync.js. Let me see if I can come up with a razzleConfig.js setup just for testing.

**Comment by therealgilles** [comment]
I think this should do, obviously very hacky:

```JS
const MiniCssExtractPlugin = require('mini-css-extract-plugin')

module.exports = {
...
  modifyWebpackConfig({
    ...
    // Add stylesheet as link tag in development mode
    if (target === 'web' && dev) {
      webpackConfig.plugins.push(
        // Extract our CSS into files.
        new MiniCssExtractPlugin({
          filename: `${razzleOptions.cssPrefix}/[name].[contenthash:8].css`,
          chunkFilename: `${razzleOptions.cssPrefix}/[name].[contenthash:8].chunk.css`,
        })
      )

      webpackConfig.module.rules.forEach(rule => {
        if ('.css'.match(rule.test) && rule.use) {
          rule.use[0] = MiniCssExtractPlugin.loader
        }
      })
    }
```

It could be implemented as an option in createConfigAsync.js, not sure if it's worth it.

**Comment by fivethreeo** [comment]
Can be a option, but use webpackOptions aswell to make stuff overridable

**Comment by therealgilles** [comment]
Trying to figure out a good name, how about `razzleOptions.cssLinkHeaderDev`?

Do you want something like this to make this plugin overridable too?
```JS
      // Extract our CSS into files.
      const miniCssExtractPlugin = webpackOptions.miniCssExtractPlugin ||
        new MiniCssExtractPlugin({
          filename: `${razzleOptions.cssPrefix}/[name].[contenthash:8].css`,
          chunkFilename: `${razzleOptions.cssPrefix}/[name].[contenthash:8].chunk.css`,
        });
```

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/blob/canary/packages/razzle/config/createConfigAsync.js#L162

**Comment by therealgilles** [comment]
Any reason why it's not used here:
https://github.com/jaredpalmer/razzle/blob/001ab54b670d700030fd10449a8b2746622978c2/packages/razzle/config/createConfigAsync.js#L852

**Comment by fivethreeo** [comment]
I was thinking something like razzleOptions.writeCssDev, no reason i think ;) a bug

**Comment by therealgilles** [comment]
Sounds good, will fix both then.

**Comment by fivethreeo** [comment]
But also add it to docs :)

https://github.com/jaredpalmer/razzle/blob/canary/website/pages/docs/customization.md#options

**Comment by therealgilles** [comment]
Something like this?
`writeCssDev: false, // add stylesheet link tag in header in development build`
or would you like me to add more explanation?

Also adding it to defaultOptions.js with false as value.

**Comment by fivethreeo** [comment]
That seems ok

**Comment by fivethreeo** [comment]
Fixed
