### ISSUE TITLE
Issue with client port and .env* variables

### ISSUE THREAD

**Issue by therealgilles** [jaredpalmer/razzle#1513]
## ❓Question

The port parameter can be defined as a razzle options. But .env* files variables are not available to modifyOptions, so it's not possible to set the port using a dotenv variable. Is there a way that this could be remedied?

**Comment by fivethreeo** [comment]
Fixed https://github.com/jaredpalmer/razzle/commit/bcfbf44c4eba54913a59be6ab6613a618387ac0b
