### ISSUE TITLE
How to turn off caching for the razzle-babel-loader?

### ISSUE THREAD

**Issue by heath-freenome** [jaredpalmer/razzle#1522]
## razzle-babel-loader cache

I'm noticing that the `razzle-babel-loader` is dumping lots of files in the `cache` directory. I'd like to either be able to turn this off in a simple way, OR if these caches are needed, at least reduce the number of files that are generated somehow since there are tons of them

I'm using  `^4.0.0-canary.17` of razzle

Thanks

**Comment by fivethreeo** [comment]
set 

```js
webpackOptions.babelRule.use[0].cache = false
```

**Comment by heath-freenome** [comment]
How about for razzle 3.x?

**Comment by fivethreeo** [comment]
```javascript
// modifyWebpackConfig

const babelLoaderIndex = webpackConfig.module.rules.findIndex(makeLoaderFinder('babel-loader'));
webpackConfig.module.rules[babelLoaderIndex].use[0].cache = false;
```

But this is only needed if you use experimental.newBabel.

**Comment by heath-freenome** [comment]
From where do I import this `makeLoaderFinder` function?
