### ISSUE TITLE
Missing 'filesize' dependency in razzle-dev-utils causes build failure when using pnpm

### ISSUE THREAD

**Issue by bartels** [jaredpalmer/razzle#1530]
## 🐛 Bug report
`razzle-dev-utils` should declare `filesize` as a dependency, otherwise the build fails when using pnpm as package manager, and probably also when using yarn v2 pnp.

### Current Behavior
Build fails when using pnpm with `Error: Cannot find module 'filesize'`

### Expected behavior
Build does not fail due to a missing dependency

### Suggested solution(s)
Add `filesize` to dependencies in package.json for `razzle-dev-utils`

### Additional context
`razzle-dev-utils` has a transitive dependency on `filesize` through `react-dev-utils`. There are no problems when using npm or yarn classic since the dependencies are hoisted.  However pnpm's module resolution is stricter and requires them to be listed explicitly in package.json. The same issue likely exists for yarn v2's new pnp installs

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 3.3.11
| Razzle Plugins   | None
| Node             | 14.15.4
| Browser          | N/A
| npm/Yarn         | pnpm
| Operating System | Linux
| TypeScript       | 4.1.3
| React            | 17.0.1

**Comment by fivethreeo** [comment]
Will not fix in 3.x is this a issue in canary aswell?

**Comment by fivethreeo** [comment]
fixed in canary
