### ISSUE TITLE
Build non-zero exit code

### ISSUE THREAD

**Issue by CarsonF** [jaredpalmer/razzle#1533]
### Current Behavior

I've added a webpack circular dependency plugin that I'd like to fail the build.
CI/Docker doesn't respect this failure because the exit code is still 0.

This happens [here](https://github.com/jaredpalmer/razzle/blob/canary/packages/razzle/scripts/build.js#L75)

### Expected behavior

An exit code of 1 on webpack errors on razzle build.

### Suggested solution(s)

Maybe an `process.exit(1)` is all that's needed after line 75?
That's what happens in the other place `printErrors` is called in the file.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 4.0.0-canary.20
| Razzle Plugins   |
| Node             | 15.3.0
| Browser          | 
| npm/Yarn         | Yarn 2.3.3
| Operating System | OSX 10.15.7
| TypeScript       | 4.1.3
| React            | 16.13.1

**Comment by fivethreeo** [comment]
Added in canary will be in canary.30
