### ISSUE TITLE
Shell Environment are ignored by Razzel

### ISSUE THREAD

**Issue by jawahar273** [jaredpalmer/razzle#1534]
### Current Behavior

Razzel accept environment variable that only start with `RAZZEL_`.
> [env.js](https://github.com/jaredpalmer/razzle/blob/5c79f597bbd4e9f11801fbb36ef6570c74331b7b/packages/razzle/config/env.js#L42) loaded as core plugin which override all environment variable

### Expected behavior
Razzel must accept aribatic environment variable.

### Reproducible example

https://gist.github.com/jawahar273/1beac74e664a8bb9721555faa3cd0002

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 3.3.7
| Node             |  14.15.4
| npm/Yarn         | 1.22.10 
| Operating System | Ubuntu 20
| React            | 17.0.1

**Comment by fivethreeo** [comment]
This is adressed in canary will not fix in 3.x

https://razzle-git-canary.jared.vercel.app/docs/customization#options
