### ISSUE TITLE
Security vulnerability introduced by a dependency

### ISSUE THREAD

**Issue by GLObus303** [jaredpalmer/razzle#1542]
### Current Behavior

It seems like one of your nested dependencies is introducing a security issue. 
![image](https://user-images.githubusercontent.com/12488648/106793932-63a75d00-6658-11eb-9f09-e0ca474db43e.png)

### Expected behavior

There are no high-security issues in the repo or any underlying dependency. 

### Suggested solution(s)

Would it be possible to upgrade that dependency as they have already fixed that? Or should it be addressed inside the "user's" repo with some npm resolution?

**Comment by fivethreeo** [comment]
Not being used in razzle canary. Will soon release it as 4.0.

**Comment by fivethreeo** [comment]
Fixed in v4
