### ISSUE TITLE
Option to disable source maps.

### ISSUE THREAD

**Issue by zenios** [jaredpalmer/razzle#1547]
A setting that would allow disabling source maps in production would be really helpful. 

If we want to do that manually we can do it via razzle.config.js
- For javascript by setting devMode = false
- For css though we have to override the built-in webpack plugins provided by razzle and pass sourceMap:false where needed

**Comment by fivethreeo** [comment]
Maybe disable by default in production and ability to turn on?

**Comment by zenios** [comment]
CRA has them enabled in production with an option to disable.Maybe its better to follow the same paradigm

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/commit/8354ffff3ef5684389a4c0467488a50f4b6d08b5 - something like this?

**Comment by zenios** [comment]
I went though cra config

I think there are other places we should disable source maps depending on
the config. Postcss-loader / devtool / babel-loader / css-loader


Check these file
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.js

 For usages of "shouldUseSourceMap"

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/pull/1549/files - like this?

**Comment by fivethreeo** [comment]
Released that branch by accident, but worked out fine :) Tests pass.

**Comment by zenios** [comment]
Works like a charm. Thanks
