### ISSUE TITLE
SPA mode on canary is setting DEV_PORT incorrectly

### ISSUE THREAD

**Issue by SimeonC** [jaredpalmer/razzle#1550]
I discovered this when setting `port: 8080` inside `razzle.config.js` and running under `spa` mode.

If I run `razzle start`, then the server runs on port 8080, but the injected client JS is pointing to `localhost:3000` instead of port 8080.

I can fix this locally by forcing the dev port like this `PORT_DEV=8080 razzle start`.

Relevant code is here, I think all we need to do is add;
```js
if (clientOnly) {
  devServerPort = port;
} else {
  devServerPort = ... // current logic
}
```
https://github.com/jaredpalmer/razzle/blob/769ae67395469096b463a4d59a6d16490838fd48/packages/razzle/config/createConfigAsync.js#L240-L243

**Comment by fivethreeo** [comment]
I think that setting port like that should be removed. Set too many places.

https://github.com/jaredpalmer/razzle/blob/canary/packages/razzle-dev-utils/setPorts.js

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/blob/769ae67395469096b463a4d59a6d16490838fd48/packages/razzle/config/createConfigAsync.js#L246

Should be set for non-razzle standard ports.

**Comment by fivethreeo** [comment]
Will remove port option for config.
