### ISSUE TITLE
Esbuild

### ISSUE THREAD

**Issue by benkingcode** [jaredpalmer/razzle#1554]
I was wondering if anyone has successfully got esbuild working with Razzle? This looks like it could be a game changer for build times.

**Comment by fivethreeo** [comment]
Razzle is mainly a webpack configuration app. So I don’t see using esbuild is possible without a complete rewrite of Razzle.

**Comment by mrceperka** [comment]
webpack loader for esbuild exists (https://github.com/privatenumber/esbuild-loader) -> so it might be possible

**Comment by yemi** [comment]
@mrceperka cool! Did you or anyone else explore the possibilities for this?

**Comment by mrceperka** [comment]
@yemi I did not, I am not using razzle right now :/

**Comment by rclmenezes** [comment]
I got it working. And I made an example and it was merged in today!

https://github.com/jaredpalmer/razzle/pull/1597#issuecomment-820649721
