### ISSUE TITLE
Minification / removing unused javascript

### ISSUE THREAD

**Issue by Jonty800** [jaredpalmer/razzle#1555]
## 📖 Documentation

Is there any guide on how to minify the bundle.js via Razzle?

Many thanks

**Comment by fivethreeo** [comment]
https://babeljs.io/docs/en/babel-plugin-minify-dead-code-elimination

https://razzlejs.org/docs/customization#customizing-babel-config

Production minimizes by default.

**Comment by fivethreeo** [comment]
I think maybe Terser already does code elimination. So that Babel plugin might not be needed.

**Comment by fivethreeo** [comment]
Razzle uses terser by default in production.
