### ISSUE TITLE
How to customize title&keywords for each page

### ISSUE THREAD

**Issue by qilovehua** [jaredpalmer/razzle#1556]
## ❓Question
"razzle": "^3.0.0"

Now I am using document.js to customise, is there any more effictive way? Thanks

**==document.js==**
`import React from 'react';
import { AfterRoot, AfterData } from '@jaredpalmer/after';
import App from './App';

export default class Document extends React.Component {
  static async getInitialProps({ assets, data, renderPage }) {
    const page = await renderPage();
    return { assets, data, ...page };
  }

  render() {
    const { helmet, assets, data } = this.props;
    let title = 'ahahha';
    let desc = '“gaagaga'
    let keywords = 'haha, heihei, hehe'
    // get attributes from React Helmet
    const htmlAttrs = helmet.htmlAttributes.toComponent();
    const bodyAttrs = helmet.bodyAttributes.toComponent();
        return (
              <html {...htmlAttrs} lang="zh-CN">
                <head>
                  <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
                  <meta charSet="utf-8" />
                  <title>{title}</title>
                  <meta name="keywords" content={keywords} />
                  <meta name="description" content={desc} />
                  <meta name="viewport" content="width=device-width, initial-scale=1" />
                  <meta http-equiv="Content-Language" content="zh-CN" />
                  {helmet.meta.toComponent()}
                  {helmet.link.toComponent()}
                </head>
                <body {...bodyAttrs}>
                  <AfterRoot />
                  <AfterData data={data} />
                  <script
                    type="text/javascript"
                    src={assets.client.js}
                    defer
                    crossOrigin="anonymous"
                  />
                </body>
              </html>
            );
        }

**Comment by kkgrigas** [comment]
This question is highly unrelated to this framework

**Comment by qilovehua** [comment]
use [react-helmet](https://github.com/nfl/react-helmet)
