### ISSUE TITLE
razzle-plugin-scss transitively imports a version of object-path with a high severity vulnerability

### ISSUE THREAD

**Issue by emwalker** [jaredpalmer/razzle#1557]
## 🐛 Bug report

`razzle-plugin-scss` [currently imports](https://github.com/jaredpalmer/razzle/blob/master/packages/razzle-plugin-scss/package.json#L19) `resolve-url-loader@v2.3.0`, which transitively brings in a version of `object-path` with a high severity vulnerability.  This vulnerability [was fixed](https://github.com/bholloway/resolve-url-loader/issues/170#issuecomment-712743988) in `resolve-url-loader@3.1.2`.  Would it be possible to upgrade to a newer version of `resolve-url-loader` that doesn't import the vulnerable `object-path` dependency?

![2021-02-20_19-41](https://user-images.githubusercontent.com/760949/108614071-adac7480-73b4-11eb-9b8c-e13a05cfc6bd.png)

**Comment by fivethreeo** [comment]
Will be releasing 4.0 shortly is fixed there.
