### ISSUE TITLE
razzle-dev-tools v4 Issues with error/warning output with Webpack 4

### ISSUE THREAD

**Issue by SimeonC** [jaredpalmer/razzle#1558]
With the canary.47 changes I found that my client bundle build warnings and errors are not being printed to the console.

From the looks of it, it's because in webpack 4 the warnings are just strings, not objects so the `printWarnings` function basically prints nothing.

I tested by adding the following code to the top of the printWarnings function and it output the information I needed.
```
if (!wrn.message && !wrn.details && !verbose) {
  console.warn(wrn);
}
```
https://github.com/jaredpalmer/razzle/blob/a1b4def5f3b1af66bc0d6f472f7c497606f7eb1e/packages/razzle-dev-utils/printWarnings.js#L14

As for the printErrors function, I tested by running `CI=true razzle build` and it looks like the `err` value is an array of strings 🤷 
The suitable catch for this I think is just checking for `err.length`, that seemed to work when testing locally.
```
if (err.length) {
  console.error(err.join(''));
}
```
https://github.com/jaredpalmer/razzle/blob/a1b4def5f3b1af66bc0d6f472f7c497606f7eb1e/packages/razzle-dev-utils/printErrors.js#L15

**Comment by fivethreeo** [comment]
Should be fixed in canary.50
