### ISSUE TITLE
Dependancy "immer" high vulnerability risk

### ISSUE THREAD

**Issue by matt-catellier** [jaredpalmer/razzle#1561]
Current Behavior
It seems like one of your nested dependencies is introducing a security issue.
image

![image](https://user-images.githubusercontent.com/16104817/108760702-d5a9ee00-7502-11eb-972f-7042b97bc911.png)

Expected behavior
There are no high-security issues in the repo or any underlying dependency.

Suggested solution(s)
Would it be possible to upgrade that dependency as they have already fixed that? Or should it be addressed inside the "user's" repo with some npm resolution?

**Comment by matt-catellier** [comment]
Any action on this?

**Comment by GLObus303** [comment]
https://github.com/immerjs/immer/releases/tag/v8.0.0, there is one breaking change, that has some fallback. Not sure that any environment logic is applicable for a library.

Would be amazing if somebody could have a look at that before Razzle v.4. Not sure how many breaking changes it will introduce. But for bigger codebases, it could be quite difficult to update major versions.

**Comment by esimons** [comment]
Just to unwind the action that would be required to address this, `react-dev-utils` updated their dependency to `immer@8.0.1` in their 11.0.3 release, which would be a major version bump in that dependency [for `razzle-dev-utils`](https://github.com/jaredpalmer/razzle/blob/31acbf3bbbeb40742ecf652bada6021111f57ae2/packages/razzle-dev-utils/package.json#L24) and [for `razzle`](https://github.com/jaredpalmer/razzle/blob/31acbf3bbbeb40742ecf652bada6021111f57ae2/packages/razzle/package.json#L47).

**Comment by fivethreeo** [comment]
Fixed in v4

**Comment by EvanCoh** [comment]
> 
> 
> Fixed in v4

Thank you. Any plans on fixing this on v3 as well?

**Comment by fivethreeo** [comment]
No plans on fixing this in 3.x since 3.x is prone to break on dep updates. It is only a dev dependency aswell that is only used in dev. So will not affect any production code.
