### ISSUE TITLE
@babel/core in prod dependencies

### ISSUE THREAD

**Issue by GLObus303** [jaredpalmer/razzle#1562]
## ❓Question

Hey, I am curious why Razzle is using `@babel/core` as a production dependency which I can't find that common. I would expect something like `@babel/runtime` to be used instead.

**Comment by fivethreeo** [comment]
Hm, yea, that may not be needed. babel-preset-razzle needs it but it is a dep there.

**Comment by GLObus303** [comment]
It does introduce quite a huge overload to the node_modules size a might be an issue for people that need to have their docker as small as possible for example.

Would some nice soul care to have a look at that?

**Comment by fivethreeo** [comment]
You need it for babel-preset-razzle anyway. Razzle should not be in prod deps.

**Comment by GLObus303** [comment]
Big mistake on our side - razzle was in prod deps. 

Thanks :)
