### ISSUE TITLE
assets-webpack-plugin v3.9.12 uses a vulnerable lodash version

### ISSUE THREAD

**Issue by heath-freenome** [jaredpalmer/razzle#1565]
### Current Behavior

We recently integrated [snyk](https://snyk.io/vuln/SNYK-JS-LODASH-567746) into our builds and it told us that it needed to patch `razzle` because the locked `assets-webpack-plugin` v3.9.12 is locked on a security vulnerable version of `lodash@4.17.15`

### Expected behavior

To have razzle not lock things that have security vulnerabilities.

### Reproducible example

N/A

### Suggested solution(s)

Please ensure that Razzle v4.x does not include vulnerable software. Not sure how reasonable it is for the project to integrate with something like `snyk`

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           |3.3.13
| Razzle Plugins   |
| Node             |
| Browser          |
| npm/Yarn         |
| Operating System |
| TypeScript       |
| React            |

**Comment by fivethreeo** [comment]
Razzle 3.x will not receive security updates. Just bugfixes.

**Comment by heath-freenome** [comment]
But 4.x will, right? Just waiting for it :)

**Comment by fivethreeo** [comment]
Yup, my precious gets everything ;)
