### ISSUE TITLE
ReferenceError: WEBPACK_VERSION is not defined

### ISSUE THREAD

**Issue by CarsonF** [jaredpalmer/razzle#1566]
### Current Behavior

```
formatWebpackMessages.js:6 Uncaught ReferenceError: WEBPACK_VERSION is not defined
    at razzleFormatWebpackMessages (formatWebpackMessages.js:6)
    at handleErrors (webpackHotDevClient.js:163)
```

https://github.com/jaredpalmer/razzle/blob/canary/packages/razzle-dev-utils/formatWebpackMessages.js#L6
`razzleFormatWebpackMessages` is looking for [`WEBPACK_VERSION`](https://github.com/jaredpalmer/razzle/blob/canary/packages/razzle-dev-utils/formatWebpackMessages.js#L6) but the config defines it at `process.env.WEBPACK_VERSION`.

https://github.com/jaredpalmer/razzle/blob/canary/packages/razzle/config/env.js#L73
https://github.com/jaredpalmer/razzle/blob/canary/packages/razzle/config/env.js#L79
https://github.com/jaredpalmer/razzle/blob/canary/packages/razzle/config/createConfigAsync.js#L167

### Suggested solution(s)

Change to `process.env.WEBPACK_VERSION`?

### Additional context

I think it's trying to throw an error about unable to parse a numeric separator `1_000`.
I didn't need the `@babel/plugin-proposal-numeric-separator` plugin, but adding that caused this error to go away too. Probably just because the code path wasn't hit.
Did something change there recently?

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | canary 6
| Razzle Plugins   |
| Node             |
| Browser          |
| npm/Yarn         | 2.4.0
| Operating System | OSX
| TypeScript       | 4.1.3
| React            |

**Comment by fivethreeo** [comment]
Ah, good catch, will fix tomorrow 😀

**Comment by fivethreeo** [comment]
Fixed, don't know about the issue that caused the error.
