### ISSUE TITLE
Module Federation example not working?

### ISSUE THREAD

**Issue by gl0gl0** [jaredpalmer/razzle#1569]
### Current Behavior

I downloaded module federation example (https://github.com/jaredpalmer/razzle/tree/canary/examples/with-module-federation) and run it.

First, I got error during "install" `> Error! Failed to install razzle@canary, razzle-dev-utils@canary, try again.`

To solve that I just tried running yarn install again. And all good.

Then I tried running it with `yarn start`.

No errors on console or terminal.

But when I open it on the browser nothing is showing up. Just blank page.

Not sure if I'm missing something?

### Expected behavior

Should be able to see App rendering
```
<div>
    <h1>Bi-Directional</h1>
    <h2>App 1</h2>
    <LocalButton />
    <React.Suspense fallback="Loading Button">
      <RemoteButton />
    </React.Suspense>
  </div>
```

once opened on http://localhost:3000/

Same with App2

### Reproducible example

https://github.com/jaredpalmer/razzle/tree/canary/examples/with-module-federation

### Your environment

env: localhost
versions: are the same provided in the package.json
node: v12.19.0

**Comment by fivethreeo** [comment]
Can you see any errors in the devtools in your browser?

**Comment by fivethreeo** [comment]
Oh, sorry, I broke it ;) Will fix now :)

**Comment by fivethreeo** [comment]
You used the create-razzle-app method? I updated the example now. If you add --verbose to create-razzle-app you can see more of what happens during install. By the way, are you using yarn1 or yarn2?

**Comment by fivethreeo** [comment]
Should be fixed now :)

**Comment by gl0gl0** [comment]
@fivethreeo  Wow thank you for taking a look into this so quickly!

It is effectively working now, but there still seems to be a problem on the `yarn start:prod`. That is looking to run the `server.js` file but there is none.

```
~/Sites/demos/with-module-federation  yarn start:prod
yarn run v1.22.4
$ concurrently "yarn start:prod-1" "yarn start:prod-2"
$ cross-env RAZZLE_APP_PATH=basic-2 NODE_ENV=production node basic-2/build/server.js
$ cross-env RAZZLE_APP_PATH=basic-1 NODE_ENV=production node basic-1/build/server.js
[0] internal/modules/cjs/loader.js:834
[0]   throw err;
[0]   ^
[0]
[0] Error: Cannot find module '.../Sites/demos/with-module-federation/basic-1/build/server.js'
[0]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:687:27)
[0]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
[0]     at internal/main/run_main_module.js:17:47 {
[0]   code: 'MODULE_NOT_FOUND',
[0]   requireStack: []
[0] }
error Command failed with exit code 1.
```

**Comment by fivethreeo** [comment]
Should be just 

https://github.com/jaredpalmer/razzle/blob/canary/examples/basic-spa/package.json#L9

Will fix tomorrow

**Comment by fivethreeo** [comment]
Fixed now

**Comment by gl0gl0** [comment]
Thank you so much!
