### ISSUE TITLE
Goodbye message breaks CLI

### ISSUE THREAD

**Issue by rolandleth** [jaredpalmer/razzle#1572]
### Current Behavior

After terminating the process, the Goodbye message is sent with a delay and it ends up breaking the CLI.

<img width="479" alt="2021-03-17 at 08 26 50" src="https://user-images.githubusercontent.com/1858700/111424501-8bc7b880-86fa-11eb-80fc-4192792881b4.png">

If I start typing, it actually works, but the experience is rather weird nonetheless.

<img width="471" alt="2021-03-17 at 08 27 02" src="https://user-images.githubusercontent.com/1858700/111424522-93875d00-86fa-11eb-9aab-c10e0717e919.png">

Kind of the same thing happens with a non-customized prompt: Goodbye appears with a delay and the prompt appears to hang, but starting to type actually works.

<img width="503" alt="Bildschirmfoto 2021-03-17 um 8 33 54 AM" src="https://user-images.githubusercontent.com/1858700/111425226-8454df00-86fb-11eb-81a2-820858e83f32.png">

Should the process not be ended by ctrl-c?

### Expected behavior

To not break the CLI.

### Reproducible example

Any project does this for me since canary and/or 4.0.1.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 4.0.1
| Razzle Plugins   |
| Node             |
| Browser          |
| npm/Yarn         | 1.22.10
| Operating System | Big Sur
| TypeScript       |
| React            |

**Comment by fivethreeo** [comment]
Will fix 😀

**Comment by fivethreeo** [comment]
Fixed in v4.0.3

**Comment by rolandleth** [comment]
Thanks for the quick fix, @fivethreeo!

But now the process "hangs": 
- press ctrl-c to terminate
- `sswp> !!! Script exited with signal SIGINT` appears, but no prompt
- only after pressing enter (or another ctrl-c) does the prompt appear again, for bash; for fish I can type anything to make it appear (and the key will also register in the prompt)

**Comment by nikopavlica** [comment]
I also experience weird behaviour when using `ctrl+c` - I end up with terminated process and no bash prompt.
