### ISSUE TITLE
create-razzle-app does not work with a SPA build type

### ISSUE THREAD

**Issue by afahrenholtzsai** [jaredpalmer/razzle#1574]
### Current Behavior

1. Run `npx create-razzle-app example-app --example with-typescript`
2. Follow [documentation](https://razzlejs.org/docs/single-page-applications) to convert to a SPA
  - Remove `index.ts`
  - Remove `server.tsx`
  - Add `index.html` to `public` folder
  - Add `razzle.config.js` to root folder with the following content:
  ```
  'use strict';
module.exports = {
  options: {
    buildType: 'spa',
  }
};
  ```
3. Run `npm run start`
4. Open http:\\localhost:3000 in browser
![Screenshot](https://user-images.githubusercontent.com/20650482/111700023-d9c9e280-8806-11eb-845f-45f471e9a4fd.png)

This also occurs without the `with-typescript` example.

### Expected behavior

A landing page with the default example content.

### Reproducible example

https://github.com/nbodesa/single-page-razzle-whitescreen

### Suggested solution(s)

¯\\_(ツ)_/¯

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 4.0.2
| Razzle Plugins   | none
| Node             | 14.6.0
| Browser          | Edge 89.0.774.54
| npm/Yarn         | npm
| Operating System | Windows 10
| TypeScript       | 4.2.3
| React            | 17.0.1

**Comment by ghost** [comment]
Running into the same issue with the most recent release

**Comment by fivethreeo** [comment]
Ah, look at the basic-spa example index.html, will fix the docs.

**Comment by fivethreeo** [comment]
Fixed docs https://razzlejs.org/docs/single-page-applications
