### ISSUE TITLE
Css chunks doesn't exist in RAZZLE_ASSETS_MANIFEST env variable. 

### ISSUE THREAD

**Issue by karna419** [jaredpalmer/razzle#1578]
I am trying to enable CSS in SSR loading. For that I use 
`extract-css-chunks-webpack-plugin`.

Still the SSR loading without css. I could see RAZZLE_ASSETS_MANIFEST only contains js chunks.

**Comment by fivethreeo** [comment]
In dev you only get js chunks unless you set options.staticCssInDev to true. You don't need extract-css-chunks-webpack-plugin
