### ISSUE TITLE
Razzle Config has a confusing API

### ISSUE THREAD

**Issue by speedy250** [jaredpalmer/razzle#1590]
### Current Behavior

razzle.config.js v4 uses a confusing set of similarly named attributes and functions to affect changes in different parts of the webpack/razzle/build config. This includes
- modifyPaths
- modifyOptions
- modifyWebpackOptions
- modifyWebpackConfig
- modifyJestConfig

Each function accepts an object, which itself is subset of some master object (in that each arg has similar overlapping properties. See [plugins docs](https://razzlejs.org/docs/customization#plugins) for each example)

Each function returns a different property of that master object.
- `modifyWebpackConfig({webpackConfig, ...rest})` returns the `.webpackConfig` portion of that object
- `modifyOptions({options: { pluginOptions, razzleOptions}, ...rest)` returns the `.options.razzleOptions` of config
- `modifyWebpackOptions({options: {pluginOptions, razzleOptions, webpackOptions}, ...rest})` returns the `.options.webpackOptions` of config

Each of those functions accepts a similar object, and returns some branch of that object, each of which impacts different parts webpacks config, or razzle's config.

You can also use `module.exports = { plugins: [...] };` to specify which Razzle plugins are loaded into Webpack.

For example, when adding Tailwind, the documents suggest the following modification to razzle.config.js:
```
module.exports = {
  modifyWebpackOptions(opts) {
    const options = opts.options.webpackOptions;
    options.postCssOptions.plugins.unshift(require("tailwindcss"));
    return webpackOptions;
  },
}
```
Typescript is added as such:
```
module.exports = {
  plugins: ['typescript'],
};
```
And loadable-components like this:
```
module.exports = {
  modifyWebpackConfig({
    env: {
      target, // the target 'node' or 'web'
      dev, // is this a development build? true or false
    },
    webpackConfig, // the created webpack config
    webpackObject, // the imported webpack node module
    options: {
      pluginOptions, // the options passed to the plugin ({ name:'pluginname', options: { key: 'value'}})
      razzleOptions, // the modified options passed to Razzle in the `options` key in `razzle.config.js` (options: { key: 'value'})
      webpackOptions, // the modified options that was used to configure webpack/ webpack loaders and plugins
    },
    paths, // the modified paths that will be used by Razzle.
  }) {
    if (target === 'web') {
      // client only
      const filename = path.resolve(__dirname, "build");
      webpackConfig.plugins.push(
        new LoadableWebpackPlugin({
          outputAsset: false,
          writeToDisk: { filename },
        })
      );
    }
    return webpackConfig;
  }
}
```

So if I put this all together (some mods for brevity) I have:
```
module.exports = {
  plugins: ['typescript','eslint'],
  modifyWebpackOptions(opts) {
    const options = opts.options.webpackOptions;
    options.postCssOptions.plugins.unshift(require("tailwindcss"));
    return webpackOptions;
  },
  modifyWebpackConfig(config) {
    if (config.env.target === 'web') {
      // client only
      const filename = path.resolve(__dirname, "build");
      config.options.webpackConfig.plugins.push(
        new LoadableWebpackPlugin({
          outputAsset: false,
          writeToDisk: { filename },
        })
      );
    }
    return webpackConfig;
  },
};
```

### Desired Behavior

Razzle v3 had a much cleaner interface for modifying config. It setup and provided the webpack config directly and made modifications much less confusing. More specifically it feels like Razzle is wrapping Webpack's config in it's own version of config, forcing the developer to learn how to translate between them to make the changes they want.

### Suggested Solution

5 functions to change 5 different aspects of config feels like an over specified API. I understand that there are many complexities to configuring the app correctly, but there must be a cleaner approach to setting up a Razzle 4 app with multiple sources of plugins.

An easier solution would be to post a more comprehensive example, showing how each method of config mod can be done in different ways. For example, a tutorial with `typescript` could show one use with Tailwind, another where the modifyWebpackConfig is defined (not the simple `plugins` array). Some way to show how the two methods might be used.

### Who does this impact? Who is this for?

This is for Beginner/Intermediate users of Razzle, enjoying the many plugins on offer.

### Describe alternatives you've considered

The config settings I've posted above result in the build not starting. I'm still diagnosing the problem - could be v3->v4 issue or something else - but the documentation around plugins was needing a bit of attention.

**Comment by speedy250** [comment]
After digging into the [Razzle config source code](https://github.com/jaredpalmer/razzle/tree/master/packages/razzle/config) and documentation a little more thoroughly, I've determined
`module.exports = { plugins: [] }` is for Razzle specific plugins, such as `razzle-plugin-typescript`

If you have a similar setup to me - ES Lint is included in the typescript plugin already, and should not be included in your 'plugins' array. Here is my functioning `razzle.config.js`
```
const LoadableWebpackPlugin = require('@loadable/webpack-plugin');
const path = require("path");

module.exports = {
  plugins: ['typescript', 'scss'],
  modifyWebpackOptions(opts) {
    const options = opts.options.webpackOptions;
    options.postCssOptions.plugins.unshift(require("tailwindcss"));
    return options;
  },
  modifyWebpackConfig(opts) {
    const config = opts.webpackConfig;
    if (opts.env.target === "web") {
      const filename = path.resolve(__dirname, "build");
      config.plugins.push(
        new LoadableWebpackPlugin({
          outputAsset: false,
          writeToDisk: { filename },
        })
      );
    }
    return config;
  },
};
```

If your plugin is not a Razzle package, then you need to modify your config with the above mentioned functions, based on which part of the config you need to change.

**Comment by fivethreeo** [comment]
Could flatten the args. The naming of the functions could be better but for composability the number of functions is needed. The idea for webpackOptions is that you can do some options that will be used in modifyWebpackConfig. Then later plugins can affect what modifyWebpackConfig gets in webpackOptions. Also some commonly modified options and option that are difficult to get at by drilling down the webpack config are put in webpackOptions. If you set options.debug.webpackOptions you can see what is going on in there 😀

I do get it is a bit confusing, but it will be like this until razzle 6 atleast. Thinking of making razzle 5 webpack 5 only. So api changes can be done in razzle 6. But it may not be too far off since 5 is sort of 4 with webpack 5 only.

**Comment by speedy250** [comment]
Makes sense. I think from the perspective of "not having to use all of these" it seems overprescribed. But once you do need them, they are very helpful. I know it wouldn't have been this way without consideration from you guys. Thanks for the info!
