### ISSUE TITLE
SCSS/CSS not being generated

### ISSUE THREAD

**Issue by speedy250** [jaredpalmer/razzle#1591]
## ❓Question
I'm facing a couple issues with SCSS while upgrading from v3 to v4, and I'm looking for some help! My project uses SCSS modules, loadable components, Tailwind, and Typescript plugins for Razzle. I use the simplified `const style = require('./style.scss');` method of importing styles.

1. The generated server html does not contain any style links, nor does the asset.json file have .css files shown. Specifically this means that `assets.client.css` is blank. (This is also the case with the [`with-scss`](https://github.com/jaredpalmer/razzle/tree/master/examples/with-scss) project in the Razzle examples folder)
2. HTML class names in both client and server apps are output as "undefined". For example a container div element is output as `<div class="undefined undefined">...</div>`
3. The `<style>` tags and all styles do render in the client app html, but they no longer have unique local identifier names like `.style_home_containter__d38f3ls`, they are just named `.container`

My razzle config is simple:
```
const SCSSPlugin = require('./packages/razzle/razzle-plugin-scss');
const LoadablePlugin = require('./packages/razzle/razzle-plugin-loadable');

module.exports = {
  plugins: [SCSSPlugin, LoadablePlugin, 'typescript'],
};
```

The custom scss plugin is a copy of [Razzle's scss package](https://github.com/jaredpalmer/razzle/blob/master/packages/razzle-plugin-scss/index.js), with Tailwind prepended to the plugins array for postcss config.

LoadablePlugin is a copy of [Razzle's example config](https://github.com/jaredpalmer/razzle/blob/master/examples/with-loadable-components/razzle.config.js).

Any help is greatly appreciated.

**Comment by fivethreeo** [comment]
rename style.scss to style.module.scss

**Comment by fivethreeo** [comment]
1. no css files are output in dev, assetss.json is empty in build aswell?

**Comment by fivethreeo** [comment]
But tailwind with scss may seem a bit sketcy. Not sure about typescript.

**Comment by fivethreeo** [comment]
May be related to

https://github.com/jaredpalmer/razzle/issues/1316

**Comment by speedy250** [comment]
Will work with these suggestions

**Comment by speedy250** [comment]
1. Confirm this is expected behavior and that prod build contains css files.

2/3. Renamed all style files style.module.scss and they are now being built as modules. However the class names are still `undefined`

Tailwind with scss works with Razzle 3 no problem, it's all about where you inject it in your build steps. I'll continue to fiddle and see if I can find the problem.

**Comment by fivethreeo** [comment]
I tried the regular with-scss example, it used the wrong postcss version. Fixed the deps and built the example it ouputs correctly in webpack 4. So must be related to typescript, the modified plugin or webpack version.

**Comment by fivethreeo** [comment]
Great if you figure it out 😀

**Comment by speedy250** [comment]
I've found the source of `undefined` problem. I was using `const style = require('./style.module.scss');` to import styles, as this was how I set the app up many moons ago. I switched those imports to `import style from './style.module.scss'` and voila! Typescript, Tailwind, SCSS, and loadable components all playing nicely together in Razzle.
