### ISSUE TITLE
Infinite Build Loop

### ISSUE THREAD

**Issue by kumarasinghe** [jaredpalmer/razzle#1596]
## yarn run start:tsc builds in a loop

Hi,
The file watcher seems to pick up changes continuously even there is no change.
Do you have any idea how to stop this?
Thanks!

![image](https://user-images.githubusercontent.com/6898293/114717067-4d053c80-9d52-11eb-80db-433601c402ef.png)

**Comment by fivethreeo** [comment]
Need more info, os / config.

**Comment by fivethreeo** [comment]
https://www.typescriptlang.org/tsconfig/#emitDeclarationOnly

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/blob/master/examples/with-typescript/tsconfig.json#L15

**Comment by fivethreeo** [comment]
tsc is only used for typechecking

**Comment by kumarasinghe** [comment]
Hi. I'm on Ubuntu. 
For the config, I set the `baseURL` to `src`
and installed the `babel import plugin`, `razzle scss plugin
`Then I set up the project from scratch. Now it seems fine.
This seems to be a webpack bug.
If it happens again, I will attach the project here.
Thank you!

**Comment by kumarasinghe** [comment]
Hi.
I'm on Ubuntu.
For the config, I set the baseURL to src
and installed the babel import plugin, razzle scss plugin.
Then I set up the project from scratch. Now it seems fine.
Looked like it came from webpack.
If it happens again, I will attach the project here.
Thank you!
