### ISSUE TITLE
Add option to disable webpackbar

### ISSUE THREAD

**Issue by ceopaludetto** [jaredpalmer/razzle#1598]
### Current Behavior

Sometimes webpackbar is mixed with another logs and this cause a chain in console

### Desired Behavior

Hide bars in console

### Suggested Solution

I think will be very useful if we extract an option called disableWebpackbar or disableBars to avoid the use of them.

### Who does this impact? Who is this for?

All users

### Describe alternatives you've considered

A dummy webpackbar package or a custom razzle.config which finds webpackbar instance and remove them from plugin chain

**Comment by fivethreeo** [comment]
I would be willing to add this, if you do a pull request it will be possible and faster 😆

**Comment by ceopaludetto** [comment]
I'll work on it
