### ISSUE TITLE
Why are many dependencies locked to a bugfix version?

### ISSUE THREAD

**Issue by robations** [jaredpalmer/razzle#1601]
## ❓Question

In the razzle package.json, many of the dependencies are locked to very specific versions: is this out of caution, or is this by accident?

https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/package.json

For example:

```
    "deepmerge": "4.2.2",
    "dotenv": "8.2.0",
    "dotenv-expand": "5.1.0",
    "file-loader": "^4.3.0",
    "fs-extra": "9.1.0",
    "inquirer": "^7.3.3",
    "jest": "26.4.2",
    "mri": "^1.1.4",
    "null-loader": "4.0.1",
    "pnp-webpack-plugin": "^1.6.4",
    "postcss": "8.2.4",
    "postcss-load-config": "3.0.0",
    "postcss-loader": "4.2.0",
    "process": "0.11.10",
    "razzle-start-server-webpack-plugin": "4.0.4",
    "react-dev-utils": "11.0.4",
```

Also compare package.json at the root which has some different and more permissive version specs in places

https://github.com/jaredpalmer/razzle/blob/master/package.json

My usual default is to use the `^` version specifier in package.json and only use the lock file to lock dependencies. Obviously, this assumes the dependency adheres to a well-managed semantic versioning.

I have a razzle project in a mono repo and I'm ending up with multiple versions of several of these dependencies, which (for example) seems to trigger a bug in yarn when resolving the jest cli, as well as increasing install/download times in general.

**Comment by fivethreeo** [comment]
No specific reason I think, dependencies always cause trouble anyway ;) But can change theese :)

**Comment by fivethreeo** [comment]
Fixed
