### ISSUE TITLE
cra, npx, npm versions

### ISSUE THREAD

**Issue by andyzeli** [jaredpalmer/razzle#1602]
## 📖 Documentation
after banging head against wall as to why npx create-razzle-app myapp was not installing properly and resulting in "module not found" errors, i saw it was necessary for me to update npx and npm and uninstall create-razzle-app from global. 

cra has this blurb which is useful
<img width="810" alt="Screen Shot 2021-04-20 at 5 32 07 PM" src="https://user-images.githubusercontent.com/4793605/115479952-5f71f100-a1fe-11eb-9f98-959a54b39a77.png">

i had to:

npm uninstall -g create-razzle-app
`npm cache clean`
update npm and npx 

may be worth adding this.

**Comment by fivethreeo** [comment]
Fixed: https://razzlejs.org/getting-started#quick-start
