### ISSUE TITLE
CORS-related issue at client-side

### ISSUE THREAD

**Issue by mikayelgr** [jaredpalmer/razzle#1636]
### Current Behavior

In Firefox Developer Edition(latest) I get this error:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:3001/static/js/client.js. (Reason: CORS request did not succeed).
```

Here's the official explanation of this error from Mozilla.

> The HTTP request which makes use of CORS failed because the HTTP connection failed at either the network or protocol level. The error is not directly related to CORS, but is a fundamental network error of some kind. In many cases, it is caused by a browser plugin (e.g. an ad blocker or privacy protector) blocking the request.

After reading that I have tried to disable all my plugins and trying again but nothing changed.

Here's a screenshot: 

![image](https://user-images.githubusercontent.com/56165400/122521743-3dda8d80-d026-11eb-97d6-52820a1e74bf.png)

### Expected behavior

When trying to open the same URL in Microsoft Edge, everything works fine

### Reproducible example

Just used `yarn create razzle-app foo` and ran `yarn start`

### Suggested solution(s)

None

### Additional context

None

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | latest
| Razzle Plugins   | latest
| Node             | 14 LTS
| Browser          | Firefox Developer Edition(latest)
| npm/Yarn         | 1.22.5
| Operating System | Windows 10(latest)
| TypeScript       | -
| React            | 17.0.2

**Comment by fivethreeo** [comment]
Is the browser address bar at http or https?

**Comment by mikayelgr** [comment]
It may be a weird problem but I reinstalled it and everything started working fine. Thanks for your help.
