### ISSUE TITLE
problem in server rendering in razzle 

### ISSUE THREAD

**Issue by shrsltn** [jaredpalmer/razzle#1646]
based on [this article](https://finmavis.dev/blog/server-side-rendering-react-with-razzle) I implement server rendering with Compression and purgecss. unfortunately, after implementation the css and js  of my application does not load and only an ugly html is available on website. .
![image](https://user-images.githubusercontent.com/31614966/124030946-f5e73d80-da0b-11eb-875c-cb330358f683.png)

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/blob/master/examples/basic/src/server.js#L34

**Comment by fivethreeo** [comment]
If you followed that, it is a bit outdated. I think the issues are just that the css links and the script tags are wrong. Follow the method I provided in the link. If this does not fix the issue feel free to reopen this issue.
