### ISSUE TITLE
Warning: Prop `id` did not match. Server: "sas_78372_tTPoc3REu9g_NbK7AQf2B" Client: "sas_78372_zGToWwkfzFKlIF36qF6gB"

### ISSUE THREAD

**Issue by obrunodelgado** [jaredpalmer/razzle#1655]
## ❓Question

Hello, 

I need to use a random ID for an HTML element in the DOM (rendered in server side) and when the component did mount I need to interact with this element using it's identifier.

The problem is that the code will generate different IDs in the front-end and in the back-end.

How can I share a backend generated value with the frontend of a component that should appear more than once in the dom with different ids?

Frontend Code:
![image](https://user-images.githubusercontent.com/2372140/124648085-b5197980-de8e-11eb-806e-4987c1be5b5f.png)

Backend Code:
![image](https://user-images.githubusercontent.com/2372140/124648022-9d41f580-de8e-11eb-8cfc-a3b7439808ee.png)

In the nextJS I could use the _dynamic_ feature to solve the problem.

**Comment by fivethreeo** [comment]
Set the shortid on a script tag. E.g. windown.shortId = '${shortId}'; then use window.shortId in frontend

**Comment by fivethreeo** [comment]
If multiple times you somehow have to use a deterministic way to map tthe ids to the component. Maybe hash the pops except shortId?

**Comment by fivethreeo** [comment]
Answered in discussions :)
