### ISSUE TITLE
How to do Favicon?

### ISSUE THREAD

**Issue by karanmartian** [jaredpalmer/razzle#1658]
What is the proper way to include a favicon that supports various device sizes in razzle? I included the favicon.ico directly in the html as an icon of type image/x-icon but it's showing as text/html and hence browser is not able to interpret it.

**Comment by karanmartian** [comment]
Ok its showing the mime type correctly now. Not sure what i did but went for a bath and restarted server after a while. Strange. But anyway, is there any plugin that automatically generates and links the needed favicons for devices?

**Comment by fivethreeo** [comment]
https://www.npmjs.com/package/favicons-webpack-plugin
