### ISSUE TITLE
Razzle 4 causes a cache/razzle-babel-loader directory to be created full of json files

### ISSUE THREAD

**Issue by heath-freenome** [jaredpalmer/razzle#1661]
### Current Behavior

While upgrading to razzle@4 I noticed a new `cache` directory showing up when I did `npm start`. This directory seems to contain a `razzle-babel-loader` directory that has a ton of `.json` files

### Expected behavior

No new directories with growing numbers of files that will fill up my HD are created

### Reproducible example

I don't believe I need to create a repro... Is there a flag to turn this directory creation off?

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 4
| Razzle Plugins   | "babel-preset-razzle": "^4.0.5"
| Node             | 14.16
| Browser          | n/a
| npm/Yarn         | 6.14.11
| Operating System | macOS
| TypeScript       | no
| React            | 16.x

**Comment by squiddy** [comment]
You can probably just set `enableBabelCache: false` in your razzle config.

See https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/config/defaultOptions.js#L12 for reference.

**Comment by heath-freenome** [comment]
That seems to have worked
