### ISSUE TITLE
Styled-components babel plugin not working

### ISSUE THREAD

**Issue by adambisek** [jaredpalmer/razzle#1663]
## 🐛 Bug report

I cloned styled-components example from: `https://github.com/jaredpalmer/razzle/tree/master/examples/with-styled-components`

Then I added plugin to .babelrc like this:

```
[
      "babel-plugin-styled-components",
      {
        "displayName": true
      }
    ]
```

According to documentation SC: https://styled-components.com/docs/tooling#babel-plugin

### Current Behavior

Everything works, but the plugin seems to do nothing (its setup does not change output HTML).

It feels like plugin effect would be overriden by some other babel/webpack setup.

Output HTML example: ```<button class="sc-bUQyIj iTipqL">```

### Expected behavior

```<button class="Button-bUQyIj iTipqL" />```

### Reproducible example

https://github.com/adambisek/razzle-with-styled-components-bugreport

### Suggested solution(s)

Check the cause.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 4.0.5
| Razzle Plugins   | ---
| Node             | v12.16.1
| Browser          | Chrome 91.0.4472.114
| npm/Yarn         | yarn 1.22.0
| Operating System | OSX 11.4
| TypeScript       | 
| React            | 17.0.1

**Comment by fivethreeo** [comment]
Did you try https://github.com/styled-components/babel-plugin-styled-components/issues/78

**Comment by adambisek** [comment]
@fivethreeo Thanks!!

This line added to .babelrc finally worked 🎆 

```
    ["@hookydev/babel-plugin-styled-components", { "ssr": true, "displayName": true, "preprocess": false }]
```

For further people with same problem, my final .babelrc is like this:
```
{
  "presets": [
    "razzle/babel"
   ],
   "plugins": [
     "@loadable/babel-plugin",
     "babel-plugin-macros",
    ["@hookydev/babel-plugin-styled-components", { "ssr": true, "displayName": true, "preprocess": false }]
   ]
}
```

**Comment by adambisek** [comment]
SOLVED
