### ISSUE TITLE
Razzle 4 server callback

### ISSUE THREAD

**Issue by EvanCoh** [jaredpalmer/razzle#1665]
## ❓Question

Hello,

I am upgrading our application from razzle 3 to razzle 4 to fix some issues. Currently we are using C# backend and calling a callback function on server.tsx that renders the html as explained on this [tutorial](https://dev.to/pruttned/integrating-react-into-asp-net-core-using-razzle-with-all-the-goodies-like-ssr-routing-code-splitting-and-hmr-part-1-2-34g8)

On razzle 3 everything worked find and I could use 
`node -p "var fn = require('./build/server'); fn((_,x)=>console.log(x), '/');"`
and the html would show on the console (in either mode, yarn build or razzle start)

You can find the repository for razzle 3 server callback here: [https://github.com/EvanCoh/razzle3callback](https://github.com/EvanCoh/razzle3callback)

When I try the above command on razzle 4 (while running _yarn start_) after the exact same changes (repository is here: [https://github.com/EvanCoh/razzle4callback](https://github.com/EvanCoh/razzle4callback) ) I get an error:

```
node -p "var fn = require('./build/server'); fn((_,x)=>console.log(x), '/');"

sswp> Handling Hot Module Reloading
[eval]:1
var fn = require('./build/server'); fn((_,x)=>console.log(x), '/');
                                    ^

undefinedTypeError: fn is not a function
    at [eval]:1:37
    at Script.runInThisContext (node:vm:131:12)
    at Object.runInThisContext (node:vm:308:38)
    at node:internal/process/execution:77:19
    at [eval]-wrapper:6:22
    at evalScript (node:internal/process/execution:76:60)
    at node:internal/main/eval_string:23:3
```

If I run '_yarn build_' and try the above, then it works fine, but the problem is that I cant get it to work in development (= yarn start). 
Both of the above repositories were created with 
`npx create-razzle-app --example with-typescript razzle4callback` 
and 
`npx create-razzle-app@three --example with-typescript razzle3callback` 
to be as close to your examples as possible, while adding the minimum changes to achieve the callback functionality.

you can take a look at the complete code of both repositories and maybe add any commit. 

Can you tell me how to fix the error above or at least how to debug what's causing it?

**Comment by fivethreeo** [comment]
Try fn = require('./build/server').default;

**Comment by EvanCoh** [comment]
Thanks but the issue persists even so:

```
node -p "var fn = require('./build/server').default; fn((_,x)=>console.log(x), '/');"
sswp> Handling Hot Module Reloading
[eval]:1
var fn = require('./build/server').default; fn((_,x)=>console.log(x), '/');
                                            ^

undefinedTypeError: fn is not a function
    at [eval]:1:45
    at Script.runInThisContext (node:vm:131:12)
    at Object.runInThisContext (node:vm:308:38)
    at node:internal/process/execution:77:19
    at [eval]-wrapper:6:22
    at evalScript (node:internal/process/execution:76:60)
    at node:internal/main/eval_string:23:3
```

**Comment by fivethreeo** [comment]
Run build first, that is the dev build.

**Comment by EvanCoh** [comment]
Actually using webpack 5 solved the issue.
