### ISSUE TITLE
HTTPS and static sj file

### ISSUE THREAD

**Issue by rubanNg** [jaredpalmer/razzle#1670]
## ❓Question

Hello.
I am using https but the js file request goes to http and I got an error. File not found
`http: // localhost: 3001 / static / js / client.js`

but if you copy and paste into the browser and change to https
`https: // localhost: 3001 / static / js / client.js`

that works great

how to fix it

**Comment by fivethreeo** [comment]
https://razzlejs.org/docs/environment-variables

process.env.CLIENT_PUBLIC_PATH
