### ISSUE TITLE
`process.env.RAZZLE_PUBLIC_DIR` is a relative path after build

### ISSUE THREAD

**Issue by nickrttn** [jaredpalmer/razzle#1688]
### Current Behavior

Logging `process.env.RAZZLE_PUBLIC_DIR` from `src/server.tsx` in development (`razzle start`) gives me:

```sh
/Users/<user>/dev/<project>/public
```

Logging `process.env.RAZZLE_PUBLIC_DIR` from `src/server.tsx` in production (`razzle build && NODE_ENV=production node build/server.js`) gives me:

```sh
build/public
```

### Expected behavior

I would expect  `process.env.RAZZLE_PUBLIC_DIR` in my production build to be `/Users/<user>/dev/<project>/build/public`.

### Reproducible example

The behavior can be seen in the default result of `npx create-razzle-app <app-name>`

### Suggested solution(s)

Make sure that `process.env.RAZZLE_PUBLIC_DIR` is always an absolute path as detailed in the documentation.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 4.0.6 |
| Razzle Plugins   | - |
| Node             | 14.17.x |
| Browser          | Firefox 91.0 |
| npm/Yarn         | yarn 1.22.10 |
| Operating System | macOS Big Sur 11.5.2 |
| TypeScript       | Yes |
| React            | Preact |

**Comment by fivethreeo** [comment]
If you deploy to a different machine than the one you built on it must be a relative path or just use a proper env var instead. You could do process.env.MY_PUBLIC_PATH || process.env.RAZZLE_PUBLIC_PATH. But a docfix is needed. 😀

**Comment by nickrttn** [comment]
That makes sense, thanks!
