### ISSUE TITLE
Is CRACO supported? Or does razzle implement alias functionality?

### ISSUE THREAD

**Issue by steadweb** [jaredpalmer/razzle#1697]
## ❓Question

Does razzle support craco? And if not, does it extend and allow aliases which is probably the only feature I'm looking for. Ideally this https://github.com/risenforces/craco-alias#examples

**Comment by fivethreeo** [comment]
https://razzlejs.org/docs/customization#aliased-paths-modules

**Comment by steadweb** [comment]
I should have read the docs 😄 thanks @fivethreeo
