### ISSUE TITLE
Cannot import axios into razzle project using Typescript

### ISSUE THREAD

**Issue by lyndonbuckley** [jaredpalmer/razzle#1719]
## ❓Question

I'm using Typescript and I am wanting to import axios.

Whenever I add an import, the build process complains about a TypeError inside the process/browser.js module.

I am struggling to make sense of this.
If anyone is able to assist on where to start, should I look into the Babel project itself for the type definition?

Or abandon using Axios all together (highly undesired) 

Thank you in advance.

```javascript
[
  './node_modules/process/browser.js\n' +
    'Module build failed (from ./node_modules/razzle/config/babel-loader/razzle-babel-loader.js):\n' +
    'TypeError: /Volumes/code/name-of-project/node_modules/process/browser.js: Property left of AssignmentExpression expected node to be of a type ["LVal"] but instead got "BooleanLiteral"\n' +
    '    at Object.validate (/Volumes/code/name-of-project/node_modules/@babel/types/lib/definitions/utils.js:130:11)\n' +
    '    at validateField (/Volumes/code/name-of-project/node_modules/@babel/types/lib/validators/validate.js:24:9)\n' +
    '    at validate (/Volumes/code/name-of-project/node_modules/@babel/types/lib/validators/validate.js:17:3)\n' +
    '    at NodePath._replaceWith (/Volumes/code/name-of-project/node_modules/@babel/traverse/lib/path/replacement.js:170:5)\n' +
    '    at NodePath.replaceWith (/Volumes/code/name-of-project/node_modules/@babel/traverse/lib/path/replacement.js:152:8)\n' +
    '    at replaceAndEvaluateNode (/Volumes/code/name-of-project/node_modules/babel-plugin-transform-define/lib/index.js:37:12)\n' +
    '    at processNode (/Volumes/code/name-of-project/node_modules/babel-plugin-transform-define/lib/index.js:62:5)\n' +
    '    at PluginPass.MemberExpression (/Volumes/code/name-of-project/node_modules/babel-plugin-transform-define/lib/index.js:99:9)\n' +
    '    at newFn (/Volumes/code/name-of-project/node_modules/@babel/traverse/lib/visitors.js:177:21)\n' +
    '    at NodePath._call (/Volumes/code/name-of-project/node_modules/@babel/traverse/lib/path/context.js:53:20)\n' +
    '    at NodePath.call (/Volumes/code/name-of-project/node_modules/@babel/traverse/lib/path/context.js:40:17)\n' +
    '    at NodePath.visit (/Volumes/code/name-of-project/node_modules/@babel/traverse/lib/path/context.js:90:31)\n' +
    '    at TraversalContext.visitQueue (/Volumes/code/name-of-project/node_modules/@babel/traverse/lib/context.js:103:16)\n' +
    '    at TraversalContext.visitSingle (/Volumes/code/name-of-project/node_modules/@babel/traverse/lib/context.js:77:19)\n' +
    '    at TraversalContext.visit (/Volumes/code/name-of-project/node_modules/@babel/traverse/lib/context.js:131:19)\n' +
    '    at Function.traverse.node (/Volumes/code/name-of-project/node_modules/@babel/traverse/lib/index.js:82:17)\n' +
    ' @ ./node_modules/axios/lib/defaults.js 1:0-37\n' +
    ' @ ./node_modules/axios/lib/axios.js\n' +
    ' @ ./node_modules/axios/index.js\n' +
    ' @ ./src/web/func/GetDataFromAPI.ts\n' +
    ' @ ./src/web/page/Home.tsx\n' +
    ' @ ./src/web/layout/App.tsx\n' +
    ' @ ./src/web/entry/app.ts'
]
```

**Comment by lyndonbuckley** [comment]
What I can't make sense of is that Axios doesn't use process.browser anywhere inside it's source.

If I comment out the line `process.browser = true` in `node_modules/process/browser.js` the build completes, but I still cannot work why.

**Comment by lyndonbuckley** [comment]
Interestingly https://github.com/jaredpalmer/razzle/blob/ddefcf8ad81a8589b633b7fb1e95a1363bf69383/packages/razzle/config/babel-loader/razzle-babel-loader.js#L200

If I comment out this line, the project builds successfully

**Comment by fivethreeo** [comment]
`process.browser = true` becomes `true = true` I think this is a axios issue , should not set process.browser

**Comment by fivethreeo** [comment]
Hm, the babel loader needs work too. But still should not be set by axios.

**Comment by lyndonbuckley** [comment]
that's the interesting part @fivethreeo.

Axios doesn't. The only thing I can find mentioning browser is the 
```json
{
"browser": { "./lib/adapters/http.js": "./lib/adapters/xhr.js" 
}
``` 
entry in package.json 

So I am assuming that at some point this entry in package.json causes the process shim to be included, but I am very confused as to what is actually going on

**Comment by fivethreeo** [comment]
Yeah, some polyfilling going on somewhere.

**Comment by fivethreeo** [comment]
I wish next.js babel loader and babel preset was its own packages then razzle could just use those.

**Comment by lyndonbuckley** [comment]
From what I can find, the issue this that `process.browser` is being replaced with a 'true' value by razzle babel loader.

It seems to have been introduced here: https://github.com/jaredpalmer/razzle/commit/6d91a4ec2d9b5a9e5f01e22a4fce21ab1a0adcce#r57070802

Which is fine is most cases where it's use as a value
```javascript
if (process.browser) {
   //do something
}
```
becomes
```javascript
if (true) {
    //do something
}
```

However, when you look at the process module (https://github.com/defunctzombie/node-process/blob/77caa43cdaee4ea710aa14d11cea1705293c0ef3/browser.js#L156)

These lines
```javascript
process.title = 'browser';
process.browser = true;
process.env = {};
```

become

```javascript
process.title = 'browser';
true = true;
process.env = {};
```

causing the assignment TypeError;


I'm thinking I might close this, create a sample repo and lodge a bug report instead. Is that the best course of action?

**Comment by lyndonbuckley** [comment]
Closing this issue.

I ended up ignoring the process module in babel by adding the following modifyWebpackConfig callback

```javscript
module.exports = ({options: {webpackOptions}, paths}) => {
    if (webpackOptions.babelRule)
        webpackOptions.babelRule.exclude = [`${paths.appNodeModules}/process`];
    return webpackOptions;
}
```
