### ISSUE TITLE
Please support 'npx create-razzle-app .'

### ISSUE THREAD

**Issue by RobertSandiford** [jaredpalmer/razzle#1734]
I often use 'npx create-X-app .' to create a project. It's a standard feature of project creators to create the project into an /empty/ folder that already exists.

```
Uh oh! Looks like there's already a directory called .. Please try a different name or delete that folder.
```

Not a major issue, but it was weird, and non-standard when this didn't work.

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/blob/master/packages/create-razzle-app/lib/index.js#L33

**Comment by RobertSandiford** [comment]
https://github.com/jaredpalmer/razzle/pull/1744
