### ISSUE TITLE
Errors for `yarn run build` are not displayed correctly

### ISSUE THREAD

**Issue by HCanber** [jaredpalmer/razzle#1753]
### Current Behavior

When running `npm run build` and build errors, for example syntax errors, are found, these are displayed as an array.

```
Failed to compile client default build.

[
  './src/App.js\n' +
    'Module build failed (from ./node_modules/razzle/config/babel-loader/razzle-babel-loader.js):\n' +
    'SyntaxError: /Users/hakan/code/raderas/my-app/src/App.js: Missing semicolon. (13:4)\n' +
    '\n' +
    '\x1B[0m \x1B[90m 11 |\x1B[39m\x1B[0m\n' +
<<<  text deleted >>>
    '    at Object.parse (/Users/hakan/code/raderas/my-app/node_modules/@babel/parser/lib/index.js:10246:18)\n' +
    '    at parse (/Users/hakan/code/raderas/my-app/node_modules/@babel/parser/lib/index.js:14984:26)\n' +
    ' @ ./src/client.js 2:0-24 6:41-44'
]
```

### Expected behavior

Expected array to be unwrapped and printed as a string:

```
Failed to compile client default build.

./src/App.js
Module build failed (from ./node_modules/razzle/config/babel-loader/razzle-babel-loader.js):
SyntaxError: /Users/hakan/code/raderas/my-app/src/App.js: Missing semicolon. (13:4)

  11 |
  12 | export default App;
> 13 | just some text
     |     ^
<<<  text deleted >>> 
```

### Reproducible example

Just create an app, add some random characters to the end of src/App.js and build:

```sh
npx create-razzle-app my-app
cd my-app
echo 'just some text' >> src/App.js
npm run build -- --noninteractive
```

### Cause

The problem is in https://github.com/jaredpalmer/razzle/blob/v4.2.6/packages/razzle/scripts/build.js#L112-L114 where the array of build errors is used to reject the promise.

``` js
if (clientMessages.errors.length) {
  return reject(clientMessages.errors);
}
```

This "error" is catched  in https://github.com/jaredpalmer/razzle/blob/v4.2.6/packages/razzle/scripts/build.js#L186-L193 and wrapped in another array. 

``` js
err => {
  printErrors(
    `Failed to compile client ${buildName} build.`,
    [err],
    verbose
  );
  rejectBuild(buildName, 'web');
}
```

`printErrors` https://github.com/jaredpalmer/razzle/blob/v4.2.6/packages/razzle-dev-utils/printErrors.js loops over the elements and for each element logs it (in this case it logs the array)

### Suggested solution(s)
The best would be to rewrite https://github.com/jaredpalmer/razzle/blob/v4.2.6/packages/razzle/scripts/build.js so that it resolves with errors the same way it resolves with warnings.
So:
``` diff
  if (clientMessages.errors.length) {
-   return reject(clientMessages.errors);
+   return resolve({ errors} );
  }
```
And in https://github.com/jaredpalmer/razzle/blob/v4.2.6/packages/razzle/scripts/build.js#L153 :

```diff
- ({ stats, previousFileSizes, warnings }) => {
+ ({ stats, previousFileSizes, warnings, errors }) => {
+   if(errors && errors.length) {
+     printErrors(
+       `Failed to compile client ${buildName} build.`,
+       errors,
+       verbose
+     );
+     return rejectBuild(buildName, 'web');
+   }
    if (warnings.length) {
```

The same should be don in the code handling server builds as well in https://github.com/jaredpalmer/razzle/blob/v4.2.6/packages/razzle/scripts/build.js

Another option is to flatten the array in https://github.com/jaredpalmer/razzle/blob/v4.2.6/packages/razzle-dev-utils/printErrors.js#L15 (hacky)
```diff
- errors.forEach(err => {
+ errors.flat().forEach(err => {
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 4.2.6
| Node             | v14.16.0
| Operating System | OSX 11.6

**Comment by fivethreeo** [comment]
I can't quite remember, but I think webpack 4 and 5 returns errors differently. So not sure about the solution.

**Comment by HCanber** [comment]
Yes, but that's handled in printErrors, https://github.com/jaredpalmer/razzle/blob/v4.2.6/packages/razzle-dev-utils/printErrors.js#L16
So webpack 5 errors will also get wrapped in an array, and be incorrectly printed as an array.

Now: The code that catches thrown errors would remain, and continue to wrap the caught error in an array and pass it on to printErrors.

**Comment by fivethreeo** [comment]
Ah, ok. Could you do a pull request?

**Comment by HCanber** [comment]
I've submitted the PR #1754. I opted for fixing it in the least intrusive way I could.
