### ISSUE TITLE
process.env is inlined with object with only `RAZZLE_CHUNKS_MANIFEST` key in node build

### ISSUE THREAD

**Issue by batusai513** [jaredpalmer/razzle#1756]
### Current Behavior
In my `index.js` file for the node server I use process.env to access some data on runtime, after updating to v4.2.6, the bundle node file started to inline the process.env expressions with 
```js
{
  RAZZLE_CHUNKS_MANIFEST: '/path/to/build/chunks.json'
}
```
All other keys in process.env are not available anymore.
I've tracked the issue and found out [that the razzle-manifest-plugin](https://github.com/jaredpalmer/razzle/commit/1fbd10f4642fc7c0bf9318ea8b23f5d46bec339e#diff-d17b1a1987868274c98865c5ef14113ad15850efb9462c867b4058b70d269faeR79-R81) is replacing the entire `process.env` with an abject with the `RAZZLE_CHUNKS_MANIFEST` key.

### Expected behavior

Do not replace/inline `process.env` for the node bundle.

### Suggested solution(s)

I've created a PR [addressing this issue](https://github.com/jaredpalmer/razzle/pull/1755)

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 4.2.6
| Razzle Plugins   | 4.2.6
| Node             | 16.13.0
| Browser          | N/A
| npm/Yarn         | yarn@1.22.7
| Operating System | macOS catalina
| TypeScript       | 4.3.5
| React            | 17.0.2

**Comment by cnrudd** [comment]
Experiencing the same issue trying to run After.js with Razzle v4.2.6.  All env variables that I specified in .env.local are gone.
@batusai513 Thanks for tracking down the fix!

**Comment by fivethreeo** [comment]
fixed
