### ISSUE TITLE
SWC instead of babel

### ISSUE THREAD

**Issue by k4mr4n** [jaredpalmer/razzle#1757]
## ❓Question
Is there a way to replace babel with swc in razzle?
I tried replacing the babel with swc with this command and it's working but of course, this is a very hacky way, and it's not efficient.

I wonder if is there any simple solution to do since swc is much faster than babel

```
modifyWebpackConfig({
    webpackConfig, // the created webpack config
  }) {

webpackConfig.rules.forEach(rule => {
  const ident = rule.use[0].ident
  if (ident === 'razzle-babel-loader') {
   return {
     ...rule, 
     use: {
         loader: "swc-loader"
     }
   }
  }
  
  return rule
})
  }
```

**Comment by fivethreeo** [comment]
there is https://github.com/fivethreeo/razzle-plugin-swc#readme

but not updated for a while

**Comment by k4mr4n** [comment]
> there is https://github.com/fivethreeo/razzle-plugin-swc#readme
> 
> but not updated for a while

I think this plugin almost does what my code shows. there is a performance issue with this type of implementation where we are calculating the rules on each module which is a heavy task so we are running this function a lot instead of running it once.
calculating the webpack config once would improve the performance a lot. is there any limitation on why we are not doing so?

**Comment by fivethreeo** [comment]
Razzle only does it twice since we separate rules between node and web. You mean the swc loader?

**Comment by k4mr4n** [comment]
> Razzle only does it twice since we separate rules between node and web. You mean the swc loader?

I've had a console log and it was printing over and over but I checked again with a counter and you are right.
Thank you
