### ISSUE TITLE
Reactstrap not working with Razzle Server Side Rendering

### ISSUE THREAD

**Issue by kambleaa007** [jaredpalmer/razzle#1758]
### Current Behavior
Reactstrap not working with Razzle Server Side Rendering

### Expected behavior
Reactstrap working with Razzle Server Side Rendering

### Reproducible example

"error":"Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports."

### Additional context
https://stackoverflow.com/questions/69909327/reactstrap-not-working-with-razzle-server-side-rendering/69909442#69909442

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           |
| Razzle Plugins   |
| Node             |
| Browser          |
| npm/Yarn         |
| Operating System |
| TypeScript       |
| React            | 17.02

**Comment by fivethreeo** [comment]
react version?

**Comment by jleei** [comment]
same issue, react version 17.02.

**Comment by fivethreeo** [comment]
Try 17.0.1, not sure if it matters but… also try logging the import

**Comment by kambleaa007** [comment]
I have seen lots of guys facing this issue on stackoverflow

**Comment by fivethreeo** [comment]
make sure razzle transpiles reactstrap https://razzlejs.org/docs/customization#transpilation-of-external-modules

**Comment by jleei** [comment]
Found the problem. caused by new version 9.0 of reactstrap.

reactstrap's src/index.js:
```
export Container from './Container';
export Row from './Row';
export Col from './Col';
```

change to:
```
export { default as Container } from './Container';
export { default as Row } from './Row';
export { default as Col } from './Col';
```
the razzle works.

**Comment by fivethreeo** [comment]
resolved
