### ISSUE TITLE
Want to help

### ISSUE THREAD

**Issue by chrisfitkin** [jaredpalmer/razzle#176]
Hi @jaredpalmer - Thanks for the repo, I really like the routing structure.  Any feature you're looking for contributions on?

**Comment by jaredpalmer** [comment]
Yes! Transpile the server, move to react router 3, and upgrading to webpack 2 would be awesome

**Comment by chrisfitkin** [comment]
What do you mean transpile the server? Rewrite the server/index.js to es5?

**Comment by jaredpalmer** [comment]
I mean run webpack on the server too

**Comment by chrisfitkin** [comment]
Got it. I am going to take a stab at webpack 2 over the next week. Wish me
luck.

**Comment by roderik** [comment]
@chrisfitkin i happened to need webpack 2 as well, so i did that todo already: #177

**Comment by chrisfitkin** [comment]
Nice work! I've gotta check it out. Thanks

**Comment by roderik** [comment]
Server transpilation and even server hot reloading is in that same pull request.

**Comment by jaredpalmer** [comment]
See #212
