### ISSUE TITLE
SPA app with backend (server.js)

### ISSUE THREAD

**Issue by akoskm** [jaredpalmer/razzle#1762]
## ❓Question

Hi and thank you for creating Razzle! 🎉 

I'm looking for a zero-configuration tool for SPA applications including the backend, and I'm not sure if Razzle is the correct tool for this.

I already started building the app using `with-typescript` example, added some API endpoints to `server.tsx`, but now I want to remove the server-side rending part.

However, as the guide says - https://razzlejs.org/docs/single-page-applications - that'd mean also removing server.js, but that already contains my endpoints.

**Comment by fivethreeo** [comment]
Just remove the express route that renders the SSR app.

**Comment by fivethreeo** [comment]
And maybe add html-webpack-plugin to create the index.html

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/config/createConfigAsync.js#L1034

**Comment by fivethreeo** [comment]
https://razzlejs.org/docs/customization#extending-webpack

**Comment by akoskm** [comment]
I copied the index.html I found here https://github.com/jaredpalmer/razzle/blob/master/examples/basic-spa/public/index.html

to `public/index.html`. I removed the express route (`"/*"`) that was rendering the SSR app.

I added the following to my razzle.config.js:

```
module.exports = {
  modifyWebpackConfig({
    webpackConfig, // the created webpack config
    options: {
      webpackOptions, // the modified options that will be used to configure webpack/ webpack loaders and plugins
    },
  }) {
    webpackOptions.enableHtmlWebpackPlugin = true;
    return webpackConfig;
  },
};
```

the HTML file doesn't seem to be processed by webpack. I'm receiving it exactly as it's in `public/index.html`.

**Comment by fivethreeo** [comment]
You need to add the plugin to webpackConfig.plugins with webpackOptions.htmlWebpackPluginOptions

**Comment by fivethreeo** [comment]
and only with target web

**Comment by fivethreeo** [comment]
Oh, I told you wrong. Use modifyWebpackOptions

**Comment by fivethreeo** [comment]
https://razzlejs.org/docs/customization#writing-plugins

**Comment by fivethreeo** [comment]
All the hook functions supported in plugins is also supported here. We show only one function here for brevity.

**Comment by fivethreeo** [comment]
```js
module.exports = {
  modifyWebpackOptions({
    options: {
      webpackOptions, // the modified options that will be used to configure webpack/ webpack loaders and plugins
    },
  }) {
    webpackOptions.enableHtmlWebpackPlugin = true;
    return webpackOptions;
  },
};
```

**Comment by akoskm** [comment]
I made this change and also put a console log in node_modules in razzle:

```
      console.log('webpackOptions.enableHtmlWebpackPlugin', webpackOptions.enableHtmlWebpackPlugin);
      if (webpackOptions.enableHtmlWebpackPlugin) {
        config.plugins = [
          ...config.plugins,
          // Generates an `index.html` file with the <script> injected.
          new HtmlWebpackPlugin(webpackOptions.htmlWebpackPluginOptions),
        ];
      }
```

and it's set to true correctly, but `public/index.html` is still not being processed:

![image](https://user-images.githubusercontent.com/3111627/142773623-ae71ca00-e856-4edb-a8df-3feed569035f.png)

**Comment by akoskm** [comment]
I think the `<%=` is not being processed correctly for some reason.

This:

```
<!-- public/index.html -->
<!DOCTYPE html>
<html lang="">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta charset="utf-8" />
    <title>Welcome to Project Varese</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <div id="root"></div>
    <script
      src="http://localhost:3001/static/js/client.js"
      defer
      crossorigin
    ></script>
  </body>
</html>
```

works correctly but I just copy/pasted the index file that the `with-typescript` generated. I hope there's a more elegant way to do this - for example the hardcoded localhost path is probably not going to work in production.

**Comment by fivethreeo** [comment]
note modifyWebpackOptions not modifyWebpackConfig

no need to add the plugin manually

**Comment by dmitryshelomanov** [comment]
you need to add index.html to public folder

and modify razzle options

```
  options: {
    buildType: 'single-page-application' // or dynamic  SSR ? 'iso' : 'single-page-application',
  },
```

@akoskm

**Comment by akoskm** [comment]
@dmitryshelomanov if I turn this into a SPA none of the server-side routes I register with express work anymore.

@fivethreeo I set the config right now:

```
module.exports = {
  modifyWebpackOptions({
    options: {
      webpackOptions, // the modified options that will be used to configure webpack/ webpack loaders and plugins
    },
  }) {
    webpackOptions.enableHtmlWebpackPlugin = true;
    return webpackOptions;
  },
};
```

and added the index.html file from here: https://github.com/jaredpalmer/razzle/blob/master/examples/basic-spa/public/index.html but it still looks the same:

![image](https://user-images.githubusercontent.com/3111627/143534727-e5bc3781-4495-4b9c-ac6b-2a303926543a.png)

**Comment by fivethreeo** [comment]
Add it here 

https://codesandbox.io/s/elated-lucy-se4b1

and I will try figuring it out

**Comment by akoskm** [comment]
@fivethreeo this fork: https://codesandbox.io/s/bitter-shape-99dko?file=/src/real.server.js contains the changes you suggested in this Issue.

I know you suggested adding them there, but I couldn't modify your app.

Changes:
 - I added my endpoint to real.server.js
 - I remove the SSR from server.js
 - added public/index.html
 - modified razzle.config.js

**Comment by fivethreeo** [comment]
https://codesandbox.io/s/busy-forest-s43hx?file=/src/Home.js

**Comment by fivethreeo** [comment]
But if the server is only meant just for backend there is no need for webpack or razzle

**Comment by akoskm** [comment]
@fivethreeo The server is meant for backend only yes, but I'd like it to return the client app as well, bundled with webpack.
This is a monolith application - I don't want to run different apps for backend and front end and I also want hot reload on both.

**Comment by fivethreeo** [comment]
Yes, but webpack may add unneccesary code in prod on the server. But hmr is nice in dev :)

Got it working?

**Comment by akoskm** [comment]
@fivethreeo no (good thing is, I've got grahpql working!), and I'm not sure why, here's my razzle config:

```js
module.exports = {
  options: {
    enableSourceMaps: process.env.NODE_ENV !== 'production',
  },
  plugins: ['scss'],
  modifyWebpackConfig({
    env: {
      target,
      dev, // is this a development build? true or false
    },
    webpackConfig,
  }) {
    if (!dev) {
      webpackConfig.performance = Object.assign(
        {},
        {
          maxAssetSize: 100000,
          maxEntrypointSize: 300000,
          hints: false,
        }
      );
    }

    if (target === 'web' && dev) {
      webpackConfig.devServer.proxy = {
        publicPath: 'http://localhost:3001',
        context: ['/api'],
        target: 'http://localhost:3000',
      };
    }

    return webpackConfig;
  },
  modifyWebpackOptions({
    options: {
      webpackOptions, // the modified options that was used to configure webpack/ webpack loaders and plugins
    },
  }) {
    webpackOptions.enableHtmlWebpackPlugin = true;
    return webpackOptions;
  },
};
```

besides this I removed the unnecessary stuff from server and added the index.html identical to the one you have in codesandbox.

The only thing I'm not sure about is the `publicPath` argument.

**Comment by fivethreeo** [comment]
Should not be set. Performance only for web target. get any errors? You open   http://localhost:3001 in browser, right?

**Comment by akoskm** [comment]
Sorry, I was opening http://localhost:3000/ in the browser - because that's what I used to open before as well 🤦 
I'm obviously not aware of what all these configs exactly mean.

http://localhost:3001/ opens & works fine. Thank you! 🙇 

> Should not be set. Performance only for web target.

I'm not sure I understand.

---

I'm also trying to figure out what publicPath, context and target mean.

I understand that now `publicPath` is the address that serves the static content - the react app - but how my API requests are proxied to `:3000`, is `context` filtering everything that starts with `/api` and reroutes it to `:3000`?

I was looking for the webpack documentation to learn more about this but there are no examples for `publicPath` inside `proxy`: https://webpack.js.org/configuration/dev-server/#devserverproxy

**Comment by fivethreeo** [comment]
The first if, only for web target

**Comment by akoskm** [comment]
> The first if, only for web target

Without that, my GitHub CI builds were failing. When I turn it off I'm receiving these warnings:

```
Client default build compiled with warnings


asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  static/js/client.33cad39a.js (741 KiB)

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  client (984 KiB)
      static/css/client.2bbda78e.css
      static/js/client.33cad39a.js
```

and these make the GitHub build fail.

**Comment by fivethreeo** [comment]
If you remove performacnce?

**Comment by fivethreeo** [comment]
i mean for web only

**Comment by fivethreeo** [comment]
too drunk now, I will look at it tomorrow :)

**Comment by akoskm** [comment]
> If you remove performacnce?

Exactly, if remove performance this error appears.

> i mean for web only

If you meant by this, what if I leave it for web only, that also makes the problem disappear.
But I think that's OK because this is a problem for the web assets in the first place.

```
    if (!dev && target === 'web') {
      webpackConfig.performance = Object.assign(
        {},
        {
          maxAssetSize: 100000,
          maxEntrypointSize: 300000,
          hints: false,
        }
      );
    }
```

with this the build is also ✅

**Comment by fivethreeo** [comment]
resolved :)
