### ISSUE TITLE
url-loader

### ISSUE THREAD

**Issue by dmitryshelomanov** [jaredpalmer/razzle#1769]
Can i use file loader instead of url ? 
jpg builded ok but png as url

**Comment by dmitryshelomanov** [comment]
![image](https://user-images.githubusercontent.com/19505559/144038254-89ab7729-2e58-46ce-9b34-3b090a5d9080.png)
![image](https://user-images.githubusercontent.com/19505559/144038263-fd6f187e-221b-4fd9-b390-2bc513edf8fc.png)
![image](https://user-images.githubusercontent.com/19505559/144038284-bfea5dfd-fbb5-4aaa-82f7-013359068512.png)

**Comment by fivethreeo** [comment]
https://github.com/fivethreeo/razzle-nextra-clone-sort-of/blob/main/razzle.config.js#L71

Remove png from this rule and from FileLoaderExclude

**Comment by fivethreeo** [comment]
Will do a media plugin in razzle5

**Comment by dmitryshelomanov** [comment]
@fivethreeo how to do it ? `Remove png from this rule and from FileLoaderExclude`
