### ISSUE TITLE
create-react-app from documentation getting-started example is "broken"

### ISSUE THREAD

**Issue by binaryangel-noa** [jaredpalmer/razzle#1788]
### Current Behavior

created app using npx create-razzle-app my-app
When trying to start app error is received: react-router-dom/server not found from server.js

### Expected behavior

Application starts on localhost :-)

### Suggested solution(s)

Might need additional package to react-router rather then react-router-dom for server.js
Adding it resulted in another error during startup which i did not follow anymore.

++++++

Switched over to typescript and that one works, using "import { StaticRouter } from 'react-router-dom';"
However pure javascript example still does not render after that after trying to access the page.

### Your environment

node 16
mac
create-razzle-app, latest version as of 20.12.2021

**Comment by fivethreeo** [comment]
That was fixed 17 days ago. Sure create-razzle-app is not cached by npx?

**Comment by binaryangel-noa** [comment]
I just checked the version (thought its not being output in create-razzle-app after using wrong parameter first time around) and it states 4.2.8 
Where are the templates located ? I could have a look there.

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/tree/master/packages/create-razzle-app/templates/default

**Comment by binaryangel-noa** [comment]
It uses the 4.2.8 version of the template (checked the package.json). And did do another check if the problem still persists.
I noticed however that i have the version 4.3.0 of react-router-dom. Tryed to pin it to version 4.2.0 but that did not help. Other then that i did not see bigger version differences.

**Comment by fivethreeo** [comment]
https://stackoverflow.com/questions/63510325/how-can-i-clear-the-central-cache-for-npx

**Comment by fivethreeo** [comment]
template uses 5.2.0

**Comment by binaryangel-noa** [comment]
> template uses 5.2.0

Correct, but its 5.2.0 after using create react app, i was expecting a auto-update in create-react-app after seeing this.

**Comment by binaryangel-noa** [comment]
> https://stackoverflow.com/questions/63510325/how-can-i-clear-the-central-cache-for-npx

Still the same behaviour after deleting the global npx :-)

**Comment by fivethreeo** [comment]
I may have found a issue, trying to fix

**Comment by fivethreeo** [comment]
give it a try now

**Comment by fivethreeo** [comment]
Server starts now, but get a client error

**Comment by fivethreeo** [comment]
Fixed :)

**Comment by fivethreeo** [comment]
Properly fixed now
