### ISSUE TITLE
Dependency - Immer critical vulnerability risk

### ISSUE THREAD

**Issue by hoop71** [jaredpalmer/razzle#1791]
## 🐛 Bug report

Expected behavior
There are no critical issues in the repo or any underlying dependency. 

Suggested solution(s)
Would it be possible to upgrade that dependency as they have already fixed that? Or should it be addressed inside the "user's" repo with some npm resolution?

### Reproducible example

https://github.com/jaredpalmer/razzle/blob/master/yarn.lock#L8520

![image](https://user-images.githubusercontent.com/25015764/146821207-aad8e0b4-b336-4a22-8e66-20280e563e6e.png)

### Suggested solution(s)

Bump dependencies 🆙 

### Additional context

Previous similar example #1561 

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | v4.2.13
| Razzle Plugins   |
| Node             |
| Browser          |
| npm/Yarn         |
| Operating System |
| TypeScript       |
| React            |

**Comment by fivethreeo** [comment]
I really don't want to update react-dev-utils, will probably break razzle as is.

**Comment by hoop71** [comment]
> I really don't want to update react-dev-utils, will probably break razzle as is.

I see. Any advice you might give to mitigate in a local repo, or we are just waiting until this get prioritized? Happy to contribute how I can to the effort. Cheers.

**Comment by fivethreeo** [comment]
Maybe use yarn overriddes or pnpm overrides for immer. But theese are just in-dev deps. So should not be a issue.

Sendt fra min iPhone

**Comment by fivethreeo** [comment]
I am rewriting razzle in typescript and dropping webpack4. But it will take time, esp docs…

**Comment by hoop71** [comment]
OK, thanks for the quick response and feedback. Excited for what's to come. What are you replacing webpack with?

**Comment by fivethreeo** [comment]
um, sorry, dropping webpack 4 in favour of webpack 5 i mean :)
