### ISSUE TITLE
Uh, can I use ESM-only packages? react-markdown seems to have refused to work for me :(

### ISSUE THREAD

**Issue by DuCanhGH** [jaredpalmer/razzle#1800]
Right, so first of all, I just recently moved to Razzle and haven't had so many issues since then, and I just want to thank devs so much for this :D

But there seems to be an issue that I can't solve myself. I tried to install react-markdown, which is a ESM-only package. It worked fine when I installed it and used it immediately for the first time, but upon starting the dev build the next day there seems to be an issue caused by build/server.js:
module.exports = require("react-markdown");
                            ^
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\path_to_project\node_modules\react-markdown\index.js from C:\path_to_project\build\server.js not supported.

Instead change the require of index.js in C:\path_to_project\build\server.js to a dynamic import() which is available in all CommonJS modules.

Is there anything I can do to fix this? I have been researching so much but there doesn't seem to be something that may be really... helpful? I really need react-markdown, and I don't really want to use older versions which support CommonJS because there might be vulnerabilities. Thanks a lot :D I am pretty dumb, I know xD

This is the server.js file I've mentioned several times. The reference to react-markdown is at around line 20740?

https://drive.google.com/file/d/1AUYY061UYe6PSu0hyyjLt7jO6Fa6Stvj/view?usp=sharing

Once again, I just want to say I love Razzle xD

My environment: 

| Software  | Version |
| ------------- | ------------- |
| Razzle  | 4.2.13  |
| Node  | 16.13.1  |
| npm | 17.0.1  |

Oh, I forgot, yarn did seem to help a few days ago, but it caught another syntax error in react-markdown's index.js... or .ts? I forgot xD But it was this: export {uriTransformer} from './lib/uri-transformer.js' which had the error.

**Comment by fivethreeo** [comment]
https://razzlejs.org/docs/customization#transpilation-of-external-modules

**Comment by DuCanhGH** [comment]
@fivethreeo nice, will look into it tomorrow :D Thanks a bunch, I guess I shall close it here, should there not be any problem...

**Comment by DuCanhGH** [comment]
@fivethreeo so, it kind of worked, but there seems to be a lot of packages with the same issue for some reason 😅 Thanks though.

**Comment by fivethreeo** [comment]
Working on server esm support in razzle5

**Comment by DuCanhGH** [comment]
@fivethreeo nice, I'm really hyped. For now, I have to live with this so as to get react-markdown up and running, I hope that I'll not stumble upon any of those ESM-only packages 'til then xD
I guess that most of these came from react-markdown

![Screenshot (75)](https://user-images.githubusercontent.com/75556609/147827486-04e9f13a-e5d6-401d-8d73-82a3b7a71999.png)

**Comment by tehraven** [comment]
For anyone that may need it, regarding ESM modules inside your node_modules, you can lean on the default nature of the webpack rule (which is to exclude all node_modules) by using a regex look-forward match.

Say the package you need to be built within node_modules is called `@org/******`:

```ts
const theRule: RuleSetRule = {
    test: /\.(tsx?)$/,
    exclude: [/node_modules[\\/](?!(@org)[\\/])/,],
    use: [/* a webpack.RuleSetUseItem */]
};
config.module.rules.push(theRule); // push or insert where appropriate
```

This tells webpack to run this rule for ts/tsx files, ignoring node_modules *unless* it's node_modules/@org.

Hope this helps!
