### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by Nirmal-cod** [jaredpalmer/razzle#1802]
i got  this issue frequently in razzle js 
home/nirmal/Public/traversun-frontend/src/graphql/user.graphql.js:3
const DETAILED_USER = gql`
^

TypeError: _apollo_client__WEBPACK_IMPORTED_MODULE_0__.gql is not a function

  1 | import { gql } from "@apollo/client";
  2 |
> 3 | const DETAILED_USER = gql`
  4 |   fragment User on UserType {
  5 |     id
  6 |     username

    at Module../src/graphql/user.graphql.js (/home/nirmal/Public/traversun-frontend/src/graphql/user.graphql.js:3:1)
    at __webpack_require__ (/home/nirmal/Public/traversun-frontend/build/webpack:/webpack/bootstrap:748:1)
    at fn (/home/nirmal/Public/traversun-frontend/build/webpack:/webpack/bootstrap:59:1)
    at Module../src/components/useCurrentUser.js (/home/nirmal/Public/traversun-frontend/build/webpack:/src/components/useCurrentUser.js:1:1)
    at __webpack_require__ (/home/nirmal/Public/traversun-frontend/build/webpack:/webpack/bootstrap:748:1)
    at fn (/home/nirmal/Public/traversun-frontend/build/webpack:/webpack/bootstrap:59:1)
    at Module../src/admin/components/sidebar.js (/home/nirmal/Public/traversun-frontend/build/server.js:1817:85)
    at __webpack_require__ (/home/nirmal/Public/traversun-frontend/build/webpack:/webpack/bootstrap:748:1)
    at fn (/home/nirmal/Public/traversun-frontend/build/webpack:/webpack/bootstrap:59:1)
    at Module../src/admin/Admin.js (/home/nirmal/Public/traversun-frontend/build/server.js:1614:77)

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           |
| Razzle Plugins   |
| Node             |
| Browser          |
| npm/Yarn         |
| Operating System |
| TypeScript       |
| React            |

**Comment by fivethreeo** [comment]
using razzle-plugin-graphql?

**Comment by Hellenic** [comment]
Hey! I just received similar error also with Apollo. Things work on the client-side but not server-side.
`Error occurred on server-rendering TypeError: (0 , _apollo_client__WEBPACK_IMPORTED_MODULE_4__.useQuery) is not a function`

Relevant versions:
```
    "razzle": "^4.2.14",
    "razzle-dev-utils": "^4.2.14",
    "razzle-plugin-graphql": "^4.2.14",
    "razzle-plugin-manifest": "^4.2.6",
    "webpack": "^5.65.0",
    "webpack-dev-server": "^3.11.2"
    
    "babel-preset-razzle": "^4.2.14",
    "html-webpack-plugin": "^5.2.0",
    "@apollo/client": "^3.5.7",
```
I tried with webpack 4: `webpack@4.46.0 html-webpack-plugin@4.5.2` but same result. I also tried with and without `razzle-plugin-graphql` but didn't affect, as it shouldn't though.

My best guess this far is that it has something to do with `.cjs` files that Apollo has, and how it does re-exporting modules in the files. Any help greatly appreciated! :pray: 

Other versions: 
Node | 14.18.3
Browser |  Chrome
npm | 6.14.15
Operating System | Ubuntu
React | 17.0.2

**EDIT**
Just happens that I found a work-around for the issue. I downgraded `@apollo/client` to 3.4.17 and this works fine. From 3.5+ onwards there seems to be this issue. I didn't dig deeper why this is so, but anyways got it working. Not sure if it's Razzle, Webpack or Apollo-related either.

**Comment by thomasjm** [comment]
I'm hitting the exact same issue with `@apollo/client`. I would really like to upgrade to `@apollo/client` 3.5+ because of a bug I'm seeing in 3.4.17. Is it possible to update Razzle's webpack config so that it recognizes `.cjs` files?

EDIT: nvm, turns out I was wrong about the bug in 3.4.17. But it would still be nice to be able to upgrade to the 3.5 series when using Razzle :)

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/config/createConfigAsync.js#L483

https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/config/createConfigAsync.js#L488

use modifyWebpackConfig to change those

**Comment by fivethreeo** [comment]
Possibly also https://razzlejs.org/docs/customization#transpilation-of-external-modules

**Comment by fivethreeo** [comment]
If you want even more control there is

https://stackoverflow.com/questions/28026428/is-it-possible-to-create-custom-resolver-in-webpack/29859165#29859165

**Comment by thomasjm** [comment]
Thanks! I did try to get this working once the way you suggest but wasn't able to within an hour or so. I'm sure it's possible with the right settings though.

I guess what I'm asking is, could Razzle just support `.cjs` files out of the box (the same way it supports `.mjs` and others)? It seems like a common thing for people to want to use (a recent version of) Apollo to render GraphQL with their SSR apps.

**Comment by fivethreeo** [comment]
On the server side the library could be externalized incorrectly since it assumes commonjs.

**Comment by thomasjm** [comment]
Huh? Not sure I understand the problem. AFAIK Webpack can mix and match CJS and other kinds of modules. So if the server side Webpack config is set up to recognize these then shouldn't it work?

**Comment by fivethreeo** [comment]
It can, but the automatic externalizing on the server thinks .js is commonjs. So you may need to be specific about what the module system is. Hm, and maybe allow .cjs here https://github.com/jaredpalmer/razzle/blob/667537e1882a6e0e025661d6ca0b607514bec171/packages/razzle/config/createConfigAsync.js#L458

**Comment by fivethreeo** [comment]
Not all packages follows conventions for mainFields either. 😕

**Comment by thomasjm** [comment]
> you may need to be specific about what the module system is

The change I'm proposing is just "treat files with the `.cjs` extension as CommonJS". I don't quite understand the externalizing considerations but I'm hoping there isn't anything ambiguous about a `.cjs` file. If it sounds like a valid feature request I'd be happy to file one separately.

> Not all packages follows conventions for mainFields either.

FWIW, the ones for `@apollo/client` are as follows:

https://github.com/apollographql/apollo-client/blob/main/package.json#L16-L17

**Comment by fivethreeo** [comment]
Can you do a pull changing .js to .c?js here https://github.com/jaredpalmer/razzle/blob/667537e1882a6e0e025661d6ca0b607514bec171/packages/razzle/config/createConfigAsync.js#L454

**Comment by thomasjm** [comment]
Here you go: https://github.com/jaredpalmer/razzle/pull/1825

**Comment by fivethreeo** [comment]
Released fix now

**Comment by Hellenic** [comment]
Ah so it was webpack config after all, nice to know! Thank you, this works great for me! :)
