### ISSUE TITLE
Razzle hangs while compiling server

### ISSUE THREAD

**Issue by pca2** [jaredpalmer/razzle#1824]
## ❓Question

When I run `razzle start` the process hangs indefinitely on compiling the server code:
![Screen Shot 2022-02-14 at 5 31 05 PM](https://user-images.githubusercontent.com/3317560/153958206-cd227826-843e-4917-9dd5-1666f43dfbde.png)

Running `razzle build` works just fine. I can then run that code manually if I want. However, I'd really like to use the hot reloading that `razzle start` provides. Anyone encountered this before?

OS: Big Sur
nodejs: 16.13.0

**Comment by fivethreeo** [comment]
This can be a webpack config issue, try adding verbose to razzle options

**Comment by pca2** [comment]
It turned out to be a combination of `maxfiles` and `ulimit` settings. I solved it with the solution outline here: https://apple.stackexchange.com/a/169606/90627
