### ISSUE TITLE
TypeScript doesn't seem to work outside of src folder

### ISSUE THREAD

**Issue by mbzr** [jaredpalmer/razzle#1834]
## 🐛 Bug report

Using the [with-typescript](https://github.com/jaredpalmer/razzle/tree/master/examples/with-typescript) example, I have a config.ts file outside of the src folder. When i import this file inside of src/index.ts file, ts checker fails with error:

`Module parse failed: Unexpected token (1:17)\nYou may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.`

Is there any way to make this work?

### Reproducible example

https://github.com/MahmoodBawazir/razzle-with-typescript

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           |  4.2.15
| Razzle Plugins   | none
| Node             | 16.3.0
| Browser          | chrome
| npm/Yarn         | yarn
| Operating System | mac
| TypeScript       | ^4.0.3
| React            | ^17.0.1

**Comment by fivethreeo** [comment]
tried include in tsconfig?

**Comment by mbzr** [comment]
@fivethreeo i did try include. Also tried the other typescript example, played with the tsLoader options, nothing seems to work.

**Comment by fivethreeo** [comment]
try setting basedir in compileroptions to .

**Comment by mbzr** [comment]
looks like razzle doesnt allow anything other than `src` for baseUrl. and tried setting rootDir to `.` didn't work either)

**Comment by mbzr** [comment]
https://codesandbox.io/s/interesting-lederberg-oxi2lc - heres the link for codesandbox i am playing with

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/config/modules.js

https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/config/createConfigAsync.js#L292

**Comment by fivethreeo** [comment]
https://razzlejs.org/docs/customization#transpilation-of-external-modules

**Comment by mbzr** [comment]
Thank you @fivethreeo! adding this to `razzle.config.js` worked:

```
module.exports = {
  modifyWebpackOptions({
    env: {
      target, // the target 'node' or 'web'
      dev, // is this a development build? true or false
    },
    options: {
      webpackOptions, // the default options that will be used to configure webpack/ webpack loaders and plugins
    }
  }) {
    webpackOptions.babelRule.include = webpackOptions.babelRule.include.concat([
      /config/
    ]);
    return webpackOptions;
  }
}
```
