### ISSUE TITLE
Using webpack alias to newer version of Terser

### ISSUE THREAD

**Issue by RicardoGaefke** [jaredpalmer/razzle#1838]
### Current Behavior

Terser error during build if I user `?.` for possible null properties.

```
Unexpected token: punc (.) [webpack://./node_modules/ts-loader/index.js??ruleSet[1].rules[4]!./src/Components/ImageUploader/ImageUploader.tsx:36,33][static/js/client.5ece3c3b.js:23169,34]
```

If I remove the `?.` it works fine.

### Expected behavior

As I know this variable is not null compiler should work.

### Reproducible example

https://dev.azure.com/interdevme/_git/HarmonyWithNature?path=/src/WebSite/ClientApp

You can run `npm i` and `npm run build` here

### Suggested solution(s)

I updated `razzle` package and manually installed `npm i terser` in client app to try to add an alias as I have in other webpack apps. This is the start of my `razzle.config.js` file:

```
module.exports = {
  plugins: [
    'typescript',
    new MiniCssExtractPlugin(),
  ],
  buildType: 'iso-serverless',
  target: 'web',
  modify: (config, { target, dev }, webpack) => {
    config.resolve = {
      extensions: ['.ts', '.tsx'],
      alias: {
        terser: path.resolve('./node_modules/terser'),
      },
    };
```

### Additional context

I'd like to add to the app a new version of Terser so the `?.` possible null error will be gone.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 4.2.16 |
| razzle-plugin-typescript | ^4.0.5 |
| razzle-dev-utils | ^4.2.16 |
| Node             |
| Browser          |
| npm/Yarn         |
| Operating System | Windows 10 |
| TypeScript       | 4.3.5 |
| React            | 17.0.2 |

**Comment by fivethreeo** [comment]
Alias only affects bundling not webpack plugins. New terser is a esm module perhaps? Razzle4 is cjs only.

**Comment by RicardoGaefke** [comment]
No... Terser (https://www.npmjs.com/package/terser) is a part of razzle. But razzle uses an old version which does not support `?.` possible nulls during the build. I'd like to use a new version of Terser wich supports possible nulls `?.`. This is an example:

```
setImageBase64(result?.toString() as string);
```

**Comment by fivethreeo** [comment]
You need to import terser and add it to webpack plugins in modifyWebpackConfig. Razzle has no modify hook in v4. razzle cannot use esm modules in config which new terser module is.

**Comment by fivethreeo** [comment]
I am working on razzle 5, but it is slow going.

**Comment by RicardoGaefke** [comment]
Thanks, @fivethreeo ... this is the way it worked for me:

1. Added the terser-webpack-plugin: `npm install terser-webpack-plugin --save-dev`
2. Added this to modifyWebpackConfig:

```
    config.optimization = {
      minimize: true,
      minimizer: [new TerserPlugin()],
    };
```

**Comment by fivethreeo** [comment]
Ah, so new works? great :)

**Comment by RicardoGaefke** [comment]
It partially worked :-(

The npm run build worked fine but server HMR didn't work... same old error... I'll ignore the nullable properties for now...

**Comment by fivethreeo** [comment]
just skip terser in dev
