### ISSUE TITLE
Socket connection instead of rest

### ISSUE THREAD

**Issue by anton-aleksandrov** [jaredpalmer/razzle#186]
Hi

First of all, thank you for great job on this kit!

So, the question is how to use socket connection but preserve data prefetching as it is in this kit. How to do it correctly?
I've seen solutions where socket listeners were called right from containers (or Views), but this looks wrong. I want to have all listeners running right from the moment when app was loaded.
I've done it this way:
[Actions](https://github.com/jaredpalmer/react-production-starter/blob/master/common/routes/PostList/actions.js) of each route exports one more function:

```
export function listenSocket(store) {
  socket.on('posts', (payload) => {
    store.dispatch({
      type: LOAD_POSTS_SUCCESS,
      payload,
      meta: {
        lastFetched: Date.now()
      }
    })
  })
  // other listeners for this container will be here
}
```
[Constructor](https://github.com/jaredpalmer/react-production-starter/blob/master/common/routes/PostList/index.js) calls this function and passes `store` as argument:

```
export default function createRoutes (store) {
  return {
    path: 'posts',
    getComponents (location, cb) {
      require.ensure([
        './containers/PostList',
        './reducer'
      ], (require) => {
        let PostPage = require('./containers/PostList').default
        let postReducer = require('./reducer').default
        injectAsyncReducer(store, 'posts', postReducer)
        listenSocket(store) // <<< THIS IS IT
        cb(null, PostPage)
      })
    }
  }
}
```

The rest of code is the same, except instead of [this piece of code](https://github.com/jaredpalmer/react-production-starter/blob/master/common/routes/PostList/actions.js#L7-L24) i have only `socket.emit('getPosts')`.

It works, but prefetching during server-side rendering is broken. Could you help me to understand how to fix it?

**Comment by jaredpalmer** [comment]
Maybe try the `onEnter` hook instead? Not sure to be honest. I've never built anything with sockets and this kit.
