### ISSUE TITLE
SVG's inside depedencies are not processed by the url-loader

### ISSUE THREAD

**Issue by Bram-Zijp** [jaredpalmer/razzle#1886]
## 🐛 Bug report
When a dependency is using SVG with the url-loader (`import svgUrl from './example.svg`), it throws an syntax error as it's skipping the url-loader. In the reproduction I added the url-loader so you can see it doesn't get processed, even when adding a webpack rule for it.

### Expected behavior
Use identical loader setup/SVG processing when SVG's are used inside dependencies as when used in the razzle project itself. Or point out in docs how to use url-loader for SVG's when used in dependencies.

### Reproducible example

https://github.com/Bram-Zijp/razzle-svg-in-dep-error-reproduction

### Your environment
See reproduction

**Comment by fivethreeo** [comment]
https://razzlejs.org/docs/customization#transpilation-of-external-modules
