### ISSUE TITLE
Release notes are very cumbersome when doing version comparisons

### ISSUE THREAD

**Issue by speedy250** [jaredpalmer/razzle#1902]
## 📖 Documentation
As the title states, going through the project's release notes are very cumbersome. If moving up a few minor versions, it is required to sift through 7 pages of notes, as each version bump dumps 1-2 pages of release notes with every plugin that razzle has. This makes comparing changes across versions very difficult!

Is there a way to lump all the plugin updates into the main release note?

**Comment by fivethreeo** [comment]
https://github.com/changesets/changesets/issues/683

**Comment by speedy250** [comment]
Closing as duplicate, thanks @fivethreeo
