### ISSUE TITLE
plugin options are coming to be undefined

### ISSUE THREAD

**Issue by bhavin-a** [jaredpalmer/razzle#1909]
### Current Behavior

In the `modifyWebpackOptions` and `modifyWebpackConfig`, I want to update the plugin options but they are coming to be undefined.  
<img width="552" alt="image" src="https://user-images.githubusercontent.com/15359575/215168550-65f803ca-7324-4ad5-b238-988c5eac9940.png">

### Expected behavior

Plugin options should have come

### Additional context

I want to specifically toggle the `useBabel` of `razzle-plugin-typescript` plugin **conditionally** but unable to do so.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | 4.0.5
| Razzle Plugins   | razzle-plugin-compression, razzle-plugin-typescript
| Node             | v14.17.3
| Browser          | Chrome
| npm/Yarn         | yarn
| Operating System | MacOS
| TypeScript       | 3.9
| React            | 16.x

**Comment by bhavin-a** [comment]
Hi @fivethreeo , razzle has been working so well but recently, there are a few questions I need help with. I see the last update on this repo was around Oct. Are there any plans for improvements? Or active development in this repo? I might be missing something. Thanks!

**Comment by fivethreeo** [comment]
Razzle is dead, I started wazzle, but i am the only dev there aswell. So no progress there. Also there is rspack and turbopack.

**Comment by bhavin-a** [comment]
This is sad news @fivethreeo, I think I missed this announcement somewhere 😢 

So is it ok to say that devs finding a few things difficult in Razzle now (like perf, version upgrades, etc) should right away look for the above-suggested alternatives? So that I don't keep visiting this repo every day to see if any activity happened 🙈?

**Comment by fivethreeo** [comment]
Correct.
