### ISSUE TITLE
Nested Layouts for routes

### ISSUE THREAD

**Issue by alex-ald** [jaredpalmer/razzle#197]
I love the boilerplate but am having issues having nested layouts for instances

```
export default (
  <Route path='/' component={BaseLayout}>
    <Route path='auth' component={Auth} />
    <Route component={AuthenticatedLayout}>
      <Route path="dashboard" component={Dashboard} />
      <Route path='Inbox' component={Inbox} />
    </Route>
  </Route>
)
```

In this instance, you can see that the authenticated routes have another layout applied to it. But this boilerplate defines a different way to construct your routes such as 

```
export default function createRoutes (store) {
  return {
    path: 'posts',
    getComponents (location, cb) {
      require.ensure([
        './containers/PostList',
        './reducer'
      ], (require) => {
        let PostPage = require('./containers/PostList').default
        let postReducer = require('./reducer').default
        injectAsyncReducer(store, 'posts', postReducer)
        cb(null, PostPage)
      })
    }
  }
}
```

So I would love assistance on this topic!

**Comment by lewis-elliott** [comment]
Did you get anywhere with this? I've tried something similar myself and couldn't get it working. I don't think redial can do data fetching on nested routes. 

I tried this:

**routes/postList/index.js:**

`
export default function createRoutes (store) {
  return {
    path: 'posts',
    getComponents (location, cb) {
      require.ensure([
        './containers/PostList',
        './reducer'
      ], (require) => {
        let PostPage = require('./containers/PostList').default
        let postReducer = require('./reducer').default
        injectAsyncReducer(store, 'posts', postReducer)
        cb(null, PostPage)
      })
    },
    getChildRoutes(partialNextState, cb) {
      path: '23',
      console.log('get child routes of parent path')
      require.ensure([], (require) => {
        cb(null, [
          require('./routes/Test').default,
        ])
      })
    },
  }
}
`
Then: 

**routes/postList/routes/index.js:**

`export default function createRoutes (store) {
  return {
    path: '/test',
    getComponents (location, cb) {
      console.log('get comp of nested route test')
      require.ensure([
        './containers/Test',
        './reducer'
      ], (require) => {
        let testPage = require('./containers/Test').default
        let testReducer = require('./reducer').default
        injectAsyncReducer(store, 'tests', testReducer)
        cb(null, testPage)
      })
    }
  }
}`

In this case Test Component doesn't use redial. This routing still doesn't work.

It would be nice to get a few things cleared up regarding how this type of routing would work with Redial and code splitting.

**Comment by jaredpalmer** [comment]
Not redial cannot do nested fetching. `[redux-taxi](https://github.com/nyt/redux-taxi)` and does.

**Comment by lewis-elliott** [comment]
@jaredpalmer Even without redial hooks on nested components the above example does not work, is this expected if the parent component is using redial?

**Comment by jaredpalmer** [comment]
```js
getChildRoutes(partialNextState, cb) {
      path: '23',
      console.log('get child routes of parent path')
      require.ensure([], (require) => {
        cb(null, [
          require('./routes/Test').default,
        ])
      })
    },
```

this isn't valid js btw.

**Comment by jaredpalmer** [comment]
your issue doesn't have to do with redial, but how your defining your routes.
`getChildRoutes` should require another route file(s). `getComponents` should require components / reducers for the current route.

**Comment by jaredpalmer** [comment]
See the React-router v3 mega app for another example

**Comment by lewis-elliott** [comment]
With this code the route gets hit:

**postlist/index.js**

```javascript
export default function createRoutes (store) {
  return {
    path: 'posts',
    getComponents (location, cb) {
      require.ensure([
        './containers/PostList',
        './reducer'
      ], (require) => {
        let PostPage = require('./containers/PostList').default
        let postReducer = require('./reducer').default
        injectAsyncReducer(store, 'posts', postReducer)
        cb(null, PostPage)
      })
    },
    getChildRoutes(partialNextState, cb) {
      console.log('get child routes of parent path')
      console.log('store: ' + store)
      require.ensure([], (require) => {
        cb(null, [
          require('./routes/Test').default(store),
        ])
      })
    },
  }
}
```

**postlist/routes/test/index.js**

```javascript
export default function createRoutes (store) {
  return {
    path: 'test',
    getComponents (location, cb) {
      console.log('get comp of nested route test')
      require.ensure([
        './containers/Test',
        './reducer'
      ], (require) => {
        let testPage = require('./containers/Test').default
        let testReducer = require('./reducer').default
        injectAsyncReducer(store, 'tests', testReducer)
        cb(null, testPage)
      })
    }
  }
}
```

![screen shot 2017-01-25 at 1 51 36 pm](https://cloud.githubusercontent.com/assets/9560692/22310956/0c515eea-e306-11e6-9713-d40a8be45563.png)

![screen shot 2017-01-25 at 1 52 17 pm](https://cloud.githubusercontent.com/assets/9560692/22310960/0fa03ca6-e306-11e6-8dc1-fbd646273d6c.png)

The getChildRoute function gets hit but the **./routes/Test** is not rendered. This page has no redial hooks on it but it still does not render on the client or the server, the parent page **/posts** is shown.

**Comment by alex-ald** [comment]
I just ended up giving up on the routing technique used in this boilerplate. I removed async reducers and just added them in normally then went back to the conventional way of react router.

**Comment by lewis-elliott** [comment]
I managed to get this working today, do you want me to post my findings ?

**Comment by jaredpalmer** [comment]
Yes please. Add to the knowledge base!

**Comment by alex-ald** [comment]
@lewis-elliott yes!
