### ISSUE TITLE
Why are no components extending React.component?

### ISSUE THREAD

**Issue by adriaanbalt** [jaredpalmer/razzle#208]
Is this for performance purposes?  Why not use `mapDispatchToProps` ?

**Comment by wedneyyuri** [comment]
As far as I know `mapDispatchToProps` is only needed when our components dispatch actions, I think it's not the case here.

Arrow functions isn't the most performant solution, but (in our case) the most readable.

**Comment by adriaanbalt** [comment]
@wedneyyuri  Sure, the app is only handling front loads of information.  However, I can imagine countless instances where a component will dispatch an action.  More often than not some form of interaction will happen to cause the loading of more data or opening a mobile navigation or send an email, etc.

The way I was able to get this to work seems contrary to other React builds I've made.  See below for a code snippet.

Version of APP within @jaredpalmer's `react-production-starter`
```js
import React from 'react'
import { connect } from 'react-redux'
import { bindActionCreators } from 'redux'
import { provideHooks } from 'redial'
import { StyleSheet, css } from 'aphrodite'

import { initialRequest, someAction } from 'common/shell/actions'
import { getInitialData } from 'common/shell/reducer'

const redial = {
  fetch: ({ dispatch }) => {
    // doesn't seem to fire on initial load
    dispatch(initialRequest())
  },
  defer: ({ dispatch }) => {
    // defer is the only way to make the request on initial load due to client/index.js Line: 71
    dispatch(initialRequest())
  }
}

const mapStateToProps = state => {
  return ({
    someData: getInitialData(state)
  })
}
const mapDispatchToProps = dispatch => bindActionCreators({
  someAction
}, dispatch)

const App = ({ children, someData, someAction }) => {
  //click handler that dispatches an action
  const clickButton = () => someAction()

  return (
    <div className={css(styles.root)}>
      {
        someData //data from the initial requeset
        &&
        <h1>someData.title</h1>
      }
      <button onClick={clickButton}>Click</button>
      {children}
    </div>
  )
}

const styles = StyleSheet.create({
  root: {
    maxWidth: 700,
    color: '#000',
    margin: '2rem auto',
    padding: '0 1rem'
  },
})

export default provideHooks(redial)(connect(mapStateToProps, mapDispatchToProps)(App))
```

Version of a "traditional" APP (note the use of `this.props` and `extends React.Component`)
```js
import React from 'react'
import { connect } from 'react-redux'
import { bindActionCreators } from 'redux'
import { provideHooks } from 'redial'
import { StyleSheet, css } from 'aphrodite'

import { initialRequest, someAction } from 'common/shell/actions'
import { getInitialData } from 'common/shell/reducer'

const redial = {
  fetch: ({ dispatch }) => {
    // doesn't seem to fire on initial load
    dispatch(initialRequest())
  },
  defer: ({ dispatch }) => {
    // defer is the only way to make the request on initial load due to client/index.js Line: 71
    dispatch(initialRequest())
  }
}

const mapStateToProps = state => {
  return ({
    someData: getInitialData(state)
  })
}
const mapDispatchToProps = dispatch => bindActionCreators({
  someAction
}, dispatch)

class App extends React.Component {
  //click handler that dispatches an action
  clickButton = () => this.props.someAction()

  render() {
    return (
      <div className={css(styles.root)}>
        {
          this.props.someData //data from the initial requeset
          &&
          <h1>this.props.someData.title</h1>
        }
        <button onClick={this.clickButton}>Click</button>
        {this.props.children}
      </div>
    )
  }
}

const styles = StyleSheet.create({
  root: {
    maxWidth: 700,
    color: '#000',
    margin: '2rem auto',
    padding: '0 1rem'
  },
})

export default provideHooks(redial)(connect(mapStateToProps, mapDispatchToProps)(App))
```

Is there any reason why I would use the 1st version instead of the 2nd?  Or are they the same?

**Comment by adriaanbalt** [comment]
If one is to `extend React.component` the class would inherit the React lifecycle functions, such as `ComponentDidMount()` etc.  Maybe inheriting is not necessary because of `redial`?  I recognize the benefit of fetching the data before rendering the page, it will reduce the number of comparisons React must perform to generate the virtual DOM, but is this the only benefit?  Or are there others that I'm unaware of?  And if this is the only benefit, couldn't one restrict the render by manipulating `shouldComponentUpdate()` to `return false` in cases that one does not want to trigger a `render()`?  Maybe I'm over thinking it and this boilerplate is to be used for something entirely different, but then my question is "what is this entirely different thing that it is to be used for, if not for building production apps?"

PS:  I like this boilerplate's structure and multitude of other benefits, just trying to understand if I'm writing my containers/components as they should be written.

**Comment by wedneyyuri** [comment]
Hi @adriaanbalt, as I said before, arrow functions aren't the most performant solution but probaly the most readable when the components are simple (just render basic html structures). Your example isn't wrong (my coments below).

In general, as arrow functions are just syntax sugars for React Component I use this version to develop simple components (no handlers, no logic) and I extend React.PureComponent (https://facebook.github.io/react/docs/react-api.html#react.purecomponent) to develop complex components (handlers, logic, control render lifecycles, etc...). 

If you want to stick using the same syntax in the whole project I advise you to use the 2nd version.

```javascript

import React from 'react'
import { connect } from 'react-redux'
import { bindActionCreators } from 'redux'
import { provideHooks } from 'redial'
import { StyleSheet, css } from 'aphrodite'

import { initialRequest, someAction } from 'common/shell/actions'
import { getInitialData } from 'common/shell/reducer'

const redial = {
  fetch: ({ dispatch }) => {
    // doesn't seem to fire on initial load, 
    // because it was already done in server side and stored in state
    dispatch(initialRequest())
  },
  defer: ({ dispatch }) => {
    // defer is the only way to make the request on initial load due to client/index.js Line: 71
    dispatch(initialRequest())
  }
}

const mapStateToProps = state => {
  return ({
    /*
    This works great, but there is a drawback: "someData" is calculated every 
    time the component is updated. If the state tree is large, or the 
    calculation expensive, repeating the calculation on every update 
    may cause performance problems.
    See https://github.com/reactjs/reselect#motivation-for-memoized-selectors
    */    
    someData: getInitialData(state)    
  })
}
const mapDispatchToProps = dispatch => bindActionCreators({
  someAction
}, dispatch)

const App = ({ children, someData, someAction }) => {
  // WARNING: It's can be a problem because "clickButton" will have 
  // a diferent value during every render phase. 
  // See http://stackoverflow.com/questions/39260595/event-handlers-in-react-stateless-components
  const clickButton = () => someAction()

  return (
    <div className={css(styles.root)}>
      {
        someData //data from the initial requeset
        &&
        <h1>someData.title</h1>
      }
      <button onClick={clickButton}>Click</button>
      {children}
    </div>
  )
}

const styles = StyleSheet.create({
  root: {
    maxWidth: 700,
    color: '#000',
    margin: '2rem auto',
    padding: '0 1rem'
  },
})

export default provideHooks(redial)(connect(mapStateToProps, mapDispatchToProps)(App))

```

**Comment by wedneyyuri** [comment]
It's how I would write your component (binding event handlers on constructor):

```javascript
class App extends React.PureComponent {
  constructor() {
    // onClickButton will not change
    this.onClickButton = this.onClickButton.bind(this);
  }

  onClickButton(evt) {
    evt.preventDefault();
    this.props.someAction('It was clicked!');
  }

  render() {
    const { children, someData } = this.props;
    return (
      <div className={css(styles.root)}>
        {someData && <h1>{someData.title}</h1>}
        <button onClick={this.onClickButton}>Click</button>
        {children}
      </div>
    )
  }
}
```

**Comment by wedneyyuri** [comment]
> If one is to extend React.component the class would inherit the React lifecycle functions, such as ComponentDidMount() etc. Maybe inheriting is not necessary because of redial?

Arrow functions are syntax sugars, it will result the same effect:

```javascript
const App = (children) => <div>{children}</div>;

class App extends React.Component {
    render() {
        return <div>{children}</div>;
    }
}
```

As you can see, the 2nd version is more verbose and more robust.


> I recognize the benefit of fetching the data before rendering the page, it will reduce the number of comparisons React must perform to generate the virtual DOM, but is this the only benefit? Or are there others that I'm unaware of? And if this is the only benefit, couldn't one restrict the render by manipulating shouldComponentUpdate() to return false in cases that one does not want to trigger a render()? Maybe I'm over thinking it and this boilerplate is to be used for something entirely different, but then my question is "what is this entirely different thing that it is to be used for, if not for building production apps?"

First of all, fetching the data before rendering the page (in most cases) will not reduce the number of comparisons React must perform to generate the virtual DOM. The basic idea behind server side rendering is show content before executing any javascript code (http://andrewhfarmer.com/server-side-render/):
 * Rendering server-side helps search engine crawlers find your content (although sometimes Google can find your content without SSR).
 * SSR will usually increase performance (page load) for your app, but not always.
 * Using SSR will increase the complexity of your application, which means less time working on other features and improvements.

The basic idea behind redial is to ensure that all data for a set of routes is prefetched on the server before attempting to render (https://github.com/markdalgleish/redial#why).

**Comment by adriaanbalt** [comment]
@wedneyyuri apart from Arrow Functions, which are getting decompiled by Babel anyway, what benefits are there to not using `extend React.Component`?  None of the classes within this project use this inheritance.  Although I am able to create App in virtually the same way, the 2nd version allows me to use the life cycle functions `componentWillMount`, `componentDidMount` etc..  Why would @jaredpalmer not use this inheritance across his classes?  If this starter is not for building apps with lifecycle, then what apps is it supposed to be used for?

Apart from this, thank you for the references to `Reselect` and how to bind the handlers in the constructor.  I'll incorporate these features into `App`.

**Comment by adriaanbalt** [comment]
came across this article... https://medium.com/dailyjs/react-is-slow-react-is-fast-optimizing-react-apps-in-practice-394176a11fba
