### ISSUE TITLE
Multiple react-router onEnter calls triggered.

### ISSUE THREAD

**Issue by lewis-elliott** [jaredpalmer/razzle#210]
Related to this [issue with redial](https://github.com/markdalgleish/redial/issues/44). When you add an onEnter function to any of the routes its called twice upon entering that route.

**Comment by lewis-elliott** [comment]
I have a fix for this which involves removing match from the client. Does anyone want me to submit a PR?

**Comment by jaredpalmer** [comment]
go for it
