### ISSUE TITLE
Error while running yarn start

### ISSUE THREAD

**Issue by fortezhuo** [jaredpalmer/razzle#260]
I have installed razzle and create new app using razzle-init, and execute yarn start
Error occur like below information :

 WAIT  Compiling...

 ERROR  Failed to compile SERVER with 1 errors

Error in multi webpack/hot/poll?300 ./server/index.js
Module not found: Can't resolve '/Users/forte/Workspace/razzle-test/server/index.js' in '/Users/XXXX/Workspace/razzle-test'

 @ multi webpack/hot/poll?300 ./server/index.js

 ERROR  Failed to compile CLIENT with 1 errors

Error in multi ./~/react-hot-loader/patch.js (webpack)-dev-server/client?http://0.0.0.0:3001 (webpack)/hot/dev-server.js ./client/index.js
Module not found: Can't resolve '/Users/XXXX/Workspace/razzle-test/client/index.js' in '/Users/forte/Workspace/razzle-test'

 @ multi ./~/react-hot-loader/patch.js (webpack)-dev-server/client?http://0.0.0.0:3001 (webpack)/hot/dev-server.js ./client/index.js

**Comment by jaredpalmer** [comment]
try with 0.4.2

**Comment by jaredpalmer** [comment]
needed to update razzle's template to use `latest` instead of `*`

**Comment by fortezhuo** [comment]
problem solved with switching to latest.
