### ISSUE TITLE
Redux, react-production-starter

### ISSUE THREAD

**Issue by designspin** [jaredpalmer/razzle#261]
This is not really an issue. 

Previously I was using react-production-starter, which allowed me to go quite far with a starter that included redux. Upon searching for react-production-starter, I land on Razzle, which looks great. This does not include Redux, any plans to include Redux? Or to add a recipe for using Redux?

**Comment by jaredpalmer** [comment]
Yup can add a Redux example. I am using razzle, redux, react-router 4 in a production app right now. Shouldn't be too tough to pull it out.

**Comment by jaredpalmer** [comment]
To answer your other question, there are no plans to include redux in the base template. In fact, I may even drop `react-router` from it and just make the template the minimum viable razzle application. 

That being said, once the redux example is done, you'll be able to bootstrap a new app from that with just two commands.

**Comment by designspin** [comment]
Thanks Jared for your great hard work. I understand keeping the base to a minimum. I think really I just need to brush up on some of these JS libraries that seem to all move so fast!
