### ISSUE TITLE
HMR not working

### ISSUE THREAD

**Issue by kireerik** [jaredpalmer/razzle#263]
I am getting the following error:
> XMLHttpRequest cannot load http://localhost:81/7c81b80bb4037989f99f.hot-update.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access.

Plus the following warning:
> [HMR] Update failed: Error: Manifest request to http://localhost:81/7c81b80bb4037989f99f.hot-update.json timed out.
>     at XMLHttpRequest.request.onreadystatechange (http://localhost:81/static/js/client.js:38:22)
> (anonymous) @ dev-server.js?b7b7:37

**Comment by jaredpalmer** [comment]
This is related to these issues... patching now.

https://github.com/webpack/webpack-dev-server/issues/533

https://github.com/webpack/webpack-dev-server/issues/883

**Comment by jaredpalmer** [comment]
@kireerik Pushing a release now. Thanks for catching this!

**Comment by kireerik** [comment]
@jaredpalmer Thank you so much for the extreme fast resolution! You are welcome!

I have also noticed something which is may related to the [previous release](https://github.com/jaredpalmer/razzle/releases/tag/v0.4.3)'s [referred issue](https://github.com/webpack/webpack-dev-server/issues/882).

http://localhost:3000/ works, but http://0.0.0.0:3000/ doesn't (ERR_ADDRESS_INVALID response) with the default (no) config.
On http://localhost:3000/ http://0.0.0.0:3001/static/js/client.js (which doesn't works too) is used instead of http://localhost:3001/static/js/client.js. Is this related to Windows or this is the expected behavior?

**Comment by jaredpalmer** [comment]
If you read through the errors above

**Comment by kireerik** [comment]
I am sorry for the misunderstanding. Maybe I should have opened a separate issue.

For example if I start the [basic example](https://github.com/jaredpalmer/razzle/tree/master/examples/basic) and visit http://localhost:3000/, than I am getting the following error message in the browser's console:
> Failed to load resource: net::ERR_ADDRESS_INVALID [client.js](http://0.0.0.0:3001/static/js/client.js)

Note: Also I need to start it twice, because it [doesn't works for the first time](https://github.com/jaredpalmer/razzle/issues/259).

I think the new title of this issue is inappropriate, HMR was simply not working regardless of host before.

**Comment by kireerik** [comment]
Using [`0.0.0.0` as the host can be ambiguous](https://superuser.com/questions/536156/how-do-i-get-0-0-0-0-to-resolve-to-localhost-when-browsing-a-url-that-contains-0/536198#536198). So maybe `127.0.0.1` should be used by default instead of `0.0.0.0`.

What do you think?

**Comment by jaredpalmer** [comment]
@kireerik Try version 0.5.0 (just released)

**Comment by kireerik** [comment]
Using the default host setting still produces the same issue under Windows.

Also [this new release](https://github.com/jaredpalmer/razzle/releases/tag/v0.5.0) introduced a new issue. I am getting this error if I start a server in development mode:
> GET http://127.0.0.1:801/static/js/client.js net::ERR_CONNECTION_REFUSED localhost/:1

Port **801** is used instead of 81 and non of them are available.

It still works fine in production mode.

**Comment by jaredpalmer** [comment]
try 0.5.2

should fix both of these.

**Comment by jaredpalmer** [comment]
K no more oops... I think 0.5.2 solved this

**Comment by kireerik** [comment]
Unfortunately not, I still getting the same issue.

**Comment by jaredpalmer** [comment]
Something is going on with lerna, because I have it working when I run npm link, but not when I publish to npm .  Hold on...

**Comment by jaredpalmer** [comment]
@kireerik are you sure about 0.5.2? This seems to be fixed on our side. Can you confirm on Windows?

**Comment by kireerik** [comment]
Well, this newly introduced bug seems kind of fixed for me as well. Now I only experience issues if I modify the port. So for example I have changed it from 127.0.0.1 to default, than back and the default is get stuck.

**Comment by kireerik** [comment]
Now, I can confirm that the newly introduced bug is fixed. What I have experienced can be some sort of caching related thing. It works now.

However using the default port still works the same way under non Unix-like systems. I think it won't work unless the default setting is changed to 127.0.0.1 as you can [read more about this here](https://superuser.com/questions/536156/how-do-i-get-0-0-0-0-to-resolve-to-localhost-when-browsing-a-url-that-contains-0/536198#536198):
> Linux or a specific browser on linux happens to silently correct it to 127.0.0.1... awesome. But as you've found out, that's not a universal thing.

**Comment by jaredpalmer** [comment]
Yup.

What's your razzle.config.js look like?

On examples without razzle.config.js, caching issue doesn't exist as far as I can tell. You can see by comparing basic and typescript with .env. However, I agree. Something is happening that the port is getting cached.

**Comment by jaredpalmer** [comment]
Quick work around to PORT issue is to modify your package.json with `rm -rf build && razzle start`. 
Need to investigate more.

**Comment by kireerik** [comment]
I think it is might worth to consider changing the default setting in terms of interoperability and new comers.

It works fine, maybe I have passed by something or can be related to the [initial dev build issue](https://github.com/jaredpalmer/razzle/issues/259).

I think we can close this issue by now.

I have noticed that you care about small details. For example you have [fixed the port printing](https://github.com/jaredpalmer/razzle/commit/4a15294507b73320f7ffcf126310bf0f88289781) in the examples. I have noticed this earlier, but didn't submitted it as an issue. I didn't think it was a big deal.
Do you welcome minor issue submissions? If so, I can point at some potential minor issues.

**Comment by jaredpalmer** [comment]
@kireerik yes please! PRs welcome.

**Comment by jaredpalmer** [comment]
So should I change default to host `localhost` or `127.0.0.1`?

**Comment by kireerik** [comment]
I think it is not a big deal, because it can be changed with configuration. However `127.0.0.1` is a better default setting in my opinion.
