### ISSUE TITLE
Add `razzle test` command

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/razzle#270]

**Comment by auser** [comment]
Yes... this would be nice. I'm struggling to get my tests running. 

More specifically, my `jest` command explodes (when using typescript) on the line: 

```js
const assets = require(process.env.RAZZLE_ASSETS_MANIFEST);
```

The error (specifically) is `TypeError: Cannot read property '0' of undefined`, which appears to me to be trouble pulling off `RAZZLE_ASSETS_MANIFEST`.

**Comment by auser** [comment]
For future:

I solved this locally by using this line:

```js
const assets = env === 'test' ? {} : require(process.env.RAZZLE_ASSETS_MANIFEST)
```

**Comment by jaredpalmer** [comment]
Why are you testing the server with jest in the first place?

**Comment by auser** [comment]
Why not? It's a fine test runner and then server-side and client-side are matched with technology. Plus jasmine (the assertion framework) doesn't care. I'm interested to know what the opposition viewpoint is...

**Comment by jaredpalmer** [comment]
I guess I could have been a bit more specific here....

I love Jest for testing Node API's. It's fantastic.

My suggestion, however, is that you _not_ use Razzle to serve your API / do things with your DB directly. You should do that on a separate server and communicate with it over HTTP or GraphQL.

**Comment by auser** [comment]
I am... server-side and client-side. 
What do you for your mode later? I've been experimenting with sequelize, knex, and typeorm (typescript)
Any preference for one or another, out of curiosity. 
		

		Get Outlook for iOS
	





On Sun, May 28, 2017 at 12:48 PM -0700, "Jared Palmer" <notifications@github.com> wrote:












I guess I could have been a bit more specific here....


I love Jest for testing Node API's. It's fantastic.


My suggestion, however, is that you not use Razzle to serve your API / do things with your DB directly. You should do that on a separate server and communicate with it over HTTP or GraphQL.

**Comment by jaredpalmer** [comment]
We use Mongo or Dynamo for almost everything. While we don't use Node.js on the backend in production anymore, on some of my Node.js side projects, I use my own DAO layer that looks like this: https://gist.github.com/jaredpalmer/5e5617f2aac34c468938d1728906f16e .

**Comment by auser** [comment]
Oh interesting. What do you use for your backend?
		

		Get Outlook for iOS
	





On Sun, May 28, 2017 at 1:12 PM -0700, "Jared Palmer" <notifications@github.com> wrote:












We use Mongo or Dynamo for almost everything. While we don't use Node.js on the backend in production anymore, on some of my side projects, I use my own DAO layer that looks like this: https://gist.github.com/jaredpalmer/5e5617f2aac34c468938d1728906f16e .
