### ISSUE TITLE
Implement Service Worker caching

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/razzle#276]
https://reason.nyc uses this via `razzle.config.js`. It loads a google font, but even so, here are lighthouse scores:

<img width="662" alt="screenshot 2017-06-01 10 22 53" src="https://cloud.githubusercontent.com/assets/4060187/26684250/6a603c74-46b4-11e7-83a4-4d4136c485fb.png">

**Comment by Grsmto** [comment]
Hey Jared,
What is blocking this issue to be done? Can we help?
Thanks.

**Comment by lukePeavey** [comment]
I was wondering about this too.

**Comment by kanzelm3** [comment]
I am also wondering about this, would love to get this implemented.

**Comment by Metnew** [comment]
`OfflinePlugin` addition to client's webpack config could resolve this issue.
In the case SW is included by default, it could become a problem to exclude SW generation from webpack config without excluding plugins inside `razzle.config.js`. 
Will SW be an optional thing?

**Comment by anz000** [comment]
Any workaround for this yet?
