### ISSUE TITLE
How to deploy?

### ISSUE THREAD

**Issue by ThekhoN** [jaredpalmer/razzle#280]
I tried to deploy a simple counter app (based-off the redux example) with some actual API call to get and update the count.
https://github.com/ThekhoN/razzle-react-redux-starter
Correct me if i'm wrong, the only requirement for deployment is the /build folder after running 
`npm run build`?
When i try to do `node server.js`, it keeps throwing module errors : "Cannot find module 'react'" etc.
Can some one explain how to resolve this so that i can safely deploy the example?
Thanks.

**Comment by jaredpalmer** [comment]
Hey so you def do not want to check in the build directory to git. So you should add that back to `gitignore`. Where are you trying to deploy?

**Comment by ThekhoN** [comment]
Thanks for getting back. i will remove it.
I actually intend to deploy it on a droplet on Digital Ocean. 
Meanwhile I had tried to deploy it on heroku, using the git, but it failed.
https://devcenter.heroku.com/articles/git

**Comment by jaredpalmer** [comment]
@ThekhoN I went ahead and made the PR's to your example repo so you can deploy to Heroku.

**Comment by jaredpalmer** [comment]
So the issue had to do with how Heroku forces you to use their `process.env.PORT`, which is only set after the heroku's build completes. 
These are changes you should make for Heroku: https://github.com/ThekhoN/razzle-react-redux-starter/pull/3

Can confirm that this works... https://razzle-redux-starter.herokuapp.com/

**Comment by ThekhoN** [comment]
Thanks so much for taking the time to make this work :)
