### ISSUE TITLE
Prettier by default?

### ISSUE THREAD

**Issue by ericclemmons** [jaredpalmer/razzle#281]
I know you loves some single quotes, but with Prettier gaining momentum, how do you feel about the code being prettier-formatted by default?

**Comment by jaredpalmer** [comment]
Prettier already (with `--write` option) runs on Razzle before every commit using a precommit hook thanks to husky + lint-staged. 

Config can be found here: https://github.com/jaredpalmer/razzle/blob/master/package.json#L26

**Comment by jaredpalmer** [comment]
@ericclemmons would it be better if I commited my vscode workspace settings so people could just get `formatOnSave`?

**Comment by ericclemmons** [comment]
Oooh!  That must've been why I didn't see it happen.  Hmmm, I dunno, because it only really affects new projects, so I'm not sure if that's much clutter or not.

**Comment by jaredpalmer** [comment]
Oh my bad. You meant adding Prettier to the templates, (I thought you meant to the repo). Yeah I can add it.
