### ISSUE TITLE
Add error overlay like create-react-app's

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/razzle#284]
Create-react-app uses a custom webpack dev server client and its own custom error overlay. We could use switch to [react-dev-utils/webpackHotDevClient.js](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-dev-utils/webpackHotDevClient.js), except that it uses [`window.location.port`](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-dev-utils/webpackHotDevClient.js#L165).  From my initial explorations, this was the dealbreaker. 

That being said, it would be really nice to get an error overlay like CRA's for Razzle

**Comment by jariz** [comment]
Hey @jaredpalmer!
What do you think of the idea to proxy all requests from `/sockjs-node/` to the webpack server from the main entry point.
It's kind of hacky but probably a better solution than forking react-dev-utils/webpackHotDevClient.js and editing it to the webpack server port.
Preferably we'd have a middleware in `razzle-dev-utils` which could be used from `src/index.js` as so:

```diff
+import razzleHMRProxy from 'razzle-dev-utils/razzleHMRProxy';

export default express()
+   .use((req, res) => razzleHMRProxy(req, res))
    .use((req, res) => app.handle(req, res))
    .listen(port, function (err) {
```

**Comment by jariz** [comment]
Or furthermore, perhaps even ditch the webpack dev server entirely and migrate it to the webpack middleware? (swapping out the proxy in above example for a webpack middleware that razzle could export)

**Comment by jaredpalmer** [comment]
That would be cool.

**Comment by jariz** [comment]
What was the reasoning behind running the dev server on a seperate port in the first place instead of using the middleware, if I may ask?

**Comment by jariz** [comment]
@jaredpalmer 🎉 
Nice!

**Comment by jariz** [comment]
Does this display serverside errors too?

**Comment by jaredpalmer** [comment]
Don't think so. It works by creating a socket from webpack-dev-server and your client bundle.

**Comment by jaredpalmer** [comment]
I am working with Dan to fix a bug that is preventing runtime errors from showing up. Right now only compiler / lint errors show

https://github.com/facebookincubator/create-react-app/pull/2515#issuecomment-325461989

**Comment by tsiq-swyx** [comment]
how about using componentDidCatch now that it exists? sorry if this has been discussed elsewhere before.

**Comment by jaredpalmer** [comment]
AFAIK componentDidCatch can’t be used with SSR
