### ISSUE TITLE
Deployment guide

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/razzle#285]
- [ ] Heroku
- [ ] Now
- [ ] Digital Ocean?
- [ ] AWS??

**Comment by dorkblue** [comment]
Heroku
AWS
Digital Ocean

**Comment by meeoh** [comment]
Would really appreciate a heroku (or platform really) deployment guide

**Comment by bdo** [comment]
Please also add Google App Engine

**Comment by david-potgieter** [comment]
@jaredpalmer - can we reopen? Current state of this issue:

- [x] Heroku
- [x] Now
- [ ] Digital Ocean
- [ ] AWS
- [ ] Google App engine
- [x] Firebase

**Comment by conary-h** [comment]
Any update?

**Comment by sachaarbonel** [comment]
Hey guys I made a deployment example on kubernetes if you want to give it a try you can find it [here](https://github.com/Sach97/razzle-k8s)

**Comment by charlie632** [comment]
A deployment guide for Azure would be helpful. I'm willing to write it, but first I need to know how to get it to run...

**Comment by charlie632** [comment]
I managed to deploy a razzle app to Azure using Docker. I will create a PR with a step by step guide and also the code for it.

**Comment by rcolepeterson** [comment]
Is there a deployment guide for AWS or GCP?

**Comment by anz000** [comment]
Deployment guide for GCP would be great.

**Comment by strommj** [comment]
I'm currently trying to deploy on DigitalOcean, a Deployment guide using pm2 and nginx for React would be useful!  (Or any other common way to deploy on a self-administered server)

**Comment by mding5692** [comment]
Any deployment guide for AWS? Our company uses Razzle and would like to know

**Comment by zsh77** [comment]
as @strommj mentioned Deployment guide using pm2 and nginx for React would be useful!

**Comment by fhayes301** [comment]
Is there a deployment guide for Google App Engine? Would be very helpful. With Razzle ^4.x.x, I'm unable to deploy and now get Razzle:not found errors.
