### ISSUE TITLE
Importing Font Awesome css

### ISSUE THREAD

**Issue by BradMcDanel** [jaredpalmer/razzle#286]
I am trying to extend Razzle to handle font awesome. Font awesome requires a ?v= as part of the path (as discussed here: https://github.com/facebookincubator/create-react-app/issues/295). Razzle appears to break in the same way discussed in that issue when trying to import font-awesome.css. It seems the fix is to add regex to the loader (https://github.com/facebookincubator/create-react-app/pull/298#discussion-diff-72889071L76). 

Just for reference, I am working off of the with-typescript example project. Thanks.

**Comment by jaredpalmer** [comment]
So it looks like all we need to do is add that extra regex to the url loader and we are good to go

**Comment by jaredpalmer** [comment]
Can you test out master to see if this is solved with new url loader setup?

**Comment by jaredpalmer** [comment]
Fixed here: https://github.com/jaredpalmer/razzle/commit/e1a374b914d0ebb784244237e5393a5b82f260cb
