### ISSUE TITLE
No sourcemap for client.js in production build

### ISSUE THREAD

**Issue by davincho** [jaredpalmer/razzle#290]
Steps for reproducing:

- Follow https://github.com/jaredpalmer/razzle#quick-start
- `yarn create razzle-app my-app`
- `cd my-app`
- Build client/server: `yarn build`

Sourcemap Files are created for:

- `build/server.js` -> `build/server.js.map`
- `build/public/static/css/client.09fcbae0.css` -> `build/public/static/css/client.09fcbae0.css.map`
- **NO** sourcemap for `build/public/static/js/client.2617cc1f.js`

I tried to tweak the webpack config with no success. Am I missing something?

**Comment by stereobooster** [comment]
I have another issue. Sourcemaps are present, but they are mostly empty. Example is here https://github.com/stereobooster/react-phone-number-input-ssr

```
source-map-explorer build/public/static/js/bundle.1bb261cb.js

Your source map only contains one source ( webpack:/webpack/bootstrap 6a97ef73520e2ab54233 )
This typically means that your source map doesn't map all the way back to the original sources.
This can happen if you use browserify+uglifyjs, for example, and don't set the --in-source-map flag to uglify.
See  https://github.com/danvk/source-map-explorer/blob/master/README.md#generating-source-maps
```
