### ISSUE TITLE
First time start in development mode doesn't completes successfully

### ISSUE THREAD

**Issue by kireerik** [jaredpalmer/razzle#292]
So only one of the server starts successfully and the other one(s) are not, as you can see here:
```shell
yarn dev v0.24.6
$ razzle start
 WAIT  Compiling...

 DONE  Compiled successfully

Your application is running at http://127.0.0.1:80


```

So I need to terminate the batch job and start it again.

Steps to reproduce:
- Delete the `build` folder
- Start the server in development mode

**Comment by jaredpalmer** [comment]
I am working on a fix for Windows. Again this doesn't happen on Mac.

Temporary workaround:

```yarn add rimraf --dev```

in your `package.json` start script

```
{
   "scripts" {
      "start": "rimraf build && razzle start"
   }
}

```

**Comment by jaredpalmer** [comment]
Are you running in VM ?

**Comment by kireerik** [comment]
No, I am using Windows (10) on my laptop.

This issue is not a big deal for me at all, I just reported it.

**Comment by kireerik** [comment]
Hi @jaredpalmer, you can keep this issue closed if you wish.

I am just leaving a note here that this is still an issue as of version `0.8.2`.

**Comment by NickCis** [comment]
On linux, on a fresh start (the `build` folder doesn't exist), this issue is present.

```bash
$ yarn start 2>&1 | tee error
# content of error file
yarn start v1.0.1
$ razzle start
 WAIT  Compiling...

[2J[3J[H DONE  Compiled successfully

Your application is running at http://localhost:3000
```
Content of `build` folder:

```
$ ls build
assets.json
```
Apparently, the `build` folder is created after the server is compiled. If the `build` folder is created before running `yarn start` everything works as expected:

```
$ rm -rf build && mkdir build && yarn start 2>&1 | tee output
# content of output
yarn start v1.0.1
$ razzle start
 WAIT  Compiling...

[2J[3J[H DONE  Compiled successfully

Your application is running at http://localhost:3000

[2J[3J[H WAIT  Compiling...

[2J[3J[H DONE  Compiled successfully

Your application is running at http://localhost:3000

✅  Server-side HMR Enabled!
> Started on port 3000
```

Content of build:
```
$ ls build
assets.json  server.js  server.js.map
```

## Steps to reproduce
As @kireerik said:

```bash
rm -rf build
yarn start
```

## Workaround

Add `rimraf` (as @jaredpalmer suggested) and `mkdirp` (in order to create the `build` folder):

```
yarn add --dev rimraf mkdirp
```

And edit `package.json`:

```
{
  // ...
   "scripts" {
      "start": "rimraf build && mkdirp build && razzle start"
   }
  // ...
}
```

## Versions:

```
$ uname -a
Linux 4.11.3-1-ARCH #1 SMP PREEMPT Sun May 28 10:40:17 CEST 2017 x86_64 GNU/Linux
$ node -v
v8.4.0
$ yarn -v
1.0.1
$ yarn list razzle                                                                                                                                                                                 yarn list v1.0.1
└─ razzle@0.8.4
Done in 0.95s.
```

**Comment by kireerik** [comment]
Hi @jaredpalmer, you can keep this issue closed if you wish.

I am just leaving a note here that this is still an issue as of version `0.8.7`.

**Comment by jaredpalmer** [comment]
I don’t have a windows machine and can’t replicate on Mac

**Comment by marcellobarile** [comment]
I'm experiencing the same issue and I'm not using yarn (the same behavior appears on Windows and GNU/Linux)... sometimes the process just got stuck on "Your application is running at http://localhost:3000" (no other outputs) even though the server is never started.

**Comment by kireerik** [comment]
This is no longer an issue as of version `2.x`.
