### ISSUE TITLE
Client and Server file path not match  

### ISSUE THREAD

**Issue by chayutzee** [jaredpalmer/razzle#296]
![screen shot 2560-06-09 at 9 30 11 am](https://user-images.githubusercontent.com/1681564/26958767-acd479e2-4cf6-11e7-92b6-9b73cd9301d6.png)

I just get this warning when upgrade razzle from 0.6.3 to 0.6.4.

**Comment by jaredpalmer** [comment]
thanks for pointing this out. releasing a patch now
