### ISSUE TITLE
Explore AutoDLLPlugin and Vendor bundling

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/razzle#305]
[This AutoDLLPlugin](https://github.com/asfktz/autodll-webpack-plugin) should dramatically speed up HMR. The question is how to generically incorporate it into Razzle. As we are in isomorphic land, it's hard to know if a dep is meant for node-only. AFAIK this means we'd have to let users specify which packages to include. 

### Idea 1: Special field in `razzle.config.js`
```js
// razzle.config.js

module.exports = {
 modify() {..},
 dll: [ 
   'react',
   'react-dom',
   ...
 ]
}
```

### Idea 2: Special Razzle package 

```js
// razzle.config.js
const razzleDLLPlugin = require('razzle-plugin-auto-dll');

module.exports = {
 modify(config) {
   return razzleDLLPlugin(config)
 }
}

```

I opt for 2 personally. Want to open this up for discussion though.

**Comment by pedronauck** [comment]
I tried to put AutoDDL plugin with Razzle but was not a good experience, I think that was a great idea thinking about that :v:

+1

**Comment by Metnew** [comment]
I tried to add AutoDLL plugin, it works only on the initial render, but after HMR it breaks an app with an error like "could not find dll-reference". However, dll script was inserted.

> Also, a special field for AutoDLL (and CommonChunksPlugin) in `razzle.config.js` looks good
