### ISSUE TITLE
babel-plugin-transform-react-jsx-source and preact example

### ISSUE THREAD

**Issue by thangngoc89** [jaredpalmer/razzle#306]
When creating a new with-preact I see `__source=[Object object]` props in every component like this

![image](https://user-images.githubusercontent.com/3049054/27835915-3aafca36-6107-11e7-815a-907351bdb5d1.png)

After poking around on preact's Slack, I come to a solution is to remove babel-plugin-transform-react-jsx-source from the default preset. Will you accept a PR to pass an option to disable it?

**Comment by jaredpalmer** [comment]
Sure.

**Comment by thangngoc89** [comment]
@jaredpalmer What should be the name of the option? `preact` or `jsx-source`.

**Comment by jaredpalmer** [comment]
`jsx-source`

**Comment by jaredpalmer** [comment]
Not seeing this anymore. Going to close.
