### ISSUE TITLE
Changing the script naming for the with-reason-react example

### ISSUE THREAD

**Issue by bjrnt** [jaredpalmer/razzle#308]
Hi,

When creating a new project with `reason-react` the following guide appears:
```
To start a local server for development:
  yarn start
```
but as shown inside the `reason-react` example, `yarn run dev` and not `yarn start` is required to run the example.

If you just run `yarn start`, you get a cryptic error message that doesn't really help:
```
❯ npm start

> razzle-examples-reason-react@0.7.2 start 
> NODE_ENV=production node build/server.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'build/server.js'
```

Either changing the post-installation message or changing the scripts required to run the reason-react example would help beginners get started. I'd be happy to PR this if needed.

**Comment by jaredpalmer** [comment]
Ahh I see what you mean, sorry about that. Feel free to submit a PR.
