### ISSUE TITLE
React Material -UI server side Rendering Razzle Example

### ISSUE THREAD

**Issue by GouthamKD** [jaredpalmer/razzle#310]
Hello Folks,

To brief about the problem which I am facing with respect to Pre-Render of React application which uses Material UI for styling aspects.

I have implemented React server side rendering of React-Material UI application using express node server.
I have followed below mentioned Razzle implementation approach.. and the Pre-Rendering is happening as expected....
https://github.com/kireerik/razzle-material-ui-styled-example

**The more information about the implementation is mentioned in Razzle blog as below.
https://github.com/jaredpalmer/razzle#razzleconfigjs**

**As per the blog the Pre Render sample solution includes the Razzle node module which has got the webpack.config within it and in the solution we don't see any webpack.config.js included.**

If at all if we want to have the webpack.config , we can have the extension for the same that we can create in our root folder ex: Razzle.config.js , we can put the our configurations within this file.**
Configuration can be to load the .less ,.css and any other .jsx files in general....
The example template of Razzle.config.js is given as below in the Razzle blog
// razzle.config.js

module.exports = {

modify: (config, { target, dev }, webpack) => {

// do something and return config

return config
}

}

**In my Sample example I am trying to load the .less files by updating Razzle.config.js as below.
and the problem is its not accepting the modules loaders configuration inside the Razzle.config.js file**

Ex:

'use strict';

console.log('From Razzle Config!!');

module.exports = {

modify: (config, {target, dev}, webpack) => {

// do something to config
resolve: {

extensions: ['', '.js', '.jsx']
},

module: {

loaders: [

    {

        test: /\.jsx?$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
        query: {

        presets: ['es2015']

        }
    }
]
}
return config
} }

In the above example its throwing error at resolve and module keyword saying 'unused label'

I am bit confused about how to update the razzle.config to load the .less files and the .jsx files.

Help would be appreciated if some one correct the way of updating Razzle.config.js to load the .less and .jsx files.

Regards,
Goutham

**Comment by walleXD** [comment]
You don't need to change webpack config to get material-ui to work. Check out this commit from my repo [here](https://github.com/AsterixMedia/Odios/commit/703a0555f31981d795721e9c5bbe395f76cba512)

**Comment by GouthamKD** [comment]
Hello ,

material-ui server side rendering is working, however I am trying to extend the webpack.config to load
**.less files**..!!!!

**Comment by GouthamKD** [comment]
Thanks for the update.

However, we are not supposed to make changes to the downloaded node_modules ...
As per your blog explanation I should be able to extend webpack.config.js using razzle.config.js and  how can i do that now???

**Comment by walleXD** [comment]
If you are using material-ui, why don't you use their css-in-js solution? It works w/o too much tinkering and you get scoping within components

And if you really wanna write separate styles, go with post-css as razzle has built in support for that. But otherwise for less, you would have to extend the webpack config using ```razzle.config.js```. Check the example folder for reference

**Comment by GouthamKD** [comment]
Hey Walee,

I have already gone through sample folders in your repo...

https://github.com/jaredpalmer/razzle/blob/master/examples/with-custom-webpack-config/razzle.config.js

--What i found is something as below and  **i don't see how to add the loaders ... similar to how we do in webpack.config.js**

+++++++++++++++++

'use strict';
module.exports = {
  modify(config, { target, dev }, webpack) {
    const appConfig = config; // stay immutable here

    // Change the name of the server output file in production
    if (target === 'node' && !dev) {
      appConfig.output.filename = 'custom.js';
    }

    return appConfig;
  },
};

++++++++++++++++++++++++


**I here by request you to provide sample of razzle.config.js so that I can load the less loaders and .jsx too...**


Thanks.

**Comment by walleXD** [comment]
You add the loaders by adding your loaders to the ```appconfig```. Here's a possible approach

```
const yourRuleForHandlingLess = {/*Add you less loader here*/}
appconfig.module.rules = [...appconfig.module.rules, yourRuleForHandlingLess]
```

This approach will make sure that existing loaders razzle loaders aren't scrapped but rather your rule is added along with them

**Comment by GouthamKD** [comment]
I tried the as below....

**+++++++++**

'use strict';

module.exports = {
  modify: (config, {target, dev}, webpack) => {
    // do something to config
    const appConfig = config;
    const RuleForHandlingLess = {
      /*Add you less loader here*/
      rules: [
        {
          test: [/\.less$/],
          loader: "style-loader!css-loader!less-loader",
        },
      ],
    }
    appConfig.module.rules = [...appConfig.module.rules, RuleForHandlingLess]
    return config
  }
}

**++++++++**


But. Neither its loading the .less files Nor its giving any errors...

Any changes to above snippet  required????

**Comment by jaredpalmer** [comment]
I have to push an update that allows .less files to be whitelisted from file loader. I made the change, just need to push a new release when I get to my computer this morning

**Comment by jaredpalmer** [comment]
@GouthamKD Please check out the latest release 0.7.3 an let me know if you still have issues with your `.less`. files

**Comment by GouthamKD** [comment]
Thanks Jared.

I will give a try and update you ...

**Comment by GouthamKD** [comment]
Hello Jared,

I just tried with the updated package.json as you mentioned...

However, happened me to witness the error while compiling as below.... while loading .less files

**ReferenceError: window is not defined**

Attached is the screen shot for reference ..



![lessloader](https://user-images.githubusercontent.com/22112377/28353070-94953196-6c77-11e7-905e-6b6bbd26aaae.png)




-- Let me know if I need to change anything further.

- Currently ,I have used my  package.json updated
- Got the less loaders included....

yet its not loading the .less files.


Let me know your concerns...


Thanks,
Goutham

**Comment by GouthamKD** [comment]
Jared,

Any clue on the above exception.......!!!!!! or how to resolve the same.....
