### ISSUE TITLE
Once more about Sass and razzle.config

### ISSUE THREAD

**Issue by vxna** [jaredpalmer/razzle#315]
Hello.

I already saw couple of issues about Sass in razzle.config.js and they're all pretty clear (there is even a [PR](https://github.com/eliot-akira/razzle/tree/with-scss/examples/with-scss)).
Would be better for me to use the old syntax instead, the .sass files. 

There is my [razzle.config.js](https://gist.github.com/surepe/bec7497a024c38fe78ed95a47ee8c4b4), what's wrong with it?

It does work with .sass in production build, but it doesn't during dev. Like at all, it just doesn't include any styles in developer mode, also doesn't produce any errors nor warnings during compile. For missing postcss options, they're in postcss.config.js file and it's just an simple autoprefixer configuration.  

I have tried everything I can find about/related to this in net, but nothing helped. Seems like I am missing something basic. Notable thing: everything working as expected with .scss files.

    "razzle": "^0.7.3",
    "node-sass": "^4.5.3",
    "sass-loader": "^6.0.6"

Thanks.

**Comment by jaredpalmer** [comment]
Ahh I think I need to add .sass to the file-loader whitelist so it isn’t intercepted

**Comment by jaredpalmer** [comment]
Stay tuned

**Comment by vxna** [comment]
Gotcha! Is it, for testing I have added /.s[ac]ss$/, in the exclude list.
```javascript
          exclude: [
            /\.html$/,
            /\.(js|jsx)$/,
            /\.(ts|tsx)$/,
            /\.(vue)$/,
            /\.(less)$/,
            /\.(re)$/,
            /.s[ac]ss$/,
            /\.json$/,
            /\.bmp$/,
            /\.gif$/,
            /\.jpe?g$/,
            /\.png$/,
          ],
```
There is also one more change in [razzle.config.js](https://gist.github.com/surepe/bec7497a024c38fe78ed95a47ee8c4b4/revisions#diff-812ea5a8107515e8693d09de45983c4d).

**Comment by jaredpalmer** [comment]
Yeah

**Comment by vxna** [comment]
So how can I correctly play with excludes in my config? 
Like, in addition of /\.s[ac]ss$/  I also need to exclude /\.svg$/, so this code would work:
```javascript
    appConfig.module.rules.push(
      {
        test: /\.svg$/,
        loader: 'babel-loader!react-svg-loader'
      }
    );
```


Previosly, for testing above I was just modified the razzle\config\createConfig.js and it's an dirty way.

**Comment by surepe** [comment]
ping @jaredpalmer 

Still no luck with setting up a custom excludes list in razzle.config, any working example will be appreciated, thanks.

**Comment by vxna** [comment]
Sorry for question above, I just started with JS. That's how I did it:

```javascript
    appConfig.module.rules.splice(2, 1,
      {
        exclude: [
          /\.html$/,
          /\.(js|jsx)$/,
          /\.(ts|tsx)$/,
          /\.(vue)$/,
          /\.(less)$/,
          /\.(re)$/,
          /\.s[ac]ss$/,
          /\.json$/,
          /\.bmp$/,
          /\.gif$/,
          /\.jpe?g$/,
          /\.png$/,
          /\.svg$/,
        ],
        loader: require.resolve('file-loader'),
        options: {
          name: 'static/media/[name].[hash:8].[ext]',
        },
      },
    );
```

**Comment by jaredpalmer** [comment]
Have been on vacation. Just got back and pushed a patch in `0.7.5`. Should just work now with `.sass`. Sorry for the delay, was taking time off.

**Comment by marcelogdeandrade** [comment]
I'm having trouble working with Sass, is this issue resolved?

**Comment by wagnerjsilva** [comment]
same here

**Comment by jeankvd** [comment]
Any help?
