### ISSUE TITLE
webpack externals

### ISSUE THREAD

**Issue by paOol** [jaredpalmer/razzle#320]
tried  `config.externals.rules.push()` but got an error.

basically trying to add `externals` to the webpack config to get Electron working.

following this 
https://stackoverflow.com/questions/34427446/bundle-error-using-webpack-for-electron-application-cannot-resolve-module-elec

**Comment by jaredpalmer** [comment]
AFAIK there is no need to have multiple webpack builds for electron. I would look to use another project more suited for electron.
