### ISSUE TITLE
Async Data Fetch

### ISSUE THREAD

**Issue by sebmor** [jaredpalmer/razzle#321]
In the example all fetching is defined in server.js, which I looks kind of messy.

Is there a way to async fetch on a container level? Similar to Next.js with getInitialProps?

**Comment by jaredpalmer** [comment]
Checkout https://github.com/jaredpalmer/react-router-ssr

**Comment by NickCis** [comment]
I've build a similar example (using Redux): [Radioactive Bird](https://github.com/NickCis/radioactive-bird) is a simple twitter search. Backed up by razzle, react, react router, react router config, redux and material ui.

**Comment by sebmor** [comment]
@jaredpalmer Thanks a bunch, very elegant solution
