### ISSUE TITLE
Npm link doesn't work

### ISSUE THREAD

**Issue by FabioAntunes** [jaredpalmer/razzle#323]
**Razzle**: v0.7.4
**node**: v6.11.1

How to reproduce:
* clone this repo:  `git clone git@github.com:FabioAntunes/symlinked-example.git`
* run `npm run build:watch`
* on the root folder do `npm link` 

Create a new razzle app somewhere:
* `create-razzle-app new-app`
* `cd new-app`
* link the local package `npm link symlinked-example`

On the `Home.js` import the Button: `import { Button } from 'symlinked-example';`

start razzle: `npm start`

Output: 
```
/Users/fabio/playground/symlinked-example/build/index.js:1
(function (exports, require, module, __filename, __dirname) { export { default as Button } from './elements/Button';
                                                              ^^^^^^
SyntaxError: Unexpected token export
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.symlinked-example (/Users/fabio/playground/razzle-bootstrap/build/server.js:872:18)
```

Repeat everything but with `create-react-app`, everything works as expected.

**Comment by robertvansteen** [comment]
Was this fixed? I'm running in to a similar issue where I'm getting `Error: Cannot find module 'react'`.
Same package but linking it to `create-react-app` works fine.

**Comment by westmark** [comment]
I also encountered this problem. It occurs when the server is started via the `StartServerPlugin` This is how I solved it:
```
module.exports = {
  modify: (config, { target, dev }, webpack) => {
    if (target === 'node') {
      // Naive way to find the index of this plugin. There is problably a better way
      const index = config.plugins.length - 3;
      const startServerPlugin = config.plugins[index];
      startServerPlugin.options.nodeArgs = [
        '--preserve-symlinks', // This is key to fix the module resolution
        ...startServerPlugin.options.nodeArgs,
      ];
    }
    return config;
  },
};

```

If v3 is released I'll submit a PR, if still needed.

**Comment by xavierzwirtz** [comment]
This is still an issue in `3.0.0`. The above patch to insert `--preserve-symlinks` resolves the issue.
