### ISSUE TITLE
cannot read client.js on production server

### ISSUE THREAD

**Issue by paOol** [jaredpalmer/razzle#326]
in my network tab, this request fails

`Request URL:http://localhost:3001/static/js/client.js`

`run start` and `build` and `start:prod` work fine locally,
but on my production server there is no CSS/js working because the client.js file fails to load.

any ideas?

**Comment by paramaggarwal** [comment]
please check whether your server is configured to serve static assets from the correct location - for example, in my case: `app.use(express.static(process.env.RAZZLE_PUBLIC_DIR))`
