### ISSUE TITLE
Add option to disable FriendlyErrorsPlugin

### ISSUE THREAD

**Issue by d4rky-pl** [jaredpalmer/razzle#329]
When using razzle in environment where more than one utility has it's STDOUT mixed in (like Docker), `FriendlyErrorsPlugin` is annoying rather than helpful because it keeps clearing up the console, obscuring errors and console logs from other containers. It would be nice if it could either A) be easily disabled or B) has some kind of env/config switch that would disable `clearConsole()`

**Comment by jaredpalmer** [comment]
Set VERBOSE=true in .env
