### ISSUE TITLE
`false` in markup

### ISSUE THREAD

**Issue by rqrqrqrq** [jaredpalmer/razzle#334]
Hi folks!

I run into strange issue:
<img width="607" alt="screen shot 2017-08-29 at 13 30 00" src="https://user-images.githubusercontent.com/19387761/29816954-e2cef8da-8cbe-11e7-94d5-9f757d7dae40.png">

Probably it caused by conditional css link rendering `${!!assets.client.css && 'link'}`, and it's ok if i change this to ternary.

v0.8.1

**Comment by jaredpalmer** [comment]
Yup gotta fix that
