### ISSUE TITLE
remove warnings 

### ISSUE THREAD

**Issue by paOol** [jaredpalmer/razzle#341]
```
 WARNING  Failed to compile with 13 warnings
./src/components/kraken/kraken.js
  Line 1:  'Component' is defined but never used  no-unused-vars
  Line 2:  'axios' is defined but never used      no-unused-vars

```

where do you disable these warning messages?

**Comment by paOol** [comment]
I commented out lines 61-66 in `\node_modules\razzle-dev-utils\FriendlyErrorsPlugin.js`

but there is probably a better way to do this.

**Comment by jariz** [comment]
You'll have to add a `razzle.config.js` to the root of your project that modifies the webpack config to remove the `eslint-loader`.
Untested, but will probably work:

```
module.exports = {
  modify: (config, {target, dev}, webpack) => {
    // remove the first loader (eslint-loader)
    config.module.rules.shift();
  
    return config
  }
}
```

**Comment by jariz** [comment]
Btw the "Failed to compile" part of the message is wrong, it actually compiles fine, so apart from them simply showing up, the warnings don't really have any downside, so I'm not 100% sure why you'd want to do this.
