### ISSUE TITLE
examples/with-typescript awesome-typescript-loader or tsloader?

### ISSUE THREAD

**Issue by yonatanmn** [jaredpalmer/razzle#342]
Trying to add TS, totally noob in it, so I'm copy-pasting your example. 
in read.me you write about awesome-typescript-loader, which to my limited knowledge in TS is better, but in the code itself you use ts-loader.

**Comment by jaredpalmer** [comment]
Awesome-typescript-loader's error messages are a bit whacky, need to update the example

**Comment by KatSick** [comment]
any updates? can i find guide for setup TS ?

**Comment by jaredpalmer** [comment]
I fixed this recently. forgot to reference this issue
