### ISSUE TITLE
babel-loader not picking up jsx extensions

### ISSUE THREAD

**Issue by GouthamKD** [jaredpalmer/razzle#346]
Hello All,

Is there any way to extend razzle.config.js ,So that I can load .jsx files in my SSR approach.
At the moment I am not able load the same.

Kindly let me know your thought s on the same.

Thanks,
Goutham KD

**Comment by jariz** [comment]
Good question. Currently we only support js extensions:
https://github.com/jaredpalmer/razzle/blob/1a351d1069831273b3083a6756dd320fe90d189a/packages/razzle/config/createConfig.js#L112

You can change this manually by adding a `razzle.config.js` (like you said) that does something along the following (untested)

```js

module.exports = {
  modify: (config) => {
    config.module.rules[1].test = /\.(js|jsx)$/;
  
    return config
  }
}
```

@jaredpalmer Do we want to add .jsx support? I personally don't see any point in it, but CRA seems to [do support it](https://github.com/facebookincubator/create-react-app/blob/6644054fc3f64533dd1b9469baa2fab94e44b721/packages/react-scripts/config/webpack.config.dev.js#L169), and we already match jsx files with our eslint loader(?), so why not, I guess
https://github.com/jaredpalmer/razzle/blob/1a351d1069831273b3083a6756dd320fe90d189a/packages/razzle/config/createConfig.js#L100

**Comment by jariz** [comment]
@jaredpalmer 
Furthermore, what's with the marking of the `s` character as optional? Is this on purpose? I can't imagine. Shouldn't this be `/\.jsx?$/`?  
It matches both `.j` and `.js` files right now which doesn't make sense 🙂
