### ISSUE TITLE
server side Rendering Razzle - support for testing framework

### ISSUE THREAD

**Issue by GouthamKD** [jaredpalmer/razzle#347]
Hello,

Since I am using Razzle in one of my trail SSR project, I would like to know if it supports any testing frameworks like Mocha, Jasmie etc. and what configuration it accepts for test runner.

Let me know your inputs on the same.

Thanks,
Goutham KD

**Comment by jariz** [comment]
Hi. Run `npm test` as usual, this will run [jest](https://facebook.github.io/jest/), which will pick up all files ending with `*.test.js`. In the default project, this would be `App.test.js`.
More info about jest can be found on it's website.

**Comment by tchcxp** [comment]
@jariz any chance we can use `mocha` rather than `jest`?

**Comment by jaredpalmer** [comment]
Nothing is preventing you from setting up mocha on your own, but we will not be adding first class support at this time
