### ISSUE TITLE
Reason / react-router / react-native-web example does not work

### ISSUE THREAD

**Issue by rsaccon** [jaredpalmer/razzle#349]
I tested on Mac with latest Safari and Chrome, no errors in console, but clicking on the links does not render the targeted component. However the URL does change, and browser reload will result in rendering the the proper component.

If I set all dependencies to latest released version, this behaviour remains the same

I tried to swap your react router bindings with https://github.com/dariooddenino/bs-react-router-dom, but still exactly the same behaviour. 

(I also tested with https://github.com/dariooddenino/bs-react-router-dom in isolation, no razzle, no react-native-web, there all worked as expected)

UPDATE:
I started to read the sources of `react-native-web` and `bs-react-native` bindings and how you use all of this. And there is one thing which irritates me: `ReactNative` gets imported from `react-native` via `bs-react-native` bindings. But  shouldn't it come from `react-native-web` ? That doesn't even has reason bindings. I am confused now ...

**Comment by jaredpalmer** [comment]
That example needs to be updated. Worked with an earlier version of Reason and Reason React-Native. Should probably remove note its deprecation at this point.

**Comment by yarra2296** [comment]
[https://www.google.com](url)
