### ISSUE TITLE
How to hot reload on non .js files?

### ISSUE THREAD

**Issue by WolfDan** [jaredpalmer/razzle#350]
I'm making a SSR app with Elm and Razzle, everything is fine, I just need to make work HMR with all `.elm` files.

Actually I can make hot reload to specific files, like this:

```javascript
if (module.hot) {
  module.hot.accept();
  module.hot.accept('./Main', () => {
    const nextElm = require('./Main').Main;
    nextElm.embed( document.getElementById( "root" ) );
  })
}
```

If I change the code of Main.elm it hot reload, but if I edit any other child elm file it dosen't work. Is really annoying add every file (much more if the project is big) so I wan't to know if is possible reload on all .elm files

Greetings

-----
_Sorry if my English writing skills are poor, I still learning ^^'_

**Comment by WolfDan** [comment]
Solved, if you're curious how to make work Elm and Razzle take a look to [this repo](https://github.com/WolfDan/elm-ssr)

**Comment by jaredpalmer** [comment]
Want to submit a PR to make this an official Razzle example?

**Comment by WolfDan** [comment]
Sure @jaredpalmer !

edit: PR created

**Comment by jaredpalmer** [comment]
Examples folder so people can install it with the CLI. I will add a link to the initial repo in the readme in the example too

**Comment by WolfDan** [comment]
@jaredpalmer I just created the pull request in the example folder ^^
