### ISSUE TITLE
Razzle SSR support for hot reloading of modules

### ISSUE THREAD

**Issue by GouthamKD** [jaredpalmer/razzle#351]
Hello All,

I would like to know is there any way I can do hot reloading of modules with Razzle Server Side rendering.
**_like we do normally with webpack-deverserver --hot_**

If it supports, let me know the configuration required.

Thanks,
Goutham KD

**Comment by jariz** [comment]
Razzle has server side hot reloading. It's included in all examples. No configuration required.
Does that answer your question?

**Comment by GouthamKD** [comment]
Can you please share one URL where I can see the references in the examples...!

**Comment by jariz** [comment]
just run `create-razzle-app` and start editing `server.js`.

**Comment by GouthamKD** [comment]
Below mentioned is my package.json config.

	"scripts": {
		"start": "razzle build && cross-env NODE_ENV=production node build/server.js",
		"dev": "razzle start"
	},

++++++++++++++
You meant to say that... I need to have the create-razzle-app module installed and next Can i start server saying..

npm start ????
 to see the hot reloading changes???

**Comment by jariz** [comment]
No. create-razzle-app only generates a project. If you already have a project, you can run `npm run dev` (I guess, looking at the json you posted)

**Comment by GouthamKD** [comment]
Thanks a lot :)
it worked.
