### ISSUE TITLE
Using libraries targeting es6 causes uglify to crash on build

### ISSUE THREAD

**Issue by d4rky-pl** [jaredpalmer/razzle#355]
When using a library that is targeting node (and es6) and does not include es5 version, everything works in development mode but uglify crashes on build.

Repo with reproduction (it imports a file from library in Home.js): https://github.com/d4rky-pl/razzle-issue

Razzle should probably handle this somehow.

**Comment by d4rky-pl** [comment]
Workaround: replace uglify with babel-minify in razzle.config.js:

```
module.exports = {
  modify: (baseConfig, { target, dev }, webpack) => {
    const appConfig = Object.assign({}, baseConfig)
    if(!dev) {
      const index = config.plugins.findIndex((plugin) => plugin.constructor.name === 'UglifyJsPlugin')
      if(index !== -1) {
        appConfig.plugins[index] = new MinifyPlugin()
      }
    }
    return appConfig
  }
}

// or with (shameful advertisement!) razzle-config-utils package:

const { replacePlugin } = require('razzle-config-utils')
// ...
    if(!dev) {
      replacePlugin(appConfig, 'UglifyJsPlugin', new MinifyPlugin())
    }
// ...
```

**Comment by Grsmto** [comment]
Seems like uglifyjs-webpack-plugin 1.0.0 supports ES6 now and Webpack 4.0 will come with it. As seens there https://stackoverflow.com/questions/43888474/unexpected-token-operator-from-uglifyjs and Razzle is using still the version coming with Webpack (webpack.optimize.UglifyJsPlugin).

**Comment by jaredpalmer** [comment]
@Grsmto feel free to submit a PR

**Comment by jaredpalmer** [comment]
Move discussion to #407
