### ISSUE TITLE
changing port?

### ISSUE THREAD

**Issue by paOol** [jaredpalmer/razzle#357]
I modified the default value in `razzle/packages/razzle/config/create-config.js`,
but i'm assuming there is a non-hacky method of changing the port?

I tried `NODE_PORT=4000` in the npm run start script, but that didn't work.

**Comment by d4rky-pl** [comment]
@paOol See https://github.com/jaredpalmer/razzle#environment-variables

**Comment by jariz** [comment]
don't prepend it with `NODE_`, also yea, see the link @d4rky-pl posted.
