### ISSUE TITLE
React v16 support

### ISSUE THREAD

**Issue by paOol** [jaredpalmer/razzle#359]
https://facebook.github.io/react/blog/2017/09/26/react-v16.0.html

time for a new branch to get everything updated and working?

**Comment by jaredpalmer** [comment]
Yup. Need to call `hydrate` instead of `render` in `client.js` with 16.  Everything else should work. (i think 😉 )

**Comment by paramaggarwal** [comment]
So would this be conditional now? Call `hydrate` on first render and then `render` in all `module.hot` updates? Thanks.

**Comment by jaredpalmer** [comment]
About to cut a release in the next hour or so
