### ISSUE TITLE
An example with razzle with auth

### ISSUE THREAD

**Issue by sebmor** [jaredpalmer/razzle#374]
I'm struggling to find the best method to store and load a cookie the "razzle" way. Curious to hear how others tackle this and potentially if we can include this as an example?

**Comment by jaredpalmer** [comment]
Yeah I can add an example. You put your token in a cookie 🍪 and that way it’s available isomorphically. If you’re using cookie parser middleware it will be in req.headers.cookie on the server. You should get the token and make it available to whatever http client you are using to fetch data. I usually have a makeFetch(req?: express.Request) that returns a wrapper of fetch() with default auth headers that gets called on both the client and server.

**Comment by barelabs** [comment]
I looked in the examples section and could not find an auth example.  Am I missing it somewhere?  Thank you for anyone for pointing out where the auth example is.  Thanks!

Tim
