### ISSUE TITLE
Best practices for error reporting?

### ISSUE THREAD

**Issue by paramaggarwal** [jaredpalmer/razzle#375]
Hi 👋 

Now that we bundle and minify the server-side code. What would be the recommended practice for error reporting to tools like Sentry? I understand this would involve use of source-maps - looking for some wisdom on how best to set this up. Thanks!

**Comment by jaredpalmer** [comment]
Haven't tried but, i would probably check out [40thieves/webpack-sentry-plugin](https://github.com/40thieves/webpack-sentry-plugin) to send up all your sourcemaps

**Comment by paramaggarwal** [comment]
Thank you - this is useful. So a common pattern would be to use a Webpack plugin for whatever error reporting service you use - which will automatically upload the source-maps. No further integration required.

Rollbar: [thredup/rollbar-sourcemap-webpack-plugin](http://github.com/thredup/rollbar-sourcemap-webpack-plugin)
Sentry: [40thieves/webpack-sentry-plugin](http://github.com/40thieves/webpack-sentry-plugin)
