### ISSUE TITLE
Razzle build with example

### ISSUE THREAD

**Issue by mikeplis** [jaredpalmer/razzle#376]
What are your thoughts on being able to run `npm run build` with an additional argument that allows users to initialize a project with different boilerplates? I started working on a [boilerplate](https://github.com/mplis/react-ssr-boilerplate) based on Razzle, but I'm thinking that it'd be a better developer experience if someone could just run `npm run build some-boilerplate` instead of having to discover/clone/run my repo.

**Comment by NickCis** [comment]
Did you see [Create razzle app](https://www.npmjs.com/package/create-razzle-app)?

**Comment by mikeplis** [comment]
I didn't notice that you could initialize a project with one of the examples. Thanks!
