### ISSUE TITLE
Add `addMiddlewares` function to make modifying webpack config modular

### ISSUE THREAD

**Issue by malekjaroslav** [jaredpalmer/razzle#378]
Hi guys, 
I was thinking how to make the Webpack modification cleaner and I came with this idea. 
Creating middlewares each responsible for its own task. This works for me really well and so maybe we could consider implementing it into Razzle.

This is how I handle it:

addMiddlewares.js
```
const R = require('ramda');

const addMiddewares = middlewares => (baseConfig, info, webpack) => {
    const config = Object.assign({}, baseConfig);
    return R.compose(...middlewares.map(middleware => middleware(info, webpack)))(config);
};

module.exports = addMiddewares;
```
and then in my razzle.config.js
```
const handleScss = require('./webpack/modifiers/addScss');
const addPatchHotReaload = require('./webpack/modifiers/addPatchHotReaload');
const addAliases = require('./webpack/modifiers/addAliases');
const addGraphqQL = require('./webpack/modifiers/addGraphql');
const addAntd = require('./webpack/modifiers/addAntd');

const addMiddlewares = require('./webpack/addMiddlewares');

module.exports = {
    modify: addMiddlewares([handleScss, addPatchHotReaload, addAliases, addGraphqQL, addAntd]),
};
```
What do you think about this approach?

**Comment by jaredpalmer** [comment]
My plan is to copy the gatsby setup and start packaging up plugins in the main repo. I also am thinking about grabbing some of preact-cli's helper methods so it's easier to write webpack mods.
