### ISSUE TITLE
Issue with Semantic-UI React

### ISSUE THREAD

**Issue by psycura** [jaredpalmer/razzle#380]
Hello, and thank you for the boilerplate.
I`m trying to use[ Semantic-UI React](https://react.semantic-ui.com/introduction) library, but when i import any component to my project and insert it to the code - the component in the browser loose all his styling from semantic and look like regular HTML component.

Why is this happen?

**Comment by usirin** [comment]
Hi @psycura, 
Semantic-UI React package doesn't include the css for semantic ui, you should include the css separately either from a cdn, or you can use [semantic-ui-css](https://www.npmjs.com/package/semantic-ui-css) package to include it in your build pipeline.
