### ISSUE TITLE
React router integration example

### ISSUE THREAD

**Issue by DimiMikadze** [jaredpalmer/razzle#382]
Hey, thanks for great work!

Are you guys planning to create example how to integrate React router v4 with Razzle?

**Comment by mistakenelf** [comment]
The default setup comes with react router 4 out of the box. What sort of example would you like to see?

**Comment by jaredpalmer** [comment]
You may find this useful: https://github.com/jaredpalmer/react-router-nextjs-like-data-fetching

**Comment by DimiMikadze** [comment]
@knipferrc I'm sorry, i was looking at redux example, thanks for the answer!
