### ISSUE TITLE
Jest issue with react-slick

### ISSUE THREAD

**Issue by meeoh** [jaredpalmer/razzle#383]
With react slick this issue arises: https://github.com/akiran/react-slick/issues/472
To solve it, you need to add a `setupFiles` key to the jest config in `package.json`, but razzle doesnt allow that and shows this on `npm test`:

```
Out of the box, Razzle only supports overriding these Jest options:

  • collectCoverageFrom
  • coverageReporters
  • coverageThreshold
  • moduleFileExtensions
  • moduleNameMapper
  • snapshotSerializers
  • testMatch
  • transform
  • transformIgnorePatterns
  • testResultsProcessor.

These options in your package.json Jest configuration are not currently supported by Razzle:

  • setupFiles
```

Is there a way to get around this so I can perform jest testing?

**Comment by jaredpalmer** [comment]
Ya setupTests.js in sec

**Comment by jaredpalmer** [comment]
**src/setupTests.js
