### ISSUE TITLE
assets.client.css not working

### ISSUE THREAD

**Issue by leon-wu** [jaredpalmer/razzle#384]
I am running examples/basic. everything is fine except assets.client.css. I did not see the stylesheet link in HTML, and also did not see assets.client.css in assets.json, there is only one line with js bundle. what is wrong?

···
$ cat ./build/assets.json
{"client":{"js":"http://localhost:3001/static/js/bundle.js"}}
···

**Comment by leon-wu** [comment]
some more information:

if i run 'npm run build', everything is absolutely right 

{"client":{"js":"/static/js/bundle.4e2e7c15.js","css":"/static/css/bundle.89ada7e4.css"}}

but if i run 'npm start', the css is missing in assets.json

{"client":{"js":"http://localhost:3001/static/js/bundle.js"}}

**Comment by FabioAntunes** [comment]
That's the correct behaviour. For you to have css hot reloading you can't use the `ExtractTextPlugin`,
