### ISSUE TITLE
import way leads to renderToString error

### ISSUE THREAD

**Issue by begoat** [jaredpalmer/razzle#388]
I am not sure if there is something wrong in the build process.

In my project when I render react-waypoint (a useful react component) the error will occur:
when I comment it out, the error disappear
```
TypeError: Cannot read property 'toLowerCase' of undefined
at ReactDOMServerRenderer.renderDOM
at ReactDOMServerRenderer.render
at ReactDOMServerRenderer.read
at Object.renderToString
```
You can check it out in this repo:
https://github.com/begoat/question.git

I changed the import way from 
`import Waypoint from 'react-waypoint'` to `const Waypoint = require('react-waypoint');`
And it worked.

I am newbie to front-end, and could you guys give me some direction to learn about the problem, why this happened?

**Comment by jaredpalmer** [comment]
waypoint might not be an ssr compatible module

**Comment by begoat** [comment]
But I can import it using require and now it works well.



Sent from myMail for iOS


Thursday, 23 November 2017, 2:39 AM +0800 from notifications@github.com  <notifications@github.com>:
