### ISSUE TITLE
absolute path for RAZZLE_PUBLIC_DIR/ASSETS

### ISSUE THREAD

**Issue by leon-wu** [jaredpalmer/razzle#389]
I am deploying razzle app in this way: building on CI server, and then push to production server and run 'npm run start:prod'.

However js/css is sent back with HTML, and the problem is at, when I run 'npm run build' on CI server, it is using absolute path for RAZZLE_PUBLIC_DIR varilable which is the path of CI server, and then push to production server, it does not work.

I need to get this round by run build command again after pushing to production server. However changing the variable to use relative path may be better?

**Comment by jaredpalmer** [comment]
```js

// Setup the public directory so that we can server static assets.
app.use(
  express.static(process.env.NODE_ENV==='production' ? path.join(__dirname, '../build/public') : 'public')
);

```
