### ISSUE TITLE
Custom build folder name

### ISSUE THREAD

**Issue by 54vanya** [jaredpalmer/razzle#391]
I see RAZZLE_PUBLIC_DIR variable in readme, but it doesn't work or I just don't understand its meaning. So I want to get the opportunity to make some independent build folders in one project

**Comment by jaredpalmer** [comment]
`process.env.RAZZLE_PUBLIC_DIR` is the readonly runtime path to the `public` folder directory. 

In dev it points to `<root>/public`, but after running `razzle build` that directory is copied into `<root>/build/public`. It's use case is serving up static assets from your server.

If you want to change the name of the build directory, you will need to modify Razzle's webpack config in `razzle.config.js`
