### ISSUE TITLE
Using ES6 node_modules

### ISSUE THREAD

**Issue by dortzur** [jaredpalmer/razzle#393]
Thanks for this project! it's awesome.

I'm trying to import private scoped es6 node_modules. 
For example: `import isMobile from '@spotim/fed-utils/is-mobile'`. 

I need these files to be processed by webpack like the src folder.
What would be the most elegant way of doing this in the `razzle.config.js` file?

Thanks!

**Comment by jaredpalmer** [comment]
See #407
