### ISSUE TITLE
Allow custom prefix for environment variables

### ISSUE THREAD

**Issue by d4rky-pl** [jaredpalmer/razzle#394]
Right now razzle forces you to use `RAZZLE_` prefix, it would be nice to be able to replace this with custom one. [Looking at code, it seems that the change would be rather simple](https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/config/env.js#L54), let me know if you're OK with this and I'll send a PR :)

**Comment by jaredpalmer** [comment]
If you keep the default as RAZZLE_, feel free to submit a PR
