### ISSUE TITLE
Check for port in use when running npm run start to avoid EADDRINUSE

### ISSUE THREAD

**Issue by jolyonruss** [jaredpalmer/razzle#397]
If I have another application running on port 3000 when I run `npm run start` I get the classic `EADDRINUSE` error.

Steps to reproduce:
 - have another node instance running on port 3000
 - create a fresh razzle project and run `npm run start`

Suggestions, follow the same pattern as create-react-app and check if the port is in use at startup

**Comment by jaredpalmer** [comment]
Yeah this would be a nice feature

**Comment by jolyonruss** [comment]
I assume that could be implemented around line 80 of `razzle/scripts/start.js`?

**Comment by guyb7** [comment]
Just to note that we actually need 2 ports: one for the app and one for the dev-server.
I can work on this. Welcoming any ideas/suggestions 🙂

**Comment by jolyonruss** [comment]
Sounds good @guyb7, that's something I hadn't considered
