### ISSUE TITLE
Cannot publish loadable example

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/razzle#400]
@glennreyes can you give me publish rights ASAP to razzle-examples-with-react-loadable on NPM?
 This is messing with lerna publish and github tagging. Thanks

**Comment by glennreyes** [comment]
I don't have permissions since I didn't publish it, looks like we need to reach out to @dortzur?

**Comment by dortzur** [comment]
How did I end up owning these modules???

**Comment by dortzur** [comment]
Added @jaredpalmer
