### ISSUE TITLE
Update eslint to latest version 4.11.0

### ISSUE THREAD

**Issue by gl0gl0** [jaredpalmer/razzle#404]
Version eslint@4.5.0 is having conflicts with some other eslint standards like airbnb's

**Comment by stout01** [comment]
I am also running into this issue. Now eslint version 4.14.0

**Comment by 617dev** [comment]
this is a problem for me too. @jaredpalmer Is there any reason it's set to an exact version of `4.5.0`? 
https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/package.json#L42

**Comment by ssanchez** [comment]
I'm curious about this as well. A workaround is to use eslint-config-airbnb@15.1.0, though that's not ideal.
