### ISSUE TITLE
README mismatch

### ISSUE THREAD

**Issue by d4rky-pl** [jaredpalmer/razzle#409]
There seems to be a growing mismatch between README from razzle repository and README in `packages/create-razzle-app/templates/default/README.md`.

I propose to either sync them automatically or rewrite `create-razzle-app` README into something shorter that says few words about what RAZZLE is (or gives some pointers on what should be in application's README) and then links to existing documentation on GitHub.

**Comment by jariz** [comment]
How about a soft link? Or does that not work well together with npm?

**Comment by jaredpalmer** [comment]
We should probably write a precommit task that copies the README in a lot of places.
