### ISSUE TITLE
[with-typescript] Server HMR fails when entry file is .ts

### ISSUE THREAD

**Issue by markyfyi** [jaredpalmer/razzle#420]
Hey, great work on razzle!  I've developing on top of latest `with-typescript`, and noticed HMR on the server is broken.

Steps to repro:
1. `create-razzle-app --example with-typescript <name>`
2. `cd <name>`
3. `npm start`
4. Edit and save `src/server.tsx`
5. Dev server output:

```
[HMR] Cannot apply update.
[HMR] Error: Aborted because ./src/index.ts is not accepted
Update propagation: ./src/index.ts -> 0
    at hotApply (<...>/razzle-ts-hmr-demo/build/server.js:400:30)
    at <...>/razzle-ts-hmr-demo/build/server.js:249:21
    at <anonymous>
[HMR] You need to restart the application!
```

If you convert `src/index.ts` to .js, HMR works again. 🤔  (demo: https://github.com/markshlick/razzle-ts-hmr-demo/commit/dc476fdc3ba03a1b018b1f783dd3a0aea556fe1a).

**Comment by eronalves** [comment]
+1

**Comment by Thomas-X** [comment]
+1

**Comment by arapl3y** [comment]
+1

**Comment by rayandrew** [comment]
have you tried the new [razzle typescript plugin](https://github.com/jaredpalmer/razzle/tree/master/packages/razzle-plugin-typescript)?

**Comment by pavelprokes** [comment]
+1

**Comment by SheikhG1900** [comment]
Problem is in index.ts file. I changed its code with following. _(Razzle default index.js code)_. Now server HMR working.
```javascript
import http from 'http'
import app from './server'

const server = http.createServer(app)

let currentApp = app

server.listen(process.env.PORT || 3000, (error) => {
  if (error) {
    console.log(error)
  }

  console.log('🚀 started')
})

if (module.hot) {
  console.log('✅  Server-side HMR Enabled!')

  module.hot.accept('./server', () => {
    console.log('🔁  HMR Reloading `./server`...')
    server.removeListener('request', currentApp)
    const newApp = require('./server').default
    server.on('request', newApp)
    currentApp = newApp
  })
}
```
