### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by d4rky-pl** [jaredpalmer/razzle#421]
It would be super-helpful if there was a CHANGELOG.md file in the repository.

**Comment by kireerik** [comment]
I think the [release notes](https://github.com/jaredpalmer/razzle/releases) are sufficient.

**Comment by kireerik** [comment]
What do you think @d4rky-pl?

**Comment by jaredpalmer** [comment]
I write release notes every release on all my projects. Perhaps we should note that in the readme

**Comment by d4rky-pl** [comment]
Yeah, marking it in README or generating CHANGELOG based on github releases would be amazing. Ever since the Github redesign I keep forgetting this tab is even there, sorry for that!
