### ISSUE TITLE
Support React 16.2+ JSX Fragment syntax

### ISSUE THREAD

**Issue by kireerik** [jaredpalmer/razzle#423]
- [React v16.2.0: Improved Support for Fragments](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html#support-for-fragment-syntax)
- https://reactjs.org/docs/fragments.html

**Comment by jaredpalmer** [comment]
What's missing? Just an upgrade?

**Comment by kireerik** [comment]
As I can see, yes you are right.

Based on the [linked article](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html#support-for-fragment-syntax) I think Razzle should be updated to the next major stable release of `Babel` and or `react-preset` and or `babel-loader` once they are released.
However it also says "If you are using Babel with Webpack, no additional steps are needed...". Maybe this isn't true for Razzle as the mentioned syntax doesn't work just yet.

Anyway the `<Fragment></Fragment>` component can be already used instead of the shorter `<></>` syntax.

**Comment by jaredpalmer** [comment]
I think we can actually just get rid of babel-preset-razzle now and move to just babel-preset-react-app. Initially hmr didn’t work, but now it seems to :shrug:

**Comment by kireerik** [comment]
That's possible. The less dependency you or the community need to maintain the merrier.

Based on the release dates of the package I think it does not support the new syntax just yet.

**Comment by bel0v** [comment]
Hello! any updates on this? It'd be really nice to be able to use fragments in CRA

**Comment by M-ZubairAhmed** [comment]
@FoxWhite you can continue to use `<React.Fragment>` while waiting to use `<>.

**Comment by kireerik** [comment]
This is not working as of version `2.0.1`. But [this commit description](https://github.com/jaredpalmer/razzle/commit/f141a267cbf3ed0645e970840ed108548ee64a2a) says it is supported.
> ✨ Upgrade deps and TypeScript. Now supports the new fragment syntax<></>

**Comment by jaredpalmer** [comment]
TypeScript supports <> via TypeScript

**Comment by jaredpalmer** [comment]
Open to a PR

**Comment by kireerik** [comment]
@stale I am not working on it, but this is still not supported as of version `2.4.0`.

**Comment by AndrewPrifer** [comment]
Also curious about this. Babel 7 is out of beta 🎉

**Comment by kireerik** [comment]
This feature is supported as of version `3.0.0-alpha.0`. I will close this once version `3.0.0` is released.

**Comment by gabimor** [comment]
Any updates on v3.0.0 release date?

**Comment by fivethreeo** [comment]
Close?
