### ISSUE TITLE
Unexpected token while running test in with-typescript example

### ISSUE THREAD

**Issue by corydeppen** [jaredpalmer/razzle#426]
I'm running into an issue getting the initial test running in the with-typescript example app. My `package.json` uses the same config as the example:

```json
"jest": {
  "transform": {
    ".(ts|tsx)": "<rootDir>/node_modules/ts-jest/preprocessor.js",
    "^.+\\.css$": "<rootDir>/node_modules/razzle/config/jest/cssTransform.js",
    "^(?!.*\\.(js|jsx|css|json)$)": "<rootDir>/node_modules/razzle/config/jest/fileTransform.js"
  },
  "testMatch": [
    "<rootDir>/src/**/__tests__/**/*.(ts|js)?(x)",
    "<rootDir>/src/**/?(*.)(spec|test).(ts|js)?(x)"
  ],
  "moduleFileExtensions": [
    "ts",
    "tsx",
    "js",
    "json"
  ],
  "collectCoverageFrom": [
    "src/**/*.{js,jsx,ts,tsx}"
  ]
}
```

Running `yarn test` I get the following:

```bash
FAIL  src\App.test.tsx
  ● Test suite failed to run

    path\to\src\Home.css:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){.Home {
                                                                                             ^

    SyntaxError: Unexpected token .

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at Object.<anonymous> (src/Home.tsx:12:1)
      at Object.<anonymous> (src/App.tsx:3:13)
```

Seems like the `cssTransform` may not be running on it, but I'm not very familiar with Jest and it's config yet.

**Comment by jariz** [comment]
You'll have to instruct ts-jest [to use a `.babelrc` file](https://github.com/kulshekhar/ts-jest#using-babelrc), and create a `.babelrc` in your root containing the same as razzle's default babel configuration:

```
{
  "presets": [
    "razzle/babel"
   ]
}
```

**Comment by jariz** [comment]
Wait, nevermind, I'm stupid, the preset of course does not transform css by default, that's webpack's task.
Considering looking into [this article](https://facebook.github.io/jest/docs/en/webpack.html).

**Comment by jariz** [comment]
@corydeppen 
I haven't seen this occur when running the updated TS example (#436) which uses CSS now.
Can you provide an example repo that isolates your issue?

**Comment by corydeppen** [comment]
It still fails, though with a slightly different error, even after copying over all the files from the updated TS example and working from an empty `node_modules` directory without a `yarn.lock` file:

```
src\App.test.tsx
  ● Test suite failed to run

    path\to\src\react.svg:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){<?xml version="1.0" encoding="UTF-8
"?>

    SyntaxError: Unexpected token <
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at Object.<anonymous> (src/Home.tsx:2:15)
      at Object.<anonymous> (src/App.tsx:3:13)
```

I've given up trying to figure out what's causing it. I cloned the TS example again, upgraded the outdated dependencies, and the test passes without an issue.

**Comment by samjetski** [comment]
I ran into the same issue with a CSS file. Turns out the file in question was under a "componen**ts**" directory and the Jest transform pattern for `ts` files wasn't strict enough. PR #872 should fix it.
