### ISSUE TITLE
assets.client.js: where come from?

### ISSUE THREAD

**Issue by valorloff** [jaredpalmer/razzle#429]
I'm reading your firebase-functions example and do not see, where does client bundle generating happen? 
I see that it come from RAZZLE_ASSETS_MANIFEST dir, but where is it?
You says, that "Universal Hot Module Replacement, so both the client and server update whenever you make edits. No annoying restarts necessary"
please, in a nutshell, how it works with the updating client bundle,
thanks

**Comment by jaredpalmer** [comment]
build/assets.json

**Comment by valorloff** [comment]
and how does client bundle generated?
about server bundle we are see:
```
      appConfig.entry = path.resolve(__dirname, './src/server.js');
      appConfig.output.filename = 'server.bundle.js';
      appConfig.output.path = path.resolve(__dirname, './server/build');
```
and how about client bundle?
