### ISSUE TITLE
What's the best way to modify the file-loader exclude rules?

### ISSUE THREAD

**Issue by piersolenski** [jaredpalmer/razzle#433]
I'd like to add SVGs to the file-loader exclude list so I can use a custom loader with them. Currently I'm doing `appConfig.module.rules[2].exclude.push(/\.svg$/);` in my `razzle.config.js` but obviously that's a bit hacky! Is there a better way?

https://github.com/jaredpalmer/razzle/blob/9a3939ac880ac6d655aa275659d3cbaae41180e4/packages/razzle/config/createConfig.js#L86

**Comment by domtronn** [comment]
I've run into a similar issue where I want to introduce a new loader that isn't covered by the default `exclude` list of `file-loader`.

I've tried adding my loader at the bottom, _(which is how Webpack says priority works)_ but it still seems to go through the `file-loader`. Adding the extension of the file to the exclude list using the same method as @superfunkminister solves the issues and means my loader works as expected.

I'd also like a way to modify the `exclude` list without having to assume the position of the loader in the `config.module.rules` array.

**Comment by AndrewPrifer** [comment]
I just had this issue too. If anyone still needs this, the official plugins seem to do it the following way:

```js
const makeLoaderFinder = require('razzle-dev-utils/makeLoaderFinder');

config.module.rules[
    config.module.rules.findIndex(makeLoaderFinder('file-loader'))
].exclude.push(/\.graphql$/);
```

@jaredpalmer I think it would make a lot of sense to document this somewhere visible because the fact that all unknown files are automatically caught by file-loader can be quite confusing. What do you think?
