### ISSUE TITLE
React-Loadable and Typescript example?

### ISSUE THREAD

**Issue by lednhatkhanh** [jaredpalmer/razzle#434]
Hello, can you add an example that combines react-loadable and typescript together, cuz I have a lot of problems trying to make them work together... Thanks.

**Comment by jaredpalmer** [comment]
I’d suggest not doing this. It means you’ll need babel and TypeScript running together. Instead I’d look at Lyft’s universal async component.

**Comment by lednhatkhanh** [comment]
Thanks, I'll take a look into it.

**Comment by seanyu4296** [comment]
hi @lednhatkhanh did you get it to work? Typescript + react loadable in razzle?
