### ISSUE TITLE
Upgrade to Jest 22

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/razzle#438]
- Upgrade to Jest 22. 

- Also explore new Jest helper for TypeScript

**Comment by FabioAntunes** [comment]
shouldn't this be just bumping the version on the package.json?

It's just with React 16, some errors are being swallowed  so it would be nice to get Jest 22 https://github.com/facebook/react/issues/11098

**Comment by JacopKane** [comment]
https://github.com/jaredpalmer/razzle/pull/462

**Comment by jamesbhobbs** [comment]
@jaredpalmer The current version of Jest in the razzle package has these vulnerabilities: https://snyk.io/test/npm/razzle Is there a reason why a simple version bump of jest wouldn't be ok (as fabio suggested)? I've tried bumping to what you have in this repo's base package.json here #648 and tests pass.
