### ISSUE TITLE
lcov code coverage output is incorrect for TypeScript

### ISSUE THREAD

**Issue by timothymclane** [jaredpalmer/razzle#439]
Since Jest 20, ts-jest no longer does code coverage mapping for TypeScript projects. Instead, it's recommended to use Jest's `mapCoverage` option.

Given Razzle does not currently support passing `mapCoverage` to Jest, code coverage output can be incorrect for TypeScript projects.

Example:

![unmapped](https://user-images.githubusercontent.com/4565854/34266922-91c1c7b6-e640-11e7-825d-586e2a7a6930.PNG)

The simplest solution I can see is to just add `mapCoverage` to `supportedKeys` in createJestConfig, unless that would cause some other issue, but it appears to work just fine.

After editing createJestConfig to allow `mapCoverage: true`:

![mapped](https://user-images.githubusercontent.com/4565854/34266929-a0d3fe5e-e640-11e7-9537-d31b7f45314a.PNG)

**Comment by jaredpalmer** [comment]
That’s fine

**Comment by LavaToaster** [comment]
It's probably worth closing this issue. :)

**Comment by timothymclane** [comment]
Quite right!
