### ISSUE TITLE
Is it possible to use Razzle with Nuxt?

### ISSUE THREAD

**Issue by nekdolan** [jaredpalmer/razzle#440]
I am using the express template for nuxt ( https://github.com/nuxt-community/express-template ) which uses backpack.

I was hoping I could swap Backpack for Razzle, but I am not sure how to hook it up or if it is possible.

Can anyone help?
Thanks in advance

**Comment by jaredpalmer** [comment]
Use backpack for Nuxt

**Comment by nekdolan** [comment]
@jaredpalmer Isn't the idea behind Razzle that a universal app like nuxt could have hot reloading instead of live reloading? I am already using backpack (see first comment).

**Comment by jaredpalmer** [comment]
Yes, but nuxt already does half the reloading for you afaik.
