### ISSUE TITLE
Readme refers to HOST as 0.0.0.0 as default, but is localhost

### ISSUE THREAD

**Issue by dvdmgl** [jaredpalmer/razzle#442]
README.md referes to `process.env.HOST:` default is `0.0.0.0`, but was set to `localhost` 49a1489.

**Comment by kireerik** [comment]
My related comments:
- https://github.com/jaredpalmer/razzle/issues/263#issuecomment-300761396
- https://github.com/jaredpalmer/razzle/issues/263#issuecomment-300888593
