### ISSUE TITLE
No way of analyzing webpack bundle

### ISSUE THREAD

**Issue by d4rky-pl** [jaredpalmer/razzle#444]
Because Razzle uses Node.js API directly, there's no way of passing `--json` argument to generate JSON file that can be used with [analyse tool](https://webpack.github.io/analyse/).

It would be nice if Razzle had a CLI command that'd allow dumping this JSON separately for client and server, so it's possible to analyze and debug bundle size.

**Comment by jorilallo** [comment]
I also started looking into this and didn't come up with a solution easily

**Comment by whs** [comment]
I use [StatsWriterPlugin](https://github.com/FormidableLabs/webpack-stats-plugin) to write stats to a file. Make sure you set `fields: null` option to get the full bundle.

**Comment by Metnew** [comment]
Just add `BundleAnalyzerPlugin` to webpack config in `razzle.config.js` if you want a report about production build

**Comment by d4rky-pl** [comment]
@Metnew good idea, thanks! I'll add it to README and send a PR once I have free time to do so
