### ISSUE TITLE
Error overlay works even without defining the crossorigin attribute

### ISSUE THREAD

**Issue by kireerik** [jaredpalmer/razzle#445]
This can be reproduced by removing the crossorigin attribute here in the `basic` example and writing some syntax errors for example:
https://github.com/jaredpalmer/razzle/blob/9d7b07d365f4525974407e961a567c4f96382ffd/examples/basic/src/server.js#L28

**Comment by jaredpalmer** [comment]
hmmm... it didn't for a while. have to examine that. it was added because react needed to know it was being served during dev from another port (and so it should consider that a CDN).

**Comment by kireerik** [comment]
I see. Does it works for you as well with the current version? Do you think that the `crossorigin` attribute can be removed?

**Comment by kireerik** [comment]
As I can see in the README the `crossorigin` attribute is only needed if a CDN is used for example.
Note: The basic and other examples are using it.

I think we can probably close this issue.
