### ISSUE TITLE
Issues upgrading to React 16

### ISSUE THREAD

**Issue by meeoh** [jaredpalmer/razzle#451]
When performing an `npm i` I'm still receiving 

`npm WARN react-addons-test-utils@15.6.2 requires a peer of react-dom@^15.4.2 but none is installed. You must install peer dependencies yourself.`

I read that react-addons-test-utils is deprecated. I'm on the latest version of razzle and was wondering how to get around this error.

**Comment by jaredpalmer** [comment]
If a yarn.lock file is present, delete it. Then try running npm i. There is some terrible and unfortunate bug in npm 5 that will mutate and mess up node_modules if you run npm i in the presence of a yarn.lock file.

**Comment by meeoh** [comment]
There is no yarn.lock file present in my repo. Theres a package-lock.json but deleting that and re-running `npm i` wasnt sucessfull.

**Comment by meeoh** [comment]
any update on this @jaredpalmer ?
