### ISSUE TITLE
per-page SEO?

### ISSUE THREAD

**Issue by paOol** [jaredpalmer/razzle#453]
What are you guys using to manage title and meta description, etc. for each page?

something like react-helmet?

would very much appreciate a working example if possible.

**Comment by jaredpalmer** [comment]
React helmet is great

**Comment by alssndr** [comment]
@jaredpalmer how can i use helmet if meta description is retrieved by an api call?

**Comment by jgcmarins** [comment]
you can do the api call on the server side, before rendering

**Comment by mohammadghaderi** [comment]
> 
> 
> you can do the api call on the server side, before rendering

how we can call api on serverside ?

**Comment by jgcmarins** [comment]
you can add [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch) and use it just like the fetch api for browsers
