### ISSUE TITLE
create-razzle-app with Vue

### ISSUE THREAD

**Issue by markserrano915** [jaredpalmer/razzle#455]
I'd been looking around and can't find a way to specify a custom framework parameter like `Vue` to create an app.

The README states: 
> Works with React, Preact, Elm, Reason-React, Inferno, and Rax as well as Angular and Vue if that's your thing

My assumption is I can use `create-razzle-app` to generate a `Vue` app, but all I get is `React`-based app.

If my assumption is incorrect, how does one use `Vue` here without manually modifying any configuration?

**Comment by jaredpalmer** [comment]
You just setup a some Vue specific stuff on your own. Your first remove all the React stuff and add vue-loader.

**Comment by markserrano915** [comment]
Thanks @jaredpalmer but I'm wondering how's that different from just running the `vue-cli`.

I guess I was under the impression that you can create a vue app similar to how you can create a react app in the cli.

**Comment by jaredpalmer** [comment]
Not yet. All we need is to add it to the examples directory though!
