### ISSUE TITLE
Example with redux and react router

### ISSUE THREAD

**Issue by JamesLeBoeuf** [jaredpalmer/razzle#467]
Hi Razzle team,

Just wanted to first say thanks for doing such an amazing job with this codebase and the ideas surrounding it. It's pretty much exactly what I was looking for without all the bloat.

This isn't really an issue per se but more of an open question. In short I'm wondering if there is an example package with react router & redux. I've searched through all the open and closed requests and the closest thing I have found is https://github.com/jaredpalmer/react-router-nextjs-like-data-fetching .

I was wondering if their might be plans to create an example app that would extend the repo that I've listed to include redux? The closest repo I have found that answers this is https://github.com/faceyspacey/redux-first-router-demo but I am a huge fan of the simplicity of what the razzle codebase does. For my needs the faceyspacey repo seems a bit much.

I've tried pretty extensively extending the 'with-redux' codebase to include react router but seem to not have much luck.

Cheers!
James

Also. Really happy to see the CSS Modules being brought in!

**Comment by siasjustin** [comment]
A good example of this would be a splendid idea! Its a pain to set up and documentation is slim.

**Comment by CallumHemsley** [comment]
I second this, a nice example would be great.

**Comment by rohanrana** [comment]
well i have integrate redux in already developed razzle app hope this will help 
[Git hub Repo](https://github.com/rohanrana/react-redux-with-ssr)
