### ISSUE TITLE
Deployment not working without node_modules folder

### ISSUE THREAD

**Issue by ash-vd** [jaredpalmer/razzle#475]
I'm trying to deploy my app to a Ubuntu server, using GitLab. I'm currently building in GitLab, and then copying the build folder to the server. This however doesn't work when I try to `node server.js`:

```Error: Cannot find module 'react'```

I found out that it works when I copy my node_modules folder to the server, but is it designed to work that way?

**Comment by iamrommel** [comment]
The way i did was i was using using extra "dist" folder. The "dist" is my webpack output, it is the production compiled/minified files, and my npm start script was pointing into from the "node dist/index.js",  

The key here is the "dist" folder, it should be the output runnable folder, if you are able to run it on your local just using node then it should work on CDD

**Comment by Metnew** [comment]
That's because of `webpack-node-externals` package. 
https://www.npmjs.com/package/webpack-node-externals
Razzle has kind of this snippet in webpack configuration (`createConfig.js`):
```
nodeExternals({
			whitelist: [
				!isProduction ? 'webpack/hot/poll?300' : null,
				/\.(eot|woff|woff2|ttf|otf)$/,
				/\.(svg|png|jpg|jpeg|gif|ico)$/,
				/\.(mp4|mp3|ogg|swf|webp)$/,
				/\.(css|scss|sass|sss|less)$/
			].filter(x => x)
		})
```

So, yeah, it's designed to work that way
