### ISSUE TITLE
For some reason i want the output of razzle build to be on "dist" folder, how can i do that?

### ISSUE THREAD

**Issue by iamrommel** [jaredpalmer/razzle#476]
For some convention for my deployment team, we want out final build to be on 'dist' folder, how can i do that?

Currently it is always on the build folder, the normal development build is fine with me that it's on the build folder for the output, but i want it to be different when it's a production build, something like "dist" folder

**Comment by jaredpalmer** [comment]
You can modify that in razzle.config.js

**Comment by iamrommel** [comment]
Sampl please

**Comment by iamrommel** [comment]
After some tinkering at webpack here is my output,
 `
const path = require('path')

module.exports = {
  modify(config, {target, dev}, webpack) {
    const appConfig = config

    if (target === 'node' && !dev) {
      //target for backend
      appConfig.output.path = path.resolve(__dirname, 'dist/')
    }
    else if (target === 'web' && !dev) {
      //target for frontend
      appConfig.output.path = path.resolve(__dirname, 'dist/public')
    }

    return appConfig
  },
}
`


I think it should be better this way, so the development output (folder named build), which always gets a lot of hotmodule stuff can be can be ignored and the dist folder can be check-in for deployment. of course the npm start script was pointed  to dist folder too

**Comment by iamrommel** [comment]
![image](https://user-images.githubusercontent.com/177265/35680023-044ccb54-0794-11e8-9f77-959e002e350c.png)
How can i change the value of appBuild and appBuildPublic folder

The build was successful, just this filesize reporter got issue
![image](https://user-images.githubusercontent.com/177265/35680364-137810ce-0795-11e8-98b6-c1e21fdd62b8.png)

**Comment by iamrommel** [comment]
For some reason it's getting complicated, reverting the whole changes, and uses the default razzle config and just copy the build folder to dist folder. https://www.npmjs.com/package/ncp helps do the job of copying
