### ISSUE TITLE
Relationship with after.js and roadmap

### ISSUE THREAD

**Issue by ewolfe** [jaredpalmer/razzle#479]
Would you mind describing the relationship between this project and after.js? How would a person decide to use one or the other? Do you see this project sticking around or getting completely absorbed by after.js? (I ask because of this commit https://github.com/jaredpalmer/after.js/commit/9406e78c4e7b86a2797ed294a757ef319b4ee93b)

**Comment by jaredpalmer** [comment]
Razzle isn't going anywhere. It's being used on cars.com, coinbase, and on all the sites that I am working on. I do want to move one of my projects over to After, but I need to do a lot of work on after before doing so.

The 2 big questions I haven't figured out yet is whether 1) there are ever going to be opinionated After.js optimizations that cannot be accomplished with Razzle and 2) if either could one day be refactored into some Node.js middleware. 

Roadmap:

- razzle plugins
- breakout razzle into more granular packages
- decide if after.js should be a "plugin" (my goal) or live on its own, but use some of the granular razzle packages

**Comment by paOol** [comment]
I think most of us just want razzle but with server-side data-fetching (getInitialProps)

**Comment by jaredpalmer** [comment]
Yeah that's probs the best of both worlds. So then after.js could then be refactored into it's lazy load helper, render middleware, and route helper and just imported into razzle or be the default example.
