### ISSUE TITLE
redux devtools Chrome extension

### ISSUE THREAD

**Issue by iampeter** [jaredpalmer/razzle#480]
I have tried using the https://github.com/zalmoxisus/redux-devtools-extension according to their instructions, with no luck. 

Does anyone have an idea of how to use it in Razzle?

**Comment by Metnew** [comment]
Razzle is not connected to Redux, there is no difference between using this extension in any starter. Probably, your extension initialization is wrong. Try to check `composeWithDevTools` usage

**Comment by iampeter** [comment]
@Metnew true mea culpa, it was just very late.
