### ISSUE TITLE
Add scss and less plugins

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/razzle#487]

**Comment by dizthewize** [comment]
any news on this being integrated yet?

**Comment by alejodaraio** [comment]
I did this extending in razzle.config.js

```
"use strict";

const MiniCssExtractPlugin = require("mini-css-extract-plugin");

module.exports = {
  modify: (config, { target, dev }, webpack) => {

    const appConfig = Object.assign({}, config);

    // Setup SCSS
    if (target === "web") {

      appConfig.module.rules.push(
        {
          test: /\.(sa|sc|c)ss$/,
          use: [
            dev ? 'style-loader' : MiniCssExtractPlugin.loader,
            'css-loader',
            'sass-loader',
          ]
        }
      );

    }
    else {
      // On the server, we can just simply use css-loader to
      // deal with scss imports
      appConfig.module.rules.push({
        test: /\.(sa|sc|c)ss$/,
        use: "css-loader"
      });
    }

    return appConfig;
  }
};
```

Dev dependencies:

```
"devDependencies": {
    "css-loader": "^1.0.0",
    "mini-css-extract-plugin": "^0.4.1",
    "node-sass": "^4.9.2",
    "razzle": "^2.4.0",
    "sass-loader": "^7.1.0"
  }
```

**Comment by CharlyJazz** [comment]
@jaredpalmer  Could you add the Hacktoberfest label?

**Comment by jaredpalmer** [comment]
Yup

**Comment by jaredpalmer** [comment]
Good Idae

**Comment by CharlyJazz** [comment]
Of course, what do you mean with plugin? Like next official plugins?

**Comment by jaredpalmer** [comment]
There are official plugins in the packages directory. You can see some examples there.

**Comment by jorgenader** [comment]
I'll share my version of scss integration as well, maybe it is useful for someone.

I thought that I should not need to redefine css rules for scss so I'm just making a copy of the original and adding scss loader.
```
'use strict';

const makeLoaderFinder = require('razzle-dev-utils/makeLoaderFinder');
const paths = require('razzle/config/paths');

const cssLoaderFinder = makeLoaderFinder('css-loader');
module.exports = {
    modify(baseConfig, {dev}, webpack) {
        /* make a copy of config */
        const config = Object.assign({}, baseConfig);

        const scssLoader = {
            loader: require.resolve('sass-loader'),
            options: {
                sourceMap: dev,
            },
        };

        // Copy base css rules and add scss support
        config.module.rules.filter(cssLoaderFinder).forEach(rule => {
            const isCssModuleRule = !rule.test.test('module.css');
            const scssExclude = [paths.appBuild];
            let scssTest = /\.s[ac]ss$/;
            if (isCssModuleRule) {
                scssTest = /\.module\.s[ac]ss$/;
            } else {
                scssExclude.push(/\.module\.s[ac]ss$/);
            }

            // Use default configs
            config.module.rules.push({
                test: scssTest,
                exclude: scssExclude,
                use: [
                    ...rule.use,
                    scssLoader,
                ]
            });
        });
        
        // adding ./src to module resolver so I can import modules with absolute paths
        config.resolve.modules.push('./src');

        return config;
    },
};
```

**Comment by Toyurc** [comment]
> I'll share my version of scss integration as well, maybe it is useful for someone.
> 
> I thought that I should not need to redefine css rules for scss so I'm just making a copy of the original and adding scss loader.
> 
> ```
> 'use strict';
> 
> const makeLoaderFinder = require('razzle-dev-utils/makeLoaderFinder');
> const paths = require('razzle/config/paths');
> 
> const cssLoaderFinder = makeLoaderFinder('css-loader');
> module.exports = {
>     modify(baseConfig, {dev}, webpack) {
>         /* make a copy of config */
>         const config = Object.assign({}, baseConfig);
> 
>         const scssLoader = {
>             loader: require.resolve('sass-loader'),
>             options: {
>                 sourceMap: dev,
>             },
>         };
> 
>         // Copy base css rules and add scss support
>         config.module.rules.filter(cssLoaderFinder).forEach(rule => {
>             const isCssModuleRule = !rule.test.test('module.css');
>             const scssExclude = [paths.appBuild];
>             let scssTest = /\.s[ac]ss$/;
>             if (isCssModuleRule) {
>                 scssTest = /\.module\.s[ac]ss$/;
>             } else {
>                 scssExclude.push(/\.module\.s[ac]ss$/);
>             }
> 
>             // Use default configs
>             config.module.rules.push({
>                 test: scssTest,
>                 exclude: scssExclude,
>                 use: [
>                     ...rule.use,
>                     scssLoader,
>                 ]
>             });
>         });
>         
>         // adding ./src to module resolver so I can import modules with absolute paths
>         config.resolve.modules.push('./src');
> 
>         return config;
>     },
> };
> ```

Hi, please what devDependencies would I need to use this your razzle config?. you failed to mention them

**Comment by jorgenader** [comment]
@Toyurc I used `node-sass@4.9.4` and `sass-loader@7.1.0`.

**Comment by tcpaul** [comment]
Hi is there any quick fix to read less?
I get 
```
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
> @import
```
no matter what I install etc

**Comment by jorgenader** [comment]
> Hi is there any quick fix to read less?
> I get
> 
> ```
> Module parse failed: Unexpected character '@' (1:0)
> You may need an appropriate loader to handle this file type.
> > @import
> ```
> no matter what I install etc

For `.less` config might look like this. I have not used less, only sass but general rules should still apply.
```
'use strict';

const makeLoaderFinder = require('razzle-dev-utils/makeLoaderFinder');
const paths = require('razzle/config/paths');

const cssLoaderFinder = makeLoaderFinder('css-loader');
module.exports = {
    modify(baseConfig, {dev}, webpack) {
        /* make a copy of config */
        const config = Object.assign({}, baseConfig);

        const lessLoader = {
            loader: require.resolve('less-loader'),
            options: {
                sourceMap: dev,
            },
        };

        // Copy base css rules and add less support
        config.module.rules.filter(cssLoaderFinder).forEach(rule => {
            const isCssModuleRule = !rule.test.test('module.css');
            const lessExclude = [paths.appBuild];
            let lessTest = /\.less$/;
            if (isCssModuleRule) {
                lessTest = /\.module\.less$/;
            } else {
                lessExclude.push(/\.module\.less$/);
            }

            // Use default configs
            config.module.rules.push({
                test: lessTest,
                exclude: lessExclude,
                use: [
                    ...rule.use,
                    lessLoader,
                ]
            });
        });
        
        // adding ./src to module resolver so I can import modules with absolute paths
        config.resolve.modules.push('./src');

        return config;
    },
};
```
`less-loader` and `less` need to be installed.

**Comment by erchaves** [comment]
I'm just skimming through some old issues about scss which I believe are resolved now. It doesn't look like there is a less package at this time, but there is a scss plugin now fyi.

The scss package is now published here and works great for me.
https://www.npmjs.com/package/razzle-plugin-scss

See example here:
https://github.com/jaredpalmer/razzle/tree/master/examples/with-scss

**Comment by fivethreeo** [comment]
Both added in next branch, closing
