### ISSUE TITLE
Add offline plugin

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/razzle#491]

**Comment by Metnew** [comment]
Will OfflinePlugin be included in razzle by default?
How can it be overridden/excluded in this case? (without filtering plugins inside `razzle.config.js`)
Or do you mean razzle-offline-plugin?

**Comment by jaredpalmer** [comment]
Razzle-offline-plugin ;)

**Comment by zebapy** [comment]
https://github.com/mschipperheyn/razzle-plugin-offline isn't published it seems. Will you be adding it?
