### ISSUE TITLE
Yarn start does not start the Server (but NPM does)

### ISSUE THREAD

**Issue by kedoska** [jaredpalmer/razzle#505]
After creating the project, the output in console (probably from `create-react-app`) is this one
```
> Success! Installed dependencies for test1

  Awesome! You're now ready to start coding.
  
  I already ran yarn for you, so your next steps are:
    cd test1
  
  To start a local server for development:
    yarn start
  
  To build a version for production:
    yarn build

  To run the server in production:
    yarn start:prod

```
However, 

`yarn start` is not starting the web server.
`npm start` works just fine.

```
 DONE  Compiled successfully

Your application is running at http://localhost:3000

✅  Server-side HMR Enabled!
🚀 started
```

**Comment by jaredpalmer** [comment]
Weird. Will have to try this out.

**Comment by corydeppen** [comment]
Could this be related to #292? I'm seeing this happen on Win10 using Yarn, where it runs fine on the second attempt.

**Comment by kedoska** [comment]
No, if is #292 is confirmed to be windows only. I'm on Linux mint.

**Comment by kedoska** [comment]
Small update,
today i created another project from scratch.

the first `yarn start` did not reached the `Server-side HMR Enabled!`
the second intent went OK

```
Your application is running at http://localhost:3000

✅  Server-side HMR Enabled!
🚀 started
```

So apparently it is not related with `yarn`

**Comment by marcellobarile** [comment]
I'm experiencing the same issue and I'm not using yarn (the same behavior appears on Windows and GNU/Linux)... sometimes the process just got stuck on "Your application is running at http://localhost:3000" (no other outputs) even though the server is never started.

**Comment by josesuarezcordova** [comment]
I have the same issue  on Mac

after run 

yarn start

I got apparently everything fine

Sorry , I get the same error after run

yarn start

seems like everything fine

[Browsersync] Access URLs:
Local: http://localhost:3000
External: http://192.168.1.37:3000
UI: http://localhost:3001
UI External: http://192.168.1.37:3001

the browser open but never load the web, my project is under bedrock the structure of web folder is

web
----app
------mu-plugins
------plugins
------themes
------uploads
----wp
-------wp-admin
-------wp-content
-------wp-includes

I ran already yarn install on root folder and theme folder too

thanks!
