### ISSUE TITLE
Interested in a updated reason example?

### ISSUE THREAD

**Issue by ulrikstrid** [jaredpalmer/razzle#512]
So I've tinkered with razzle and reason and even got routing working (client and server) with the new built in ReasonReact router.
Want me to clean it up and make a PR?

**Comment by jaredpalmer** [comment]
Yes please!

**Comment by ulrikstrid** [comment]
Will do in the next couple of days then 👍

**Comment by ulrikstrid** [comment]
This should have been closed as my PR was merged
