### ISSUE TITLE
Resolve.alias is ignored in razzle.config.js 

### ISSUE THREAD

**Issue by JoshuaJones** [jaredpalmer/razzle#523]
In `webpack.config.js` we have the option to configure aliases. For example:

```
resolve: {
    alias: {
      'components': path.resolve(__dirname, 'src/js/components/'),
      'containers': path.resolve(__dirname, 'src/js/containers/'),
    },
},
```

The above works in an existing project, but the following in a razzle.config.js:

```
module.exports = {
  modify: (config, { target, dev }) => {
 
    config.resolve['alias'] = {
        'components': path.resolve(__dirname, 'src/js/components/'),
        'containers': path.resolve(__dirname, 'src/js/containers/'),
    }

    return config;
  }
};
```

produces the following errors:

`Module not found: Can't resolve 'components/Button'`

I couldn't find any examples or previous issues related to this. Does razzle not support the use of aliases in the config?

**Comment by jaredpalmer** [comment]
Hmm. Not sure why that didn't work. The way I have it our codebase is

```
config.resolve.alias.common = path.resolve('./src/common');
```

Can you try without the `__dirname` and report back?

**Comment by JoshuaJones** [comment]
It was indeed the `__dirname` that screwed it up. Thanks for the feedback, closing.

**Comment by bryaan** [comment]
This doesn't seem to be working anymore

    config.resolve.alias = {
      '~': path.resolve('./src'),
      '@layouts': path.resolve('src/layouts/')
    }

./src/routes/Home/Home.js
Module not found: Can't resolve '~/layouts/FrontPageLayout' in '/Users/bryan/Developer/hirefeed/hirefeed-web/src/routes/Home'
