### ISSUE TITLE
Interested in the Terminal style in README

### ISSUE THREAD

**Issue by yijiasu** [jaredpalmer/razzle#524]
This terminal screenshot in README looks so cool. I am wondering if I could know which appearance plug-in make such effects...

![](https://cloud.githubusercontent.com/assets/4060187/26324663/b31788c4-3f01-11e7-8e6f-ffa48533af54.png)

**Comment by jaredpalmer** [comment]
Hyper.sh and just macOS’s built in screenshot capture of a window
