### ISSUE TITLE
CSS "pop-in" / CSS always bundled in js

### ISSUE THREAD

**Issue by aforty** [jaredpalmer/razzle#529]
The CSS seems to pop-in as it is always being loaded from the js bundle rather than compiled into a separate file. 

In `src/server.js` `assets.client.css` is never defined and I can't seem to find any proper documentation on how to accomplish this. My main problem with the bundling approach is that the CSS pops in a few milliseconds after page load which makes for a jarring experience for the user.

Am I missing something super obvious or is this just how it works? I even used `create-razzle-app` and the only mention of CSS is in the generated README.md where css-modules are referenced.

**Comment by jaredpalmer** [comment]
This jank only happens during dev. It's something that will be removed when we move to webpack 4.

**Comment by aforty** [comment]
Hmm I did test this in production and saw the same pop-in behavior because even in production the css is bundled with the js. 

Running `yarn build` produced the following `build/assets.json` file.

{"client":{"js":"/static/js/bundle.5d7488da.js"}}

**Comment by aforty** [comment]
I thought I was seeing it in production as well but that was my fault, added sass support and wasn't extracting it correctly. Good to hear about Webpack 4, thanks!
