### ISSUE TITLE
Bring your own dependencies

### ISSUE THREAD

**Issue by bartlangelaan** [jaredpalmer/razzle#534]
Razzle is awesome because of it's no-config-needed approach. Everything works out of the box.

To make this all possible, Razzle has a lot of dependencies. Currently, these dependencies are locked. It seems like they are locked since 2e68e7dd399131369aee51e3c1f3a27f40e7e940.

By locking these dependencies, it's hard for projects that use razzle to upgrade to a newer version of these dependencies. For example, eslint is currently locked at `4.5.0` while the latest version is `4.18.2`. As stated in #404, old dependencies can become incompatible with other modules like eslint-config-airbnb.

If you run `yarn add eslint`, the newest version of eslint will be added to the project. But Razzle will still use the old version, because it's dependencies are locked. The only way to make Razzle use the new eslint is by changing the webpack config, but the old eslint will still be installed while it's never used.

Why were the Razzle dependencies locked? When they are loosened with a caret, it would be easier for users to update modules like eslint and babel. As long as dependencies uphold semver, updating them won't break Razzle.

**Comment by jaredpalmer** [comment]
Totally understand the frustration. Razzle runs on a lot of mission critical applications for my clients, so locking down deps is just a habit. When Babel 7 is released, I plan to do a large overhaul. I will consider relaxing them.

**Comment by jaredpalmer** [comment]
Feel free to submit a PR with the changes to eslint you'd like to see

**Comment by AndyArcherKG** [comment]
Any ideas when this will get a npm tag so we can pull this as a dependency?

**Comment by jaredpalmer** [comment]
I have been working on 2. I think it’s about time to tag 0.8 as 1

**Comment by JP-GNL** [comment]
Following on from @bartlangelaan's comment - I was also trying to use `eslint-config-airbnb` with Razzle. However, it relies on eslint `^4.9.0` and Razzle uses `4.5.0`, so I've upgraded to `4.19.1` in my app and remapped Razzle's eslint to use my local app's:

```
config.module.rules[0].use[0].options.eslintPath = path.resolve(__dirname, 'node_modules/eslint');
```
Hope this helps.

**Comment by AndyArcherKG** [comment]
@JP-GNL in which file did you put this?

**Comment by JP-GNL** [comment]
Sorry, should have said: `razzle-config.js` in your app root.

**Comment by AndyArcherKG** [comment]
So for clarity, using the example for `custom webpack config` the completed file would look something like this:

```
'use strict';
const path = require('path');
module.exports = {
  modify(config, { target, dev }, webpack) {
    config.module.rules[0].use[0].options.eslintPath = path.resolve(__dirname, 'node_modules/eslint');
    return config;
  },
};
```

**Comment by nolandg** [comment]
Thank you @AndyArcherKG! I was fighting with this for a while, your solution works perfectly, didn't realize that was possible.
