### ISSUE TITLE
How to integrate with react-intl?

### ISSUE THREAD

**Issue by nickretallack** [jaredpalmer/razzle#536]
Razzle seems pretty nice for dev.  I'm pretty impressed with it.  But, how would you write such an app with internationalization and translation support?  This is something that has to interact pretty intimately with the server and client side rendering system, since you want to be able to produce server-side rendered content in any language but you only want to ship the messages for a particular language on the client side to keep things light.  I'd appreciate it if you had a guide on how to integrate this.

**Comment by felipeleusin** [comment]
You should probably use a custom renderer to include your IntlProvider with the correct messages in the server.

In the client I would recommend using dynamic imports to be able to load the bundle. If you want to include the current locale messages directly you can include it as a global variable or with data.

**Comment by cheapsteak** [comment]
Anyone else run into this? Code samples would be great
