### ISSUE TITLE
The start:prod Does Not Work on Windows

### ISSUE THREAD

**Issue by dhurlburtusa** [jaredpalmer/razzle#541]
I get the following error message when I `yarn start:prod`:

```
'NODE_ENV' is not recognized as an internal or external command, ...
```

I found that using `cross-env` makes it work.

I'll create a PR for this.

In the meantime, here is the workaround:

```sh
yarn add --dev cross-env
```

In `package.json`, prefix the `start:prod` command with `cross-env ` like so:

```json5
    "start:prod": "cross-env NODE_ENV=production node build/server.js"
```

**Comment by krystianjj** [comment]
In Windows you must use **set NODE_ENV=production** and && between command
try:
`"start:prod": "cross-env && SET NODE_ENV=production && node build/server.js"`

**Comment by dhurlburtusa** [comment]
`"start:prod": "cross-env && SET NODE_ENV=production && node build/server.js"` will break the `cross-env` command which is expecting a set of environment variables being set followed by a command with arguments.

Also, I don't want to make `start:prod` only work in Windows only.
