### ISSUE TITLE
Webpack 4

### ISSUE THREAD

**Issue by John0x** [jaredpalmer/razzle#544]
Hello, are there any ETA on webpack 4 support?

**Comment by krazyjakee** [comment]
Here is the thread to watch. Once that is merged, then razzle can make use of it: https://github.com/facebook/create-react-app/pull/4077

**Comment by rafbcampos** [comment]
The PR [#525](https://github.com/jaredpalmer/razzle/pull/525) has already been merged. Razzle @ next already has Webpack V4.
