### ISSUE TITLE
Render method fired twice

### ISSUE THREAD

**Issue by mkrds** [jaredpalmer/razzle#557]
Hi,

I've noticed that render method of for example Home component in default razzle template is called twice - once on the server and again on the client. I've simply put `console.log('render')` in render method to check it. Is that behavior intended? I've checked few SSR examples and usually render was only called on the server.
Nevertheless I have to say that razzle helped me a lot with SSR. I'd say that it provides the easiest way to get up and running with SSR in react so big thanks for making it! :).

**Comment by jaredpalmer** [comment]
Hrmmm that shouldn’t be the case. Perhaps there is a bug in the example. Will take a look today. What version are you running on?

**Comment by mkrds** [comment]
"razzle": "0.8.14"

I've created a new app just now, and it still happens.
FYI I've read somewhere that render might be run twice, since:
1. HTML is rendered on the server - so the render method has to be fired.
2. All the handlers and JS is attached on client side - so the render method has to be fired again.

Although I'm not entirely convinced by that explanation :)
