### ISSUE TITLE
razzle start: Cannot find module `/build/assets.json`

### ISSUE THREAD

**Issue by ipostol** [jaredpalmer/razzle#568]
Hello, 
Have some problem, when i am use `razzle start` i see error, its not critical after some time app up, but i think we can try fix this.

in start script

start.js
```
 // Compile our assets with webpack
 const clientCompiler = compile(clientConfig);
```

client compiler (he create `assets.json file`)

but server compiler call before and when we use some code on server like
start.js
```
const serverCompiler = compile(serverConfig);
```
server.js (custom)
```
const assets = require(process.env.RAZZLE_ASSETS_MANIFEST)
``` 

i think replace client compile before server with this problem

**Comment by jaredpalmer** [comment]
This is out in 2.0.0-alpha.8.

**Comment by drejohnson** [comment]
On 2.0.0-alpha.8 I'm still seeing this error.

**Comment by ipostol** [comment]
@jaredpalmer , https://github.com/jaredpalmer/razzle/pull/575 in this PR fix for start server after webpack `done` hook (https://github.com/webpack/docs/wiki/plugins#donestats-stats)
