### ISSUE TITLE
Current latest release has detected vulnerabilities 

### ISSUE THREAD

**Issue by pcraig3** [jaredpalmer/razzle#572]
We're using [after.js](https://github.com/jaredpalmer/after.js) for a new project we're working on, and our [Snyk vulnerability check](https://snyk.io/org/cdssnc/test/github/cds-snc/ircc-rescheduler/e05df5a579cf1afe4700b0b69a3337428f646300?severity=high&severity=medium&severity=low) has detected some vulnerabilites in Razzle. 
- 5 are low severity
- 2 are medium severity

We're currently on the latest release, so we can't get rid of them until Razzle is updated. What do you suggest?

**Comment by jaredpalmer** [comment]
Can you submit a PR with changes?

**Comment by pcraig3** [comment]
Yeah, sure.

**Comment by jaredpalmer** [comment]
Thanks!

**Comment by pcraig3** [comment]
As a latent follow-up, I'm not sure when/if I'll have time to do this. 
We can keep it open for a few more weeks, but I can't promise anything.

**Comment by pcraig3** [comment]
Closing because these have pretty much been mitigated.
