### ISSUE TITLE
Unexpected token (

### ISSUE THREAD

**Issue by FreedCapybara** [jaredpalmer/razzle#573]
(Opening this issue so that maybe someday it will help somebody on the internet 🙏)

`yarn start` on a new project was giving me an error like
```
module.exports = async () =>

Unexpected token '(' at node_modules/razzle/razzle-dev-something.js
```
(the actual error text is lost, so that'll have to be good enough for you)

## What worked for me
Check your version of node. If it's super old like mine was (I was on 5.x), update it and try again. `yarn start` should fire up your Razzle app.

**Comment by jaredpalmer** [comment]
Yeah Razzle requires async/await support.
