### ISSUE TITLE
razzle start: Cannot find module `/build/assets.json`

### ISSUE THREAD

**Issue by ipostol** [jaredpalmer/razzle#578]
maybe my comment is lost, reopen this issue https://github.com/jaredpalmer/razzle/issues/568
https://github.com/jaredpalmer/razzle/pull/575

**Comment by lfantone** [comment]
Also the same issue described #565 
Still happen with latest alpha release

**Comment by jaredpalmer** [comment]
Yeah. It’s a race condition. Otherwise we will have 2x slow start times. I’m he best option is to actually switch to manifest plugin and use a transform fn to make it output like assets webpack and have manifest seed the file with the defaults.
