### ISSUE TITLE
2.0.0-alpha.9 build error: webpack.optimize.UglifyJsPlugin has been removed, please use config.optimization.minimize instead.

### ISSUE THREAD

**Issue by MarkLyck** [jaredpalmer/razzle#579]
after removing node_modules and installing razzle 2.0.0-alpha.9 I get the following error when running build:

`webpack.optimize.UglifyJsPlugin has been removed, please use config.optimization.minimize instead.`

The weird thing is that I console.logged the config from Razzle, and that .uglifyJsPlugin doesn't seem to be there, and in the source code on GitHub it looks alright too?

my razzle.config.js file:

```js
const path = require('path')
const OfflinePlugin = require('offline-plugin')

module.exports = {
    modify: (config, { target, dev }, webpack) => {
        console.log(config)
        if (!dev && target === 'web') {
            config.plugins.push(new OfflinePlugin({
                relativePaths: false,
                publicPath: '/',
                caches: 'all',
                externals: [ '/' ],
                ServiceWorker: {
                    output: './sw.js',
                    navigateFallbackURL: '/'
                }
            }))
        }

        return config;
    },
};
```

I checked my node_modules as well. and oddly razzle version seems to be "version": "2.0.0-y.0",

**Comment by MarkLyck** [comment]
Hmm I created a new app from scratch using create-razzle-app, upgraded that to the same version and it works. Then tried to install the same packages and found out that offline-plugin somehow breaks in the newest version of Razzle 😞 

I suppose this is a bug to fix on offline-plugin's side, so closing the issue. But I thought I'd leave it here if anyone else runs into the same problem after upgrading to 2.x

**Comment by jaredpalmer** [comment]
Interesting. Thanks for posting this
