### ISSUE TITLE
v2: hmr isn't working if PORT not set

### ISSUE THREAD

**Issue by gregmartyn** [jaredpalmer/razzle#582]
This is for the "next" branch.

If the PORT environment variable isn't specified, webpackHotDevClient.js is using window.location.port for the SockJS connection when it should be window.location.port + 1.

Additionally, if the page is served on port 80, then window.location.port = ''. I'm only hitting that because I have razzle.config.js removing PORT from the DefinePlugin array as a stopgap until #528 moves forward. Regardless, it's a case that can be handled pretty easily.

I've created #581 to address both of those issues.

**Comment by gregmartyn** [comment]
@jaredpalmer this is still an issue for me, fixed by the #581 pr.

**Comment by gregmartyn** [comment]
@jaredpalmer is there anything left to do for #581 to be accepted? Seems like a simple fix to me. window.location.port returns "" if port is 80, and that wasn't being handled by the existing code.

**Comment by gregmartyn** [comment]
still not stale

**Comment by fivethreeo** [comment]
Fixed. Closing
