### ISSUE TITLE
thread-loader's 'poolTimeout' should be overridden when watching

### ISSUE THREAD

**Issue by edmorley** [jaredpalmer/razzle#587]
Hi!

Currently razzle uses [thread-loader](https://github.com/webpack-contrib/thread-loader) to speed up babel-loader:
https://github.com/jaredpalmer/razzle/blob/0632d9b056561a7c77d7210bf97fe5270c009929/packages/razzle/config/createConfig.js#L134

This configuration is fine in production, however as [mentioned here](https://github.com/webpack/webpack/issues/7086#issuecomment-383467496), when watching is enabled (ie in development mode with webpack-dev-server) the `poolTimeout` option should be changed from its default of `500` ms to `Infinity` to avoid paying the overhead of worker startup on every rebuild.

See:
https://github.com/webpack-contrib/thread-loader#examples

**Comment by jaredpalmer** [comment]
Can you submit a PR?
