### ISSUE TITLE
What are you struggling with?

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/razzle#59]

**Comment by ranyefet** [comment]
Managing CSS is a little bit cumbersome. 
I'm using [BassCSS](http://www.basscss.com/) as a global utility library and use it with Aphrodite in components like:
```js
const styles = StyleSheet.create({
  header: {
    backgroundColor: 'red',
  }
});

const Header = () => <div className={`m1 p2 ${css(styles.header)}`}>...</div>
```

Also adding third party components with their own CSS is messy, I either add their CSS into my "global" css file or just write my own styles if possible. 

Besides CSS, I guess working with static assets like images also needs special solution to work in server side rendering so it could be improved as well. 

Thanks for the great work!

**Comment by jaredpalmer** [comment]
Yeah Aphrodite biggest downfall is that can't compose / curry styles easily. Thus default styles are almost impossible. 

I have been using Pete Hunt's jsxstyle in a few projects recently. My main issue with it is that buttons are really really annoying to deal with.

**Comment by sebastiancarlsson** [comment]
I'm having problems with CSS as well, I want to use scss and tried to install the isomorphic-style-loader that is mentioned in issue #60, but I can't get it to work, I get this error: 

"Warning: Failed Context Types: Required context `insertCss` was not specified in `WithStyles(App)`. Check the render method of `RouterContext`". 

The author of isomorphic-style-loader has an example project but his router is set up in some different way and I don't understand what I should do to make this work.

**Comment by developerwok** [comment]
How would you guys approach user authentication for this project?

**Comment by jaredpalmer** [comment]
@developerwok Use `passport-js` + whatever strategy you want (FB, Github, etc), `express-session`, and `connect-redis` / `connect-mongo` for session persistence.  Then pass `req.user` to your redux store through initial state. You then can write some `ensureAuth()` express middleware to protect API routes and use `redux-auth-wrapper` to protect `react-router` routes.

**Comment by jaredpalmer** [comment]
@developerwok did that help?

**Comment by misterfresh** [comment]
Hi Jared, I'm not getting 'redial'. It looks complicated and yet another abstraction layer. Would it be possible to make the data-fetching isomorphic simply by adding in the action creators something like:
```
if(window)
  return dispatch ( fetch(url) ).then(do stuff) 
else
 return dispatch ( db.select(posts) ) .then(do stuff)
```

Just asking I haven't completely understood how isomorphic data-fetching works.
 
The other thing I'm not sure I understand is the async routes / async reducers part. What's the purpose of making that async? If we have SSR, the page will be shown immediately to the user, and while he figures out what to do the bundle.js can load in the background. So it seems to me that if SSR is enabled, it isn't so crucial to reduce the size of the js download, and the added complexity of async routes / reducers is not worth it, especially for the kind of projects that would use a starter-kit to begin with. Feel free to correct me :)

**Comment by jaredpalmer** [comment]
Async routes ensure bundle size minimization and js sandboxing. For example, if you have a protected but sync route, _all_ of your app's js still gets bundled into your main js file. In contrast, if it's async, it get's chunked out and cannot be loaded without auth. This lets you scale out your app without ever worrying about bundle size or leaking sensitive logic to the client. I agree that this isn't a big deal for little apps, but if you have an app with ~20 routes (like we do on my team) it starts to become more important.

**Comment by misterfresh** [comment]
I tried to make my routes and reducer async, and it almost works but I get the following error : 

> combineReducers.js : 36 Unexpected properties "styles" found in previous state received by the reducer. Expected to find one of the known reducer property names instead: "display", "user", "project"

**Comment by jaredpalmer** [comment]
@misterfresh 

> Hi Jared, I'm not getting 'redial'. It looks complicated and yet another abstraction layer. Would it be possible to make the data-fetching isomorphic simply by adding in the action creators...

If you are struggling with redial, I suggest replacing it with more vanilla promise resolver. Github search for code with `fetchComponentData()` you'll find some examples of other promise resolution approaches.

**Comment by harrybabu** [comment]
It would be great if you can add a stateful component page to the boilerplate, this will help people who have just start adpoting the new react concepts...

**Comment by Quixomatic** [comment]
GET /api/v0/posts 304 302.139 ms - -
{ protocol: 'http',
  host: 'isomorphic-quixomatic.c9users.io:80' }
[TypeError: posts.data.map is not a function]

Not used to the new => markup but I tried converting it to just a plain old function returning what's inside the function and that still gave the same error.

**Comment by jhabdas** [comment]
I'm struggling with how awesome this boilerplate is. Prepare for takeoff. 😄

**Comment by walshe** [comment]
is there an easy way to access process.env variables from the client side ?

**Comment by jaredpalmer** [comment]
@walshe you can put stuff the `initialState` that is injected [here] (https://github.com/jaredpalmer/react-production-starter/blob/master/server/index.js#L64), make sure you update the respective [reducer too](https://github.com/jaredpalmer/react-production-starter/blob/master/common/createReducer.js#L2). Remember, never ever send any password/api-keys/sensitive info!

**Comment by walshe** [comment]
ah great, thanks

**Comment by andrewpenrose** [comment]
Doing a "npm run start:prod" and get the following and getting the error below. "npm start" works fine.

******************************************
module.js:328
    throw err;
    ^

Error: Cannot find module 'C:\git\react-production-starter\build\server.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "sta
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! react-production-starter@0.2.0 start:prod: `cross-env NODE_ENV=production node ./build/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-production-starter@0.2.0 start:prod script 'cross-env NODE_ENV=production node ./build/server.js'.
npm ERR! This is most likely a problem with the react-production-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production node ./build/server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-production-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by walshe** [comment]
how can I temporarily ignore all the js lint warnings ? 

I tried adding a .eslintignore at the root with 

**/*.js

nu made no difference

**Comment by jaredpalmer** [comment]
Remove the standard loader from webpack config.

**Comment by walshe** [comment]
can you be a bit more specific which part needs changing, I'm a newb to webpack


  module: {
    preLoaders: [
      {
        // set up standard-loader as a preloader
        test: /\.jsx?$/,
        loader: 'standard',
        exclude: /(node_modules)/
      }
    ],
    loaders: [
      {
        test: /\.js$/,
        loader: 'babel',
        exclude: /(node_modules|server)/,
        query: {
          cacheDirectory: true,
          presets: ["es2015", "react", "stage-0"]
        }
      },
    ]
  },

**Comment by lewis-elliott** [comment]
Do you have examples of nested routes? The containers within the nested routes get sent to the client but don't seem to render?

**Comment by jaredpalmer** [comment]
@lewis-elliott unfortunately, redial forces you to have "fat controllers." All SSR data fetching must be declared at the route component level.

**Comment by lewis-elliott** [comment]
@jaredpalmer Thanks for the quick response. So it's not possible to have routes like A/b/:bId/c using redial? Is this a drawback or done intentionally due to a best practice or pattern?

**Comment by jaredpalmer** [comment]
No it is. My mistake. I misunderstood your question. I thought you were talking about nested data fetching. You can checkout the react router 3 mega app demo. Basically, this uses the same technique, but wraps the route declaration in a function if you need to inject reducers.

**Comment by lewis-elliott** [comment]
So the way I tried to achieve that was nesting components ([like this](https://github.com/ReactTraining/react-router/tree/master/examples/huge-apps)) but the provide hooks are ignored on the components that are nested on child routes. I think [this](https://github.com/markdalgleish/redial/issues/28) is what you're referring to? I'll try and find that demo and go from there.

**Comment by sathishkategaru** [comment]
i am trying to use css files and included css loader in webpack, but cant get it working..Installed css-loaded, style-loader and in my webpack load
loaders: [
                ...,
             {
                test: /\.css$/,
                loader: 'style!css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]',
                exclude: /(node_modules|server)/
            }
]
I get following error while 
npm run start
> react-production-starter@0.2.0 start /Users/sathish/Desktop/Desktop/reactPro
> cross-env NODE_ENV=development node -r "babel-register" ./server

/Users/sathish/Desktop/Desktop/reactPro/node_modules/babel-core/lib/transformation/file/index.js:600
      throw err;
      ^

SyntaxError: /Users/sathish/Desktop/Desktop/reactPro/common/routes/Home/components/Home.css: Unexpected token (1:0)
> 1 | .text {
    | ^
  2 |     border: 1px solid black;
  3 | }
  4 | 
    at Parser.pp$5.raise (/Users/sathish/Desktop/Desktop/reactPro/node_modules/babylon/lib/index.js:4246:13)
    at Parser.pp.unexpected (/Users/sathish/Desktop/Desktop/reactPro/node_modules/babylon/lib/index.js:1627:8)
    at Parser.pp$3.parseExprAtom (/Users/sathish/Desktop/Desktop/reactPro/node_modules/babylon/lib/index.js:3586:12)
    at Parser.parseExprAtom (/Users/sathish/Desktop/Desktop/reactPro/node_modules/babylon/lib/index.js:6402:22)
    at Parser.pp$3.parseExprSubscripts (/Users/sathish/Desktop/Desktop/reactPro/node_modules/babylon/lib/index.js:3331:19)
    at Parser.pp$3.parseMaybeUnary (/Users/sathish/Desktop/Desktop/reactPro/node_modules/babylon/lib/index.js:3311:19)
    at Parser.pp$3.parseExprOps (/Users/sathish/Desktop/Desktop/reactPro/node_modules/babylon/lib/index.js:3241:19)
    at Parser.pp$3.parseMaybeConditional (/Users/sathish/Desktop/Desktop/reactPro/node_modules/babylon/lib/index.js:3218:19)
    at Parser.pp$3.parseMaybeAssign (/Users/sathish/Desktop/Desktop/reactPro/node_modules/babylon/lib/index.js:3181:19)
    at Parser.parseMaybeAssign (/Users/sathish/Desktop/Desktop/reactPro/node_modules/babylon/lib/index.js:5694:20)

I tried using this with no luck as it runs but production build still causes issues..
require.extensions['.css'] = () => {
    return;
};
Any ideas how to solve this..and how can i use extract-text-webpack-plugin to seperate css file and it can be cached..Thanks to exports in advance..

**Comment by lewis-elliott** [comment]
any idea how to get an indexRoute redirect working?

```javascript
   indexRoute: {
      onEnter: (nextState, replace) => {
        replace('foo')
      }
    },```

This returns a 404 when `foo` is a registered child route of root.

**Comment by kobkrit** [comment]
Can not run $ npm run build

```
> react-production-starter@0.2.0 build /Users/kobkrit/git/ibusWeb
> webpack -p --config ./tools/webpack.client.prod.js && webpack -p --config ./tools/webpack.server.prod.js

/Users/kobkrit/git/ibusWeb/tools/webpack.client.prod.js:32
    new webpack.DefinePlugin({
    ^^^
SyntaxError: Unexpected token new
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/kobkrit/git/ibusWeb/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/Users/kobkrit/git/ibusWeb/node_modules/webpack/bin/webpack.js:39:40)
```

![image](https://cloud.githubusercontent.com/assets/280986/22723778/b9687fc6-edf3-11e6-8a8b-2bf412831819.png)

**Comment by Alex-1989** [comment]
renderProps is undefined on the client side when trying to use onEnter for a route:

```javascript
export default function createRoutes (store) {
  return {
    path: 'foo(/:id)',
    getComponents (location, cb) {
      require.ensure([
        './containers/page',
      ], (require) => {
        let page = require('./containers/page').default
        cb(null, page)
      })
    },
    onEnter: (nextState, replace) => {
      if (nextState.params.id === undefined || nextState.params.id === null) {
        replace('/app/test/foo/someIdFromState')
      }
    }
  }
}```
Any idea how to fix this?

**Comment by ischyrus** [comment]
I tried to run the boilerplate in docker, here are the steps I took.

1) Cloned
2) npm install
3) npm start (server came up)
4) npm build
5) docker build -t [imagename] .
6) docker run [imagename]

The console says "server 1 listening on port 5000" although I would have expected it to come up on port 80. The site is not available on port 80 or 5000.
