### ISSUE TITLE
Puppeteer + Jest + Razzle?

### ISSUE THREAD

**Issue by rhodee** [jaredpalmer/razzle#590]
I am interested in implementing Puppeteer into an existing Razzle managed project (as proposed here: https://facebook.github.io/jest/docs/en/puppeteer.html).

For this to work the following keys need to be added `[globalSetup, globalTeardown, testEnvironment]` to this array: https://github.com/jaredpalmer/razzle/blob/next/packages/razzle/config/createJestConfig.js#L41.

Here is my desired setup for my package.json

```json
  "jest": {
    "globalSetup": "<rootDir>/config/jest/setup.ts",
    "globalTeardown": "<rootDir>/config/jest/teardown.ts",
    "testEnvironment": "<rootDir>/config/jest/puppeteer_environment.ts",
  }
```

Happy to make a PR - even happier to understand why preventing the keys being added was implemented so I can use that as a guide for understanding if adding it is the right thing to do, or exploring an alternative.

**Comment by jaredpalmer** [comment]
@rhodee was just to parallel CRA. Fine with opening up jest options. Feel free to submit a PR.

**Comment by rhodee** [comment]
Seems less necessary with 2.x out. Closing.
