### ISSUE TITLE
Webpack Config Exposure

### ISSUE THREAD

**Issue by AndyArcherKG** [jaredpalmer/razzle#591]
Hello just wondering if there was any chance you might have an `npm run eject` function similar to that of CRA so that we can look at the Webpack Config.

I appreciate you can add to the webpack config with the razzle.config.js but being able to see whats under the hood more specifically would be good.

**Comment by jaredpalmer** [comment]
Not at this time. Console.log ?

**Comment by TreTuna** [comment]
Yeah, I just did this in my razzle.config.js to see the underlying configuration:

```
module.exports = {
  modify: (config, { target, dev }, webpack) => {
    console.log(config);
    return config;
  }
};
```
