### ISSUE TITLE
Use of browser modules such as "window"?

### ISSUE THREAD

**Issue by awitherow** [jaredpalmer/razzle#594]
Hello! Really excited to use razzle in conjunction with heroku. I am new to this server side rendering stuff, and am not sure how to use the window module from the browser in conjunction with razzle.

For example, in my `index.js componentWillMount`, I execute the following code...

```javascript

  componentWillMount() {
    const localStorageState = JSON.parse(
      window.localStorage.getItem("example")
    );

    if (typeof localStorageState === "object") {
      this.setState({ ...localStorageState });
    }
  }
```

Is this not possible with a server side rendered application?

Looking forward to hearing from you guys and thanks for this cool little project,

Austin

**Comment by dfcarpenter** [comment]
I would say that if you are accessing something like localstorage, which is a client side (browser api), in your component, and also rendering on the server you should perhaps instead use componentDidMount. Therefore the fetching, parsing and setting of the component state will occur on DOM insertion. Besides not having access to the window object another issue with componentWillMount is that it will be called twice, once on the server render and again on the client.  Be careful with that.

**Comment by ComputerCarl** [comment]
There are some cases where I also test for a window object to conditionally run stuff on the client side;
```
if (typeof window !== 'undefined' && window.localStorage['feathers-jwt'] && !props.user) props.handleLogin();
```
