### ISSUE TITLE
Is it possible to build a client-side only static bundle?

### ISSUE THREAD

**Issue by jannisg** [jaredpalmer/razzle#597]
The production server obviously makes use of the full setup with SSR so `razzle build` is all I need for that.

I would like to (if possible) use Netlify's auto deployment scripts to publish a build per branch (PR branches mostly) however the Netlify service will only serve static files in this scenario.

In the traditional CRA build output is a static `index.html` file and this makes it work just fine in this static deployment environment, with razzle I can't figure out if there is any way to generate the client only without any of the SSR stuff so I could run that build (passing some build param or setting an .env flag) on Netlify while running the regular build for prod.

Any thoughts or tips would be great :)

---

Update: I've read through the razzle build script and createConfig script and after initially hoping that maybe seeing `BUILD_TARGET=client yarn build` producing a client-only build it seems obvious now that there is currently no hook to generate a static `index.html` file.

I guess the only way to get this working would be to extend the webpack config and add the HTML webpack plugin and a `public/index.html` template of some sort.

Is that right or am I missing something here?

**Comment by ComputerCarl** [comment]
There are some other packages specifically made for building static sites like `react-static` or `jekyll`. While Razzle is great at SSR, you may not need SSR.

**Comment by jaredpalmer** [comment]
This is outside the scope of Razzle. Just use CRA. Or create react app rewired

**Comment by jannisg** [comment]
Thanks for the responses, as I want to use SSR in the production env I will continue with razzle etc but at least I know it won't work the way I had hoped for static preview branches :)
