### ISSUE TITLE
Importing a module for client side only

### ISSUE THREAD

**Issue by tomtaylor** [jaredpalmer/razzle#606]
I've got a Map component that imports from ReactMapboxGl:

```
import ReactMapboxGl, { Feature, Layer } from 'react-mapbox-gl';
```

But when I use it, I get the following error in the server console and the server won't boot:

```
/Users/tom/projects/soigneur/node_modules/mapbox-gl/dist/mapbox-gl.js:509
"use strict";module.exports=self;
                            ^
ReferenceError: self is not defined
```

That's fine I think, I don't expect it to be able to render server side, so I'll use it client side only by setting some state inside `componentDidMount` that turns it on. However, even just importing the module causes this error, even when it's not being rendered.

How can I do a build time conditional in Razzle, so the entire library is excluded from the server side build? I'm using Typescript, if it matters.

I can see `process.env.BUILD_TARGET` but Typescript won't let me toggle on this unless I use a dynamic import, and I don't think that's what I want here.

**Comment by ComputerCarl** [comment]
You can dynamically import the module using `require` instead of using `import`.

**Comment by jaredpalmer** [comment]
Correct.

**Comment by jgibo** [comment]
Would using the es6  dynamic`import()` achieve the same result and would there be any differences in behaviour?

https://reactjs.org/docs/code-splitting.html#import

**Comment by nhimhobao** [comment]
The better solution is to use webpack feature for separate import. For example this is my folder structure
```
# tree src/components/phaserGame
src/components/phaserGame
├── index.js
├── index.server.js
└── package.json

```
And package.json file
```
{
  "name": "phaserGame",
  "main": "index.server.js",
  "browser": "index.js"
}
```
