### ISSUE TITLE
razzle-plugin-eslint

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/razzle#607]
Also remove eslint from the default setup.

**Comment by dambrogia** [comment]
I'm running into an eslint error on my project.

I use airbnb's javascript styles for my projects. There is a compatibility issue in their eslint guidelines with `eslint<4.10`.  [See here if interested](https://github.com/airbnb/javascript/issues/1599).

I realize the error does not exist in the razzle project, but I did want to bring this to your attention and see what the options were for situations like this. 

    ├─ razzle@2.0.0-y.0
    │  └─ eslint@4.5.0

Thanks for all your contributions so far, it is much appreciated!

**Comment by jamesbhobbs** [comment]
As referenced above we'd be keen for this to happen/to help. Can we get a better definition of the plugin so work could be started? Alternatively, please let us know of any WIP that isn't linked.

**Comment by jaredpalmer** [comment]
@benjaminhobbs thanks for offering to help. I don't use `eslint`, so I'm 100% open to suggestions.
