### ISSUE TITLE
How to use svg sprites

### ISSUE THREAD

**Issue by norrbacka** [jaredpalmer/razzle#613]
Hi!

We are using Razzle with React and Redux and we have an SVG sprites file filled with icons. We have used the Razzle Redux example as a base for the project and the SVG sprites file is located at src/assets/images/svgs/icons.svg. Inside one of our components we first have an import line like this:

`import icons from '../../../../assets/images/svgs/icons.svg'`

Then we have a react-component:

`const Icon = ({ name, color, size }) => (
    <svg className={`icon ${name}`} fill={color} width={size} height={size}>
        <use xlinkHref={`${icons }#name`} />
    </svg>
);`

Later on, we use the Icon-component and the compiled HTML looks like this:

`<svg class="icon someIcon"><use xlink:href="http://localhost:3001/static/media/icons.5c0a4f08.svg#someIcon"></use>
</svg>`

However, our shadow-root in dev-tools is blank and the image is not loading. But the address http://localhost:3001/static/media/icons.5c0a4f08.svg seems to be working just fine because we can see the svg-sprite-file there correctly. However, the id-tag does not seem to work.

We have not done anything in razzle.config.js with the result above. We have tried changing the config with different plugins such as url-loader, file-loader, and some specific webpack svg-loaders, but without luck. So what can we do? Is it possible to use svg-sprites like this with Razzle? Or do we need to do something special to make this work? If there is another alternative on how we should SVGs, like best practice in Razzle, we are open to change how we import these icons.

I should also mention that SVGs that are loaded directly without the #-property or by css-classes works without any problems.

Any help would be greatly appreciated!

**Comment by norrbacka** [comment]
A short update. Still, no success but the HTTP response on the svg-url-adress is blocked:origin. Maybe someone has any ideas then?

**Comment by norrbacka** [comment]
Okay, I now know the cause of the issue. When we are importing svgs using the "import icons from 'url.svg'" the request is being made but is stopped because the Access-Control-Allow-Origin is not set for that request. The other assets we are getting from the server has the correct request headers on them and therefore can successfully get their files from 3001 port. How can I setup Razzle so that the import-statement includes these necessary request headers? I have the default Razzle config.

**Comment by srsajjad** [comment]
Facing same issue for svg sprite.

On production, it's fine though.

But on dev, network request failing. Tried svg-sprite-loader, not working.
