### ISSUE TITLE
Changing the folder structure

### ISSUE THREAD

**Issue by MaxGoh** [jaredpalmer/razzle#614]
Create Razzle App has been great.

However, I would like to have a proper structure for the application

|- client
|- server
|- shared
...root

How can I achieve that?

**Comment by benhamlin** [comment]
The default config assumes a server entry point at 'src' and a client entry point at 'src/client'. You can get your desired folder structure basically without changing that; in fact that's how the [redux example works](https://github.com/jaredpalmer/razzle/tree/next/examples/with-redux/src).

If you want to get rid of the src/ folder, or move the server entry point, or do anything else more complicated, you'd need to [override the webpack config](https://github.com/jaredpalmer/razzle/tree/next/examples/with-custom-webpack-config) to change the entry points.

**Comment by MaxGoh** [comment]
Thanks! It's all good now, I'm pretty new to Razzle.
