### ISSUE TITLE
with-afterjs example does not serve CSR (client-side-rendering)

### ISSUE THREAD

**Issue by vladp** [jaredpalmer/razzle#619]
Apologies in advance, if I am mis-interpreting the available capabilities.
But I understood that razzle let's me manage build/serve pipeline for  a SSR, and, CSR (client side rendering) from the same project (same source, same package.json ).
And without injecting CRA or other CSR-side-only packaging/build tools.

I do not see index.html produced, so it is not clear to me how the CSR side is to be leveraged/tested.
(meaning that I want to point my nginx server (or webpack's dev server for dev), to My apps's index.html (that references built/bundled js produced by razzle's   build command). 

Would very much appreciate help/guidance on how to do that (without installing/using a separate tool for CSR side)
I could not find examples, docs, stackoverflow or other posts on this subject.  Therefore the the question.

----

This is what I had done sofar:
Downloaded with-afterjs example.
ran   

> npm install
> npm start

when accessing http://localhost:3001/
(which is, according to razzle doc is the default **client-side-render** bundle's listening port)
However, getting error: 

> Cannot GET /

My understanding from the doc, was that I could test client side only render by going to 3001 that would be served by the webpack's build in webserver (rather than by Node itself)

> 
> "... the client bundle (i.e. entry point at src/client.js) is served via webpack-dev-server on a different port (3001 by default) with its publicPath explicitly set to localhost:3001 …"

--- 

I also tried to install react-create-app scripts into my (create-razzle-app generated) package.json.
To see if I could leverage the CRA's scripts for CSR dev/build cycle mode.  However, react-scripts rely on webpack 3, while latest razzle is webpack 4.  Therefore both cannot be used within same project at the same time.

--- 

I also tried adding webpack-html plugin (the webpack-4 branch in their repo) to razzle.config.js
```
if (target==='web'){
    config.plugins.push(new HtmlWebpackPlugin());
}
```

This seems to modify how webpack-dev-server services localhost:3001
I can see that my browser downloads a bunch of Js, css from my test app.

Then going to http://localhost:3001
On the browser I get 

![csr_issue01](https://user-images.githubusercontent.com/94890/40340779-054adc7e-5d4f-11e8-9adf-49a07d3aa3ab.png)

And in the console window, I get a failure at ensureReady.js (this is after.js code), saying that cannot get textContent of null (meaning that a dom node with 'server-app-state'  does not exist).

![csr_issue_1_1](https://user-images.githubusercontent.com/94890/40340883-adf4e766-5d4f-11e8-8269-009a7644a1fc.png)

**Comment by jonjamz** [comment]
I am quite sure I have Razzle and After.js working together fine in my own project. I don't see a request to the server when navigating with `Link` from `react-router-dom`. I am still in the process of vetting the setup more thoroughly (loading data, etc.) but basically what I did is just start with a regular Razzle setup and add in all the After.js stuff piece by piece...

(Also, you probably already know this but just in case, the way universal rendering typically works is the initial request serves up SSR and subsequent navigation in the browser happens with CSR.)

**Comment by vladp** [comment]
@jonjamz .  Thank you for the follow up.     
Wanted to clarify my original question.
In my setup  SSR is working (page shows up with some basic layout, and whatever rendering I could do on the server, and then a few moments later, it hydrates with the JavaScript bundle, and it becomes CSR.

This works well, thx to the razzle and with-afterjs config example.  The default serving port for this is 3000.


What I thought I could do (and this could have been wrong expectation) -- was that if point my web browser at 3001, I would get essentially straight CSR (that is no server side rendering, just CSR like I would get, with say , create-react-app).

But that's not what happening ( I think because 3001 port is not really setup to serve straight CSR , and instead is setup by razzle as a 'supplement' to SSR).


So I posted the above question, in the hope to get a clarification if a straight CSR setup is possible within the same configuration as the SSR (just a different port).

Reason I am looking for this, Is that I would like my app to be essentially deployed in both modes (so that I can route certain types of client connects to SSR, and others CSR) -- so I was hoping I could get my test/debug environment to be setup like this with razzle (where SSR is essentially serviced by node.js, and CSR by webpack's built in webserver )
