### ISSUE TITLE
Error when using react semantic ui

### ISSUE THREAD

**Issue by jamalx31** [jaredpalmer/razzle#624]
I get the error: `inst.render is not a function` When I use any Semantic component.

```
{
  "name": "my-razzle-app",
  "version": "2.0.0-alpha.8",
  "license": "MIT",
  "scripts": {
    "start": "razzle start",
    "build": "razzle build",
    "test": "razzle test --env=jsdom",
    "start:prod": "NODE_ENV=production node build/server.js"
  },
  "dependencies": {
    "express": "^4.16.3",
    "razzle": "^2.0.0-alpha.12",
    "react": "^16.4.0",
    "react-dom": "^16.4.0",
    "react-router-dom": "^4.2.2",
    "semantic-ui-css": "^2.3.1",
    "semantic-ui-react": "^0.80.1"
  }
}
```

**Comment by vladp** [comment]
Would it be possible to provide bit more details?
Eg, what file / line number is error coming from?  Is this even located in razzle's sources?

Also, I came across a project that already has a working setup for razzle/semantic -ui, may be it will help as well:  https://github.com/Metnew/suicrux

**Comment by jamalx31** [comment]
It was an issue with Semantic-ui lastest update .. fixed now
https://github.com/Semantic-Org/Semantic-UI-React/issues/2849
