### ISSUE TITLE
env not work

### ISSUE THREAD

**Issue by gabe2code** [jaredpalmer/razzle#626]
Hi every one, im try to deploy a razzle project in a server with Ubuntu. 
I'm have created a .env and inside 2 variables port=80 and host=192.168.1.5 (for example)
when i run the project is running in localhost:3000 (default)
I try export PORT=80 and run for this port
But when i try to set the HOST show me an error (Error: Could not find an open port at 192.168.1.5 )
if export 0.0.0.0 not load the client side.
Please Help.

**Comment by krazyjakee** [comment]
Is 192.168.1.5 the actual assigned network IP of your ubuntu server?

**Comment by gabe2code** [comment]
@krazyjakee thanks for response, yep, is the ip in the ubuntu server, but is for the local network, but the public network has another address 81.122.222.121 (for example). I have installed windows and works perfect.

**Comment by gabe2code** [comment]
Fixed... the problem is, in windows accepts the names in lowercase, but linux is only in UPPERCASE. I'm closing the issue. Thanks

**Comment by akif-ih** [comment]
I am facing the same issue on ec2 ubuntu server.
