### ISSUE TITLE
Webpack not available in razzle.config.js during build

### ISSUE THREAD

**Issue by jonjamz** [jaredpalmer/razzle#632]
Hi,

Running `console.log(webpack)` during `razzle build` logs `undefined`. During `razzle start` it logs the webpack object as expected. I'm using v2.0.0.

I imagine this isn't intentional?

Best,

Jon

**Comment by jonjamz** [comment]
It looks like webpack is not passed in as of the most recent update a few days ago:

https://github.com/jaredpalmer/razzle/commit/f141a267cbf3ed0645e970840ed108548ee64a2a#diff-789bf5765f4f2f82e409674bb95e9b0b

**Comment by jaredpalmer** [comment]
Good catch, cutting a release now

**Comment by jonjamz** [comment]
Thank you so much!
