### ISSUE TITLE
thread-loader increases build time

### ISSUE THREAD

**Issue by benhamlin** [jaredpalmer/razzle#633]
This may be specific to Windows, since that's the environment I'm in. After upgrading to 2.0.0, I noticed significantly increased build times.

Build times with thread-loader:
Client: ~13s
Server: ~12s

After removing thread-loader:
Client: ~7s
Server: ~3s

It looks like thread-loader is spawning 10+ worker processes, which the thread-loader documentation claims costs ~600ms each - which is probably where the perf hit is coming from.

Not sure what the right fix here is, but as a workaround I'm simply removing thread-loader via my razzle.config.js

**Comment by jaredpalmer** [comment]
Yeah I think we should remove. I actually forgot about it (because we use TypeScript without Babel). Can you submit a PR?
