### ISSUE TITLE
Question: Notes on upgrading to razzle@next

### ISSUE THREAD

**Issue by ion-willo** [jaredpalmer/razzle#637]
Hi,

We've bene using Razzle from about the December 2017. Things have moved on and we'd love to make use of the latest features (such as WebPack 4). We've had to expand quite extensively on razzle.config.js, so my question is this: What do we need to look out for or change in our razzle.config.js in order to upgrade to razzle@next?

Any tips or ideas appreciated.

**Comment by vladp** [comment]
probably majority of your challenges will be with webpack plugins (if you use any, outside of razzle).
For example:
```
//No supporting webpack 4
//const ExtractTextPlugin = require('extract-text-webpack-plugin');
//replaced with
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

```

```
//Does not work with webpack 4
//const InlineChunkManifestHtmlWebpackPlugin = require('inline-chunk-manifest-html-webpack-plugin');


```


A good chunk of razzle's internal things are based off Create React App.
Create React App is in early stages of migrating to webpack 4.
Eventually Razzle, could take advantages of the changes they are making in CRA.
In a way, razzle is a bit ahead of CRA in this respect, at least now
 (as CRA official releases are still on web pack 3)

**Comment by ion-willo** [comment]
Yeah, we do. We use things like SASS, SWPrecache and CodeSplitting.
We'd love to know when Razzle starts implementing these so we don't have to. 🥇 

Should we then look to see which of these features (such as SWPrecache) is implemented in CRA?

You're quite correct in porting the ones we have to WP4, will be a challenge.
