### ISSUE TITLE
CircleCI upgrade

### ISSUE THREAD

**Issue by jamesbhobbs** [jaredpalmer/razzle#652]
This repo runs on CircleCI 1 which is shortly (this summer) to be deprecated. Upgrade should be done to CircleCI 2 or to another free to open source CI such as TravisCI (which I suggest).

The upgrade path for CircleCI is about as much work as setting up for Travis, I'm happy to do the PR, but can I get a steer on the preference of CI?

**Comment by jaredpalmer** [comment]
The nice thing about Circle is that I'm able to SSH into the builds and check things out. Does travis have that yet?

**Comment by romainquellec** [comment]
I dont see how TravicCI is better Than CircleCI 2. Can you elaborate on that @benjaminhobbs ?

**Comment by jamesbhobbs** [comment]
I didn't mean it was better, merely an alternative (if one were to be considered) hence asking preference.

re sshing to the build: https://docs.travis-ci.com/user/running-build-in-debug-mode/#Connecting-to-the-job-running-in-the-debug-mode
