### ISSUE TITLE
Plugin Question

### ISSUE THREAD

**Issue by rhodee** [jaredpalmer/razzle#670]
Hey so I built a plugin and had some questions (Plugin here: https://github.com/rhodee/razzle-plugin-pwa). It _should_ work given this line: https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/config/runPlugin.js#L9. 

I am happy to discuss design, but generally I followed the `razzle-plugin-typescript` model to get to this point. If it makes sense to add this to the the repo as package, I'd be happy to make a PR, it didn't feel like a _core_ addition, but I can be persuaded otherwise.

Cheers - D

**Comment by rhodee** [comment]
I was hoping to keep the package bumps in line with Razzle itself. Not sure that is a requirement, but it could be a nice feature for users. Thoughts?

**Comment by jaredpalmer** [comment]
This is awesome. Would love to add as a package!

**Comment by rhodee** [comment]
Awesome. I did this one too: https://github.com/rhodee/razzle-plugin-postcss

**Comment by rhodee** [comment]
Should create a test project in examples and then play around a bit at work. I wrote both in TS, which leads me to wonder how best to integrate. Leave me your thoughts, in the meantime.
