### ISSUE TITLE
Upgrade assets-webpack-plugin

### ISSUE THREAD

**Issue by rhodee** [jaredpalmer/razzle#680]
Images emitted by file-loader doesn't show in assets.json. Appears this is fixed in https://github.com/ztoben/assets-webpack-plugin/issues/41

Thoughts on upgrading razzle to 3.8.3 (or most stable version) to support this?

**Comment by jaredpalmer** [comment]
Yeah let’s bump

**Comment by SaraVieira** [comment]
@jaredpalmer Want a pr or has this been done ?

**Comment by jaredpalmer** [comment]
Yes please!
