### ISSUE TITLE
Add Apollo Client SSR example

### ISSUE THREAD

**Issue by daniellmartins** [jaredpalmer/razzle#683]
https://www.apollographql.com/docs/react/features/server-side-rendering.html

**Comment by corydeppen** [comment]
This appears to be a duplicate of #509.

**Comment by n0umankhan** [comment]
can we have some example with graphql and apollo with razzle ?

**Comment by rizalibnu** [comment]
@n0umankhan @daniellmartins  check this out for example [#950](https://github.com/jaredpalmer/razzle/pull/950)
