### ISSUE TITLE
Find eslint and babel config in package.json

### ISSUE THREAD

**Issue by olehreznichenko** [jaredpalmer/razzle#686]
It would be cool if razzle can find eslint [config](https://eslint.org/docs/user-guide/configuring) also in `package.json`

**Comment by olehreznichenko** [comment]
Hmm, [babel](https://babeljs.io/docs/en/babelrc.html#use-via-packagejson) also can be here

**Comment by olehreznichenko** [comment]
If this is ok and not to hard implement i will try to submit PR 🤔 @jaredpalmer

**Comment by jaredpalmer** [comment]
Yes! Anything to cut down on dotfiles! Ideally we should copy someone’s existing resolution system when it comes to conflicts. Maybe parcel’s?
