### ISSUE TITLE
Can I get HMR working behind a reverse proxy

### ISSUE THREAD

**Issue by kasbah** [jaredpalmer/razzle#690]
Hello, thanks for Razzle and After. I am working on a project where I need my Razzle/After frontend to be behind an Nginx reverse proxy while developing. Is there a way to get HMR working when it's being proxied to a different port?

**Comment by kasbah** [comment]
Hmmm.. it actually seems to be working after all. I think the console message about the server being disconnected confused me.

**Comment by laurencefass** [comment]
hi please can you post config for this been trying for two weeks to get it working still no result. thanks

**Comment by kasbah** [comment]
Sorry, this was too long ago. I believe it was working with default settings/config.
