### ISSUE TITLE
Library CSS import Unexpected token error

### ISSUE THREAD

**Issue by amosyuen** [jaredpalmer/razzle#692]
When I try adding some libraries such as `react-flexbox-grid`, the build fails with:

```
E:\web\src\my-app\node_modules\flexboxgrid2\flexboxgrid2.css:1
(function (exports, require, module, __filename, __dirname) { .container {
                                                              ^

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\web\src\my-app\node_modules\react-flexbox-grid\lib\classNames.js:8:20)
```

Looks like it's not able to import css correctly. My understanding is razzle should take care of handling these css imports. Am I misunderstanding something or doing something wrong?

Git repository for reproing: https://github.com/amosyuen/razzle-flexboxgrid

**Comment by CharlyJazz** [comment]
I have the same problem.

**Comment by vineyardbovines** [comment]
If you take a look at the [webpack config](https://github.com/roylee0704/react-flexbox-grid/blob/master/webpack.config.js) for `react-flexbox-grid`, you'll see that it doesn't have a rule to compile CSS yet it imports a css file. The build script compiles the dist via webpack, so my guess is the problem stems from there.

**Comment by amosyuen** [comment]
Libraries like `react-flexbox-grid` are meant to have the CSS handled by the clients that builds it. So their build process intentionally doesn't process CSS. They have instructions specifically for clients to process the css in their webpack build: https://github.com/roylee0704/react-flexbox-grid#minimal-configuration. And from a brief reading of Razzle webpack config, it should process all CSS files.

**Comment by vineyardbovines** [comment]
Have you added the `include: /flexboxgrid/` option to the CSS rule in your razzle config? Bc according to that guide, that has to be added.

**Comment by amosyuen** [comment]
I haven't because my understanding is that razzle should compile the css in `node_modules`. Looking at the razzle webpack config CSS rule https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/config/createConfig.js#L184, since it doesn't exclude `node_modules` or define an explicit `include`, I would expect that it should compile all CSS in `node_modules` including `flexboxgrid`.

**Comment by vineyardbovines** [comment]
I understand, but adding that include statement to webpack is required by that specific lib, according to their documentation. And the reason for needing that include statement is because `react-flexboxgrid` doesn't compile CSS for its build releases.
