### ISSUE TITLE
Enabling compression for production mode

### ISSUE THREAD

**Issue by nolandg** [jaredpalmer/razzle#699]
Can someone point me to where the production server is serving static assets? like bundle.js etc?

I imagine it's something like `express.static()` and I want to replace it with something from https://github.com/tkoenig89/express-static-gzip but I can't find where this actually happens for production mode. 

This area of `server.js` isn't what I'm looking for because that's serving over 3000 and not 3001 where bundle.js is found.

````
const server = express();
server
  .disable('x-powered-by')
  .use(express.static(process.env.RAZZLE_PUBLIC_DIR))
  .get('/*', async (req, res) => {
````

Where is the static file production server setup and how can I get it to use pre-compressed gzip versions of files?

Thanks so much!

**Comment by benhamlin** [comment]
3001 is the port that the webpack-dev-server is running on. It doesn't run as part of a production build (`yarn start:prod`). In production, that line in server.js is exactly where the static files are handled.

**Comment by constantin-v** [comment]
On the same subject : I saw on the server express configuration that there is no compression.
Something like :
```
const compression = require('compression');
app.use(compression());
```
could be enough to reduce the payload size (mostly the html that is not compressed).

I think you already thought about it and wonder why it's not in Razzle. 
Thanks

**Comment by jaredpalmer** [comment]
This is a user land thing and not a concern of razzle. While I agree it is a must have for prod with express, maybe better to just add a section to docs about going to production.

**Comment by SamirJouni** [comment]
You could use a plugin like the one I just created for my own app:
https://www.npmjs.com/package/razzle-plugin-brotli-gzip-zopfli

I thought someone else might need it too. I will be writing a good readme tomorrow detailing all the options available.
 
To use just install with npm (or package manage of choice) and put this in your razzle.config.js:
```
// razzle.config.js

module.exports = {
  plugins: ['brotli-gzip-zopfli'],
};
```
