### ISSUE TITLE
Add support for esm for loading external modules on the server

### ISSUE THREAD

**Issue by AndrewPrifer** [jaredpalmer/razzle#703]
My specific issue is that I want to use lodash-es because it provides tree-shaking with webpack. However, it is not isomorphic because it exports ES modules and node_modules are treated as `externals` by webpack on the server.

One solution would be to somehow enable [esm](https://www.npmjs.com/package/esm) support for Razzle.

@jaredpalmer what do you think? My issue is specific to lodash but I imagine there are other libraries as well with ES-only exports that folks might want to use on both sides.

**Comment by mattlubner** [comment]
I'd like this as well!

Webpack tree shaking relies on ES2015 module syntax (see: https://webpack.js.org/guides/tree-shaking/), so I wouldn't say it's specific to lodash as much as it is to Webpack tree shaking.

**Comment by AndrewPrifer** [comment]
@mattlubner true, you can use esm for tree shaking any module, lodash-es is just an example. :)
