### ISSUE TITLE
className mismatch error on refresh

### ISSUE THREAD

**Issue by butterybread** [jaredpalmer/razzle#705]
I downloaded the `with-styled-components` example from the repo and ran `yarn install` & `yarn start`. All fine.

After making a code change the HMR works fine and the browser is updated.
But refreshing the browser after a code change, results in an error.
```
Warning: Prop `className` did not match. Server: "sc-bwzfXH eaLeSp" Client: "sc-bdVaJa igGFgA"
```
I am not sure what the expected behaviour is after a refresh.

**Comment by nolandg** [comment]
Try it in production mode. As far as I can tell, the mismatch only happens when reloading a page that was updated by HMR. Rarely a serious in dev and not applicable in prod.

**Comment by butterybread** [comment]
Yes, the error occurs only while developing and not in production. Since you don't have HMR there.
But I am wondering what the underlying bug is. Why is there a mismatch after I refresh?
The client bundle that the server uses is probably not updated.
In theory it doesn't have to be because we use HMR and therefore the original script doesn't have to be updated. But why not keep it in sync to avoid the error?

**Comment by nolandg** [comment]
I fought with this for a few hours but gave up because it didn't bother me enough. 

I think it's because the class name generator can only be instantiated identically on the first load. On subsequent loads, only the modified module (the M in HMR) seems to be run through the generator and all the other unmodified modules are left out and none of the server is re-run through the generator.  I think I saw this in the integer suffixes of the class names too.

I suspect you might have to feed all the HTML through the same generator again including both server and unmodified client modules in the identical sequence as you do on first load.

Let us know if you make progress on this.

**Comment by jaredpalmer** [comment]
Any progress?

**Comment by nolandg** [comment]
My work around is to hit rs on the server terminal to restart it. Loads after that are perfect until the next HMR. 

@jaredpalmer  The rs reload is so fast, it would add little time to the HMR process to just restart after each HMR. Could we add an option for that? I think that resart is what's running all of both client and sever through the same generator and correcting it.

**Comment by Octember** [comment]
Bump on this issue, seeing the same thing. Definitely seems related to HMR. Though something even using the `rs` command or restarting completely shows the same issue. I'm shooting in the dark here, razzle is an incredible piece of software but issues like this are really scary as an amateur JS dev.

**Comment by nolandg** [comment]
If rs doesn't fix it, check your code carfefuly. I've never run into that.
Check how you're instantiating the class name generator and how you're
saving references to it. Inspect the integer suffixes of the class names,
they can point you to where the generator might be reset or new.

Yes, SSR is quite tricky to setup and it must be perfect to work at all.

**Comment by sandervspl** [comment]
I've set it up like this and I get zero errors or warnings. Maybe this will help.

`client.js`
```js
hydrate(
  <ThemeProvider theme={theme}>
    <BrowserRouter>
      <After data={data} routes={routes} />
    </BrowserRouter>
  </ThemeProvider>,
  document.getElementById('root'),
);
```

`server.js`
```js
server
  .disable('x-powered-by')
  .use(express.static(process.env.RAZZLE_PUBLIC_DIR))
  .get('/*', async (req, res) => {
    const customRenderer = (node) => {
      const App = (
        <ThemeProvider theme={theme}>
          {node}
        </ThemeProvider>
      );

      return {
        html: renderToString(App),
        serverState,
      };
    };

    try {
      const html = await render({
        req,
        res,
        routes,
        assets,
        document: Document,
        customRenderer,
      });
      res.send(html);
    } catch (error) {
      res.json(error);
    }
  });
```

`Document.js`
```js
export default class Document extends React.Component {
  static async getInitialProps({ assets, data, renderPage }) {
    const sheet = new ServerStyleSheet();
    const page = await renderPage(App => props => sheet.collectStyles(<App {...props} />));
    const styleTags = sheet.getStyleElement();

    return { assets, data, ...page, styleTags };
  }

  render() {
    const { helmet, assets, data, styleTags, serverState } = this.props;
    const htmlAttrs = helmet.htmlAttributes.toComponent();
    const bodyAttrs = helmet.bodyAttributes.toComponent();

    return (
      <html {...htmlAttrs}>
        <head>
          <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
          <meta charSet="utf-8" />
          <title>React Prime AfterJS</title>
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          {helmet.title.toComponent()}
          {helmet.meta.toComponent()}
          {helmet.link.toComponent()}
          {styleTags}
        </head>
        <body {...bodyAttrs}>
          <AfterRoot />
          <AfterData data={data} />
          <script
            type="text/javascript"
            src={assets.client.js}
            defer
            crossOrigin="anonymous"
          />
        </body>
      </html>
    );
  }
}
```

**Comment by nolandg** [comment]
@sandervspl So you don't get a `className` mismatch even when you modify a component that uses `withStyles`, HMR reloads, and then you reload the page?
