### ISSUE TITLE
[question] ant-design support or example?

### ISSUE THREAD

**Issue by cbbfcd** [jaredpalmer/razzle#708]
i hava try many times to support antd in razzle. but not work now. so anyone have a idea?

**Comment by SaraVieira** [comment]
Hey!

Have you tried changing your .babelrc to:

```json
{
  "presets": ["razzle/babel"],
  "plugins": [
    "transform-decorators-legacy",
    [
      "import",
      {
        "libraryName": "antd",
        "style": "css"
      }
    ]
  ]
}
```

Can you specify your error after trying this ?

**Comment by mohamadsdg** [comment]
@SaraVieira hi
I added this to .babelrc

```
{
  "presets": [
    "razzle/babel"
  ],
  "plugins": [
    [
      "import",
      {
        "libraryName": "antd",
        "libraryDirectory": "es",
        "style": "css"
      }
    ]
  ]
}
```
But I get an error 
```
(function (exports, require, module, __filename, __dirname) { import './index.css'; 
SyntaxError: Unexpected string 
```

Do you know what the problem is?

**Comment by jsshizhan** [comment]
> @SaraVieira hi
> I added this to .babelrc
> 
> ```
> {
>   "presets": [
>     "razzle/babel"
>   ],
>   "plugins": [
>     [
>       "import",
>       {
>         "libraryName": "antd",
>         "libraryDirectory": "es",
>         "style": "css"
>       }
>     ]
>   ]
> }
> ```
> 
> But I get an error
> 
> ```
> (function (exports, require, module, __filename, __dirname) { import './index.css'; 
> SyntaxError: Unexpected string 
> ```
> 
> Do you know what the problem is?

do you solve the problem?
