### ISSUE TITLE
[transpiler err] in FF < 45

### ISSUE THREAD

**Issue by hasft** [jaredpalmer/razzle#709]
i've got warn from firefox 43: `SyntaxError: let is a reserved identifier`
looks like babel-loader can't transpile es6 to es5 inside node_modules. for an example: if i add `query-string` module it throws an error inside browser console. is it a decision by design or what?

**Comment by jaredpalmer** [comment]
Hrmmm. Can you make a demo repo so I can take a look?

**Comment by frei-0xff** [comment]
Seems like I run into the same issue with es6 code and IE11.
Looks like babel doesn't transpile es6 arrow functions from modules in node_modules.

How to replicate the issue:
Create new app with create-razzle-app
npm install --save split-on-first
Add `import splitOnFirst from 'split-on-first'` to src/client.js
npm run build
npm run start:prod

In build/public/static/js/bundle.xxxxxxxx.js can be found 
...
`"use strict";
e.exports=(e,t)=>{
if("string"!==typeof e||"string"!==typeof t)
throw new TypeError("Expected the arguments to be of type `string`");
`
...

And in IE11's console we get Syntax error in bundle.xxxxxxxx.js

I put that sample in https://github.com/frei-0xff/razzle-ie11-issue
