### ISSUE TITLE
using babel in ts-jest

### ISSUE THREAD

**Issue by jamalc** [jaredpalmer/razzle#718]
I'd like to be able to add `
"globals": {
      "ts-jest": {
        "useBabelrc": true
      }
    }`. I'm using the typescript plugin but I have some babel plugins that I need for tests to be able to run. Is there a reason globals is not one of the allowed config overrides?

**Comment by jamalc** [comment]
solved with #719

**Comment by mksony** [comment]
Hi @jaredpalmer, do you have any plans to release a version the change in #719? I have seen that it's merged since quite a while but it's not part of the currently published `2.4.0`.
