### ISSUE TITLE
How to use jQuery

### ISSUE THREAD

**Issue by zhaofang** [jaredpalmer/razzle#720]
my code:   
appConfig.plugins.push(
                new webpack.ProvidePlugin({
                    $: 'jquery',
                    jQuery: 'jquery',
                    jquery: 'jquery',
                    Popper: ['popper.js', 'default'],
                }),)

but it is failed.Line 11:  '$' is not defined  no-undef

**Comment by CharlyJazz** [comment]
Avoid the use of Jquery with React, thats is a bad idea

**Comment by lallmon** [comment]
@CharlyJazz

Where did he say he was trying to use React with jQuery? I thought Razzle was not React dependent? It bills itself as unopinionated, so If jQuery is this guy’s choice of DOM manipulation, it should work, no?
