### ISSUE TITLE
Are polyfills included by default in Razzle?

### ISSUE THREAD

**Issue by AndrewPrifer** [jaredpalmer/razzle#725]
Currently things are breaking in IE11 for me (includes, find). What polyfills are included by Razzle, if any, and what is the preferred way of including them yourself?

**Comment by DevanB** [comment]
Curious about this as well. I was considering adding `babel-polyfill` as I'm seeing `Array.from` errors in IE11 constantly.

**Comment by AndrewPrifer** [comment]
@DevanB I checked in the meantime, there’s only a very minimalistic set of polyfills included (like Promise) that are essential for React to work, others are not. For now I added babel-polyfill to the beginning of the client entry but I’m still curious if there’s a neater way, perhaps through webpack.

**Comment by jaredpalmer** [comment]
We polyfill exactly like CRA does, which as you’ve described. Is the bare minimum to get React working. In v3, we may  make all the starters come will more generic polyfill with a huge warning that you need to remove and replace with your own.

**Comment by DevanB** [comment]
@andrewpeterprifer I, too, simply threw `babel-polyfill` in at the top of `client.js` to solve my problems in the interim.

@jaredpalmer This seems like a good path in v3, assuming it is well documented. Thanks for the hard work on this project!

**Comment by marcellobarile** [comment]
I'm also struggling in making a razzle app working on <=IE11, after having downgraded the "target" conf. to "es5", now I'm getting errors about template literals.
Did anyone come up w/ a solution for such a situation?

**Comment by olehreznichenko** [comment]
I recommend trying this https://polyfill.io/v2/docs/

**Comment by brody2consult** [comment]
??
