### ISSUE TITLE
 Build bundle for modern browsers and legacy browser separately

### ISSUE THREAD

**Issue by alexparish** [jaredpalmer/razzle#729]
Shipping a smaller bundle for modern browsers. Is this something that would make sense to have in Razzle?

See similar issue on Next.js: https://github.com/zeit/next.js/issues/3056

**Comment by jaredpalmer** [comment]
This would be a cool plugin, but probably outside the scope of the core

**Comment by brody2consult** [comment]
Hope to see this as a plugin

**Comment by dantman** [comment]
This one is a feature request useful to anyone, so it shouldn't go stale.

**Comment by fivethreeo** [comment]
Not stale

**Comment by fivethreeo** [comment]
On my radar after 4.0 is out

**Comment by fivethreeo** [comment]
Closed in favour of https://github.com/jaredpalmer/razzle/issues/1393
