### ISSUE TITLE
Error using yaml-loader

### ISSUE THREAD

**Issue by knoid** [jaredpalmer/razzle#731]
It worked on version 0.8.14 with the following code but I can't make it work now on the newer version. I even tried adapting it to webpack 4 config structure but it fails to find the yaml file on the server.

```js
// razzle.config.js
module.exports = {
  modify(config, { target, dev }, { DefinePlugin }) {
    // Configure YAML loader
    const fileLoaderRule = config.module.rules
        .find(({ loader }) => loader && loader.indexOf('file-loader') > -1);
    fileLoaderRule.exclude.push(/\.ya?ml$/);

    config.module.rules.push({
      test: /\.ya?ml$/,
      loader: ['json-loader', 'yaml-loader'],
    });

    return config;
  },
};
```

Did anybody manage to get this working?
Thanks.

**Comment by ourmaninamsterdam** [comment]
I'm using Razzle 2.0.0-alpha.8 and tried your config and https://github.com/okonet/yaml-loader and it seemed to be working fine. I'm currently using yaml-loader in a project.

What errors are you getting?

**Comment by knoid** [comment]
I only tried on Razzle 2.4.0. The error was the yaml file not being found and throwing on the browser.

**Comment by knoid** [comment]
The error was that I needed to actually install json-loader as a dependency... sorry!
