### ISSUE TITLE
process.env.PUBLIC_URL isn't set when running tests

### ISSUE THREAD

**Issue by gregmartyn** [jaredpalmer/razzle#738]
We have some code that expects there to be a valid process.env.PUBLIC_URL, but https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/scripts/test.js#L16 sets PUBLIC_URL = ''

Would you be open to having that come in as a cli parameter?

Also, I don't really understand the rationale behind setting it to ''. It'd help if that were documented / explained.

**Comment by mAAdhaTTah** [comment]
Related to #736.

**Comment by gregmartyn** [comment]
Not stale

**Comment by gregmartyn** [comment]
Not stale

**Comment by fivethreeo** [comment]
Should be set now
