### ISSUE TITLE
Remove extract-text-webpack-plugin mention from react-native-web example

### ISSUE THREAD

**Issue by MrLoh** [jaredpalmer/razzle#744]
It seems like extract-text-webpack-plugin was removed from razzle. The react-native-web example still mentions it. 

https://github.com/jaredpalmer/razzle/blob/master/examples/with-react-native-web/README.md

**Comment by jaredpalmer** [comment]
Can you submit a PR?

**Comment by MrLoh** [comment]
Sure. Just wanted to make sure I didn’t overlook something. Extract-text Plugin was really removed right.

**Comment by jaredpalmer** [comment]
Yes. When we moved to webpack 4
