### ISSUE TITLE
razzle 2.4.0 broke paths.

### ISSUE THREAD

**Issue by MarkLyck** [jaredpalmer/razzle#753]
I'm afraid I don't have a whole lot of information to go on here.

But after upgrading from razzle 2.2.0 to 2.4.0 I'm getting the following error compiling the client:

```
09/16 08:55 PM (18m)
Module build failed (from ./node_modules/razzle/node_modules/babel-loader/lib/index.js):
09/16 08:55 PM (18m)
TypeError: /home/nowuser/src/src/pages/Dashboard/Admin/API/API.jsx: Cannot read property 'path' of undefined
09/16 08:55 PM (18m)
    at new Promise (<anonymous>)
09/16 08:55 PM (18m)
    at new Promise (<anonymous>)
```

I confirmed after deleting the API.jsx component the compile step passes.
And with the component after downgrading to 2.2.0, this works fine again.

I'm not sure what changed here. I don't use "path" anywhere in that component.

I do have 2 external dependencies only used in this component though (both popular).
React-dropzone and d3-queue.

My guess is that Razzle 2.4.0 has become incompatible with one of these npms.

**Comment by jaredpalmer** [comment]
Hmmmm. Need to investigate further
