### ISSUE TITLE
Npm audit fail for react-dev-utils

### ISSUE THREAD

**Issue by vacuumdreams** [jaredpalmer/razzle#757]
Seems like the razzle-dev-utils lib uses a strict v4 for react-dev-utils, while in the same time the main razzle lib uses 4^. Would be nice to make it uniform across, if possible, to get rid of this failing audit check regarding react-dev-utils < v4.2.2.

Related npm advisory ticket: https://www.npmjs.com/advisories/695

**Comment by Toyurc** [comment]
Has this been fixed?, I got the same error this morning.

**Comment by ghost** [comment]
razzle@2.4.0 > razzle-dev-utils@2.4.0 > react-dev-utils
```
├─┬ razzle@2.4.0
│ └── react-dev-utils@4.2.3
└─┬ razzle-dev-utils@2.4.0
  └── react-dev-utils@4.1.0
```
https://www.npmjs.com/advisories/695

**Comment by moxxuk** [comment]
I hope this PR gets merged soon!
