### ISSUE TITLE
heroku deploy error App crashed

### ISSUE THREAD

**Issue by oluomoniyi** [jaredpalmer/razzle#777]
Super tool...create-react-app-ssr!

I am having a few issues with my deploy to heroku, it runs locally and builds without any issues, however once i deploy to heroku the app crashes with the following error.

`heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host={host_name} request_id={red_id} fwd="82.23.129.44" dyno= connect= service= status=503 bytes= protocol=https`

package.json
```
"scripts": {
    "start": "razzle start",
    "build": "razzle build",
    "test": "razzle test --env=jsdom",
    "prestart:prod": "yarn build",
    "start:prod": "NODE_ENV=production node build/server.js",
    "deploy": "git push heroku master"
  },
```

Procfile
`web: yarn start:prod`

index.js
```import express from "express";

let app = require("./server").default;

if (module.hot) {
  module.hot.accept("./server", function() {
    console.log("🔁  HMR Reloading `./server`...");
    try {
      app = require("./server").default;
    } catch (error) {
      console.error(error);
    }
  });
  console.info("✅  Server-side HMR Enabled!");
}

const port = process.env.PORT || 3000;

export default express()
  .use((req, res) => app.handle(req, res))
  .listen(port, function(err) {
    if (err) {
      console.error(err);
      return;
    }
    console.log(`> Started on port ${port}`);
  });```

**Comment by CharlyJazz** [comment]
Check this razzle app already deployed in Heroku
https://github.com/TWOIOT-git/TWO-Waste-Dashboard
