### ISSUE TITLE
Why 2 webpack instances?

### ISSUE THREAD

**Issue by hornta** [jaredpalmer/razzle#778]
Hi. Is there a reason for having two separate webpack instances vs. using webpacks multicompiler(https://webpack.js.org/api/node/#multicompiler)

**Comment by cloud-walker** [comment]
Yes, you need to first build the client to ensure assets.json creation, because the server needs it to generate the HTML

**Comment by blujedis** [comment]
@hornta Multicompiler runs sync. Essentially it is doing the same thing Razzle is in that Razzle compiles the client then server. 

as @cloud-walker points out you need the assets built so even if you used the Multicompiler in parallel via third party module you'd still need to ensure the client it built.
