### ISSUE TITLE
Tree-shaking is not happening

### ISSUE THREAD

**Issue by krazyjakee** [jaredpalmer/razzle#780]
The webpack plugin "ModuleConcatenationPlugin" doesn't seem to run in `production` mode.

Any `import { x } from 'x'` adds the entire module `x` to the production bundle.

What could be causing this?

Here is a minimal example of this issue in action: https://github.com/krazyjakee/Razzle-Sandbox/blob/tree-shaking/src/App.js#L2

You can see the entire date-fns package is imported to the bundle when running `npm run build`.

**Comment by krazyjakee** [comment]
Updated with an example repo

**Comment by krazyjakee** [comment]
@jaredpalmer confirmed this is planned for V4 and is not a bug, just not implemented.

https://spectrum.chat/notifications?thread=68062cb8-a254-43c2-9330-69e537a9753d

**Comment by krazyjakee** [comment]
This is fixed in v4

**Comment by mrmartineau** [comment]
@krazyjakee don't you mean v3?

**Comment by krazyjakee** [comment]
@mrmartineau sorry getting ahead of myself
