### ISSUE TITLE
index.js vs server.js multiple hosts during development

### ISSUE THREAD

**Issue by blujedis** [jaredpalmer/razzle#784]
Looking to get pointed in right direction if you would be so kind. This post is related to understanding the architecture. New to Razzle.

**So what is the purpose of instantiating express twice? Once in index.js and the other in server.js.**

Secondly ${assets.client.js} will point to localhost:3000 unless you explicitly define your LAN IP. The issue is that although the default listens at 0.0.0.0 allowing any IP on your machine including localhost to resolve, to me this defeats the purpose of using 0.0.0.0.

This is because if you hit your LAN IP from say a phone, the page will load but all the assets, since they're pointing to localhost, can't load. :(

At least for me this is important so that you can test multiple platforms simultaneously.

Has anyone run into this? How did you tackle the problem?

**Comment by blujedis** [comment]
On the IP external device issue I just built a plugin to get the machine's IP and always bind to it when in dev mode.

Seems a bit hacky but works fine. Again new to Razzle so if you have a better way I'm all ears.

**DEV HOST PLUGIN:**

```js
const { address } = require('ip');
const { parse } = require('url');

module.exports = function (config, env) {

  // Bind to LAN ip so that external 
  // devices can load assets correctly.
  if (env.dev) {
    const addr = address();
    const parsed = parse(config.output.publicPath);
    process.env.HOST = addr;
    config.output.publicPath = `${parsed.protocol}//${addr}:${parsed.port}/`;
  }

  return config;

};
```

**RAZZLE.CONFIG.JS**:

```js
const { devhost } = require('./plugins');
module.exports = {
  plugins: [devhost]
};
```

**Comment by dguo** [comment]
I ran into the same issue because I needed to test my website on a phone. My workaround was to use [ngrok](https://ngrok.com/). 

`ngrok.yml`:
```yml
tunnels:
  web:
    addr: 3000
    proto: http
    # bind_tls so that the http proxy is not enabled, so that we stay within the
    # free plan limits
    bind_tls: true
  static:
    addr: 3001
    proto: http
    bind_tls: true
```

Run `ngrok start -config ./ngrok.yml --all`.

You'll get output like:
```
Forwarding     https://8d7b8ee9.ngrok.io -> http://localhost:3001
Forwarding     https://b62330e1.ngrok.io -> http://localhost:3000
```

The domain for 3000 is what you should load in your browser.
The domain for 3001 is what you need to use as the host for static assets.

Start the server with the 3001 domain:
```sh
CLIENT_PUBLIC_PATH=https://8d7b8ee9.ngrok.io/ yarn start
```
