### ISSUE TITLE
Long compilation and HMR timing

### ISSUE THREAD

**Issue by MaxGoh** [jaredpalmer/razzle#789]
I'm currently using Razzle for a project that is becoming pretty huge. The compiling time takes up to more than a minute for a first build, and flat 1 minute for subsequent reloads.

I tried googling around for resources and I can't seem to decrease the time it takes. Other than focusing on code splitting and direct importing, I'm not too sure what I can do at this point.

It would be really great if someone could direct me on how I can further optimise and improve my performance down to bearable timespan.

Thanks!

**Comment by AmirTahani** [comment]
I have the same problem too and I'm not sure what causes this. 
I'm gonna try code split and chunk to see if it reduces the compile time or not.
but for sure its going to reduce load time 
I'll let you know as soon as I find a solution

**Comment by MaxGoh** [comment]
Hey, thanks for responding.

i currently have route based code splitting in my project, I feel that it's increasing my compilation time though. Do let me know how was your experience.

**Comment by olehreznichenko** [comment]
I have the same long time compilation, but I think it's not relative with razzle.
Depends have many have babel plugins and haw big is a project.
@MaxGoh try to test your project in CRA. if average time for compilation will be the same it's definitely webpack or babel issue.
Maybe parcel can improve speed. Or when merge branch with babel7
