### ISSUE TITLE
Release plans

### ISSUE THREAD

**Issue by mksony** [jaredpalmer/razzle#799]
Hey @jaredpalmer,
first of all thanks for this awesome project :) I noticed that the last release was done quite a while ago and now I wonder if there are any plans with releasing a new version with the changes which have been merged to master since July. Let me know if there's anything I can help with :)

Cheers Max

**Comment by stigkj** [comment]
I guess you have seen the v3 alpha?

**Comment by jaredpalmer** [comment]
V3 alpha is out

**Comment by jaredpalmer** [comment]
Waiting for more feedback before official release

**Comment by mksony** [comment]
Thanks, using for a typescript project and works perfectly for me :)
