### ISSUE TITLE
Async reducer with server-side rendering

### ISSUE THREAD

**Issue by svrcekmichal** [jaredpalmer/razzle#8]
Hi @jaredpalmer thanks for starter :) it's awesome. I liked it much so I wanted to try to port it to my `reasync` lib nex to `redial` to see differences. I found it quite easy, you have done a lot of good work, but I have found one issue

When i server-side render page where async reducer is used (Post), i get following error 
`Unexpected key "currentPost" found in initialState argument passed to createStore. Expected to find one of the known reducer keys instead: "posts". Unexpected keys will be ignored.`

With redial, it only show empty page, as it is not doing fetching when initial state is i page. I little bit tweaked your functions if should something be fetched and make it working in my fork with reasync. Take a look if you want https://github.com/svrcekmichal/react-production-starter

It's working because I'm fetching data on client, but it's not solving the issue. But if you find out  how to work around that async reducer it would be awesome! :)

**Comment by jaredpalmer** [comment]
From my research, it's not a 'real' error. It's actually just a warning: http://stackoverflow.com/questions/34095804/replacereducer-causing-unexpected-key-error

**Comment by svrcekmichal** [comment]
@jaredpalmer hm, I have completely reinstalled package and it works fine now, even with reasync. Warning is there, but it's working. It's funny because when i posted this issue, I had only initial state even after fetch
