### ISSUE TITLE
apollo subscriptions break HMR

### ISSUE THREAD

**Issue by Evanion** [jaredpalmer/razzle#835]
I'm adding apollo server to a razzle based project... and since SSR already comes with a node server, and Apollo being so Frontend centric ... we treat it as just a API layer to the client (a descriptive comparison would be; apollo-client = redux, apollo-server = redux-saga).

I got in to a bit of trouble when I started adding the subscription middleware... it needs to be added to the `http.createServer` wrapped version of the application... and when I do that ... in the file that contains the HMR reload code (the same file that already wrapps the express app in `createServer`).. HMR stops reloading.. and I need to restart the process on every code change...

https://www.apollographql.com/docs/apollo-server/features/subscriptions.html#middleware
from the docs in link above:
```js
const server = new ApolloServer({ typeDefs, resolvers });

server.applyMiddleware({app})

const httpServer = http.createServer(app);
server.installSubscriptionHandlers(httpServer);
```

the apollo server gets defined in the same file that the express app gets instantiated in, and the apollo server gets applied to the express app as a middleware...
The last two lines would have to be in the HMR file, since thats where Razzle wrapps the process in `createServer`....
so.. how can I apply the subscription handlers, without HMR calling it quits?

**Comment by noeljackson** [comment]
@Evanion Have you thought about splitting up your Apollo Server into a separate project from your frontend?

**Comment by Evanion** [comment]
Yea, thats how I usually do it,  but this time I wanted to try bundling them in to one.

**Comment by blujedis** [comment]
@Evanion Have a look at the Apollo kit. I had it working at one point but didn't save it but referred here.

https://github.com/sysgears/apollo-universal-starter-kit/blob/master/packages/server/src/server.ts#L11

Maybe that will help you!

**Comment by Evanion** [comment]
closing as it's no longer relevant, decided to go with [Nest.js](https://nestjs.com/) for the GQL server.
