### ISSUE TITLE
Add node 9, 10, 11 to Circle test suite

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/razzle#840]
Run the existing test suite against other node versions

**Comment by kkalavantavanich** [comment]
Does #1057 solve this?

**Comment by jaredpalmer** [comment]
@kkalavantavanich I merged your PR, but tests are failing on Node 12. Any thoughts?

**Comment by kkalavantavanich** [comment]
@jaredpalmer I am trying to resolve that. Seems the resolved gRPC version is not compatible with node12.

**Comment by kkalavantavanich** [comment]
@jaredpalmer #1058 should fix that.

**Comment by kkalavantavanich** [comment]
Seems the build is passing on Node 12 but failing on Node 9. I will try to investigate if I have time, which will probably be in 2 - 3 days.

**Comment by kkalavantavanich** [comment]
@jaredpalmer  I am unable to reproduce the bug shown in CircleCI. Can you trigger a run on Node 9 to see if it is a problem by chance with CircleCI for that last build?

**Comment by kkalavantavanich** [comment]
Just rechecking things and seems that everything is up and running now. Should this issue be closed?

**Comment by nimaa77** [comment]
there is a problem with windows tests, jest can't find the tests on windows, any ideas?
I have a windows machine I will give a try on my windows machine tomorrow

**Comment by kkalavantavanich** [comment]
@nimaa77 Which Windows tests? I can see only node9 failing on CircleCI.

**Comment by nimaa77** [comment]
@kkalavantavanich https://github.com/jaredpalmer/razzle/pull/1210/checks?check_run_id=509343331
it can't find tests on windows 10 with node 10 and 12, and there is a problem with windows and node 8, it has connectivity issues

**Comment by kkalavantavanich** [comment]
Seems like it fails on a lot of branches though... I am suspicious of the file glob in `jest.config.json`
```
"testMatch": [
    "<rootDir>/tests/**/?(*.)(spec|test).(ts|js)?(x)"
  ]
```
Seems like it might not be windows compatible.

**Comment by kkalavantavanich** [comment]
Might be related: https://github.com/facebook/jest/issues/7914

**Comment by nimaa77** [comment]
I found this: https://github.com/facebook/jest/issues/7914#issuecomment-464352069
I have a windows machine I will test and tell you the results here.

**Comment by fivethreeo** [comment]
Fixed, closing
