### ISSUE TITLE
How to access loadable-stats.json from `server.js`

### ISSUE THREAD

**Issue by jbsmith731** [jaredpalmer/razzle#847]
I'm trying to use the latest version of [loadable components](https://github.com/smooth-code/loadable-components) but it requires babel 7 so I'm using razzle@next. I'm not using this for a production app... just poking around.

I'm having trouble accessing the `loadable-stats.json` from the server. The output path of the loadable-stats is set similar to the [with-react-loadable](https://github.com/jaredpalmer/razzle/tree/master/examples/with-react-loadable) example in the razzle examples. The stats file isn't showing up in the `build` directory however the path is showing in razzles `assets.json` so I know it's being created.

I'm not sure if this is something related to the razzle@next build or just a simple mistake on my end. Any insight would be greatly appreciated!! https://github.com/jbsmith731/razzle-with-loadable

**Comment by lazyd3v** [comment]
I've got it working using

```js
async function getStatsFile() {
  if (process.env.NODE_ENV === 'production') {
    return {
      statsFile: pathResolve('build/public', 'loadable-stats.json'),
    }
  }

  const file = await axios('http://localhost:3001/loadable-stats.json')
  return {
    stats: file.data,
  }
}
```

**Comment by jbsmith731** [comment]
Possibly resolved if the PR from this issue is merged https://github.com/smooth-code/loadable-components/issues/158
