### ISSUE TITLE
jest supports typescript?

### ISSUE THREAD

**Issue by hardfist** [jaredpalmer/razzle#849]
It seems that jest doesn't supports jest now, and it's kind hard to overwrite the jest config to support typescript.

**Comment by hardfist** [comment]
since babel7 supports typescript now, It seems that  supports .tsx? extension is enough?

**Comment by Evanion** [comment]
Check the [Typescript example](https://github.com/jaredpalmer/razzle/tree/master/examples/with-typescript). It has tests written in TS.
