### ISSUE TITLE
Using semantic-ui-css - flickering on page load

### ISSUE THREAD

**Issue by elviejokike** [jaredpalmer/razzle#851]
When using semantic-ui in our application, the experience is that CSS loads after page is rendered. 
Is there a way to avoid this ? 

In my App.js I have:

``
import 'semantic-ui-css/semantic.min.css';
``

I think the issue is similar to  https://github.com/jaredpalmer/after.js/issues/118

**Comment by elviejokike** [comment]
Ok. It can be closed. it is just during development. After carefully reading the doc, i saw that it does not happen on production mode.

**Comment by stevepepple** [comment]
Oh, I got tripped up on this too. Thanks for explaining!
