### ISSUE TITLE
Use third party lib that depends on `window`

### ISSUE THREAD

**Issue by ulrikstrid** [jaredpalmer/razzle#858]
I'm using a [third part library for rendering Power BI charts](https://www.npmjs.com/package/react-powerbi). It depends on the [official Power BI javascript lib](https://github.com/Microsoft/PowerBI-JavaScript) and that in turn uses the `window` object.

What is the suggested way to use libraries that uses `window`, can I conditionally import it depending on if we're on the server or the client?

**Comment by ulrikstrid** [comment]
If anyone is interested I worked around it by loading the component lazily in `componentDidMount`. It's not the prettiest but it solves my issue for now.

**Comment by krazyjakee** [comment]
You can import the library safely but to use it you will either need to use the `typoeof window !== 'undefined'` conditional or do as you did, call it at a point that the client has mounted.

The solution would be for the library to be isomorphic but that is not always possible, until then, as you say, these are the work-arounds.

**Comment by nimaa77** [comment]
this will help you 
https://github.com/jaredpalmer/razzle/issues/1193#issuecomment-599810292

so my suggestion here is to create a component called NoSSR like this:

class NoSSR extends React.Component {
  state = {
    isClient: false
  }
  componentDidMount() {
     this.setState({ isClient: true })
  }
  render() {
    const { isClient } = this.state
    const { children } = this.props
    return isClient ? children : null;
  }
}
and use it in this way:

<NoSSR>
   <BadComponent />
</NoSSR>
