### ISSUE TITLE
Caching Issue

### ISSUE THREAD

**Issue by wagnerjsilva** [jaredpalmer/razzle#859]
Hi,

I was wondering if anyone had a similar issue and how you dealt with it.

What happens is that sometimes, after a build, chrome will need to have its cache cleared, before CORS errors, and other issues disappear. 

In the past I used to append a build number to the end of JS files, and I can see my bundle file is changing names, so that looks good. 

Any ideas?

**Comment by fivethreeo** [comment]
Should not be a issue in latest dev version
