### ISSUE TITLE
TS3 References Support

### ISSUE THREAD

**Issue by brianjd** [jaredpalmer/razzle#863]
I'm currently trying to add Razzle to an existing monorepo with TS3 project references.  But currently getting the following:

```
ERROR in ./src/client.tsx
[tsl] ERROR
      TS5069: Option 'declarationMap' cannot be specified without specifying option 'declaration' or option 'composite'.
 @ multi ./node_modules/razzle/config/polyfills.js /Users/brian/Projects/razzle/packages/razzle-dev-utils/webpackHotDevClient.js ./src/client client[2]

ERROR in ./src/App.tsx
[tsl] ERROR
      TS5069: Option 'declarationMap' cannot be specified without specifying option 'declaration' or option 'composite'.
```

Both `composite` and `declaration` are enabled.  I was thinking it had to do with `razzle-dev-utils` not exporting any declarations.  But after writing some, that didn't appear to resolve anything.  Any insight appreciated.

**Comment by nettiopsu** [comment]
@brianjd why did you close this question? did you resolve it?

**Comment by walleXD** [comment]
@nettiopsu This is a typescript error
