### ISSUE TITLE
ps-tree version "1.1.0" has a deprecated dep due to malicious code

### ISSUE THREAD

**Issue by rg-najera** [jaredpalmer/razzle#866]
Bump ps-tree to  >=1.1.1
Safe version has event stream locked to 3.3.4 https://github.com/indexzero/ps-tree/tree/1.1.1

More info on the threat
https://github.com/indexzero/ps-tree/issues/33

Response from Yarn when trying to install deps
```
https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Request failed "404 Not Found"
```
Specifics on why its important:
https://github.com/dominictarr/event-stream/issues/116

**Comment by jaredpalmer** [comment]
Can you submit a PR?

**Comment by fivethreeo** [comment]
fixed
