### ISSUE TITLE
Can't get SCSS working for me

### ISSUE THREAD

**Issue by SarKurd** [jaredpalmer/razzle#867]
I have installed `razzle-plugin-scss` and created the `razzle.config.js` file
```
module.exports = {
  plugins: ["scss"]
};

```

But still says
`You may need an appropriate loader to handle this file type.`

**Comment by thm-design** [comment]
@SarKurd I believe the source code for `razzle-plugin-scss` has not been published in NPM yet. A workaround is to add the plugin code into a folder in your app and link to it in your package.json like this: `"razzle-plugin-scss": "./lib/razzle-plugin-scss"`

**Comment by SarKurd** [comment]
Thanks, you are correct. 
It works great, hopefully they will release it soon.

**Comment by kaeon** [comment]
Meanwhile it has been released but I still have this issue, can't get it to work, just using default options as described in first post here. I started from the with-typescript example, any ideas?

**Comment by yogthesharma** [comment]
In future if somebody get this problem , try to run npm install first...

**Comment by yogthesharma** [comment]
In future if somebody get this problem , try to run `npm install` first...
