### ISSUE TITLE
webpack module caching causing problems with server-rendering

### ISSUE THREAD

**Issue by alidcast** [jaredpalmer/razzle#868]
webpack doesn't use `require.cache` when compiling to the Node.js target, instead it uses it's own installed modules cache which by default keeps initialized modules per-module. this means that if you have 2 entrypoints loaded into the same app they will not share the same instance

this creates many issues when libraries rely on the singleton pattern (I encountered this problem when adding react-native-web support for [rogue.js](https://github.com/alidcastano/rogue.js), since we use razzle as the ssr build tool)

this issue was also faced with nextjs's webpack setup. here's a useful discussion of the issue on spectrum (which has explanations as well as links to the commits that fixed it): https://spectrum.chat/next-js/general/singleton-issue-when-transpiling-local-modules~ba78d3a3-4ab3-48ef-9b77-956642dfbdb1?m=MTUzNjY3MTEzMDI0NQ==

there was also an issue about it on react-native-web's repo https://github.com/necolas/react-native-web/issues/1079

**Comment by alidcast** [comment]
@jaredpalmer have you not experienced this issue at all? 

found the relevant webpack issue: 
https://github.com/webpack/webpack/issues/7556

**Comment by fivethreeo** [comment]
Should be fixed in dev
