### ISSUE TITLE
How to use environment variables at razzle.config.js

### ISSUE THREAD

**Issue by hardfist** [jaredpalmer/razzle#871]
I want to use `process.env.REACT_BUNDLE_PATH` in razzle.config.js, what's the best way to do that,and how to access `process.env.REACT_BUNDLE_PATH` in server code.

**Comment by hardfist** [comment]
I want to use process.env.REACT_BUNDLE_PATH in `razzle.config.js`, what's the best way to do that

**Comment by krazyjakee** [comment]
@hardfist what is preventing you from using this env variable? Some error?

**Comment by mschipperheyn** [comment]
Anything that is not part of Razzle `.env` already, you have to prefix with `RAZZLE_RUNTIME_` (for runtime variables and `RAZZLE_` for build time variables

**Comment by nimaa77** [comment]
you can use `process.env.REACT_BUNDLE_PATH` inside `razzle.config.js`.
