### ISSUE TITLE
Server build throws inaccurate error when a loader not found

### ISSUE THREAD

**Issue by PezCoder** [jaredpalmer/razzle#873]
### What ?
This is regarding an issue I faced & it took me quite some time to debug it because the errors that the build threw weren't that accurate. Maybe there is a scope for improvement here.

For the following razzle config:
```js
module.exports = {
  modify: (baseConfig, { target, dev }) => {
    const appConfig = Object.assign({}, baseConfig);


    // Note: null-loader is not installed in package.json
    appConfig.module.rules.push({
      test: /.scss$/,
      exclude: /node_modules/,
      use: 'null-loader',
    });


    return appConfig;
  },
};
```

where `null-loader` is not installed in `package.json` when importing an `scss` file inside a `js` module I got this error:

1. When Building the app the following error comes:

![screenshot 2018-12-27 at 12 55 31 pm](https://user-images.githubusercontent.com/8057916/50472607-76fa8f80-09df-11e9-90c2-5b3d2c889494.png)
> Which doesn't explains why the current issue is happening & a google search didn't help me there. My different assumptions at this point included, maybe the file name is wrong or maybe some issue with my webpack config file with sass-loader/css-loader configuration

2. When hot reloading the following error came up:

![screenshot 2018-12-27 at 12 56 05 pm](https://user-images.githubusercontent.com/8057916/50472633-998ca880-09df-11e9-9d7a-590e607c8596.png)

> Which is very accurate & exactly what any project with same webpack configuration without razzle would throw. ✅

### Expectation
I don't know why there is a discrepancy in these errors but I feel these errors should be consistent & precise for better debugging for developers.

I think razzle should just pass whatever error `webpack` is throwing, like in the scenario of hot reloading.

### Minimal reproducible project
You can quickly try what I explained there, just follow the README:
https://github.com/PezCoder/razzle-server-inaccurate-error-demo

Commit: https://github.com/PezCoder/razzle-server-inaccurate-error-demo/commit/55cd1254773b1fbbd0a1b458b9522d79f5d5449e

**Comment by jaredpalmer** [comment]
Is this a razzle issue or webpack one?

Cc @thelarkinn is there a plugin that can check if loaders are installed ? Or provide a better error message?

**Comment by PezCoder** [comment]
@jaredpalmer I think this is a razzle issue because I tried reproducing the same with a webpack project (without razzle) & the errors are very specific like the one in razzle's hot reloading case .. i.e
`Can't resolve x-loader`..

I'm not sure why razzle server is throwing a different error for the same webpack configuration.

**Comment by Tarpsvo** [comment]
I spent more than an hour debugging the Razzle config. Had the same issue - one loader was not installed.

**Comment by fivethreeo** [comment]
Errors can now be more verbose assuming this is fixed
