### ISSUE TITLE
serverCompiler watcher dose not close before a new one is created

### ISSUE THREAD

**Issue by yaoweiprc** [jaredpalmer/razzle#875]
Hi, I'm reading the razzle source code.
When it came to packages/razzle/scripts/start.js
I found this piece of code:
<pre>
clientCompiler.plugin('done', () => {
    serverCompiler.watch(
      {
        quiet: true,
        stats: 'none',
      },
      /* eslint-disable no-unused-vars */
      stats => {}
    );
  });
</pre>

It means everytime the clientCompiler compiles,the serverCompiler create a new watcher.

But the webpack API document says 

> It’s not allowed to watch or run again before the existing watcher has been closed or invalidated.

[https://webpack.js.org/api/node/#close-watching](url)

So I think there is something wrong here.

I'm looking forward to your early reply!

**Comment by jaredpalmer** [comment]
Nice. About to patch this.
