### ISSUE TITLE
Problems with some kind of cache in hot-reload

### ISSUE THREAD

**Issue by eloff** [jaredpalmer/razzle#882]
I've been having very strange issues with razzle and hot reloading. Is there a cache it uses that I can clear? Sometimes the hot reloading will be working, and adding console.log shows up, but other parts of the code will not have updated so what's on disk and what I see in the browser is subtly different. Restarting razzle or the computer solves that problem. But I also see other wierd things that even seem to survive reboots. Case in point:

```
✅  Server-side HMR Enabled!
[HMR] Cannot apply update.
[HMR] Syntax Error: Unexpected )

GraphQL request (6:47)
5:             name
6:             buildings(status: "ACTIVE", sort: ) {
                                                 ^
7:                 data {

[HMR] You need to restart the application!
Running in development mode
🚀 started

> grep buildings src/queries/AvailabilityQueries.js
            buildings(status: "${BUILDING_STATUS.ACTIVE}") {
```

That dangling sort: comes from code I was working on yesterday, on a different branch. I've rebooted since then, I'm on a clean branch, and as you can see there's no dangling sort: on disk. So how is that error happening? I feel like this is a very clear example of the problems I've been having.

I managed to fix it by doing `rm -rf node_modules && npm install`. I'm a bit puzzled by why that worked, is there some kind of cache in the node_modules directory maybe?

```
os: Ubuntu 18.04
node version: v10.12.0
npm version: 6.4.1
razzle version: 2.4.0
```

Do you have any ideas about what might be going wrong? Thanks!

**Comment by jaredpalmer** [comment]
Can you create an example repo?

**Comment by jaredpalmer** [comment]
Pro tip you can write `rs` into the terminal and hit enter and razzle will restart the HMR server watcher

**Comment by brunomperes** [comment]
Not necessarily the same issue, but I was having similar symptoms: Restarting razzle wouldn't pick up new code that I had, and babel loader was complaining at the old code syntax (which wasn't there anymore).

Some digging showed that babel cache can be problematic https://github.com/Jam3/babel-plugin-static-fs/issues/7 and https://github.com/kentcdodds/babel-plugin-preval/issues/19#issuecomment-316208777. But in my case purging `node_modules` didn't help.

What helped was to remove the `build` folder completely.

**Comment by nimaa77** [comment]
Closed due to inactivity. Holler if this is a mistake, and we'll re-open it.
