### ISSUE TITLE
install bugsnag and generate source map in razzle.config.js file

### ISSUE THREAD

**Issue by albertobebz** [jaredpalmer/razzle#884]
I'm quite new to Razzle, but I'd like to install bugsnag for error tracking in my app.
I was able to install bugsnag, but I'm experiencing issue to produce the source map file necessary to locate the error in my app.

my module.export in `razzle.config.js` looks like so:

```
module.exports = {
	modify(config, { target, dev }, webpack) {
		const newConfig = isHeroku
			? razzleHeroku(config, { target, dev }, webpack)
			: config

		newConfig.node = {
			fs: 'empty',
			module: 'empty',
			console: true
		}

		newConfig.devtool = dev ? 'cheap-module-source-map' : 'source-map'

		if (isHeroku && !dev) {
			newConfig.plugins = [
				new BugsnagSourceMapUploaderPlugin({
					apiKey: 'MY-API-KEY-HERE',
					appVersion: '1.2.3'
				}),
				...newConfig.plugins
			]
		}

		if (target === 'web') {
			newConfig.plugins.push(
				new ReactLoadablePlugin({
					filename: './build/react-loadable.json'
				})
			)
		}

		return newConfig
	}
}
```

any advice on how to produce a source map file using Razzle?

thanks in advance

**Comment by nimaa77** [comment]
Closed due to inactivity. Holler if this is a mistake, and we'll re-open it.

**Comment by vivekfyi** [comment]
I am also looking for the same. from  `razzle.config.js` i am returning
  ` appConfig.devtool ='source-map';` but its not generating sourcemap on `razzle build`
