### ISSUE TITLE
ESLint for VSCode

### ISSUE THREAD

**Issue by ryands17** [jaredpalmer/razzle#889]
Is it possible this code could be added in `package.json` by default so that VSCode detects and gives eslint errors in the file itself:

```json
"eslintConfig": {
  "extends": "react-app"
}
```

**Comment by bartlangelaan** [comment]
Eslint will be removed from the default Razzle setup (see #839 and #888). So I think this should just be moved to the installation instructions of the new plugin, instead of adding this by default.
