### ISSUE TITLE
Zeit Now 2.0 example?

### ISSUE THREAD

**Issue by ukyiwin** [jaredpalmer/razzle#900]

**Comment by jaredpalmer** [comment]
Feel free to open a PR

**Comment by Siilwyn** [comment]
Think this would replace the current Now example since 1.0 seems to be on its way out.

**Comment by chrisdrackett** [comment]
I came here to open then as I am getting a build error currently when using `@now/node-server`. Has anyone else had luck getting razzle to build on now?

**Comment by revskill10** [comment]
@chrisdrackett It's not hard .
BUT in my case, i have to "prebuild" the app with manual `ncc` , instead of using `now` as CI.

**Comment by chrisdrackett** [comment]
yeah, I can get it going with a pre-build, but I'd much rather build on deploy if possible

**Comment by lessp** [comment]
hmm, I can't figure out a reasonable way to pre-build it. @revskill10, you said something about `ncc`, would you mind elaborating?

**Comment by bausk** [comment]
@lessp `ncc` is Zeit's transpiler for Node.js that bundles dependencies into a single file, it can be run locally as an npm script and, to my understanding, works similarly to Zeit's builders like `@now/node` and `@now/node-server`.

I have just tried using it to deploy Razzle and found it to be just repetition of the standard Zeit build process, at least for the standard Razzle template with no dependencies. Here's my `now.json`, for reference:

```
{
    "version": 2,
    "name": "example",
    "builds": [
        {
            "src": "build/public/**",
            "use": "@now/static"
        },
        {
            "src": "build/server.js",
            "use": "@now/node-server"
        }
    ],
    "routes": [
        { "src": "/assets.json", "dest": "build/assets.json" },
        { "src": "/favicon.ico", "dest": "build/public/favicon.ico" },
        { "src": "/robots.txt", "dest": "build/public/robots.txt" },
        { "src": "/static/(.*)", "dest": "build/public/static/$1" },
        { "src": "/(.*)", "dest": "build/server.js" }
        
    ]
}
```
Maybe someone knows how to get rid of these abominations of routes BTW.
