### ISSUE TITLE
Update react-dev-utils (seems broken in next)

### ISSUE THREAD

**Issue by mschipperheyn** [jaredpalmer/razzle#905]
The React-dev-utils package seems outdated. The version used in `next` is older than the one in `master`? I'm having significant problems with it. Particularly, intermittently but regularly the whole page is inlined as escaped Javascript and becomes unresponsive. I have only worked with `next` so far and I can't say when it happens, just that it does regularly. 

`master razzle/react-dev-utils`: 6.1.1
`next razzle/react-dev-utils`: *6.0.4*
`CRA react-dev-utils`: 7.0.1

<img width="537" alt="screenshot 2019-01-25 at 13 45 51" src="https://user-images.githubusercontent.com/384959/52001564-de0bd800-24a6-11e9-81e7-77faacd93292.png">

**Comment by nimaa77** [comment]
check #1210
