### ISSUE TITLE
Typescript plugin doesn't allow regular .js files

### ISSUE THREAD

**Issue by mschipperheyn** [jaredpalmer/razzle#909]
The typescript plugin should allow the use of javascript files next to typescript files. It doesn't. 

Loading a regular javascript in your typescript template will lead to a compilation error:

```
Module parse failed: Unexpected token (3:19)
You may need an appropriate loader to handle this file type.
```

**Comment by jaredpalmer** [comment]
Add allowJs: true to your tsconfig
