### ISSUE TITLE
.babelrc - Requires Babel "^7.0.0-0", but was loaded with "6.25.0" error

### ISSUE THREAD

**Issue by kkarkos** [jaredpalmer/razzle#912]
Hi, I'm trying to install "https://github.com/airbnb/babel-plugin-inline-react-svg" and as per docs I'm using a root based .babelrc

`{
  "presets": [
    "razzle/babel", // NEEDED
    "stage-0"
  ],
  "plugins": ["inline-react-svg"]
}
`

I get the following error:
`ERROR in ./src/client/index.js
Module build failed (from ./node_modules/razzle/node_modules/babel-loader/lib/index.js):
Error: Requires Babel "^7.0.0-0", but was loaded with "6.25.0". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what iscalling Babel.
    at throwVersionError (/Users/konrad/Documents/Projects/widget-interim-repo/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
    at assertVersion (/Users/konrad/Documents/Projects/widget-interim-repo/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)`

Does razzle/babel only work with version 6 as stated here? https://github.com/babel/babel/issues/8688#issuecomment-420485466

I'm using:

`    "@babel/core": "^7.2.2",
    "babel-core": "^7.0.0-bridge.0",`

Also tried it without the bridge. Cleaned the "npm cache" and all other kind of suggestions for this error online. 

Any idea? Thank you!

**Comment by mschipperheyn** [comment]
I recommend using `razzle@next`, that one uses babel 7.

**Comment by kkarkos** [comment]
Thanks, I bumped to `v3.0.0-alpha.2`- now. With babel 7 "stage-0" got removed (https://babeljs.io/blog/2018/07/27/removing-babels-stage-presets). No errors with using 

`{
  "presets": [
    "razzle/babel", // NEEDED
  ]
}
`

However, I can't use alpha in production.

**Comment by kkarkos** [comment]
This can be closed -> answer here: https://github.com/jaredpalmer/razzle/issues/881#issuecomment-460891060
