### ISSUE TITLE
typescript error in node_modules

### ISSUE THREAD

**Issue by HamidTanhaei** [jaredpalmer/razzle#914]
i'm using razzle typescript. and i get error from node_modules by typescript.
sample error:
```
ERROR in /home/hamid/my/www/with-typescript/node_modules/@types/react-redux/index.d.ts(118,29):
TS2370: A rest parameter must be of an array type.
```
I have tried to change tsconfig.json configs to exclude node_module files but it was not successful.
how can i disable it forever?

**Comment by jaredpalmer** [comment]
This is not a Razzle issue but a TypeScript one.

**Comment by HamidTanhaei** [comment]
according to an issue in **fork-ts-checker-webpack-plugin** package i solved this problem by this reply:
https://github.com/Realytics/fork-ts-checker-webpack-plugin/issues/128#issuecomment-407371617

unfortunately, lots of packages have problems in their typescript and possible to you get them as errors and stops you from building razzle.

I say this for anybody has this problem
add `"skipLibCheck": true` in compilerOptions in tsconfig.json in your project's root.

@jaredpalmer I can open a pull request for default examples in the master branch.
