### ISSUE TITLE
add persistor to redux

### ISSUE THREAD

**Issue by fuadqerja** [jaredpalmer/razzle#917]
guys i'm confused how to setUp configureStore in razzle, since my project have to use redux-persistor
here's what i've come up with for now, is this the right way to configure the store? am i doing  it right?
```
const persistedStore = preloadedState => {
  const rootReducer = {
      homeReducer: HomeReducer,
      headerReducer: HeaderReducer,
      profileReducer: ProfileReducer,
      orderReducer: OrderReducer,
      singleOrderReducer: OrderDetailReducer,
      balanceReducer: BalanceReducer,
      editProfileReducer: EditProfileReducer,
      trackingReducer: TrackingReducer,
      pickupDetailReducer: PickupDetailReducer,
      feederReducer: FeederReducer,
      corporateReducer: CorporateReducer
  }

  const Immutable = require('immutable')
  const Serialize = require('remotedev-serialize')
  const reduxPersist = require('redux-persist')

  function immutableTransform(config) {
    config = config || {}

    const serializer =  Serialize.immutable(Immutable, config.records)

    return reduxPersist.createTransform(serializer.stringify, serializer.parse, config)
  }

  const persistConfig = {
      transforms: [immutableTransform()],
      key: 'root',
      storage
    }

  const reducer = combineReducers(rootReducer)
  const persistedReducer = persistReducer(persistConfig, reducer)

  const store = createStore(persistedReducer, preloadedState, applyMiddleware(thunkMiddleware))
  const persistor =  persistStore(store)

  if (module.hot) {
    // Enable Webpack hot module replacement for reducers
    module.hot.accept('../reducers', () => {
      const nextRootReducer = require('../reducers').default;
      store.replaceReducer(nextRootReducer);
    });
  }
  return store
}

export default persistedStore;
```

**Comment by mattlubner** [comment]
You'll want to define your `configureStore()` method (for creating the Redux store) separately from the persistence setup, as you're most likely going to want to handle persistence differently between the client and server.

If you/others think it's worthwhile, I can extract my setup into a small example of how to setup redux-persist with razzle.

**Comment by mattlubner** [comment]
I should clarify that it's the `persistStore()` call that likely needs to be different between client/server. You'll still want `configureStore()` to return the persisted reducer.

**Comment by fuadqerja** [comment]
> If you/others think it's worthwhile, I can extract my setup into a small example of how to setup redux-persist with razzle.

that will help a lot, i really need that setup for this. i still trying to figure it out how to do it with redux-persist but still no clue how to setup between client/server

**Comment by HamidTanhaei** [comment]
you should create your store in client and server. and stay them updated and synced

**why?**
you can store your redux data in browser storage but you don't have browser storage in the server.

then you should store your data in browser storage or cookie or ... in the browser, and save them in somewhere accessible on the server.

**what is the easiest way?**
if you store your redux data on cookie, you can get them on every request and create your store (on the server side) with initial data gotten from the cookie.

**how you can do it?**
use _redux-persist-cookie-storage_
https://github.com/abersager/redux-persist-cookie-storage

**what is the drawback?**
you can't store more than 4096 chars on the cookie.

**Comment by HamidTanhaei** [comment]
I have configured my redux and persistor this way and everything is working fine and synced
https://medium.com/@HamidTanhaei/react-ssr-persist-redux-data-19cc2a667217
https://github.com/abersager/redux-persist-cookie-storage
