### ISSUE TITLE
 Class constructor XYZ cannot be invoked without 'new'

### ISSUE THREAD

**Issue by mschipperheyn** [jaredpalmer/razzle#919]
There is a problem that I have when extending classes from packages in `node_modules` e.g. `sequelize` and other tools such as `apollo-rest-client`. It is caused by trying to extend transpiled classes.

Discussions about this can be found here: 
https://github.com/sequelize/sequelize/issues/7840
https://github.com/apollographql/apollo-server/issues/2216 
and many other places. 

There is a PR open for this issue @babel https://github.com/babel/babel/pull/8656 bur who knows if and when it gets merged.

The common suggested workaround is applying
```
               [
			"@babel/preset-env",
			{
				"targets": {
					"node": "current"
				}
			}
		]
```

Unfortunately, that doesn't work with `razzle`, presumably because `@babel/plugin-transform-runtime` is used which is one of the other suggestions to solve this: remove that library. 

Does anyone have this same problem and possibly a workaround? It's starting to hit me in more and more of the libraries I want to use.

**Comment by mschipperheyn** [comment]
Workaround / Fixed: 

babel.config.js
```
const razzleBabel = require('razzle/babel');

module.exports = function babelConfig(api) {
	api.cache(true);

	const babel = razzleBabel();

	babel.presets[0] =
		process.env.BUILD_TARGET === 'client'
			? [
				require.resolve('@babel/preset-env'),
				{
					modules: false,
				},
			  ]
			: [
				require.resolve('@babel/preset-env'),
				{
					targets: {
						node: 'current',
					},
					exclude: [
						'babel-plugin-transform-classes',
						'@babel/plugin-transform-classes',
					],
					modules: false,
				},
			  ];
              [...]
```

**Comment by 1Jesper1** [comment]
Hello @mschipperheyn Could you describe your fix? When I add 
 ```
targets: {
  node: 'current',
},
``` 

to my _babel.rc_ I get the following error: 

_ReferenceError: regeneratorRuntime is not defined_

Babel 7 and Node 12
