### ISSUE TITLE
What's new in Razzle 3.0?

### ISSUE THREAD

**Issue by yaoweiprc** [jaredpalmer/razzle#923]
I can not wait to try it!

**Comment by alaycock** [comment]
You can see the diff here: https://github.com/jaredpalmer/razzle/compare/v2.4.1...v3.0.0-alpha.2

Looks like Babel 7, Jest 23 are the main reasons for the major version bump (so far).

**Comment by lucasterra** [comment]
There is this breaking change: https://github.com/jaredpalmer/razzle/tree/next#polyfills

**Comment by gabimor** [comment]
Any updates on when v3.0.0 is out?

**Comment by fivethreeo** [comment]
Any stoppers for 3.0.0? Would testing it help? Installed alpha.2, running fine :)

**Comment by ThisIsMissEm** [comment]
Razzle 3.0.0 is out, this issue can be closed

**Comment by ThisIsMissEm** [comment]
See: https://github.com/jaredpalmer/razzle/releases/tag/v3.0.0
