### ISSUE TITLE
Production: SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by SarKurd** [jaredpalmer/razzle#924]
My app works for both development and production locally but when i push to heroku i get SyntaxError: Unexpected token < and Resource interpreted as Stylesheet but transferred with MIME type text/html

**Comment by SarKurd** [comment]
Downloaded `razzle-heroku` and everything fixed, i don't know what was going on

**Comment by tejovanthWork** [comment]
Does this work outside heroku too?
