### ISSUE TITLE
Resource interpreted as Stylesheet but transferred with MIME type text/html 

### ISSUE THREAD

**Issue by cca313** [jaredpalmer/razzle#932]
first, run npm run build  on jenkins
next,  move the whole project to server and pm2 restart
and i got Uncaught SyntaxError: Unexpected token < on console
this confuse me for few days,i added publicPath= './public/' in webpack and RAZZLE_PUBLIC='./build/public' for env variables,the problem still unresolved.

**Comment by cca313** [comment]
@jaredpalmer can you help me out?

**Comment by cca313** [comment]
just add RAZZLE_PUBLIC_DIR=./build/pubic with command line when build

**Comment by fivethreeo** [comment]
In razzle 4 ensure cwd is the project root.
