### ISSUE TITLE
Brotli compression

### ISSUE THREAD

**Issue by gsharath** [jaredpalmer/razzle#933]
I recently came to know Brotli which is found to compress files to a lesser size when compared to gzip compression.

Do we have Brotli compression in razzle which I can use in a react project hosted on node?
I know the support for it not for all browsers, but I would like to understand if I can compress my binaries using brotli because of its good compression techniques.

**Comment by nimaa77** [comment]
hello @gsharath, read this 
https://codeburst.io/express-brotli-webpack-a60773e7ec6c
this will help you to do it :)
