### ISSUE TITLE
react-loadable example error

### ISSUE THREAD

**Issue by drodriguez7** [jaredpalmer/razzle#934]
The example with react-loadable throws an error in the dynamic import syntax, maybe is because of the webpack version used in razzle?

Error: 

You may need an appropriate loader to handle this file type.
```
| var Intro = Loadable({
|   loader: function loader() {
>     return import('./Intro');
|   },
|   modules: ['./Intro'],
```

**Comment by fivethreeo** [comment]
Don't use react-loadable, use @loadable/component until lazy and Suspense work serverside. See my django razzle repo, the example here is outdated
