### ISSUE TITLE
How to install a forked version of razzle or HEAD / branch?

### ISSUE THREAD

**Issue by mschipperheyn** [jaredpalmer/razzle#938]
I want to use the HEAD of the `next` branch for our project. But I'm having a really hard time getting it installed. Normally, I would use a a `git` commit url to install the version I want but this not working. This might be because it uses the concept of `workspaces`. Anybody have an idea?

**Comment by revskill10** [comment]
@mschipperheyn How about `yarn add https://github.com/jaredpalmer/razzle#master` ?

**Comment by mschipperheyn** [comment]
```
yarn add https://github.com/jaredpalmer/razzle#next
yarn add v1.10.1
[1/4] 🔍  Resolving packages...
error Can't add undefined: invalid package version undefined.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by revskill10** [comment]
@mschipperheyn There's no `next` branch in `razzle` git repo.

**Comment by mschipperheyn** [comment]
@revskill10 https://github.com/jaredpalmer/razzle/tree/next Perhaps I'm not getting it
