### ISSUE TITLE
React router v4 + redux + scss

### ISSUE THREAD

**Issue by The-Code-Monkey** [jaredpalmer/razzle#951]
How would I intergrate all 3 of these together using your wrapper i also use connected-react-router, i keep getting errors like  Cannot read property 'pathname' of undefined from ConnectedRouter

**Comment by RodolfoGS** [comment]
+1

**Comment by nimaa77** [comment]
use [after.js](https://github.com/jaredpalmer/after.js) it will help you with these
and it has examples for redux and scss
