### ISSUE TITLE
Invitation to peer review: Razzle with loadable-components

### ISSUE THREAD

**Issue by mbrochh** [jaredpalmer/razzle#954]
I have given Razzle + loadable-components another try and I think this time I got pretty far. I have it good enough to continue with my work, but I have a feeling that my solution still is somewhat of a hack and I would like to invite others with more expertise to tell me what is the missing piece of the puzzle ;)

I have published a sample repo here to allow you to quickly set this up on your machine:

https://github.com/mbrochh/razzle-loadable-components

You can set it up like so:

```
git clone git@github.com:mbrochh/razzle-loadable-components.git my-app
cd my-app
yarn
mkdir build
yarn start
# go to localhost
```

At this point, you can click around and everything should work. Note the "render Home" and "render About" output. I added those to show that React has actually loaded on the client-side and I'm not just seeing the server rendered page.

Now remove the `asd` in `Home.js` and save the file. You will see that the page goes blank and the console throws a warning:

```
index.js:1 Uncaught Error: Iframe has not been created yet.
```

It's annoying but I'm OK with this, I don't mind refreshing the page after making changes in my code (after all, I want to see if the server rendered page still looks good as well).

---

So what is the problem? Have a look at [what I did in `server.js`](https://github.com/mbrochh/razzle-loadable-components/blob/master/src/server.js#L15).

You can switch to the branch `master_broken` and now try to change something in `Home.js` - when you refresh the browser, your change does show up, but React does not load on the client side any more and you just seeing the server rendered page until you restart `yarn start`.

In the past, when I attempted this, I realised that client and server get out of sync when I change stuff in my files and I always have to restart `yarn start` to be able to continue to work, which is extremely annoying when compilation takes 40 seconds.

I think I now understand why this happens:

1. we have two dev-servers running, one for the client, and one for the server
2. when we change a file, both dev-servers re-compile
3. however, we can't control the order (and speed) in which they re-compile so it can happen that the server re-compiles faster than the client (that would be expected because the server doesn't need to create chunks)
4. this means, when the server re-compiles, it will sometimes read the outdated `loadable-stats.json` file because the client is still compiling and has not created a new file, yet
5. now client and server are out of sync and all kinds of crazy annoying stuff happens during development, you must run `yarn start` again to get them back into sync

So as my ugly hacky workaround, I am now doing this:

1. if we are working in local development mode (NODE_ENV === 'development'), we will simply read the stats file on every request. I assume that in a production environment, this would be overkill and put too much stress on the server (maybe I'm wrong and just worrying too much?)
2. So in a production environment, I will just load the file once when the server starts, after all, I'm never changing the file on my PROD server unless I make a deployment and when I do make a deployment, I will restart the server anyways and it will then load the latest file

My questions are:

1. Is this the best way to do it?
2. Is there some better trick to make sure that the server only ever compiles AFTER the client has finished compiling?
3. Would it be OK even in a PROD environment to read the stats-file on every request?
4. How can I get rid of this `Uncaught Error: Iframe has not been created yet.` error?

Any and all input is hugely appreciated! Many thanks in advance!

**Comment by revskill10** [comment]
I have no problem with combining these two. The code is in some lines of code.
`server.ts`
```js
import { ChunkExtractor, ChunkExtractorManager } from '@loadable/server';
const extractor = new ChunkExtractor({
      statsFile: path.resolve(__dirname, 'loadable-stats.json'),
      entrypoints: ['client'],
    });
  
    const markup = ReactDOM.renderToString(
        <ChunkExtractorManager extractor={extractor}>          
              <App />
        </ChunkExtractorManager>
    );
const html = `<html>
<head>
${extractor.getLinkTags()}
${extractor.getStyleTags()}
</head>
<body><div id="root">${markup}</div>
${extractor.getScriptTags()}
</body>`;
```

**Comment by mbrochh** [comment]
@revskill10 so that code in your case gets executed on every single request, correct? 

otherwise I don't see how this could work, because as far as I understand it, the stats file will not be guaranteed to be updated by the time the server re-compiles after you change the sourcecode.

EDIT: also, we found that ChunkExtractorManager doesn't seem to work at all, but I will give it another try...

EDIT2: I tried with ChunkExtractorManager again inside the request and it works!

**Comment by revskill10** [comment]
@mbrochh Yes, the whole code is inside a `handler (req, res)`. I'm using the above code and it works normally.

**Comment by mbrochh** [comment]
@revskill10 that makes sense! As I mentioned in my initial post, I am a little bit concerned of the CPU overhead to read and parse the stats file on every single request. That file is 154k in our app. Surely, parsing that file on every single request will add a few ms to the request-response time, right?

EDIT: I have done it now like you suggest and it works like a charm. I'm still worried that I might be wasting a few milliseconds here in the request-response cycle but I will deploy this to PROD anyways and see if the Google Lighthouse plugin will complain (I guess not)
