### ISSUE TITLE
Warning: `startReportingRuntimeErrors` doesn’t accept `launchEditorEndpoint` argument anymore. Use `listenToOpenInEditor` instead with your own implementation to open errors in editor 

### ISSUE THREAD

**Issue by plkoiu** [jaredpalmer/razzle#955]
index.js:1 Warning: `startReportingRuntimeErrors` doesn’t accept `launchEditorEndpoint` argument anymore. Use `listenToOpenInEditor` instead with your own implementation to open errors in editor

**Comment by wagnerjsilva** [comment]
We're also having this warning, not breaking anything at the moment, but it would be nice to see it go.

**Comment by jlramosr** [comment]
I also have this warning. Any news on this matter?

**Comment by brianpmaher** [comment]
Seeing this issue using latest razzle version `2.4.1`.

**Comment by diogocapela** [comment]
No more warning when updating to version `3.0.0`.

**Comment by wagnerjsilva** [comment]
Still seeing it in 3.0, just not in the production build.

**Comment by fivethreeo** [comment]
Is this still a issue?

**Comment by fivethreeo** [comment]
Assuming this is no longer a issue, reopen if it still is
