### ISSUE TITLE
Server-side HMR doesn't work on linux

### ISSUE THREAD

**Issue by nikparo** [jaredpalmer/razzle#957]
Hi. I'm testing out Razzle, but I'm having trouble with server-side HMR. It simply doesn't work on my Linux box (Archlinux). The exact same thing work just fine on my MacBook.

Creating a new razzle app using:
`npx create-razzle-app my-razzle-app`
`cd my-razzle-app/`
`npm start`
Gives my this kind of output when making minor changes to the code (e.g. adding console.log statements):
```
Compiling
✔ success client compiled in 2s 11ms
✔ success server compiled in 226ms
✅  Server-side HMR Enabled!
🚀 started
✔ success server compiled in 77ms
✔ success server compiled in 71ms
✔ success server compiled in 162ms
✔ success client compiled in 173ms
```

As you can see, the line `🔁  HMR Reloading ./server...` is missing, and the server does in fact never reload. Client side HMR works fine. It does re-compile the server code though, so the changes are picked up for that.

Any idea what's going on here? I have tried `npm install`, creating a new app, updating and rebooting my system, and running `sudo npm start`. `safe write` shouldn't be a problem since I use VS Code (which apparently doesn't have it), and my `max_user_watches` is at 524288, so that should also be ok.

**Comment by nikparo** [comment]
This is likely a webpack and/or node issue, as I can reproduce it outside of razzle, e.g. with [webpack/hot-node-example](https://github.com/webpack/hot-node-example)

I've filed an issue with webpack:
[Server-side HMR not updating in node v11.11.0+](https://github.com/webpack/webpack/issues/8970)

**Comment by bnlokash** [comment]
I encountered the same issue on Node 11.13. Fixed by installing 10.15.3 LTS

**Comment by sneridagh** [comment]
@nikparo @bnlokash 
Linux has the max_user_watches limited, increase it by:
`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

**Comment by nikparo** [comment]
Thanks @sneridagh, but I checked `max_user_watches` before opening this issue. Furthermore, I've noticed the exact same thing on my macbook. There's now also another issue filed with webpack for this: [Server-side hot reload not working for Node 11.x #9012](https://github.com/webpack/webpack/issues/9012)

**Comment by sneridagh** [comment]
@nikparo strange! I solved the problem just this last week with one of my coworkers using the `max_user_watches`.

I also have no problem in my Macbook, but it's true that I tweaked it long time ago to support more open files (file descriptors) (I do not remember exactly what I did, I'll have to search again for it). Hope this helps!
