### ISSUE TITLE
CSS Modules and subclass element

### ISSUE THREAD

**Issue by alexbigapps23** [jaredpalmer/razzle#960]
Hi i need set razzle.config.js for supported CSS modules and  supported  subelement classs like in attach file 
How i can do this ? any Ideas ?
![jshOc](https://user-images.githubusercontent.com/23071049/55136871-345c6680-5138-11e9-9328-d8b431304c14.png)

**Comment by nimaa77** [comment]
razzle supports CSS modules by default, no need to customize anything
