### ISSUE TITLE
Workspace package works during build, but not development

### ISSUE THREAD

**Issue by philipnilsson** [jaredpalmer/razzle#964]
I'm using yarn workspaces which links workspace packages under `node_modules` without running babel on the package. For this reason I'd like to ensure that my razzle setup runs babel on these packages.

Most likely my problem can be simplified to "run babel also for imports under `node_modules/@myorg`", potentially with the complication that these packages are symlinks.

I've tried changing my configuration by adding a `razzle.config.js` webpack override, which runs during packaging

```js
const path = require('path');

module.exports = {
  modify: (config, { target, dev }, webpack) => {
    // rules[2] is the babel loader.
    config.module.rules[2].include.push(
      path.join(__dirname, './node_modules/@myorg')
    );
    return config;
  },
}
```

Everything seems to be going fine when I run the `build` script. My code comes out transpiled correctly. However, when I'm running the `start` scripts, I keep getting an error preventing the server from starting.

![image](https://user-images.githubusercontent.com/2103391/55401205-54cd5c00-5550-11e9-964c-df9d8fcbaa03.png)

Any advice?

**Comment by vitorcamachoo** [comment]
> I'm using yarn workspaces which links workspace packages under `node_modules` without running babel on the package. For this reason I'd like to ensure that my razzle setup runs babel on these packages.
> 
> Most likely my problem can be simplified to "run babel also for imports under `node_modules/@myorg`", potentially with the complication that these packages are symlinks.
> 
> I've tried changing my configuration by adding a `razzle.config.js` webpack override, which runs during packaging
> 
> ```js
> const path = require('path');
> 
> module.exports = {
>   modify: (config, { target, dev }, webpack) => {
>     // rules[2] is the babel loader.
>     config.module.rules[2].include.push(
>       path.join(__dirname, './node_modules/@myorg')
>     );
>     return config;
>   },
> }
> ```
> 
> Everything seems to be going fine when I run the `build` script. My code comes out transpiled correctly. However, when I'm running the `start` scripts, I keep getting an error preventing the server from starting.
> 
> ![image](https://user-images.githubusercontent.com/2103391/55401205-54cd5c00-5550-11e9-964c-df9d8fcbaa03.png)
> 
> Any advice?

You Forgot to add whitelist in node-externals.

**Comment by philipnilsson** [comment]
Thanks for the advice. A variation of this worked to resolve this.

**Comment by simonmares** [comment]
> A variation of this worked to resolve this.

@philipnilsson can you share the `razzle.config.js` file? Thank you.
