### ISSUE TITLE
Unable to access port 3001 from a remote machine

### ISSUE THREAD

**Issue by elis** [jaredpalmer/razzle#968]
It's probably trivial to fix (with the `--host 0.0.0.0` flag) - but no clear details on how to provide this configuration to the project.

**Comment by marcellobarile** [comment]
hi @elis 
isn't https://github.com/jaredpalmer/razzle/blob/master/README.md#environment-variables or https://github.com/jaredpalmer/razzle/blob/master/README.md#runtime-variables helpful for you?

Plus, are you sure that your issue is related to Razzle and not to your network/server machine?

**Comment by elis** [comment]
@marcellobarile no, unrelated to variables.

Out of the box when running in local development mode, the default port (3000) will be accessible from outside, while the secondary development server is not. basically rendering the entire thing broken so much so that I don't even load the svg or CSS.

**Comment by marcellobarile** [comment]
could you be more precise about this "secondary development server"? What's that?

**Comment by elis** [comment]
https://github.com/jaredpalmer/razzle/blob/master/README.md#how-razzle-works-the-secret-sauce

> While your server is bundled and run on whatever port you specify in src/index.js (3000 is the default), the client bundle (i.e. entry point at src/client.js) is served via webpack-dev-server on a different port (3001 by default) with its publicPath explicitly set to localhost:3001 (and not / like many other setups do).

**Comment by marcellobarile** [comment]
@elis oh I see what you mean now; honestly, in my setups, if they have to be accessible from the outside, I always tend to have a web server that acts as a proxy pass towards my Node.js apps. Btw, maybe you can try with the following webpack custom configuration? https://webpack.js.org/configuration/dev-server#devserverhost

**Comment by elis** [comment]
Ugh, I figured out the issue...

When accessing from a remote machine, the requests are pointing to `http://localhost:3001/` regardless of what configuration I provide; e.g. it doesn't respect the currently accessed hostname (elimbps in my case).

Checkout the attached screenshot:

![image](https://user-images.githubusercontent.com/101744/55554886-9135bf00-56ec-11e9-8955-af60ebb2eb93.png)

**Comment by elis** [comment]
Found the cause and a wanky workaround;

The cause seems to be this configuration line: https://github.com/jaredpalmer/razzle/blob/43160eb1cdbbe5b4353a714a3db7faba629a1bd3/packages/razzle/config/createConfig.js#L103

> `    (IS_DEV ? `http://${dotenv.raw.HOST}:${devServerPort}/` : '/');`

So by providing a `HOST` env variable that matches my hostname that allows access to the devServer from that hostname, but will not work when trying to access on localhost now.

There's no need to modify the webpack configuration in any way; the issue is solely with the way these URIs are generated.

**Comment by elis** [comment]
"resolved itself: today when I decided to hop back on the project and did a clean install with NPM.

Hate those bugs that resolve themselves without any clue as to why they happened or what fixed them. I'd assume something went wrong in my local machine's network settings.

**Comment by gazpachu** [comment]
I managed to make it work with `HOST=192.168.0.101 npm start` but then, the Safari inspector stops working.

When I plug the USB cable, it detects the iPhone in Safari Develop Menu, but as soon as I click on the localhost item, the dev tools panel opens and then it closes right away after a couple of seconds. Then the Safari Develop Menu item turns into "Connecting..."

This strange behaviour only happens when I ran the start command with the HOST env var.

**Comment by jrolfs** [comment]
For anyone else coming across this, I had to use a combination of some of the above suggestions to get it working properly.

Specify `HOST` environment variable to point to the host:

```sh
HOST=10.10.10.10 yarn start
```

Bind Webpack dev servers to `0.0.0.0`:

**razzle.config.js**
```js
module.exports = {
  modifyWebpackConfig: (_, webpackConfig: config }) => {
    config.devServer ||= {};
    config.devServer.host = '0.0.0.0';

	return config;
  }
}
```
