### ISSUE TITLE
Support jest.setupFilesAfterEnv

### ISSUE THREAD

**Issue by weslleyaraujo** [jaredpalmer/razzle#972]
Hello 👋

Is there a particular reason why [`setupFilesAfterEnv`](https://jestjs.io/docs/en/configuration#setupfilesafterenv-array) is not supported on [`createJestConfig`](https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/config/createJestConfig.js#L41) by razzle?

I am trying to setup something like https://github.com/gnapse/jest-dom but it seems like only `setupFiles` option is not enough 😐

**Comment by nimaa77** [comment]
hi, setupFilesAfterEnv is for jest v24, razzle 3 uses jest v23 and you have to use setupTestFrameworkScriptFile for this, by default setupTestFrameworkScriptFile loads <rootDir>/src/setupTests.js so you can import `jest-dom` inside setupTests.js file ...

**Comment by brendanmorrell** [comment]
not a perfect solution, but you can also just import '@testing-library/jest-dom/extend-expect' in your test-utils file. you are likely going to be importing something from that in every test you write where you would need to extend expect anyway, so it will run as you want it already, and you won't have to manually import it in each test (which I assume is why you want to use setupFilesAfterEnv).
