### ISSUE TITLE
Working with antd?

### ISSUE THREAD

**Issue by kykungz** [jaredpalmer/razzle#973]
Has anyone successfully implemented `antd` (with custom theme) and razzle? It seems like every issues about `antd` are left closed by the bot or not working.

So, can anyone use `antd` with razzle?
Could you provide a step-by-step example?

**Comment by JCheungX** [comment]
this is what i have 
```
const styleLoader = IS_DEV ? 'style-loader' : MiniCssExtractPlugin.loader;
 const theme = /* your custom theme */
  const lessCssConfig = {
    loader: 'css-loader',
    options: { importLoaders: 1 },
  };

 config.module.rules.push({
    test: /\.less$/,
    include: [/node_modules\/.*antd/],
    use: IS_NODE
      ? [
        lessCssConfig,
        `less-loader?{"javascriptEnabled" : true, "modifyVars":${JSON.stringify(theme)}}`,
      ]
      : [
        styleLoader,
        lessCssConfig,
        `less-loader?{"javascriptEnabled" : true, "modifyVars":${JSON.stringify(theme)}}`,
      ],
  });
```

**Comment by revskill10** [comment]
It's tricky. You need separate babel for `node` and `web` target.

**Comment by olup** [comment]
I can't seem to have Antd work with razzle either, @JCheungX can you ellaborate on the snippet you posted, like present your complete Razzle config ? I could make it work until a cretain point but server side allways stumble upon the @import rules, when loaded with the babel import plugin in .babelrc.

Any suggestions ?

**Comment by olup** [comment]
I'll add that i try to import antd less styles with the babel plugin import, and that's when the error is triggered.

**Comment by JCheungX** [comment]
@olup 
our webpack is heavily customised for our own project.
did u use antd import plugin as well? We didnt use it for server, only for client side.

**Comment by olup** [comment]
Yes, i finally managed to get it work smoothly, I used mini css extract
plugin in combination with the import plugin.

However, as you said, the plugin import needs to be called only in building
the client.

That was a bit tricky as i couldnt find a way to discriminate the client
build either in babelrc or in babel.config.js. I had to use a verbose bit
of code to modify the razzle.config.js webpack config, extract babel config, and add the
plugin conditionally.

Now all is well, but i'd love a cleaner way, through babel.config.js.

**Comment by olup** [comment]
For future readers, the snippet posted by @jCheungX is very helpfull to load the less files properly. However it omits the need to add the babel plugin import for antd only while building the client. On node it will throw an error. 

There is probably multiple ways to achieve that but you can use https://github.com/jaredpalmer/razzle/issues/510#issuecomment-465940252 which worked ok for me.
