### ISSUE TITLE
Output Project directory structure

### ISSUE THREAD

**Issue by franleplant** [jaredpalmer/razzle#981]
Hi! Thanks a lot for razzle, it is amazing!

I was wondering if there has been any discussion or if there are already any solutions to setting up the output project directory structure.

To be more concrete, I would like to do something like this

`create-razzle-app --dir-structure=my-company my-app`

And this will output, instead of the default, flat, directory structure something like this (just as an example)

```
- myApp/src
  - client/
     - components/
     - containers/
     - ...
     - index.js
   - server/
     - routes/
     - middleware/
     - ...
     - index.js

```

This will allow multiple razzle apps not only share plugins, and code but directory structure (without any manual intervention)

I've seen that there is the `--example` flag in `create-razzle-app` but I don't fully understand what it does. Can we leverage that to accomplish this feature?

Thanks a lot!

**Comment by nimaa77** [comment]
nice idea.

`--example` is used to download an example from [here](https://github.com/jaredpalmer/razzle/tree/master/examples) and basically it will create your razzle-app with that configuration and folder structure.

what you can do is create your own folder structure and create a GitHub template for it and after that each time you want to create a new app just open GitHub and create a new repo with that template.
