### ISSUE TITLE
Example on how to use styled-components + material ui in Document.js

### ISSUE THREAD

**Issue by serge20** [jaredpalmer/razzle#982]
I've been trying to migrate from next.js to razzle. I'm running into a problem since I use both styled-components and material-ui. I can't find an example that uses the Document.js file to do SSR on the styles for both libraries. 

Anyone has tried to do that?

**Comment by edersign** [comment]
Do u need edit a [ server.js ](https://github.com/jaredpalmer/razzle/blob/master/examples/with-styled-components/src/server.js), you can see the template of [material-ui](https://github.com/jaredpalmer/razzle/blob/master/examples/with-material-ui/src/server.js).

**Comment by nimaa77** [comment]
hello, @serge20 please use [after.js](https://github.com/jaredpalmer/after.js). it has the same setup as nextjs with razzle for webpack tolling
