### ISSUE TITLE
eslint warnings and errors in Overlay in stead of Terminal after upgrade

### ISSUE THREAD

**Issue by mschipperheyn** [jaredpalmer/razzle#986]
I have been using 3.0.0-alpha.0.0.2 for a while and upgraded to 3.0.0 yesterday. I had a go at that eslint plugin. Right away, style errors, some of which I can't get rid of, started appearing in the error overlay instead of the Terminal. That makes development a pain. 

So, when you try to supply custom options to the plugin, right away, you run into the fact that this plugin is not configurable.

Reviewing the source code, the eslint plugin seems to be pretty much inline with the way it was, so not sure why this is happening. I use a custom eslintrc.js.

```
module.exports = {
	rules: {
		'prettier/prettier': [
			'warn',
			{
				singleQuote: true,
				trailingComma: 'all',
			},
		],
		indent: [1, 'tab'],
		'class-methods-use-this': 'off',
		'no-use-before-define': 'off',
		'no-class-assign': 'off',
		'no-restricted-syntax': ['off', 'ForInStatement'],
		'no-tabs': 0,
		'no-debugger': 0,
		'linebreak-style': ['warn', 'unix'],
		'import/prefer-default-export': 0,
		'no-param-reassign': 0,
		'react/destructuring-assignment': 0,
		'react/jsx-filename-extension': 'off',
		'react/jsx-indent': [1, 'tab'],
		'react/prop-types': 'off',
		'react/require-extension': 'off',
		'react-hooks/rules-of-hooks': 'error',
		'react-hooks/exhaustive-deps': 'warn',
		'react/jsx-uses-react': 'error',
		'react/jsx-uses-vars': 'error',
		'no-unused-vars': ['error'],
		'no-console': ['warn'],
	},
	settings: {
		'import/resolver': {
			node: {
				paths: ['./', 'src/shared', 'src'],
				extensions: ['.web.js', '.js', '.jsx', '.json'],
			},
			alias: {
				map: [
					['components', 'src/shared/components'],
					['modules', 'src/shared/modules'],
					['locale', 'src/shared/locale'],
					['router', 'src/shared/router'],
					['store', 'src/shared/store'],
					['styles', 'src/shared/styles'],
					['server', 'src/server'],
					['App', 'src/App'],
					['AppContext', 'src/AppContext'],
				],
			},
		},
		'import/extensions': ['.web.js', '.js', '.jsx', '.json'],
		'import/external-module-folders': [
			'node_modules',
			'../common-lib/node_modules',
			'../common-lib/src',
			'../social/node_modules',
			'../social/src',
		],
	},
};

```

**Comment by sibelius** [comment]
did you fix it?

**Comment by mschipperheyn** [comment]
@sibelius Don't remember. One thing's for sure. I don't have an error overlay. So I guess I ripped it out.

**Comment by sibelius** [comment]
How did you removed the error overlay?

**Comment by mschipperheyn** [comment]
I'm not 100% sure but I ended up a very convoluted effort to be able to change the webpack config by making the config customizeCra compatible and then using that tool to change a bunch of settings bc razzle is not compatible with all the CRA tools. I later realized there was another tool able to do that (also don't remember). 

Also had a bunch of issues with jest since razzle is way too restrictive in what you can use. I used razzle for the server side processing but ending up having tons of problems with that using loadable components with Apollo and Material-ui, still do. So, in the end, not so sure it was all worth it. Sorry I can't be more helpful.
