### ISSUE TITLE
Replacing tslint with eslint?

### ISSUE THREAD

**Issue by jleclanche** [jaredpalmer/razzle#988]
With [create-react-app](https://github.com/facebook/create-react-app) having migrated to full eslint even with the typescript setup, thoughts on doing the same here?

**Comment by dguo** [comment]
This should happen eventually, as the TSLint team [plans to deprecate](https://github.com/palantir/tslint/issues/4534) it in 2019 in favor of ESLint.

**Comment by jaredpalmer** [comment]
I think this makes a lot of sense. We are should likely just adopt eslint config and setup from CRA

**Comment by iberodev** [comment]
Can we switch tslint to eslint by tweaking some configuration?
I see that currently tslint is required when using razzle-plugin-typescript

PS: I found https://github.com/jaredpalmer/razzle/issues/936

**Comment by nimaa77** [comment]
We have some plans for `razzle-plugin-eslint` and `razzle-plugin-typescript`.
we are going to replace tslint with eslint

**Comment by hcharley** [comment]
For those that want to disable tslint right now:

https://github.com/jaredpalmer/razzle/issues/936#issuecomment-503639140

**Comment by fivethreeo** [comment]
Fixed in canary
