### ISSUE TITLE
Initial load of razzle runs both server and clientside.

### ISSUE THREAD

**Issue by Pixelatex** [jaredpalmer/razzle#992]
Running a basic example of razzle, a componentdidmount fires on first load. So the client is actually rerendering the page once the server loads.

This shouldn't be the case, I'm doing this with a clean install, no changes...

Does anyone know what could be causing this?

**Comment by Pixelatex** [comment]
p.s. running the ^3.0.0 version

**Comment by revskill10** [comment]
I have some express middlewares, and it seems that HMR doesn't work on express middlewares. Anyone has the same issue as mine ?

**Comment by Pixelatex** [comment]
> I have some express middlewares, and it seems that HMR doesn't work on express middlewares. Anyone has the same issue as mine ?

Why are you posting this here? Has no relevance to this issue. 🤔

**Comment by stepanh** [comment]
@Pixelatex - This is OK - componentDidMount fires when React hydrates a server side rendered component. See https://reactjs.org/docs/react-dom.html#hydrate

@revskill10 HMR refreshes, but doesn't reload server code. You can type 'rs' in console where you run  razzle and server will restart quickly, without recompile.

**Comment by txs** [comment]
> @Pixelatex - This is OK - componentDidMount fires when React hydrates a server side rendered component. See https://reactjs.org/docs/react-dom.html#hydrate
> 
> @revskill10 HMR refreshes, but doesn't reload server code. You can type 'rs' in console where you run razzle and server will restart quickly, without recompile.

Thanks for sharing the rs command. Is there a way to auto 'rs' so that it feels like server HMR also?

**Comment by nimaa77** [comment]
let's move this conversation to #1069.
