### ISSUE TITLE
Newer version webpack-dev-server injects unwanted entries

### ISSUE THREAD

**Issue by appden** [jaredpalmer/razzle#994]
This causes a ton of client-side errors since Razzle uses its own `webpackHotDevClient.js` entry. The easiest short-term fix would be to lock to version `3.1.14` in the `package.json`.

Since I'm using yarn, my workaround was to add this to my own `package.json`:
```json
"resolutions": {
  "razzle/webpack-dev-server": "3.1.14"
},
```

**Comment by nimaa77** [comment]
hello, @appden what is the problem with the `webpack-dev-server`? I don't really understand the problem here

**Comment by fivethreeo** [comment]
Razzle is using the last version now. Closing.
