### ISSUE TITLE
Client-side HMR console logs not working in 3.0

### ISSUE THREAD

**Issue by ecozoic** [jaredpalmer/razzle#997]
I'm testing out Razzle v3 in some of my apps, and I have noticed that client-side HMR seems to be behaving differently in the latest 3.0.0. This occurs even using the basic examples and when using `create-razzle-app`.

Steps to Reproduce:
```
npx create-razzle-app --example basic razzle-test
cd razzle-test
yarn start
```

When you navigate to http://localhost:3000, you'll see the app, but if you open up the DevTools console you'll see the following log:

```
[HMR] Waiting for update signal from WDS...
```

and you will never see the expected follow up message (something like `[WDS] Hot Module Replacement enabled`).

This worked fine for me in 2.x so I'm assuming the upgrade to WDS in v3 is causing this issue? I am going to try and dig into it over the next few days but wanted to go ahead and get an issue out here in case anyone else is running into it.

I've tested with both Node 11 (latest) and Node 10 (LTS).

EDIT - It appears the HMR functionality itself is working, so maybe just an issue with how it's being logged to console. Code changes take affect but you won't see anything in the console about the updates being applieed

**Comment by nimaa77** [comment]
@fivethreeo

**Comment by fivethreeo** [comment]
Might be here this happens. https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/config/createConfig.js#L394

**Comment by fivethreeo** [comment]
This issue is quite old. Is this still a issue? Closing
