### ISSUE TITLE
Debugger not attaching to Jest instance VS Code

### ISSUE THREAD

**Issue by felixnorden** [jaredpalmer/razzle#999]
# Issue: Debugger not attaching to Jest instance in VS Code

I'm trying to run a Jest process with a debugger in VS Code, but VS Code doesn't seem to be able to attach the debugger to the Jest child process that is being run when executing `razzle test` or `npm test`.

Everything seems to stop as soon as razzle starts the child process using `spawn`, but I'm not sure why this is happening.

## Suggestion (if possible)
Add the capability to launch a debug instance of `razzle test` through flags, the same as it is done for `razzle start`. 

## Current `launch` task for debugger:
```json
        {
          "type": "node",
          "request": "launch",
          "name": "Razzle: Jest All",
          "env": { "NODE_ENV": "test" },
          "cwd": "${workspaceRoot}",
          "program": "${workspaceRoot}/node_modules/.bin/razzle",
          "runtimeArgs": ["--nolazy", "--inspect"],
          "args": [
            "test",
            "--env=jsdom",
            "--runInBand",
          ],
          "console": "integratedTerminal",
          "stopOnEntry": true,
          "internalConsoleOptions": "neverOpen",
          "disableOptimisticBPs": true,
          "autoAttachChildProcesses": true,
          "sourceMaps": true,
          "windows": {
            "program": "${workspaceFolder}/node_modules/razzle/bin/razzle",
          },
          "port": 9229
        }
```

I have also checked both node and jest issues, but no suggestions have worked so far...

Always appreciate alternative solutions/workarounds as well! 
Thanks!

**Comment by fivethreeo** [comment]
Inspect works for test in razzle 4 canary now. Also added —nowatch so you can turn watch off
